### ISSUE TITLE
showInlineError not working on `ListField`

### ISSUE THREAD

**Issue by jamielob** [vazco/uniforms#100]
Getting an error that `showInlineError` prop isn't allowed on `section`.  Looks like it's because the `ListField` component isn't wrapped in a `FormGroup` which is where the inline errors are handled?

To replicate, just create a `ListField` component with `showInlineError` as a prop.

p.s. Great package.

**Comment by radekmie** [comment]
Well, yes - it's not passed down. If you want, create a PR for it (it's only two lines in two packages - 4 LOC). No matter what, it will be refactored - you can track progress in #87.

**Comment by radekmie** [comment]
Now it's propagated like `disabled`, so setting it on `ListField` will set it on the nested fields.

**Comment by radekmie** [comment]
OK, now I see, that this is not the case...

**Comment by radekmie** [comment]
Implemented in [`d4fadf8`](https://github.com/vazco/uniforms/commit/d4fadf876bd61f2c599174ff7389853670f52faf).
