### ISSUE TITLE
defaultValue in Array fields should populate model with SimpleSchema

### ISSUE THREAD

**Issue by Floriferous** [vazco/uniforms#1008]
When you set a `defaultValue` in an `Array` field with SimpleSchema, the initial model doesn't properly reflect it:

```js
const schema = new SimpleSchema({
  list: { type: Array, defaultValue: [{ title: 'Hello world' }] },
  'list.$': Object,
  'list.$.title': String,
})
```

When a form mounts with this schema, I expect the `list` field to be already populated with one element, with the `title` field filled. The model should also contain this data immediately, and not after editing the form first.

Currently, this `defaultValue` has no effect, and the array is initialized as empty.

**Comment by wadamek65** [comment]
Hi @Floriferous , thanks for the issue report.

I've checked the behavior that you have described and it seems like there is a problem with logic in the bridge.

[JSON Schema bridge](https://github.com/vazco/uniforms/blob/master/packages/uniforms-bridge-json-schema/src/JSONSchemaBridge.ts#L205-L227) seems to return `defaultValue` right away and returns `undefined` as a fallback, [whereas in SimpleSchema](https://github.com/vazco/uniforms/blob/master/packages/uniforms-bridge-simple-schema-2/src/SimpleSchema2Bridge.ts#L72-L86) `defaultValue` is returned as a fallback - in this case the code follows the `type === Object` path and returns an empty object. 

@radekmie Do you know if there is any exact reason for this inconsistency or is this simply an oversight? If it's an oversight, I will create a fix for this.

**Comment by radekmie** [comment]
@wadamek65 No, that's just an oversight. Feel free to take this one.
