### ISSUE TITLE
A number field does not seem to let me enter "0" as the number.

### ISSUE THREAD

**Issue by arrygoo** [vazco/uniforms#101]
I have a SimpleSchema field like so:

```
  'hoursMin': {
    type: Number,
    min: 0,
```

I've tried with and without the min, but in both cases the form does not allow me to enter "0" as the number. It lets me put "-1" or "0.1", but I can't find any way to input "0". It seems like a bug to me unless it was done by design?

**Comment by radekmie** [comment]
I'll investigate it.

**Comment by radekmie** [comment]
[Yes, that's a bug](https://github.com/vazco/uniforms/blob/v1.0.0-rc.32/packages/uniforms-unstyled/src/components/fields/NumField.js#L32). I'm already working on it.

**Comment by radekmie** [comment]
Will be included in `1.0.0-rc.33`.
