### ISSUE TITLE
onChange converts to controlled component? (Question)

### ISSUE THREAD

**Issue by chiester** [vazco/uniforms#1014]
When I add an `onChange` prop to my AutoField and then select an item (it's a select list), the selected item no longer stays selected. What's the preferred way for me to be able to use the selected value in React state somehow but still have it be visibly selected and usable by uniforms?

**Comment by wadamek65** [comment]
Hi @chiester ,

If you only need the fields value I think `useField` hook could help you with this. [You can find the documentation for this here](https://uniforms.tools/docs/api-context-data#accessing-context-data). This hook will give you access to all of the fields data and you won't need to pass a `value` and an `onChange` to it explicitly.
