### ISSUE TITLE
A number field does not seem to let me enter "0" as the number.

### ISSUE THREAD

**Issue by arrygoo** [vazco/uniforms#102]
I have a SimpleSchema with a number filed like so:
```
hoursMin: {
    type: Number,
    min: 0,
}
```

And I simply have an Autoform generated from it. When I try to fill in the form, it doesn't allow me to input `0` for hoursMin. It removes it as I type the `0` similar to how it disallows Alphabetical characters for the `Number` field.

It allows `0.1` or `-1`, but disallows typing `0`. I've tried it both with and without the `min: 0` but had the same issue. I can provide more context if this is not clear enough, but seems to be a generic enough issue.

**Comment by radekmie** [comment]
Duplicate #101.

**Comment by arrygoo** [comment]
@radekmie Sorry I thought the previous issue I made was not posted. Thanks for addressing that :).

**Comment by radekmie** [comment]
@arrygoo No problem.
