### ISSUE TITLE
[Question] Async validation: what has to be returned?

### ISSUE THREAD

**Issue by chiester** [vazco/uniforms#1020]
I'm looking at the documentation at https://uniforms.tools/docs/api-forms/#asynchronous-validation

It seems that `onValidate()` has to return errors in order for the errors to be rendered in the form. What is the correct way to modify the errors to return them? 

I'm making a call to my API to do my async validation and if it fails, it's not clear to me how to pass that response back to the form. I also looked at ajv's recommended approach (https://ajv.js.org/guide/async-validation.html), but couldn't get it working in my bridge.

**Comment by radekmie** [comment]
Hi @chiester. As with all errors in uniforms, the format of the error is specified by the bridge you're using. So, if you're using JSON schema bridge (I assume so, based on the ajv in your message), you have to return a list of [`ErrorObject`](https://ajv.js.org/api.html#error-objects)-like objects. (I say `ErrorObject`-like, as we're not using all of the properties. You can always check the [`getError`](https://github.com/vazco/uniforms/blob/8dd2d7435d4a19c695af6e06fe0d27f97eeb7c0b/packages/uniforms-bridge-json-schema/src/JSONSchemaBridge.ts#L96-L114) implementation to see the details.)

> What is the correct way to modify the errors to return them?

In `onValidate`, you are supposed to return a new error, not modify the one you received. So, for example, in JSON schema, simply add your custom errors to the `details` array. To make them visible with the `showInlineError`, make sure that the `instancePath` is correct.

> I'm making a call to my API to do my async validation and if it fails, it's not clear to me how to pass that response back to the form. I also looked at ajv's recommended approach (https://ajv.js.org/guide/async-validation.html), but couldn't get it working in my bridge.

You don't have to use `onValidate` for that - you can use the validator itself (the function that you pass to the `JSONSchemaBridge` constructor). The only thing is that you have to return the error in a proper format (and not `reject` or `throw` it).

---

I hope this answers the question. If not, please do let me know.
