### ISSUE TITLE
Required property inside required property does not show error

### ISSUE THREAD

**Issue by mdesousa** [vazco/uniforms#1024]
Let us know what is happening. Do provide us with:

Hi, we are seeing this issue with the following packages:
uniforms@3.5.5
uniforms-bridge-json-schema@3.5.5
uniforms-material@3.5.5

We have a json schema defined as shown at the bottom... for example: `{ myObject: { myString: 'x'} }`
In this scenario, both myObject and myString are required properties.
We have a form with an `<ErrorField name="myObject.myString" />
The problem occurs when the model is `undefined`... in that case, `<ErrorField>` does not show an error even though the validation fails. We would expect that the error field would show an error in this scenario. Thanks.

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/MyType1",
  "definitions": {
    "MyType1": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "myObject": {
          "$ref": "#/definitions/MyType2"
        },
      },
      "required": [
        "myObject"
      ]
    },
    "MyType2": {
      "type": "object",
      "properties": {
        "myString": {
          "type": "string"
        }
      },
      "required": [
        "myString"
      ],
      "additionalProperties": false
    },
  }
}
```

**Comment by radekmie** [comment]
Hi @mdesousa. Could you provide us with a more detailed instruction on how to reproduce it? When I used your schema in a playground ([link](https://uniforms.tools/playground/#?N4IgDgTgpgzlAuIBcICCATd0YwAQAoApAZQHkA5YgYwAsoBbAQwEoQAacCAezBmVEYBXeFxiMAblGQAzRgBs4HISLGSAIlDmMAnsgCMABgMd0ASzEAjOVHQz5ikFoubk8CIKgcwWqlBpc5dCgIOwVPEGhGdFIAOzldJFkwjhhaBkZkEHx8ZlwAXgA-XGAAHRjcXCouGJh4XEYAK3F83BioAHdcVCb8YHq5OQBRCG4IGCRcNw82XEE4DVlBOXhxyfdPXABrKG12rgh0VYBtEpBBGNNpffoYU4BdXABfZgBuMoqqmrrUuiYW0vKuFOABIfulThNTjR4PAwEgAPTwhowaoAWjBTAAdPsAObwrCMaTwVEGADs8IxjAAxKc2O8gSBgdBpBCGVT8VBpKYLvBTNUYPCALLaAAq2jAUD0tPppyCXJ5fJqrIBFQqp2FYolUuQxXpqoZ8HFUFZpy4FgaUCo8GlgP1pyiZl51XkAAVuBKILzYKykoo9arTpAeMEvbcdSr9QGQPRtKRzZbreH_ZGGUzOSaQOy5dzTE6akLRUaAEynZOqx5023lysp07QACOglM0HQrJOVbt0dj8atpY7uDu_or_vVhYlJaT_dOholGbNFt77DLgfdIdM3snKbVXeIbm5OOVZc7M-NOtOtQg-77W6eZeHU4iUEbzZsbaPDJju8vMQPIDLdxrSN7UwXNFVdVdPXXMMJl9Y0q3vCpHjKJCYjeGJ6Wkc4rUVSpIngKAADV5FMdBGBECB8EpXIIw-fk6nEYjSPIlpGnETEqnoMBTGsSi0iYV4yn9aB4EECBynweguCCORckKXV-wYuQSLI_YJKkzQBPQ_tLgIRTlPIzFglGPAADITNwPSmP2QyRn2GBMWsH94Boaj32E0Tyj6IJ4EYbjVkslSIBs4ynjQlMUP1R4wtvLTaK-XBKSIpSrIgFoqDwwjGMC3jfhYND6XcsTWg6XASAoahcoAIUvdAcSgHL0hmRKsvIzTnhydgQBgfx2gASTibkoGGUZXHWJQYG0GIqFiYhBAsehc1CBxGAmqbYiS_SpESewoArEBnIYLauvSGJeSoEBHiAA)), it just shows the error. A playground link is enough, but maybe you'd need to use CodeSandbox instead ([template](https://codesandbox.io/s/github/vazco/uniforms/tree/master/reproductions)).

**Comment by mdesousa** [comment]
Ah, sorry... it's a simplified version of what we are doing. I'll try to find a way to reproduce it... may take me a few days.
Thanks!

**Comment by radekmie** [comment]
I'm closing this for now, but feel free to comment as soon as you'll have a reproduction. Thanks!
