### ISSUE TITLE
custom field error after update: "useForm must be used within a form"

### ISSUE THREAD

**Issue by niklasdahlheimer** [vazco/uniforms#1029]
Hey guys,

After I updated my uniforms-packages my custom fields are no longer working and I get a console error:
```
Invariant Violation
useForm must be used within a form.
```
This is strange, because of course I use my custom fields inside a form (AutoForm)

It looks like updating the **uniforms-semantic**-package from **3.5.0 to 3.5.1** breaks it.

Have a look at this striped down example:
https://codesandbox.io/s/uniforms-custom-field-useform-issue-ejx3j?file=/src/App.js

If you downgrade the uniforms-semantic in the sandbox to 3.5.0 it shows the custom field placeholder text correctly.

What has changed or what's wrong with my use of the custom fields?

Greetings!

**Comment by niklasdahlheimer** [comment]
any news on this? I couldn't find any breaking changes between 3.5.0 and 3.5.1
https://github.com/vazco/uniforms/compare/v3.5.0...v3.5.1

I'm not using TypeScript in my custom field but this should not cause the react error...

**Comment by Monteth** [comment]
Hello @niklasdahlheimer ,
At the very beginning, I wanted to thank you for preparing the reproduction environment  👏🏻 
I confirm that updating only the `uniforms-semantic` version somehow breaks the app, but I didn't spot such a situation while updating them all together, which we strongly recommend. Is it possible to you to stick with one version for all uniforms packages? 
I think the changelog is right - I cannot spot any change in code related to the `uniforms-semantic` nor core `uniforms` package between 3.5.0 and 3.5.1, so please, try the solution I described above.
I'd be happy to hear any updates from you!

**Comment by niklasdahlheimer** [comment]
Hey @Monteth ,

>  At the very beginning, I wanted to thank you for preparing the reproduction environment 👏🏻 I 

In 90% reproduction environments and reducing the issue to it's core solves the problem, so building the sandbox was driven by self-interest :D

> ...but I didn't spot such a situation while updating them all together...

Did you try to update them all together _in the sandbox_? Because I still get the error when updating all the uniforms-packages to 3.6.0 (latest) there
I just used different package-versions to delimit the issue, I do not need different package versions. If everything would work fine with all packages at the latest version, I would be totally satisfied but because updating to 3.6.0 breaks all custom fields in my app, that's not a solution. So I have to stay at 3.5.0. 
Because I can not see any issue with my striped down custom field example in the sandbox, I guess this probably could be an issue with uniforms, but would be happy to be proven wrong :)

**Comment by Monteth** [comment]
>In 90% reproduction environments and reducing the issue to it's core solves the problem, so building the sandbox was driven by self-interest :D

Couldn't agree more :) 

>Did you try to update them all together in the sandbox? Because I still get the error when updating all the uniforms-packages to 3.6.0 (latest) there

Yes, I did, and I am able to fix your reproduction app by changing the import source in `PopupColorField` from `uniforms/es6`
`uniforms;`. 
This could be the main reason, but please confirm if you have similar cases in your real application.

**Comment by niklasdahlheimer** [comment]
that indeed fixed the issue! Thank you! I guess I have to learn more about typescript and how it compiles to understand why this fixed it.
