### ISSUE TITLE
Material UI ThemeProvider

### ISSUE THREAD

**Issue by flean** [vazco/uniforms#1038]
I'm using the Material UI ThemeProvider that wraps my APP in React

import { ThemeProvider } from '@mui/material'

But when I import import { AutoForm } from 'uniforms-material' it messes up my theme.

How do I make uniforms-material use my theme? 

I noticed that you use "@material-ui/core" and I'm using "@mui/material". I'm guessing this could be the issue, if so is there a workaround ? Thanks

**Comment by radekmie** [comment]
Hi @flean! As you've noticed, the `uniforms-material` package is based on `@material-ui/core`, not `@mui/material`. There's no "workaround" for that, other than creating a new theme, using the new package. You can follow our discussion about that in #1011.
