### ISSUE TITLE
Multi field/value connectField() input, not nested

### ISSUE THREAD

**Issue by zeroasterisk** [vazco/uniforms#105]
I'd like to make a custom component for a date range picker, from airbnb.
https://github.com/airbnb/react-dates

This component has an onchange handler function, all good:

> onDatesChange is the callback necessary to update the date state being held in the parent component and pass that back down to the DateRangePicker as props. onDatesChange receives an object of the form { startDate: momentPropTypes.momentObj, endDate: momentPropTypes.momentObj } as an argument.

The problem is, it's change handler returns 2 fields, nested in an object.

My schema has `start,stop` as 2 date fields, on the root of the schema, no nesting.

How do I make a single, non-nested component, connect to 2 different values?

**Comment by radekmie** [comment]
I wouldn't use `connectField` here because you are creating a _composite field_, not a _field_ - I would [use context directly](https://github.com/vazco/uniforms#context-data). Example implementation:

```js
import get from 'lodash.get';
import {BaseField} from 'uniforms';
import {DateRangePicker} from 'react-dates';

const DateRangeField = ({endDate, startDate, ...props}, {uniforms: {model, onChange}}) =>
    <DateRangePicker
        {...props}
        endDate={get(model, endDate, null)}     // As in docs - null if not set
        startDate={get(model, startDate, null)} // As in docs - null if not set
        onDatesChange={value => {
            onChange(endDate, value.endDate);
            onChange(startDate, value.startDate);
        }}
    />
;

DateRangeField.contextTypes = BaseField.contextTypes;
```

Of course, if you would nest those two in one key, `connectField` would be the best option (in terms of code clarity and performance). Example implementation:

```js
import {BaseField, connectField, filterDOMProps} from 'uniforms';
import {DateRangePicker} from 'react-dates';

// As in docs - null if not set
const DateRange = ({onChange, value: {endDate = null, startDate = null} = {}, ...props}) =>
    <DateRangePicker
        {...filterDOMProps(props)}
        endDate={endDate}
        startDate={startDate}
        onDatesChange={onChange}
    />
;

// undefined is an acceptable value
const DateRangeField = connectField(DateRange, {ensureValue: false});
```

**Note:** I haven't tested it.

**Comment by zeroasterisk** [comment]
Looks great, thank you!!!  Once I finalize, I'll submit as an example
