### ISSUE TITLE
custom props on Form-Components should not be passed down to <form>

### ISSUE THREAD

**Issue by macrozone** [vazco/uniforms#106]
I have a Quickform, where i defined a custom property to disable the submit button:

```
import {QuickForm} from 'uniforms';

import BaseForm    from './BaseForm';
import AutoField   from '../fields/AutoField';
import ErrorsField from '../fields/ErrorsField';
import SubmitField from '../fields/SubmitField';

const Quick = parent => class extends QuickForm.Quick(parent) {
    static Quick = Quick;

    getAutoField () {
        return AutoField;
    }

    getErrorsField () {
        return ErrorsField;
    }

    getSubmitField () {
      return () => this.props.hideSubmit ? (
        <span />
      ) : (
          <SubmitField />
      )

    }
};

export default Quick(BaseForm);
```

This will show a react-warning that hideSubmit is not allowed on a `<form>`-Tag, because every property (besides some defined props in https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/components/forms/BaseForm.js#L200) are passed to the form-tag.

I am not sure how to fix this, but having a whitelist in https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/components/forms/BaseForm.js#L200 instead of a blacklist (like the current approach) might be the better solution.

**Comment by radekmie** [comment]
0. You can override `getNativeFormProps` and remove your extra prop.
0. You can pass `submitField={() => null}` _(or `nothing`, if you want to be compliant with the React 0.14)_ to the [`QuickForm`](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/components/forms/QuickForm.js#L48).
0. Whitelist? [No](https://twitter.com/dan_abramov/status/751066839359361024).

**Comment by macrozone** [comment]
Hi @radekmie 

thx, you are right. Overriding getNativeFormProps is the right approached:

```
const Quick = parent => class extends QuickForm.Quick(parent) {
    static Quick = Quick;

    getAutoField () {
        return AutoField;
    }

    getErrorsField () {
        return ErrorsField;
    }

    getNativeFormProps() {
      const {hideSubmit, ...nativeProps} = super.getNativeFormProps();
      return nativeProps;
    }

    getSubmitField () {
      return () => this.props.hideSubmit ? (
        nothing
      ) : (
          <SubmitField />
      )

    }
};

export default Quick(BaseForm);

```
