### ISSUE TITLE
componentDetectorContext throws error if null is returned as a component

### ISSUE THREAD

**Issue by macrozone** [vazco/uniforms#1064]
I am about to add conditional rendering, but that has to be schema driven.

So i need to alter the Autofield to check for a `condition` property.

Here, you probably would return `null` as a component like this:

```
import React, { Fragment } from 'react';
import { AutoField } from 'uniforms-material';

const AutofieldContextProvider: React.FC = ({ children }) => (
  <AutoField.componentDetectorContext.Provider
    value={(props, uniforms) => {
      const show = props.condition?.(uniforms) ?? true;

      return show
        ? AutoField.defaultComponentDetector(props, uniforms)
        : null; // return null to show no field
    }}
  >
    {children}
  </AutoField.componentDetectorContext.Provider>
);

export default AutofieldContextProvider;
```

but that throws an error. Solution is to return a `Noop`-component:

```
import React, { Fragment } from 'react';
import { AutoField } from 'uniforms-material';

const AutofieldContextProvider: React.FC = ({ children }) => (
  <AutoField.componentDetectorContext.Provider
    value={(props, uniforms) => {
      const show = props.condition?.(uniforms) ?? true;

      return show
        ? AutoField.defaultComponentDetector(props, uniforms)
        : () => null; // return null to show no field
    }}
  >
    {children}
  </AutoField.componentDetectorContext.Provider>
);

export default AutofieldContextProvider;
```

**Comment by wadamek65** [comment]
Hi @macrozone ,

This is the correct behavior. The context expects you to return a function that a quick form can then call to render appropriate components. What kind of error exactly are you getting? Is it a runtime error or a TS error? If the latter then there is probably an inconsistency in the typings.

**Comment by macrozone** [comment]
> Hi @macrozone ,
> 
> This is the correct behavior. The context expects you to return a function that a quick form can then call to render appropriate components. What kind of error exactly are you getting? Is it a runtime error or a TS error? If the latter then there is probably an inconsistency in the typings.

there is a invariant error, no type error, and yes , that is intentional, not sure if its a good api though. I think its legitimate to decide to render no field on props.

Workaround is easy to do, but not obvious, its kind of a "principle of least surprise"-violation.

**Comment by wadamek65** [comment]
@macrozone Thanks for the clarification. I understand your point of view, but at the same time, I think the API is simple enough and there should also be TS types to help. Also, due to how the current component logic (usage of `createElement`) is written a change in API like this may not be trivial so we probably will not implement this currently. @radekmie @Monteth @kestarumper any thoughts?

**Comment by macrozone** [comment]
@wadamek65 i mean there is another way to go:

i used this approach by beeing able to hide fields by defining custom properties on the schema
(see this example in the [docs of my library "react-page"]( https://react-page.github.io/docs/#/custom-cell-plugins?id=passing-props-to-fields) with the `showIf`-property),  I heared this [complaint](https://github.com/react-page/react-page/discussions/1091) alot that people are not able to hide fields based on other fields).

So its probably best to add it to the recipes as an example.

@radekmie feels wrong to render the default component in my opinion, that is non-intuitive. If you override the componentDetector, you are already able to implement a fallback logic to display a component of your choice as a default component. Returning explicit null seems more of an intent to render nothing. (If anything, `undefined` could fall back to a default component)

**Comment by radekmie** [comment]
_(We've had a team discussion about this issue, and here are the notes.)_

What happens now, is that the component is required, therefore the code fails when `null` is returned (both on type level and in the runtime).

Possible options:
1. `null` remains not allowed.
2. `null` means "render nothing".
    ```diff
    diff --git a/packages/uniforms/src/createAutoField.tsx b/packages/uniforms/src/createAutoField.tsx
    index 6d9821ad..91ec6851 100644
    --- a/packages/uniforms/src/createAutoField.tsx
    +++ b/packages/uniforms/src/createAutoField.tsx
    @@ -24,7 +24,7 @@ export type Component = ComponentType<any> | ReturnType<typeof connectField>;
     export type ComponentDetector = (
       props: ReturnType<typeof useField>[0],
       uniforms: Context<Record<string, unknown>>,
    -) => Component;
    +) => Component | null;
    ​
     export function createAutoField(defaultComponentDetector: ComponentDetector) {
       const context = createContext<ComponentDetector>(defaultComponentDetector);
    @@ -33,6 +33,9 @@ export function createAutoField(defaultComponentDetector: ComponentDetector) {
         const [props, uniforms] = useField(rawProps.name, rawProps);
         const componentDetector = useContext(context);
         const component = props.component ?? componentDetector(props, uniforms);
    +    if (component === null) {
    +      return null;
    +    }
    ​
         invariant(component, 'AutoField received no component for: %s', props.name);
    ```
3. `null` means "fallback to default".
    ```diff
    diff --git a/packages/uniforms/src/createAutoField.tsx b/packages/uniforms/src/createAutoField.tsx
    index 6d9821ad..41f3904e 100644
    --- a/packages/uniforms/src/createAutoField.tsx
    +++ b/packages/uniforms/src/createAutoField.tsx
    @@ -24,7 +24,7 @@ export type Component = ComponentType<any> | ReturnType<typeof connectField>;
     export type ComponentDetector = (
       props: ReturnType<typeof useField>[0],
       uniforms: Context<Record<string, unknown>>,
    -) => Component;
    +) => Component | null;
    ​
     export function createAutoField(defaultComponentDetector: ComponentDetector) {
       const context = createContext<ComponentDetector>(defaultComponentDetector);
    @@ -32,7 +32,10 @@ export function createAutoField(defaultComponentDetector: ComponentDetector) {
       function AutoField(rawProps: AutoFieldProps): ReactElement {
         const [props, uniforms] = useField(rawProps.name, rawProps);
         const componentDetector = useContext(context);
    -    const component = props.component ?? componentDetector(props, uniforms);
    +    let component = props.component ?? componentDetector(props, uniforms);
    +    if (component === null) {
    +      component = defaultComponentDetector(props, uniforms);
    +    }
    ​
         invariant(component, 'AutoField received no component for: %s', props.name);
    ```
4. `null` means "render nothing", `undefined` means "fallback to default".
    ```diff
    diff --git a/packages/uniforms/src/createAutoField.tsx b/packages/uniforms/src/createAutoField.tsx
    index 6d9821ad..2d4d8615 100644
    --- a/packages/uniforms/src/createAutoField.tsx
    +++ b/packages/uniforms/src/createAutoField.tsx
    @@ -24,7 +24,7 @@ export type Component = ComponentType<any> | ReturnType<typeof connectField>;
     export type ComponentDetector = (
       props: ReturnType<typeof useField>[0],
       uniforms: Context<Record<string, unknown>>,
    -) => Component;
    +) => Component | null;
    ​
     export function createAutoField(defaultComponentDetector: ComponentDetector) {
       const context = createContext<ComponentDetector>(defaultComponentDetector);
    @@ -32,7 +32,14 @@ export function createAutoField(defaultComponentDetector: ComponentDetector) {
       function AutoField(rawProps: AutoFieldProps): ReactElement {
         const [props, uniforms] = useField(rawProps.name, rawProps);
         const componentDetector = useContext(context);
    -    const component = props.component ?? componentDetector(props, uniforms);
    +    let component = props.component ?? componentDetector(props, uniforms);
    +    if (component === null) {
    +      return null;
    +    }
    +
    +    if (component === undefined) {
    +      component = defaultComponentDetector(props, uniforms);
    +    }
    ​
         invariant(component, 'AutoField received no component for: %s', props.name);
    ```

We've decided to go with option 1, i.e., not changing the way it works.
