### ISSUE TITLE
Simple `if/then` fails to render.

### ISSUE THREAD

**Issue by hickscorp** [vazco/uniforms#1072]
## Bug

Consider the following type:

```
export enum ReviewCompletionAnswer {
  Yes,
  No,
}

interface SuccessDeliveryCompletionReview {
  readonly deliverySuccess: ReviewCompletionAnswer.Yes;
}

interface FailedDeliveryCompletionReview {
  readonly deliverySuccess: ReviewCompletionAnswer.No;
  readonly additionalInformation: string;
}

export type ReviewCompletionSchema = SuccessDeliveryCompletionReview | FailedDeliveryCompletionReview;
```

The schema follows this type one for one:

```
const schema: JSONSchemaType<ReviewCompletionSchema> = {
  type: "object",
  properties: {
    deliverySuccess: {
      type: "integer",
      enum: [ReviewCompletionAnswer.Yes, ReviewCompletionAnswer.No]
    }
  },
  required: ["deliverySuccess"],
  if: {
    properties: {
      deliverySuccess: {
        type: "integer",
        enum: [ReviewCompletionAnswer.No],
      }
    }
  },
  then: {
    properties: {
      additionalInformation: {
        type: "string"
      }
    },
    required: ["additionalInformation"],
  }
};
```

When uniform tries to render this, everything works until the user selects the option that would require generating new fields.
Note that we have simplified the problem into a simple example - in reality we have much more complex conditions, involving severa variables in the `if/then` or `oneOf/allOf` blocks - so having a separate schema per "branch" of conditional expression is not an option for us - it would increase exponentially as the number of variables grow.

Note that we cannot utilize uniform-specific directives (such as `DisplayIf`), as we are using the same Json Schemas in other applications - and we can only have one source of truth to maintain (otherwise it would defeat the purpose of using Json Schema in the first place).

Any suggestion?
Thank you.

**Comment by radekmie** [comment]
Hi @hickscorp. The answer is short: in uniforms, the forms know about the possible fields from the bridges. And the bridges cannot depend on the current model (i.e., data). So overall, in the current architecture, it's simply not possible.

But! The option would be to implement a custom `AutoField` that would actually understand the `if/then` and any other properties (including your custom ones, if ready). In such a field you can access the schema (via bridge) as many times as needed, but you also can access the model.

I hope it's clear. Do let me know!

**Comment by hickscorp** [comment]
@radekmie thanks a lot for taking the time to support our question.
I'm looping in one of our frontend developers to evaluate the implications - we will surely let you know what is our thought process and decision in the end, in case it is helpful.

**Comment by radekmie** [comment]
Great! I'll close the issue for now, but feel free to comment here if you'll have anything.
