### ISSUE TITLE
Tie multiple fields together, and trigger re-render on change

### ISSUE THREAD

**Issue by zeroasterisk** [vazco/uniforms#108]
I've been making custom fields via `connectField()` _(no problems)_

I've been able to make "mega" fields, based on `BaseField` and the uniforms context _(super powers, engage)_

Recently I've been trying to use your example, context aware helper `DisplayIf` [link](https://github.com/vazco/uniforms#example-displayif) _(living in the future)_

So then, of course, I tried to combine tactics and it sort-of failed.

If I put `<DisplayIf>` inside a `connectField()` wrapped component, it doesn't trigger a re-render correctly.

```js
MyFieldBase = props => (
  <div>
    <DisplayIf condition={(ctx) => !!_.result(ctx.model, 'some.nested.field')}>
      <p>Yup</p>
    </DisplayIf>
    <DisplayIf condition={(ctx) => !_.result(ctx.model, 'some.nested.field')}>
      <p>Nope</p>
    </DisplayIf>
  </div>
);
MyField = connectField(MyFieldBase)
```

If I put `<DisplayIf>` on the page and turn on/off (or change props of) rendered `connectField()` components, it works fine.

This is either a minor bug, or a "deal with it" gotcha we should at least clarify in the docs for that example.

thanks!

**Comment by radekmie** [comment]
> It's not a bug it's a feature.

It is because most fields care only about its own props. As a solution (solution, not workaround) I would suggest using custom `BaseField` subclass:

```js
class CompositeField extends BaseField {
  shouldComponentUpdate() {
    // By default, field update only, if it's required - now
    // we have to rerender if one of all subfields change, but
    // it's not necessary - all of them will check for their
    // change anyway. Leave it or write your custom logic.
    return true;
  }
}

// Then...

const X = props => { ... };
const XField = connectField(X, {baseField: CompositeField, includeInChain: false});
```

_I think, that I have to write a blog about my work with uniforms, because if I stumble upon thing like this, probably in a week or two there's an issue for it._

**Comment by zeroasterisk** [comment]
Thanks!
