### ISSUE TITLE
Cannot call a class constructor without new with local copy of uniforms-unstyled on meteor cordova

### ISSUE THREAD

**Issue by JanMP** [vazco/uniforms#1084]
Working with a copy of the sources of uniforms-unstyled (both in the meteor project itself and from a meteor-package) works fine in the browse now, but causes the old type error #1001 on cordova.

Tested with uniforms 3.7.0 and meteor 2.5.3.

```
[Error] TypeError: Cannot call a class constructor without |new|
	AutoValidatedQuickUnstyledForm (modules.js:39890)
	_ (app.js:231)
	constructClassInstance (modules.js:16777)
	updateClassComponent (modules.js:21486)
	callCallback (modules.js:8006)
	dispatchEvent
	invokeGuardedCallbackDev (modules.js:8055)
	invokeGuardedCallback (modules.js:8117)
	beginWork$1 (modules.js:28025)
	performUnitOfWork (modules.js:26837)
	workLoopSync (modules.js:26768)
	renderRootSync (modules.js:26731)
	performSyncWorkOnRoot (modules.js:26354)
	scheduleUpdateOnFiber (modules.js:25942)
	updateContainer (modules.js:29543)
	(anonyme Funktion) (modules.js:30082)
	unbatchedUpdates (modules.js:26492)
	legacyRenderSubtreeIntoContainer (modules.js:30081)
	(anonyme Funktion) (app.js:2097)
	maybeReady (meteor.js:975)
	releaseReadyHold (meteor.js:964)
	(anonyme Funktion) (cordova.js:827)
	(anonyme Funktion) (cordova.js:232)
```

See https://github.com/JanMP/uniforms-repro for a reproduction.

**Comment by radekmie** [comment]
Hi @JanMP, thanks for the reproduction! @kestarumper - can you look into it? You've done a great job with #1001 and this is somehow the same.

**Comment by JanMP** [comment]
I've been working with a workaround (change uniforms-unstyled in a fork of the uniforms repo, build the whole thing and then npm import, wich really is not fun when you fiddle around with it). I just reverted the workaround and noticed that the code with the local copy of uniforms-unstyled is still running in the cordova app. Seems the bug is only happening when you actually build the cordova app with meteor run iOS or meteor run android. But when you run the existing cordova app and it gets the problematic version via hot code push it works.

**Comment by kestarumper** [comment]
Hi @JanMP , I tried to reproduce the build error on Cordova but I wasn't able to (yet it gave _weird_ output).
I did run `meteor run ios` which **successfully built** and run the emulator, however, it displays an empty app.
Could I ask you to give me the set of instructions you ran to receive the error?

**Comment by JanMP** [comment]
That's (probably) exactly the error.
While running meteor run ios you can also look at the app on your browser (preferably Safari) on localhost:3000
I just added a toggle button to the repro. So now you should at least see that button when you run one of the broken imports. And that toggle also keeps Meteor from rejecting the hot-code push of broken versions once you have tried the working import (that's why I added the yellow and pink background in the broken versions, so I could see if the version running in the browser and the version running in the simulator were the same...).
While the iPhone simulator is running you can get the browser logs of the web-view in cordova via the safari developer menu.

**Comment by kestarumper** [comment]
> While running meteor run ios you can also look at the app on your browser (preferably Safari) on localhost:3000. If everything is working they should behave the same.

The app (from `meteor run ios`) was served on `localhost:3000` and working fine. It's just the emulator that did not show anything - but I also suspect that maybe my computer was overloaded. I'll try running it on an actual device.

Btw, thanks for an update. I'll continue the investigation.

**Comment by radekmie** [comment]
A small update: we're having a hard time finding the culprit of this issue. We'll still continue, but with a slightly lower priority, as it seems not to have any impact on other platforms.

In any case, if anyone would like to help with this one, go ahead!

**Comment by JanMP** [comment]
I'm back on the workaround. What I do: I got a fork of the uniforms repo and copy my version of uniforms-unstyled  into uniforms-unstyled/src and build the repo.  Then I commit the changes to just the uniforms-unstyled repo (https://github.com/JanMP/uniforms-custom). I can then use ```npm i github:janmp/uniforms-custom```  and then imports from 'uniforms-custom' work fine.

I thought the problem might be meteor's TS compilation so I tried copying just the esm and cjs folders into my meteor-package and import from one of those instead of the source. This works fine in the browser but I get the error on cordova again. So the problem get's magically fixed when the js is imported from node_modules instead directly ?!?

**Comment by radekmie** [comment]
@JanMP Can you maybe try to configure Browserslist for Cordova? I'm not sure whether it's possible, but it solved a similar problem in https://github.com/vazco/uniforms/issues/1089.

**Comment by JanMP** [comment]
I finally got around to open an issue about this in meteor https://github.com/meteor/meteor/issues/11969

**Comment by radekmie** [comment]
Great that you've finally found it! Looking forward to some feedback from the Meteor side.

**Comment by radekmie** [comment]
The problem got solved in https://github.com/meteor/meteor/issues/11969.
