### ISSUE TITLE
1.1.3 says it needs simpl-schema as peer dependency

### ISSUE THREAD

**Issue by vladejs** [vazco/uniforms#109]
> npm WARN uniforms@1.1.3 requires a peer of simpl-schema@^0.0.3 but none was installed.

I don't wanna use `simpl-schema`, I wanna stick with meteor package `aldeed:simple-schema`

**Comment by radekmie** [comment]
I can't turn off this npm warning. In `v1.1.3`, I've fixed `Unable to resolve some modules: ...` meteor warning.
