### ISSUE TITLE
Custom Uniforms Component with nested schema at multiple places

### ISSUE THREAD

**Issue by EricSoldierer** [vazco/uniforms#110]
I am having some problems to properly create custom components when using a nested schema. My schema has 8 subschemas which some of them would benefit from a custom UI component. Additionally I have these components on multiple places throughout my application, therefore want to be able to reuse them. This is the reason why I don't want to define my custom elements in the AutoForm and then omit them from the autofields.

What i did:
In my AutoForm:
```js
<AutoFields autoField={ CustomAutoField } omitFields={['someField']}/>
```
The custom component
```js
const CustomAuto = props => {
  const Component = determineComponentFromProps(props);
  return (
    <Component {...props} />
  );
};

export const CustomAutoField = connectField(CustomAuto, {
  includeInChain: false,
});
```

One of the 8 subschemas with the coresponding component
```js

const Duration = new SimpleSchema({
  target: {
    type: Number,
    uniforms: {
      label: 'ui.targetDuration',
    },
  },
  min: {
    type: Number,
    uniforms: {
      label: 'ui.minDuration',
    },
  },
  max: {
    type: Number,
    uniforms: {
      label: 'ui.maxDuration',
    },
  },
});


export class Duration extends someComponent {
  render() {
    //console.log(this.props);
    return (
      <section>
        <AutoField name="duration.target" />
        <AutoField name="duration.min" />
        <AutoField name="duration.max" />
      </section>
    );
  }
}
```

Now the problem:
How can I replace the AutoField in my Duration class with my own custom UI. I am having difficulties to access the translated label from the schema. I was only able to get it via a very very hideous call:
```js
  getName(field) {
    return this._reactInternalInstance._context.uniforms.schema.schema._schema[`duration.${field}`].uniforms.label;
  }
```

**Comment by radekmie** [comment]
Where exactly you want to receive that `label`? In the `Duration` component? I don't really get it.

**Comment by EricSoldierer** [comment]
Yes, i want to access the ``label`` from the schema inside my ``render`` method of the ``Duration`` class in order to build a custom UI and not use ``AutoField``. I currently can read it via the ``getName`` method. But i don't feel comfortable to use code like this in production. It feels very hacked (especially since i am accessing "private" (_reactInternal, etc.) members). 

On a higher level, the question would be: How can i effectively create my own custom components that i can reuse at several places and not copy the whole code of the ``AutoForm``.

**Comment by radekmie** [comment]
You can use [`context`](https://github.com/vazco/uniforms#context-data) directly _(there are some examples)_. Your example could look like this:

```js
// Firstly
Duration.contextTypes = BaseField.contextTypes;

// Then
getName (field) {
    return this.context.uniforms.schema.getProps(field).label;
}
```

It's public and schema agnostic.

**Comment by EricSoldierer** [comment]
Ok, i got this working with: 
```js
getName(field) {
  return this.context.uniforms.schema.getField(`duration.${field}`).uniforms.label;
}
```

Next step is that validation fails when i actually use my custom html component, rather than something uniforms related.
```js
render() {
    return (
      <Panel>
        <h3>{this.props.field.label}</h3>
        {this.props.fields.map((field) => {
          return (
            <div>
              <label htmlFor={field}>{this.getName(field)}</label>
              <input type="text" id={field} name={`duration.${field}`}/>
              {/* <TextField name={`duration.${field}`}></TextField> */}
            </div>
          );
        })}
      </Panel>
    );
  }
```

When using the uniforms `TextField`, validation works. But not with my label and input.

How can I achieve this ?

**Comment by radekmie** [comment]
Create custom fields using [`connectField`](https://github.com/vazco/uniforms/blob/master/API.md#connectfield). If you need example, look into README.md.

**Comment by EricSoldierer** [comment]
I tried doing that and it did not work. However I got it working by doing
```js
<input
  type="number"
  id={field}
  name={`${this.name}.${field}`}
  onChange={
    (event) => {
      this.onChange(field, event);
    }
  }
/>
```
and

```js
onChange(key, event) {
    let value;
    switch (event.target.type) {
      case 'number':
        value = parseInt(event.target.value, 10);
        break;
      default:
        value = event.target.value;
        break;
    }

    this.context.uniforms.onChange(`${this.name}.${key}`, value);
  }
```

I could imagine that i can get rid of my `onChange`. I created a base class for all my custom components where this functionality resides, but not having it in the first place would be better. 

When using  `connectField`  on my custom components, I specified `includeInChain: false` because setting this to `true` did not render anything at all. Could this be related to the validation.

How is the validator supposed to know about my custom inputs and validate them in the first place ?

**Comment by radekmie** [comment]
0. What have you tried? Every single component in this package is created using `connectField`.
0. You should use `includeInChain: false` only in _wrapper_ fields - fields which have nested fields.
0. Validator validates **model**, not **field**.

**Comment by EricSoldierer** [comment]
I tried to create my component with
```js
class Materials extends CustomBase {...
...
export const Material = connectField(Materials, {
  includeInChain: false,
});
```
rather than
```js
export class Materials extends CustomBase {...
```
When doing this, the data entered into my `input` field was not validated. I am using the same `input` as above, just removed the `onChange` method . The validation always states `somefield is required`. I suppose this was because the data is not set to the actual model. How can I set this data to the model ? Is it only done via the `onChange` method ?

**Comment by radekmie** [comment]
0. If you do `Y = connectField(X)`, then `X` is the _pure_ field and `Y` is the field, you should use in your forms.
0. Yes, model _**should**_ be changed only by `onChange`.

**Comment by EricSoldierer** [comment]
1. I did use the `Y` field.
2. If I can not change the model without doing `onChange`, when would I use `connectField` in the first place, if have to call `onChange` manually anyway.

**Comment by radekmie** [comment]
We have to clarify this or it will never end: you want to create a **field** _(any kind of input with corresponding field(s) in model)_, a **composite field** _(set of few fields, grouped logically)_ or a **fieldset** _(reusable block of form; set of unrelated fields)_?

* **Field**: `connectField`.
* **Fieldset**: ordinary component with optional access to context.
* **Composite field**: `connectField` with `includeInChain: false`.

_Normally, only fields should change model._

**Comment by EricSoldierer** [comment]
Ok, i will take a step back and explain the scenario. I have:

A nested schema for an `Exercise`:
```js
const Materials = new SimpleSchema({...});
const Duration = new SimpleSchema({...});
... // more schemas

Exercises.schema = new SimpleSchema({
  materials: {
    type: Materials,
    uniforms: {
      label: 'ui.materials',
      customElement: 'materials',
    },
  },
  duration: {
    type: Duration,
    uniforms: {
      label: 'ui.duration',
      customElement: 'duration',
    },
  },
  ...// more values
});
```

I then have two places where I render an `Exercise` form.
Also, I would like to render a complete custom UI for a `Material`, a `Duration` etc.

I now created a `CustomExerciseView` class used in the `AutoForm`.
```js
class CustomAuto extends React.Component {

  determineComponentFromProps(props) {
    switch (props.customElement) {
      case 'materials':
        return Materials;

      case 'duration':
        return Duration;
      ...
      default:
        return AutoField;
    }
  }

render() {
    const Component = this.determineComponentFromProps(this.props);
    return (
      <Component {...this.props} />
    );
  }
}

export const CustomExerciseView = connectField(CustomAuto, {
  includeInChain: false,
});
```

I did this because I can only specify one class in the `autoField` property of the `AutoFields`.

This is how one of my actual forms is being rendered:
```js
render() {
    return (
      <AutoForm
        schema={this.translator.translateSchema(ExercisesClientSchema)}// replace uniforms.label with actual translation
        onSubmit={this.onSubmit}
      >
        <SelectField
          name="category"
          placeholder={i18n.__('ui.chooseCategory')}
          transform={(value) => i18n.__('ui', value)}
        />
        <AutoFields autoField={ CustomExerciseView } omitFields={['category']}/>
...     
```

Now for the actual Materials class:
```js
export class Materials extends CustomBase {
  constructor(props) {
    super(props, 'materials');
  }

  render() {
    return (
      <Panel>
        <h3>{this.props.field.label}</h3>
        {this.props.fields.map((field) => (
          <div>
            <label htmlFor={field}>{this.getLabel(field)}</label>
            <input
              type="number"
              id={field}
              name={`${this.name}.${field}`}
              onChange={
                (event) => {
                  this.onChange(field, event);
                }
              }
            />
          </div>
        ))}
      </Panel>
    );
  }
}
```

The only component that is being created and used with a `connectField` is the `CustomExerciseView` in order to pass the `props` from the `AutoForm`.

This works now thanks to your help.

It allows me to use my `CustomExerciseView` and my `Materials` etc. in multiple places.

However, two questions:

1. Is there a better way to render  multiple of my custom components in the AutoForm without having to group them in the `CustomExerciseView`. I currently do this because i can only specify one class in `<AutoFields autoField={ CustomExerciseView }/>`
2. Is there a way to pass some parameters to my `CustomExerciseView` ? Something like `<CustomExerciseView a={() => {console.log("hello");}} b={5}>` but inside the `autoField={ CustomExerciseView }`

**Comment by radekmie** [comment]
1. Kind of:
```js
<AutoForm schema={...}>
    <MaterialFormPart />
    <DurationFormPart />
    {/* ... */}
</AutoForm>
```

2. Again, kind of:
```js
autoField={props => <CustomExerciseView a={...} b={...} {...props} />}
```

---

1. Why you can't simply do `<*Field />` in your `<Materials />`? Then it don't have to be a field.
2. There's a `fields` prop in your `Material` component - what is it?
3. Could you show your `CustomBase` component? I think, that this is the clue of this whole conversation.

**Comment by EricSoldierer** [comment]
1. I want to create a custom UI for some of the fields in my schemas. Like a slider to set a value from a range etc. Therefore i can't use a uniform `SomeField`.

2. It contains the attributes from the nested schema. So all the things I specify inside the Materials schema. By looping through this, I can render all the input fields required to create a new Material.

3. The intention behind this class is to put code in there that is shared by my `Materials` and `Duration` class:
```js
import { BaseComponent } from '../base.js';
import { BaseField } from 'uniforms';

export class CustomBase extends BaseComponent {
//BaseComponent is not relevant just more shared stuff in there
//nothing to do with uniforms or schema

  constructor(props, name) {
    super(props);
    this.name = name;
    this.getLabel = this.getLabel.bind(this);
    this.getField = this.getField.bind(this);
    this.onChange = this.onChange.bind(this);
  }

  getLabel(field) {
    return this.getField(field).uniforms.label;
  }

  getField(field) {
    return this.context.uniforms.schema.getField(`${this.name}.${field}`);
  }

  onChange(key, event) {
    let value = event;
    let field;
    if (typeof(event) === 'object') {
      switch (event.target.type) {
        case 'number':
          value = parseInt(event.target.value, 10);
          break;
        default:
          value = event.target.value;
          break;
      }
      field = `${this.name}.${key}`;
    } else {
      field = key;
    }
    this.context.uniforms.onChange(field, value);
  }
}

CustomBase.contextTypes = BaseField.contextTypes;
```

It abstracts the schema stuff like `uniforms.label` from the individual components. Same goes for the `contextTypes` etc. etc. The binding to them is done via the super call in the `Material` class where the name of the schema is passed in.

---

I ended up not using `AutoFields` at all. I also had some problems with laying them out and after all it is just easier to define the components myself.

I now do it with this inside the `AutoForm`:
```js
<Row>
          <Col md={4} xs={12}>
            <Panel>
              <CustomAutoField name="title"/>
              <CustomAutoField name="description"/>
            </Panel>
          </Col>
          <Col md={4} xs={12}>
            <CustomAutoField name="category"/>
          </Col>
          <Col md={4} xs={12}>
            <CustomAutoField name="image" setFile={this.setFile}/>
          </Col>
        </Row>
```

Yes, this means i have to specify all my components myself and also repeat the same code in the other file. But first of all it gives me absolute full control over the layout, and second, I can give parameters to the components when I need to. (as seen in the `image`). So it is not too bad.

**Comment by radekmie** [comment]
1. You can create fields for it to make it _really reusable_.
2. OK, so loop through it, but use uniforms fields, so it will be managed by form.
3. It's completely useless - basefield already provide you `label` _(from schema)_, `field` _(complete props)_ and `onChange` _(by default binded to your field name)_.

---

Example:
```js
const Materials = () =>
    <div>
        <SliderField name="x" />

        <div>
            <TextField name="y" />
            <AnotherField name="z" />
        </div>
    </div>
;
```
Is this enough?

**Comment by radekmie** [comment]
I think everything is already clear. If not, feel free to comment.
