### ISSUE TITLE
How to clear a form model

### ISSUE THREAD

**Issue by afmfe-iul** [vazco/uniforms#1107]
Hey there again! This issue is a feature/documentation/advice request given a use case we just faced.

Here's our use case: we have an `Autoform` to handle filters for a list. Those filters are saved to the url because we want users to be able to bookmark them, so we set the `Autoform` initial model to what was defined in the URL, so far so good! However we would like to have a button/link to clear the model (note, not reset to its initial value), so `formRef.reset()` didn't work for us.

We didn't find any example on how to solve this scenario with `uniforms`. In the meantime we found a "solution" that doesn't seem very safe at all, potentially very wrong also:
```ts
formRef.setState({ ...formRef.state, model: {} } as AutoFormState<unknown>);
```

Any help/advice would be very appreciated! 😃

**Comment by wadamek65** [comment]
Hi @afmfe-iul ,

While there is no built-in option to achieve what you would like, you can extend the form functionality yourself. You can simply create a subclass of the form you are trying to use and add additional method which would then call appropriate `setState` with any model you would like. [Here you can find some documentation on how to extend forms](https://uniforms.tools/docs/examples-custom-form/).

As a side note, while your current solution is not very idiomatic to react, I don't think it should pose any major problems. It does have a potential bug where a stale state could be overwritten. You should either be using the callback signature of `setState` or just omitting this part completely and just doing `setState({ model: {} })`

Please let me know if this helps you.

**Comment by afmfe-iul** [comment]
Thanks a lot for the quick reply @wadamek65 both tips are very helpful, I actually missed the callback pattern on `setState`! Will try to extend  `BaseForm` which likely solves the type issue also. Thanks ;)

**Comment by radekmie** [comment]
On top of extending the form, you can always change the `model` prop from the outside - as long as it's not `_.isEqual` with the previous one, it'll override it ([source](https://github.com/vazco/uniforms/blob/8cbb12516490c88d0ab0a71e2a7d467f92f4ae2f/packages/uniforms/src/AutoForm.tsx#L46-L48)).
