### ISSUE TITLE
React 18 compatibility

### ISSUE THREAD

**Issue by mariusrak** [vazco/uniforms#1109]
Hello, the project doesn't work with newest react 18

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: canny@0.2.0
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.0 || ^16.8.0" from uniforms@3.9.0
npm ERR! node_modules/uniforms
npm ERR!   uniforms@"3.9.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Please upgrade dependencies, thanks

**Comment by radekmie** [comment]
Hi @mariusrak! Have you checked whether it works by any chance? I have no idea whether or not the changes introduced in v18 will affect us.

When it comes to properly supporting it, the only downside I see is the fact that the majority of our tests is written in Enzyme and it doesn't work with v18... It's on radar though.

**Comment by mariusrak** [comment]
I didn't notice any issues with react 18

**Comment by idmadj** [comment]
Hey @radekmie, it would most probably be fine to add 18.1.0 to peer deps and continue using 17 with Enzyme until there is bandwidth to migrate that too. Uniforms doesn't use any of the client rendering APIs that broke: https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html

Let me know if I can help

**Comment by radekmie** [comment]
That's something we already considered but decided to postpone it a little. But as there's not much traction in updating the tests, I think we should do just fine with a note in the docs.
