### ISSUE TITLE
dateField in semantic

### ISSUE THREAD

**Issue by mprzodala** [vazco/uniforms#111]
When you use:
```js
<DateField name="someName" label="someLabel" />
```
this input display "datetime-local" field. I think it should display "date" field or you should change field name to DateTimeField.

Documentation has wrong field type in section "Fields components" there is "date-localtime" in field description.

**Comment by radekmie** [comment]
0. It renders `datetime-local` input, because it's the only one [widely supported](http://caniuse.com/#feat=input-datetime).
0. It's called `DateField`, because it operates on `Date` object.
0. I'll correct that typo, thanks!
