### ISSUE TITLE
DisplayIf (useForm) doesn't work with mui 5 theme

### ISSUE THREAD

**Issue by wight554** [vazco/uniforms#1118]
**Version**: 
```json
{
    "uniforms": "^3.10.0-rc.0",
    "uniforms-bridge-json-schema": "^3.9.1",
    "uniforms-mui": "^3.10.0-rc.0",
}
```
When using [DisplayIf](https://uniforms.tools/docs/examples-custom-fields/#displayif) field from docs (or any other custom field that uses `useForm`) , app crashes with following error:
```
Uncaught Invariant Violation: useForm must be used within a form.
```

**Comment by radekmie** [comment]
Hi @wight554. Make sure you have exactly one `uniforms` package in your dependencies. The best would be to update `uniforms-bridge-json-schema` and then check the `package-lock.json`.

**Comment by wight554** [comment]
> Hi @wight554. Make sure you have exactly one `uniforms` package in your dependencies. The best would be to update `uniforms-bridge-json-schema` and then check the `package-lock.json`.

re-checked, same with:
```json
{
    "uniforms": "^3.10.0-rc.0",
    "uniforms-bridge-json-schema": "^3.10.0-rc.0",
    "uniforms-mui": "^3.10.0-rc.0",
}
```

**Comment by radekmie** [comment]
@wadamek65 Could you take a look at that?

**Comment by wight554** [comment]
NVM it worked after `package-lock.json` regen with `node_modules` removal. But not too great migration-wise

**Comment by radekmie** [comment]
If that helped, then you most likely had duplicated `uniforms` package. It happens because we update the packages as well as their dependencies at the same time. For the future, just make sure that while updating the packages, there are no duplicates added.
