### ISSUE TITLE
JSON Schema

### ISSUE THREAD

**Issue by radekmie** [vazco/uniforms#112]
[JSON Schema](http://json-schema.org/) is a very good candidate for the next built-in schema. Writing a whole new validator is not the best idea, but using already existing one like [`ajv`](https://github.com/epoberezkin/ajv) or [`is-my-json-valid`](https://github.com/mafintosh/is-my-json-valid) is a good option as those seem to be quite popular and mature.

Thoughts? Ideas? Demands?

**Comment by radekmie** [comment]
@MacRusher
@macrozone
@serkandurusoy
@zeroasterisk

**Comment by macrozone** [comment]
never used anything but simple-schema, because i also use collection2 to validate on inserts and updates,  but for non-meteor-projects this might be interesting.

**Comment by serkandurusoy** [comment]
I would say the next evolution could somehow be related to graphql/apollo.

Frankly, I have never used uniforms outside of meteor either. Now I know
uniforms offers much more and is in no way strictly coupled with simple
schema, but I've always considered uniforms just because it indeed works
well with simple schema and I have not considered it for non-meteor
projects, you know just because much more widely accepted alternatives
exist.

But I would say, if uniforms were to somehow offer similar value with
graphql-based projects, it would prove to be even more beneficial.

**Comment by radekmie** [comment]
OK. As I can see, JSON schemas are not so popular _(at least here)_, so I'll close it and open separate issue for graphql-related ideas.

**Comment by mkrn** [comment]
JSON schema is great and is becoming a standard.
I would like to implement a JSON schema wrapper for uniforms.

At first I thought to convert JSON schema to Simpleschema and there is a convertor but won't be easy to use without meteor.

Let me know if someone have done this so far, otherwise i'd be happy to share once done if successful.

**Comment by radekmie** [comment]
@mkrn I don't think it would be a good idea, to mess it with SimpleSchema. If you want, I'd love to help you with it.

**Comment by mkrn** [comment]
@radekmie I'm starting at it right now.. trying to follow the MyLittleSchema example and documentation...

Some questions:

`this.schema[name.replace(/\.\d+/g, '.$')]` = what does this supoosed to mean? is it a way to reach to nested fields? what format the `name` would be in?

`getSubfields` - should it return `properties` for object and `items` for array? 

`getProps` - not sure where's the list of props that it could return.. Is title one of those - to be used in label? Just need to know the possible names.

Thanks for reaching out! Let me know how to best collaborate I could start repository - should it just export the Bridge extended class?

**Comment by radekmie** [comment]
At first, I'd suggest creating a PR with a new `JSONSchemaBridge`or `JSONBridge` directly in the `uniforms` package, just like the others. It's already on the roadmap to split them into packages.

About that regex: functions like `getField` will receive full field name, like `friends.0.name` - it's replacing all nested numbers _(array indices)_ with `$`, to treat them as _item of this array_.

About `getSubfields`: only nested object properties. It should be `[]` for arrays.

About `getProps`: well, you can return anything. Also, `label` and `placeholder` have a little different meaning, you can trace it [here](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/BaseField.js#L175).

**Comment by radekmie** [comment]
@mkrn?

**Comment by oluckyman** [comment]
I gonna make JSONSchemaBridge too, but more detailed [Bridge API](https://github.com/vazco/uniforms/blob/master/API.md#bridge) documentation will help dramatically. What I’m missing is detailed description for each method, something like this:
```
/*
 * Field's scoped error.
 *
 * @param {string} name Is it the name of the field with error?
 * @param {object} error ... ?
 * @returns {object} Is there specific format it should return?
 */
getError (name, error) { /* ... */ }

...
```

**Comment by oluckyman** [comment]
Another question about `validator`.
I’m gonna use `ajv` in my project, and seems I have to make a wrapper function `validator` which will be called this way `validator(model)`.
```
import Ajv from 'ajv';
import mySchema from 'mySchema.json'; // some JSONSchema

const validator = (model) => {
  // use ajv and `mySchema` to validate `model`
  // throw errors if any
};
```
And then use it like this:
```
const schema = new JSONSchemaBridge(mySchema, validator);

render () {
  return <AutoForm schema={schema} />
}
```

I’m wondering should `JSONSchemaBridge` tightly depend on `ajv` validator or is it possible to make a bridge validator-agnostic?

**Comment by radekmie** [comment]
`getError(name, error)` should extract error object for the field called `name` _(possibly nested, like `a.b`)_. What is this error object? It's either the `error` prop from your form or _(only in `ValidatedForm` and derivatives)_, the error returned from the validator, obtained from `getValidator`. `getValidator(options)` should return a function of type `model -> error`.

For example: [`GraphQLBridge`](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/GraphQLBridge.js#L191-L193) is completely validator-agnostic. Why? Because I've made a [_standard error format_](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/GraphQLBridge.js#L29-L36) for it. In short, it looks like this: `{details: [{name: 'a', message: 'A is required.'}, {name: 'c.d', message: 'Object C has a required field D.'}]}`. [Here](https://github.com/vazco/uniforms/blob/master/INTRODUCTION.md#graphql-definition) is an example of usage.

**Comment by oluckyman** [comment]
Thanks @radekmie! could you please provide similar explanations for all other methods in the Bridge:
```
    getErrorMessage (/* name, error */) {
    getErrorMessages (/* error */) {
    getField (/* name */) {
    getInitialValue (/* name, props */) {
    getProps (/* name, props */) {
    getSubfields (/* name */) {
    getType (/* name */) {
    getValidator (/* options */) {
```
What’s type of input parameters. With examples of arguments.
What’s expected as return value. With examples of return values.
Where the method is used.

I would like to organise that info into comments for Bridge.js and make a PR for you to review

**Comment by radekmie** [comment]
Sounds good to me, @oluckyman!

```js
class ExampleBridge {
    // Extract error object for the field called `name` from `error`.
    getError (name : string, error : BridgeError) : ?any {
        return error && error[name];
    }

    // Extract error message for the field called `name` from `error`.
    // If there's no error, return ''.
    getErrorMessage (name : string, error : BridgeError) : string {
        return error && error[name] && error[name].message || '';
    }

    // Extract all error messages from `error`.
    getErrorMessages (error : BridgeError) : string[] {
        return Object.keys(error).map(field => error[field].message);
    }

    // Schema-specific object passed as `field` prop.
    getField (name : string) : object {
        return {};
    }

    // Initial value of field called `name` with props `props`.
    getInitialValue (name : string, props : object) : ?any {
        return undefined;
    }

    // Additional props passed to the field called `name` with props `props`.
    // Props `label` and `placeholder` are somehow special, because of it's
    // inheritance style.
    getProps (name : string, props : object) : ?object {
        return {label: name};
    }

    // Names of subfields of field called `name`.
    // Example: for object {a: {b: 0, c: '', d: [1, 2, 3], e: {f: 0}}}
    //     getSubfields('a')   // ['b', 'c', 'd', 'e']
    //     getSubfields('a.b') // []
    //     getSubfields('a.c') // []
    //     getSubfields('a.d') // []
    //     getSubfields('a.e') // ['f']
    getSubfields (name : string) : string[] {
        return [/*...*/];
    }

    // Type of field called `name`, used for field component detection in the
    // <AutoField />. It's also passed as `fieldType` prop to the field.
    getType (name : string) : function {
        return String; // Or something.
    }

    // Validator used by <ValidatedForm /> and it's subclasses. These `options`
    // are passed through the `validator` prop of the form.
    getValidator (options : ?any) : (model : BridgeError) {
        // Here `validateWithOptions` is your function.
        return model => validateWithOptions(model, options);
    }
}
```

If you need more info or examples - let me know.

**Comment by oluckyman** [comment]
Currently I’ve switched to another project and put that task on hold. But I’m sure these comments will help anyone who works on their own Bridge implementation. @radekmie thanks a lot!

**Comment by waheed25** [comment]
i just want to know uniforms supported json schema or not???

**Comment by radekmie** [comment]
No, it's not at the moment.

**Comment by zeroasterisk** [comment]
❤️
