### ISSUE TITLE
Simplify label prop to a string type

### ISSUE THREAD

**Issue by wadamek65** [vazco/uniforms#1120]
Initially discussed [here](https://github.com/vazco/uniforms/pull/1091#discussion_r856300340).

Currently, we allow for `label` passed onto fields to be a `ReactNode`. This causes problems because `transform` for example expects it to be a `string` so passing a `transform` with a `label` that is a `ReactNode` may produce undefined behavior. This also breaks typings in a few places.

It may be best to simplify the `label` to only accept a `string` type.

**Comment by wadamek65** [comment]
@radekmie I did some digging and this is what I managed to figure out:

The `transform` prop was not present in the initial version of the material theme package. It seems to have been introduced [here](https://github.com/vazco/uniforms/commit/ab12392055bb200098c860d01c278ca241b01663#diff-f2776e6f23fbc0b5a4e1dac77af47ea2d91d268a81f3e6a4a1d6a107a1fd33dfR28). And this change probably comes from the fact that the `BoolField` implementation is nearly identical to `RadioField` implementation due to them being the same component in material. So my guess is that the `RadioField` implementation was copied and then readjusted slightly which resulted in the `transform` property being left over.

So it may make sense to just remove it in v4 to make it consistent across other fields and themes.

**Comment by radekmie** [comment]
@wadamek65 Then let's remove it. In the meantime, please do mark it as deprecated.

**Comment by kestarumper** [comment]
- We've decided to retain `label: React.ReactNode` wherever possible as this is desired behavior.
- We're removing `transform` in #806 so the problem disappears

**Comment by kestarumper** [comment]
Closed by #806.
