### ISSUE TITLE
CSRF / form signing

### ISSUE THREAD

**Issue by rrjanbiah** [vazco/uniforms#1128]
Documentation or an example for the form security handling

**Comment by radekmie** [comment]
Hi @rrjanbiah. uniforms are mostly used for forms handled with JavaScript, not the `action` parameter; if you'd like to do it, it's possible as well (see https://github.com/vazco/uniforms/issues/1060). However, it's up to you to implement any security measures required for your use case. For example, if you have a CSRF token generated by your server, you can use `HiddenField` to render a hidden input with the token.

**Comment by rrjanbiah** [comment]
@radekmie That makes sense. Thanks for sharing the insight. Will check that. Thanks again
