### ISSUE TITLE
Migrate tests from Enzyme to React Testing Library

### ISSUE THREAD

**Issue by radekmie** [vazco/uniforms#1130]
As Enzyme is no longer supported and we already rely on a community-made workaround for React v17 and there's nothing sure for v18 we should push for getting rid of it entirely.

Support for v18 was requested in #1109 and added in #1129.

**Comment by radekmie** [comment]
Maybe we could try https://github.com/enzymejs/enzyme/issues/2524#issuecomment-1117039658 to buy us more time?

**Comment by ErnestTeluk** [comment]
> Maybe we could try [enzymejs/enzyme#2524 (comment)](https://github.com/enzymejs/enzyme/issues/2524#issuecomment-1117039658) to buy us more time?

unfortunately it did not work (tested on react 17), when it comes to react 18 there is one more blocker which is https://github.com/facebook/docusaurus/issues/7264

**Comment by kestarumper** [comment]
- [x] [Migrated AutoField tests to @testing-library/react](https://github.com/vazco/uniforms/pull/1266)
- [x] [Migrated AutoFields tests to @testing-library/react](https://github.com/vazco/uniforms/pull/1271)
- [x] [Migrated BoolField tests to @testing-library/react](https://github.com/vazco/uniforms/pull/1268)
- [ ] ListField
- [ ] ListItemField
- [x] [Migrated NestField tests to @testing-library/react](https://github.com/vazco/uniforms/pull/1270)
- [x] [Migrate RadioField tests to @testing-library/react](https://github.com/vazco/uniforms/pull/1258)
- [ ] [Rewrite SelectField tests](https://github.com/vazco/uniforms/pull/1294)
- [ ] TextField
- [x] [Migrated SubmitField tests to @testing-library/react](https://github.com/vazco/uniforms/pull/1269)

src: https://github.com/orgs/vazco/projects/4/archive
