### ISSUE TITLE
Missing FileField in uniforms-unstyled

### ISSUE THREAD

**Issue by mariusrak** [vazco/uniforms#1134]
Hi, is there any reason why FileField is missing in uniforms-unstyled?
If no, can we add it, please?

**Comment by radekmie** [comment]
Hi @mariusrak. How would you like it to work? The only solution for a cross-theme one with no backend involved would be to use [a `type="file"` input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file), which I honestly rarely did directly. The other problem is that the "value" of such input is the [`FileList`](https://developer.mozilla.org/en-US/docs/Web/API/FileList) object, which won't fit into any of the schemas.

Usually, you use a library that provides some UI for that and provides you with a URL of the uploaded file.

Can you elaborate on how you see the `FileField`?

**Comment by radekmie** [comment]
As there's no answer, I'm closing this one. Feel free to comment further, though.
