### ISSUE TITLE
Date Field not updating visually

### ISSUE THREAD

**Issue by mbseid** [vazco/uniforms#1138]
When a field is configured to be a date only field (not date and time) the field value gets updated but the form field does not update. The form field continue to shows the placeholder. I tried to debug the issue but couldn't get to the core issue. It seems like the field temporarily shows the selected value then gets rerendered to show the placeholder.

Let us know what is happening. Do provide us with:

- Latest version of uniforms with all style frameworks. This issue happens in Firefox and Chrome.
- Setup Uniforms to use the following configuration:
```
new SimpleSchema2Bridge(
  new SimpleSchema({
   "date":{
      "type": Date,
      "defaultValue":new Date(),
      "uniforms":{
         "type":"date"
      }
   },
   "adult": Boolean,
   "size":{
      "type":"String",
      "defaultValue":"m",
      "allowedValues":[
         "xs",
         "s",
         "m",
         "l",
         "xl"
      ]
   },
   "rating":{
      "type":Number,
      "allowedValues":[
         1,
         2,
         3,
         4,
         5
      ],
      "uniforms":{
         "checkboxes":true
      }
   }
  })
)
```
- [Playground Link](https://uniforms.tools/playground/#?N4IgDgTgpgzlAuIBcIDqUA2BjA9gWygEIQAacCHMGZUAQwFd4cZaA3KZAM1ozjIaYt2AEUy0AnsgCMABhlkAJgEsWAIwxQFXHnxAZaqzMngR6UMmH1YoACxwYFUCNt7mQ0WgoDyAOwySkblcyGCwbKDxaZBAfKAB3AAIAZSU8SygksIjaACYAIQglBQBzKAAKAB0fBITYxJS0jUzwyLLgKpqEipAFWngobqR26s6a7vhxMAHkBOE-8w7Rrp6obnoMeAA1HjNButn5soBKEkXR7vofJU4cCDwYQeGl85AJqcHu3v7us86AXzOf1OI2WnnW8EGCTyOHsUFoPmBnW6MCUAC9pkNfmNXpMMd0kiYlD5it1EUtPqsGBtthhdshunhSVjQRgMDg4poaWYHsgANrMpEgAAePLJz2WooF2MZpClywwTJBz26QoVIGZAF1AWLuhA-kSSTRmeNcYMAHL0PCGCBiwU8NkchRc2CDflKpZSW1LHJe0YAZl9nQALIGagBWTW-i5XG53HmY90vLJYADWqhwQpdxlMA0TAJB-ZqfyOVSOpBAMDscQAkn4iVAAKIQCjOQI6Ny0GDiHxYXxJeiqPBKRBIExmfhdnu-GlFeYuOBA14tDgoPD0JQgP5AA)
![image](https://user-images.githubusercontent.com/547496/175076519-c0204038-f8af-44d8-8e43-ca7817064725.png)

**Comment by wadamek65** [comment]
Hey @mbseid,

Thanks for the issue report. I checked it out and there seems to be an inconsistency in the implementation of handling this date type across some of the themes. I've already started working on the fix.
