### ISSUE TITLE
Chakra UI support?

### ISSUE THREAD

**Issue by bard** [vazco/uniforms#1149]
I've played with Uniforms and other schema-to-form libraries, and I've found Uniforms well over the competition in terms of architecture and ergonomics. Would love to use it in actual projects, but most projects I work on nowadays use Chakra UI (which is similarly well designed and developer-friendly, and whose popularity is steadily increasing).

Unfortunately, in the time that I could devote to the experiment, I wasn't able to write a Chakra theme for Uniforms.

Is Chakra support anywhere on the radar?

**Comment by radekmie** [comment]
Hey @bard. We have a somehow standard policy when it comes to additional themes:
1. Create a theme yourself.
2. Use it directly in your project.
3. (Optional) Publish it on npm.
4. If it gains enough traction, we'll happily merge it in the main repo (i.e., this one).

There are a few community themes (I have to update docs on that, sorry!) and we're here to help if you have problems with creating one. But as we don't use Chakra UI ourselves, it's hard for us to tell how to do it properly.

Could you tell us what problems exactly you faced while creating your own theme? We do that quite regularly, but maybe there's something Chakra UI-specific.

**Comment by bard** [comment]
That makes complete sense!

It's been a while, but from what I remember, I tried to mimic the Material-UI theme, and got lost figuring what was there due to being needed by Material-UI, and what due to being needed by Uniforms. Having more time and cross-comparing with other themes would have helped (or maybe I didn't pick the theme that was the easiest starting point to begin with). It wasn't anything specific with Chakra.

Hopefully I'll find time to have another try!

**Comment by radekmie** [comment]
I think it'll be easier to start with `uniforms-antd` or even `uniforms-unstyled`, as both Material-UI and MUI themes are more complex due to typing. In any case, I'll close this issue for now, but feel free to ping us once you have something to show or will face some problems.
