### ISSUE TITLE
Implement a `zod` bridge

### ISSUE THREAD

**Issue by radekmie** [vazco/uniforms#1159]
While being focused on type inference, [`zod`](https://github.com/colinhacks/zod) makes a decent general schema library. By looking at the code of the [`deepPartialify`](https://github.com/colinhacks/zod/blob/59768246aa57133184b2cf3f7c2a1ba5c3ab08c3/src/types.ts#L1614-L1639) function, it looks like it'll be fairly easy to create a bridge for it. We won't use the typing part (for now...), but it'd make a nice addition for people who wanted to try out uniforms.

Thanks, @wadamek65, for the suggestion!

**Comment by javijupra** [comment]
I'm getting a 404 at this address:
[https://registry.npmjs.org/uniforms-bridge-zod](https://registry.npmjs.org/uniforms-bridge-zod)

**Comment by radekmie** [comment]
@javijupra It's not published yet - it'll be available with the first alpha release of v4.

**Comment by radekmie** [comment]
@javijupra It's released now: [`uniforms-bridge-zod`](http://npmjs.com/package/uniforms-bridge-zod).
