### ISSUE TITLE
Creation of Custom Date Field

### ISSUE THREAD

**Issue by Akshaya-009** [vazco/uniforms#1186]
While we are creating custom date field, it is taking type as 'datetime-local' and we are giving type as 'date', form value is not getting updated after selecting the date.

**Comment by kestarumper** [comment]
Hi @Akshaya-009,

I believe this has been fixed by #1140 and #1103. Could you provide us with what version of uniforms you are using?

**Comment by Akshaya-009** [comment]
We are using version 3.10.0. And in case of styles, it is uniforms-unstyled.

**Comment by kestarumper** [comment]
Try updating to `3.10.1` because the PR that I mentioned are included in that version. See [list of changes `v3.10.0...v3.10.1`](https://github.com/vazco/uniforms/compare/v3.10.0...v3.10.1).

**Comment by kestarumper** [comment]
I'm closing this issue because no the author has not responded within a week. I'm assuming that version `3.10.1` fixes the issue, however, if it's not, then please let us know.
