### ISSUE TITLE
Support SimpleSchema v3

### ISSUE THREAD

**Issue by JanMP** [vazco/uniforms#1189]
SimpleSchema2Bridge does not entirely work with simple-schema v3. At first glance Forms still seem to work with v3 but at least SimpleSchema2Bridge.getSubfields does not seem to work anymore.

**Comment by radekmie** [comment]
Hi @JanMP! As far as I understand https://github.com/longshotlabs/simpl-schema/pull/465, which is the only changelog I found, the only breaking change that affects uniforms is the removal of `SimpleSchema._makeGeneric`. The suggested replacement is to use the `mongo-object` package directly, which is fine, as it's a dependency of `simpl-schema` anyway. Alternatively, we could normalize it ourselves, as [it's a very simple function](https://github.com/longshotlabs/node-mongo-object/blob/main/lib/util.ts#L201-L212).

Anyway, it'd be great if you could see if patching `SimpleSchema._makeGeneric` is enough.

**Comment by JanMP** [comment]
That function isn't there in simple-schema 1.12.3 (wich works for me) either and patching it in in V3 doesn't seem to do any good (maybe I did not patch it in the right place...).
Then I tried calling `bridge.getSubfields(makeKeyGeneric(key))` wich did not fix the problem either, but then I took a closer look it and found this seems to be an edge case for key being an empty string (wich works fine with 1.12.3).
Using a modified makeKeyGeneric on the key works.

```
export default function makeKeyGeneric(key: string): string | null {
  if ((typeof key !== 'string') || (key == '')) return null;
  return key.replace(/\.([0-9]+|\$\[[^\]]*\])(?=\.|$)/g, '.$');
}
```

**Comment by radekmie** [comment]
What I meant was to do something like this:
```ts
SimpleSchema._makeGeneric = name => MongoObject.makeKeyGeneric(name);
```

And see if it works. Doing `bridge.getSubfields(makeKeyGeneric(key))` instead won't work, as `getSubfields` uses `SimpleSchema._makeGeneric` anyway.

**Comment by JanMP** [comment]
Ah ok. I took a look at the source of SimpleSchema2Bridge and figured that I need to do the patching of SimpleSchema in there. That works with my revised makeKeyGeneric but not with mongo-object.makeKeyGeneric. And my attempt with `bridge.getSubfields(makeKeyGeneric(key))` (in my own code) does work.  I don't get how it works either, but it does. And it also works with fields of type Object (tat's the place where the bridge uses getSubfields itself and I did not fix that with this method).

**Comment by radekmie** [comment]
I tested it quickly and this workaround works:
```ts
SimpleSchema._makeGeneric = name => name?.replace(/\.\d+(\.|$)/g, '.$$$1');
```

I suggest you try it out for now as updating the packages to make them work with v3 will take more time due to an overhaul of their typings.

**Comment by JanMP** [comment]
Where do you apply that workaround? I could not make the other workaround work from my own application code but had to apply it inside SimpleSchema2Bridge.

**Comment by radekmie** [comment]
Do that in your app's code, before uniforms are used.

**Comment by mariusrak** [comment]
Hi, I've also stumbled across this issue. Would it be possible to make hotfix for uniforms if this is that simple? It is no workaround to change node module code directly and applying the workaround in project after import doesn't work. So the only way is to hotfix the bridge.
Thanks.

**Comment by radekmie** [comment]
Yeah, I think we could release this as a workaround. However, when I tried updating the repo to v3 to run our tests, there's a lot of type problems... We'll discuss it tomorrow and let you know here and in the PR.

**Comment by radekmie** [comment]
We've decided to make it in v3 of uniforms - I'll review the PR.
