### ISSUE TITLE
Cannot unselect a SelectField that is optional

### ISSUE THREAD

**Issue by todda00** [vazco/uniforms#119]
Expected behavior: When a field in the schema is optional, the SelectField will have an option to de-select the selection.

Placeholder works only until the user clicks on the select box, then they are presented with all the options, but no way to remove their selection.

Example schema:
```
...
minEnrollment: {
    type: Date,
    optional: true,
    label: 'Earliest enrollment term',
  },
...
```

Example SelectField:
```
<SelectField
  name="minEnrollment"
  allowedValues={enrollmentRangeOptions()}
  transform={enrollmentRangeDisplay}
  placeholder="--Select Enrollment Term--"
/>
```

HTML Output (nothing selected yet):
![nothing-selected](https://cloud.githubusercontent.com/assets/8363924/19766948/78aba354-9c1e-11e6-8b5f-0ca2936d8404.png)

Initial click into dropdown:
![fullscreen_10_27_16__8_19_am](https://cloud.githubusercontent.com/assets/8363924/19766972/91a45914-9c1e-11e6-88b9-680a171b4577.png)

HTML Code:
![html](https://cloud.githubusercontent.com/assets/8363924/19766989/aceda23e-9c1e-11e6-8211-27229a1e217e.png)

It seems the disabled and hidden need to be removed from the placeholder, although I would think this would have more implications in other use cases. I found #78 referencing the same issue as well.

**Comment by radekmie** [comment]
I think, that change from:
```js
<option value="" disabled hidden>
```
to
```js
<option value="" disabled={required} hidden={required}>
```
would be enough. And now, there's a question - will it break anything?

**Comment by radekmie** [comment]
Also changing to an `<option />` with empty value _(the unselected one)_ could remove it from the model, but this might be tricky, when it will be nested inside an array and an object...

Any thoughts, @todda00?

**Comment by radekmie** [comment]
It looks great, @todda00!
