### ISSUE TITLE
How to disable the form if all fields are empty?

### ISSUE THREAD

**Issue by satsathish1710** [vazco/uniforms#1208]
I have to disable submit when all fields in form is empty 

And if there is any state like invalid, pristine or dirty it would help to validate easily

**Comment by radekmie** [comment]
Hi @satsathish1710. uniforms have a slightly different approach here and there are no such field-centric values here. To block the submit button if the form is invalid (i.e., the model does not match the schema), then you can do it quite easily: [check for `context.error`, just like the builtin `SubmitField`s](https://github.com/vazco/uniforms/blob/e9c8ab63830b42cfc063f17ddc275c494fc773f6/packages/uniforms-antd/src/SubmitField.tsx#L20).

As for the pristine/dirty/touched state of a field, feel free to file another issue with more details what exactly you'd like to see in uniforms.

**Comment by radekmie** [comment]
I'll close this one as there's no answer so far. Feel free to comment further if needed.
