### ISSUE TITLE
Improve getNativeFormProps in bridges to a more specific type

### ISSUE THREAD

**Issue by wadamek65** [vazco/uniforms#1212]
In #1044 the types of `getNativeFormProps` methods in bridges were improved. I believe we can add more exact typings to the returned value here by also specifying the `children` prop type. Possibly other form props as well? Perhaps we could base the type on the native form prop types provided by React and omit all the necessary properties. [Method in question.](https://github.com/vazco/uniforms/blob/6353c831673adc9a786932c4ab60483c59de3d9c/packages/uniforms/src/BaseForm.tsx#L180-L208)

Example problematic case when creating a custom `Form` component by extending the `BaseForm`:

```ts
	public render() {
		const {children} = this.getNativeFormProps()
		return (
			<div>
				{children}
			</div>
		)
	}
```

which produces the following type error:

```
TS2322: Type 'unknown' is not assignable to type 'ReactNode'.   Type 'unknown' is not assignable to type 'ReactPortal'.
```

**Comment by radekmie** [comment]
To make it clear: we did that in the first place, because of React Native compatibility. But as this is a rather small percentage of uniforms users, we can make it easier for the rest at a cost of some _unused_ typings in RN.
