### ISSUE TITLE
[MUI] and [Material] `min` and `max` properties are not being applied to a Date field

### ISSUE THREAD

**Issue by vcardins** [vazco/uniforms#1213]
The `min` and `max` properties are necessary to avoid that arbitrary values re entered in a `Date` type field, however, even setting 
```javascript
<AutoField
	type="date"
	variant="standard"
	min={<any value>}
	max={<any value>}
/>
```
they are not applied.

The code

![image](https://user-images.githubusercontent.com/2383329/215632988-f06f8c9f-9b61-4984-b03c-5ac4919ef4eb.png)

generates the html

![image](https://user-images.githubusercontent.com/2383329/215633117-421defca-6c22-448c-8943-3c43584da4b5.png)

**Comment by radekmie** [comment]
Hi @vcardins and thanks for the report! That's true, neither of these two themes supports that, but all of the other themes do. Feel free to file a PR with that!

**Comment by vcardins** [comment]
@radekmie Please review https://github.com/vazco/uniforms/pull/1215.
