### ISSUE TITLE
MUI Textfields do not register text when using vite to create a react app

### ISSUE THREAD

**Issue by petercinibulk** [vazco/uniforms#1217]
Steps to reproduce:
1. Create a react app using Vite https://vitejs.dev/guide/
2. Install uniforms and mui dependencies
3. Copied example from https://uniforms.tools/docs/tutorials-basic-uniforms-usage/ into App.tsx

When typing in the textfield, no text appears.

**Comment by petercinibulk** [comment]
After further debugging it seems that React 18's createRoot is the problem. Using the same steps above:
```
import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import "./index.css";
import { render } from "react-dom";


const root = document.getElementById("root") as HTMLElement;
render(
    <React.StrictMode>
        <App />
    </React.StrictMode>,
    root
);
```
This works!

```
import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import "./index.css";
import { render } from "react-dom";

ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
    <React.StrictMode>
        <App />
    </React.StrictMode>
);
```
This does not

**Comment by petercinibulk** [comment]
Turns out removing React.StrictMode fixed it

**Comment by radekmie** [comment]
Hi @petercinibulk and sorry for the late response! `StrictMode` compatibility is tracked in #1194.
