### ISSUE TITLE
FR: allow omit=true in schema to exclude fields in autoforms

### ISSUE THREAD

**Issue by macrozone** [vazco/uniforms#122]
Similar to aldeed:autoform (https://github.com/aldeed/meteor-autoform#putting-field-attribute-defaults-in-the-schema):

```

new SimpleSchema({
  createdAt: {
    type: Date,
    uniforms: {
      omit: true
    },
    autoValue() {
     //...
    }
  },

```

this should exclude the field from ever be rendered in an autoform.

what do you guys think?

**Comment by serkandurusoy** [comment]
Hmm, this may actually be also useful for #123 if used in conjunction

**Comment by radekmie** [comment]
It's quite achievable even [right now](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/bridges/SimpleSchemaBridge.js#L163-L170):

```
import {nothing} from 'uniforms';

const schema = {
    createdAt: {
        type: Date,
        uniforms: () => nothing // or null, if React@0.14 compatibility is not needed
    }
};
```

I know, it's not the best option, but... Well, one of mine components accepts an `omit` prop. How about `uniforms: false`?

---

How it exactly should work? I mean: empty `AutoField` is OK, or not? If no, then it's quite big change.

**Comment by radekmie** [comment]
Any thoughts?

**Comment by macrozone** [comment]
@radekmie:

The second way works for me:

```
const schema = {
    createdAt: {
        type: Date,
        uniforms: () => null // does not work for me
    },
    updatedAt: {
        type: Date,
        uniforms: {
           component: () => null // that's ok!
        }
    },
};
```

I think empty Autofield is ok. 

It would be best to just exclude it from Autoform (without Autofield's in it), but render it normally, if is requested explicitly:

```
<AutoForm>
   <AutoField name="createdAt" /> // this should render normal
</AutoForm>
```

something like `uniforms: false` might therefore not be the best solution, because you might want to define a custom component in the schema , in case it is requestd explicitly.

**Comment by radekmie** [comment]
@macrozone I understand you, but I'm still not convinced to `omit: true`... Do you have a different idea?

**Comment by vladejs** [comment]
I think it should be implemented as in AutoForm.

**Comment by radekmie** [comment]
@vladejs 

> I think it should be implemented as in AutoForm.

What do you mean?

**Comment by vladejs** [comment]
I mean that you should be convinced about implementing: `omit: true` property. It worked well in AutoForm   (blaze version) so it should here too

**Comment by radekmie** [comment]
@vladejs OK, it's all right in both SimpleSchema and SimpleSchema2, but not so obvious in GraphQL - there's no place for _non-props_ data. I'd like to have a general solution.

**Comment by Floriferous** [comment]
I'd be really interested in this feature. What is the current best way to hide a few fields from a large schema when using AutoForm ?

**Comment by radekmie** [comment]
@Floriferous there's no the _best_ way, more, there's no even a _desired_/_standard_/_suggested_ way to do it. If you are using only `AutoForm` _(without using `AutoField` explicitly, [this](https://github.com/vazco/uniforms/issues/122#issuecomment-258089742) is a good option)_. Custom `AutoField` is also an option _(it might have a more complex logic to filter fields)_.

**Comment by matheusjardimb** [comment]
I'm getting this error:
```
Error: Invalid definition for deleted field: "uniforms" is not a supported property
  at myproject/node_modules/simpl-schema/dist/SimpleSchema.js:910:13
  at Function._.each._.forEach (myproject/node_modules/underscore/underscore.js:158:9)
  at checkAndScrubDefinition (myproject/node_modules/simpl-schema/dist/SimpleSchema.js:908:24)
  at myproject/node_modules/simpl-schema/dist/SimpleSchema.js:487:50
  at Function._.each._.forEach (myproject/node_modules/underscore/underscore.js:158:9)
  at SimpleSchema.extend (myproject/node_modules/simpl-schema/dist/SimpleSchema.js:486:28)
  at new SimpleSchema (myproject/node_modules/simpl-schema/dist/SimpleSchema.js:94:10)
  at meteorInstall.imports.api.companies.companies.js (imports/api/companies/companies.js:41:20)
  at fileEvaluate (packages/modules-runtime.js:197:9)
  at Module.require (packages/modules-runtime.js:120:16)
```

when using the following schema:
```
import SimpleSchema from 'simpl-schema';
...
Companies.schema = new SimpleSchema({
  deleted: {
    type: Boolean,
    uniforms: () => null,
  },
...
```

I'm using v1.17.2. Am I missing something?

**Comment by radekmie** [comment]
@matheusjardimb have you imported `uniforms` package elsewhere before this? [It's required](https://github.com/vazco/uniforms/blob/master/INTRODUCTION.md#simpleschema-definition).

**Comment by matheusjardimb** [comment]
@radekmie No, I didn't. :flushed: Now it's fixed. Thanks!

**Comment by radekmie** [comment]
Suggested solution:

```js
// GraphQL
const schema = new GraphQLBridge(type, validator, {
    // Use `nothing` from `uniforms/nothing` for compatibility with React@0.14.
    example: {component: () => null}
});

// SimpleSchema
const schema = new SimpleSchema({
    // Use `nothing` from `uniforms/nothing` for compatibility with React@0.14.
    exampleA: {type: String, uniforms: () => null},
    exampleB: {type: String, uniforms: {component: () => null}}
});

// To render default component
<AutoField name="exampleA" component={undefined} />

// To render different component
<AutoField name="exampleA" component={Component} />
```

After a long time, I'm finally closing it.

**Comment by matheusjardimb** [comment]
@radekmie great! 

BTW, is it in the docs? It may be easier to new lib users to find it instead of looking into closed issues ;)

**Comment by radekmie** [comment]
@matheusjardimb not yet. Would you like to submit a PR with it?

**Comment by aleksandrenko** [comment]
This is not working. 
Is the hidden field with uniforms: () => nothing is required the form is still unsubmitable. It will require the field.

The only sustainable way is to create custom form :/ 👎

**Comment by radekmie** [comment]
This field is **hidden**, not removed from schema - you probably want to make it optional.
