### ISSUE TITLE
Add buttons for ListItems don't work

### ISSUE THREAD

**Issue by manchuwook** [vazco/uniforms#1220]
I've tried bootstrap-5, mui-5, and even unstyled - none of them have a working add button for a ListItem.  The closest I got was that MUI-5 shows a section and a button, but clicking it does nothing.

![image](https://user-images.githubusercontent.com/431161/218319732-371ac73b-1b3b-4f28-ab17-5ba8a0070122.png)

Do I need something to be loaded at the App.tsx level?

**Comment by manchuwook** [comment]
Please ignore this, going to GitHub discussions on this instead

**Comment by radekmie** [comment]
Hey @manchuwook. You can always convert an issue into a discussion on GitHub. In any case, I'll continue there.
