### ISSUE TITLE
Uniforms and autotests (ui.vision, selenium)

### ISSUE THREAD

**Issue by slavb18** [vazco/uniforms#1222]
Generated input controls have numeric id, like id=uniforms-0002-0002
This lead to ui test generation problem.
When we record test in [ui.vision](https://ui.vision/), it generates command like 
```
{
      "Command": "click",
      "Target": "id=uniforms-0002-0000",
      "Value": "",
      "Targets": [
        "id=uniforms-0002-0000",
        "name=firstName",
        "xpath=//*[@id=\"uniforms-0002-0000\"]",
        "xpath=//input[@id='uniforms-0002-0000']",
        "xpath=//input",
        "css=#uniforms-0002-0000"
      ],
      "Description": ""
    },
```

But when form changes, ids could be shifted, and generated test will fail.

Is there possibility to generate constant ids on input elements for autotests?

**Comment by radekmie** [comment]
Hi @slavb18. uniforms provide unique IDs by default, but as you've noticed, the exact values change when the form does (and only then). If you'll provide a `id` prop to the field, it'll take precedence over the automatically generated ones. You can do that in React props or in the schema.
