### ISSUE TITLE
uniforms-bootstrap5 is setting the maxLength in the wrapper, instead of in input

### ISSUE THREAD

**Issue by rrjanbiah** [vazco/uniforms#1223]
Hope, the below screenshot helps better than the description:

![image](https://user-images.githubusercontent.com/4907427/219856747-bf7d11e0-f781-47e9-945c-96d3fb66088b.png)

**Comment by radekmie** [comment]
Hi @rrjanbiah. Thanks for the report! It affects other themes too, as well as other properties, e.g., `minlength`.

**Comment by rrjanbiah** [comment]
@radekmie I thought of fixing and raising a PR. If it affects all themes, should that be fixed at every theme level or somewhere in a single place. In that case, please pinpoint the location as that will help me. Thank you

**Comment by radekmie** [comment]
You can start [here](https://github.com/vazco/uniforms/blob/482d8993324be0eca6ec5717bf592c66050caa91/packages/uniforms-bootstrap5/src/TextField.tsx#L14-L34), with Bootstrap 5 - it's basically the same in other themes. And make sure to add tests too!

**Comment by rrjanbiah** [comment]
Thank you. Will work on it
