### ISSUE TITLE
Bad documentation

### ISSUE THREAD

**Issue by stuk88** [vazco/uniforms#1224]
First of all, I'd like to say thank you for developing this great library!
It works great and super easy to control once you understand the schema.

But. I want to add that the doc in the website and in here, are lacking.

In the schema-json - it should write in the website in the Bridges, that it does not support Date, List, or any other complex form fields.

In Simple Schema - it should write the schema that is displayed in the playground, and add a link to here:

https://codesandbox.io/s/priceless-bush-f6l5kt?file=/schema/all-fields-schema.tsx
https://github.com/longshotlabs/simpl-schema#schema-rules

That way it's easier to understand the schema and its capabilities.

**Comment by radekmie** [comment]
Hi @stuk88. As you've pointed out a few things in one issue, let me reply to them one by one.

> In the schema-json - it should write in the website in the Bridges, that it does not support Date, List, or any other complex form fields.

`JSONSchemaBridge` supports both dates and arrays, as well as nested objects (I hope that's what you meant by "other complex form fields"). Both arrays and objects work out of the box ([playground link](https://uniforms.tools/playground/#?N4IgDgTgpgzlAuIBcICCATd0YwAQAoApAZQHkA5YgYwAsoBbAQwEoQAacCAezBmVEYBXeFxiMAblGQAzRgBs4HISLGSAIlDmMAnsgCMABgMd0ASzEAjOVHQz5ikFoubk8CIKgcwWqlBpc5dCgIOwVPEGhGdFIAOzldJFkwjhhaBkZkEHx8ZlwAXgA-XGAAHRjcXCouGJh4XEYAK3F83BioAHdcVCb8UvKK-rk5AFEIbggYJFw3DzYygdxBOA1ZQTl4Sen3T3mBgGsobXauCHRNgG0AckEY02kT-hhLgF05_oBfZgBuXaqautSdCYLT6C3g2jAUCmly4FgaUCo8EubwWkB4wXgplgU1BC1w0ncpg2ON2eOmEKhuEujDGOmRpLxRIYm1xZIq4Mh0NqEFMMQA5vT-mT3ii8SKGRVJHyEIwrNjihKBhzKdTadpBWzcEzHjjcAASaDSaEAYgA9HqgtIYKapXysZdcOKhQMnQtXQMLVArSTnZKoHy7ZTWXjldDYfDERq2dAAI6CUzQdBTK62rHkRj0KDIqmpqAAGVMBxeorJaMhEEx8uDZNz6czPs1YIpXLcvIFJcbQVSPLAmOq0IAKnRWhmoLguNJpsOpTK5QA6KOa92a3MFg4Nxvs5tUixcAJQRgxRed2BUHt9mLQtRcXAASVwckLY_gNHMuBn8Fl1gA_MfhR23QAx0O3dd4fhiXZpBuRFTGqSpIngKAADV5FMdBGBECB8EBdJcmDP5anfVD0MwlpGnEOcqnoMBTGsbC0iYb4ygZaB4EECBynweguCCORckKBVfSIx8SJOLieM0JiIKEu4CHEYiMJOOdgnGPAADI1OEtDFIgZSxhOGA52sfkXzwxUKlY9jymAXAgk_WjNnkkSdL01THXA4UGTA3Z3mY_oCIBBjGBQ5zSLyeCD0QkLtMw-igRYcDdksjjWg6XASAoah4oAIR5dBpTi9I2FwHCmGi0SICkz4cnYEAYH8dpbziXkoFGcZQgcRgYG0GIqFiYhBAsegiQ68Iup6vqYnKjCpESewoBFEAXwYWaQEPeBbHeIA)).

Dates require a little more work, as one, these have to be configured in Ajv (I recommend [`ajv-formats`](https://ajv.js.org/packages/ajv-formats.html)) and then transformed from `Date` objects, that uniforms operate on, into `string`s, that Ajv operates on. That can happen in the `modelTransform` function (only for the validation) or even in the validator itself. Here's a [playground link](https://uniforms.tools/playground/#?N4IgDgTgpgzlAuIBcICCATd0YwAQAoApAZQHkA5YgYwAsoBbAQwEoQAacCAezBmVEYBXeFxiMAblGQAzRgBs4HISLGSAIlDmMAnsgCMABgMd0ASzEAjOVHQz5ikFoubk8CIKgcwWqlBpc5dCgIOwVPEGhGdFIAOzldJFkwjhhaBkZkEHx8ZlwAXgA-XGAAHRjcXCouGJh4XEYAK3F83BioAHdcVCb8UvKK-rk5AFEIbggYJFw3DzYygdwAekXcYZjGKyhcAAN0RngoAFp4U3oobdxpLggmeAA6eYGrm_3J4twAcj2D49OoD6mMy2AF85v0KgBrKDadrXdBvADaH0EMVMz3oMA-AF0wQtBHANLJBHJ4G8gbjcMDmABuMqPKo1OqpOhMFp9BbwbRgKBTD5cCwNKBUeAfCkVSA8YInWBTYC4KAAD0Y9G8PPenO5vNqEFMMQA5qLLtdbrzvkcTmcPpTKWLcNAAI6CUzQdBTJGK5Wq7GPYG0mKPaQo4WmaqVSIHABq8lM32u-GZ6Vy7IGDNquHE0djEBajXEdyqKtM1njaSYNLp4LtCEEEHK-HoXCCclyhWKjwWy1wABUIIwaujpnRcGbcEwYoJ5PEHpWKg2m2zcHcl3PNGx5UqVdYpiu5HcPZuoAB-O4iEgUHKUv0LCoZuQx_Zxnfl_0z3Bogi3-8iCB7sbXPAAGQAemmYPj-wTjDAdzWPq8A0Em7bXtA8A1uUcpBPAjBFm8n5Zr-kGXohFTAohvo-hWFSpkypaMFGd5Zi0VDhlAdFfnGCZln6jzIahrQdLgZ6UDRABCOroHqUAliyjBrhxtGgd-z5Ujk7AgDA_jtAAknEupQKM4yhA4jAwNoMRULExCCBY9CmIgiT2OExmmeZMSsWahlQKCIBwQwUgoH28C2MCQA) that does exactly that.

> In Simple Schema - it should write the schema that is displayed in the playground, and add a link to here: [...]

I don't understand this point, sorry. We have a strong assumption, that if one decides to use schema X, they know how to use it, or know where to find the documentation about it. However, I agree that we could link their docs to ease the usage.

**Comment by radekmie** [comment]
As there's no follow up, I'll close this one. Feel free to comment, though!
