### ISSUE TITLE
Getting Invariant error Field not present in schema  file.0

### ISSUE THREAD

**Issue by sathish2k** [vazco/uniforms#1249]
I have schema like this

```
{
title: 'file',
type: 'array'
}
```
I wanted to build a custom component which will accept multiple files

**Comment by radekmie** [comment]
Hi @sathish2k. File upload is not something we plan to handle in uniforms, but you can wire any file upload component with it. Usually, you upload the files directly to some storage and get a URL (or other key) of it, and store it instead. As it's usually a string, an array of strings handles such case just right.

**Comment by satsathish1710** [comment]
Hi @radekmie ,

How to upload binary files and what is the type for binary in JsonSchema

**Comment by radekmie** [comment]
There are many ways of doing that, and many packages that take care of this complexity. As I said, usually you don't store binary data, but only the URLs (strings) instead.

In any case, this topic is not related to uniforms but file upload, so I'll close it.
