### ISSUE TITLE
Question about ListField usability.

### ISSUE THREAD

**Issue by mattscooter** [vazco/uniforms#125]
I have a set of fields defined as an object array in my schema.  This is really similar to the "addresses" example on your demo app. 

I have everything working ok, except that I have noticed that when adding a new item to the list by pressing on the add/plus icon any unsaved data entered in the existing fields is cleared out. 

From a usability perspective this is bad.  Lets say the user adds one set of records and completes the details, then they realise that they want to add a second item.  Everything they've entered will be lost.  This would be especially annoying for them if the list contains a large number of fields.  Also if the user modifies an existing record and then hits add the existing data rows are reverted to the saved data.  If the user isn't paying attention then they may miss the fact that their data has been reverted.

The same thing is happening with the remove/minus button.

Is there any way that we can keep any data already entered when the user clicks to add or remove rows?

If you want to see this in action the checkout the addresses example in the demo app.

**Comment by radekmie** [comment]
At first I was like: _What? Really?_ Now I've tested it and... Yes - it's a very, *very* big issue! It was working before, exactly how you described it. I'll take care of it later today.

**Comment by radekmie** [comment]
Okay, the issue is right [here](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/components/fields/BaseField.js#L59-L67). If you are not changing the length, then the `ListAddField` and `ListDelField` have the old value, so pressing `+` or `-` is _resetting_ it. Maybe you want to create a PR for it?

**Comment by radekmie** [comment]
Check version `1.4.1`.

**Comment by mattscooter** [comment]
Thank you so much!  

I have just tested 1.4.1 and it's working properly now.
