### ISSUE TITLE
DisplayIf required validation and on hide still data passes to model

### ISSUE THREAD

**Issue by sathish2k** [vazco/uniforms#1254]
I wanted to pass a validation [required] for displayIf component on only showing condition and once hiding the validation should not happen

**Comment by radekmie** [comment]
Hi @sathish2k. Can you confirm if it's about the uniforms package or the Forminer (previously Form Builder)? Also, we could help you faster if you'd share an example of what you'd like to achieve.

**Comment by radekmie** [comment]
No response so far, so I'm closing. Feel free to comment further!
