### ISSUE TITLE
Layout of ListFields using Bootstrap 3

### ISSUE THREAD

**Issue by mattscooter** [vazco/uniforms#126]
I want to have more control over where the Add and Remove item buttons appear as well as how my subforms are layed out.  

For example I want the delete icon on the right for some of my forms and on the left for others.  I want the label to be outside the panel aligned with the other field labels.

I have tried playing with the CSS but that can only get me so far especially since there are embedded classnames in the ListItemField to control where the add and remove Icons are displayed.

Is this something that I can achieve by using the ListAddField and ListDelField and manually setting up my layout?  I can't seem to find any examples of using these fields directly.

Or is it a matter of taking a copy of and building my own versions of the ListField and ListItemField to layout everything the way I want?

**Comment by radekmie** [comment]
Take a look at the [`ListField` source](https://github.com/vazco/uniforms/blob/master/packages/uniforms-bootstrap3/src/components/fields/ListField.js). It's the biggest component I think, but it's very easy to create a custom one. If you want to customize only the `ListDelField`, then take a look at the [`ListItemField` source](https://github.com/vazco/uniforms/blob/master/packages/uniforms-bootstrap3/src/components/fields/ListItemField.js). Then you have to decide, if the `ListField` is OK for you - if not, create custom `ListField` _(and, optionally `ListItemField`)_. If it's OK, then create custom `ListItemField`and use it like this:

```js
<ListField>
    <CustomListItemField name="$" />
</ListField>
```

I hope it's clear now.
