### ISSUE TITLE
How can I send defaultValue to AutoForm

### ISSUE THREAD

**Issue by burakakca** [vazco/uniforms#1260]
For example i have an state machine and it's stores user information and I'm using multiple steps form. When I want to go previous form for some changes I need to see ( Stored value must fill in the AutoForm ) stored user information data after I send.

Can  I do that? or How?

**Comment by radekmie** [comment]
Hi @burakakca. The `AutoForm` component accepts `model`, just like any other `Form` component in uniforms. You can pass the `model` to it and update yours after `onSubmit` happens. (Alternatively, you can watch for `onChangeModel`.) Let me know if that's clear now.
