### ISSUE TITLE
Support v5 of AntD

### ISSUE THREAD

**Issue by radekmie** [vazco/uniforms#1261]
Firstly check, whether it's possible to support both v4 and v5 with the same code. If so, do that. If not, we'd need to create a new theme, just like with Bootstrap.

**Comment by Monteth** [comment]
AntD v5 seems to be significantly incompatible with v4, so we'd need to create a new theme for it. AntD v4 is quite a popular theme for uniforms, and AntD v5 itself seems to be widely adopted, so it would be nice to officially support it. We need to consider implementing it after releasing uniforms v4.

**Comment by fschmutz** [comment]
Great work on uniforms! 
Many of us maybe are eagerly waiting for the update to make it compatible with v5 to move along with React 18 advancements.
We appreciate the hard work involved and are keen to support in any way we can to help make this transition happen. Looking forward to the update and how we can contribute!
