### ISSUE TITLE
ZodBridge should ignore literal property type

### ISSUE THREAD

**Issue by kziemski** [vazco/uniforms#1262]
- uniforms-zod-bridge
Properties defined as z.literal("string") should be ignored in Forms

crashing in [getType](https://github.com/vazco/uniforms/blob/cf3d3da51dff980f677bef26c32850dc0245b689/packages/uniforms-bridge-zod/src/ZodBridge.ts#L245)
for instance 
const PersonSchema = z.object({ __typename: z.literal("Person").optional(), name: z.string().min(1) })
const schema = new ZodBridge(PersonSchema)
...
<AutoForm schema={schema} /> 

Crashes and throws Field "__typename" has an unknown type.

**Comment by radekmie** [comment]
Hi @kziemski! Thanks for reporting this. The thing is, it's not necessarily true that these properties should be ignored - I can imagine a case, where they are rendered as read-only fields instead.

To work round that, it'd be easiest to build it into the bridge. You could subclass the `ZodBridge` and change the `getSubfields` method to exclude such fields.

Let me know how it went!

**Comment by kziemski** [comment]
Agree it would be better if it could also be rendered as a readonly.  
Assuming it could be treated as a bug

Is there anyway to ignore fields and subfields in which ZodBridge cannot understand type as opposed to crashing?

**Comment by radekmie** [comment]
Rendering it as read-only out-of-the-box is a problem on its own, as `z.literal` accepts `null` and `undefined`. Also, not all themes support read-only fields.

> Is there anyway to ignore fields and subfields in which ZodBridge cannot understand type as opposed to crashing?

Not in a "if crash then ignore" way, as if it reaches the `getType` method, rendering already started. As I said above, such fields could be ignored in `getSubfields`.

**Comment by radekmie** [comment]
No response so far, so I'm closing. Feel free to comment further, though!
