### ISSUE TITLE
[Component] Single error field

### ISSUE THREAD

**Issue by serkandurusoy** [vazco/uniforms#13]
I see that there is a component, ErrorsField, for displaying all error messages but I could not spot a component to display a single error message for a given field.

Trying to achieve aldeed:autoform's [`affieldmessage` helper](https://github.com/aldeed/meteor-autoform#affieldmessage), would this work? And if it did, could we add it to the standard packaging?

```javascript
import React          from 'react';
import {connectField} from 'uniforms';

const Error = ({
    errorMessage,
    ...props
}) =>
    <section {...props}>
        {errorMessage && (
            {errorMessage}
        )}
    </section>
;

export default connectField(Error);
```

**Comment by radekmie** [comment]
Yes, that's neat. Also, your implementation is almost perfect - `<section>` shouldn't receive `onChange`. I'll add it soon.

**Comment by serkandurusoy** [comment]
Wow, thanks! And thank you also for pointing out my oversight. It helps me think about how I design new components, which I will probably do over the coming weeks.
