### ISSUE TITLE
ModifierForm Zero Values

### ISSUE THREAD

**Issue by EricSoldierer** [vazco/uniforms#131]
For updating my model, I’m using your *ModifierForm* example which is explained in the *README.md* file.

Now, when I try to update the value of a number field to 0, the value won't be updated in the database.
I have looked at that example more closely and I'm a bit confused about the conditions in the following two lines in your example.

```js
const update = keys.filter(key =>  doc[key]);
const remove = keys.filter(key => !doc[key]);
```

Indeed, if the value behind *doc[key]* is for example 0, the result of the expression !0 would be *true*. This means, the property will be removed from the modifier object and not updated in the database. However  in my scenario a value of 0 is valid.

This is what I did to prevent this from happening.

```js
const update = keys.filter(key => doc[key] != null);
const remove = keys.filter(key => doc[key] == null);

**Comment by radekmie** [comment]
Good catch!

I'm really glad, that somebody is reading the README. Yes - that's my mistake - to be honest, I've never tested it in-depth. I'll fix it in a moment.
