### ISSUE TITLE
Can't type decimal numbers properly if the field has a default value (with meteor-SimpleSchema-bridge)

### ISSUE THREAD

**Issue by macrozone** [vazco/uniforms#135]
when i have a field with something like this:

```
{
  aValue: {
     type: Number,
     decimal: true,
     defaulValue: 1
}
```

You can't type in say 0.5, because you can't delete the 1. I think its always putting in the default value as soon as the field is empty.

Sorry, i could not reproduce this properly with the demo, because it is using the npm-version of simpl-schema and seems to behave differently.

**Comment by radekmie** [comment]
Is it not reproducible in the new SimpleSchema? Weird. If compare both `getInitialValue` functions ([1](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/bridges/SimpleSchemaBridge.js#L141-L159), [2](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/bridges/SimpleSchema2Bridge.js#L97-L115)), then it should work exactly in the same way.

@macrozone, as you know uniforms quite in depth, what do you think, about extending [this](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/components/fields/BaseField.js#L199) condition with an additional `&& !changed`? Then default _(and/or initial)_ values would be calculated only on demand and the first render.

**Comment by radekmie** [comment]
I've done some initial work and it looks like it's not that easy - many tests fail... I'll try to make it work. Also, it's somehow related to #130 - that's you couldn't reproduce it.

**Comment by radekmie** [comment]
Arrived in 1.6.0-beta.4. I hope it's not a breaking change - current behaviour changed a little, but it was a bug, not a feature.
