### ISSUE TITLE
More complex onChange

### ISSUE THREAD

**Issue by mariusrak** [vazco/uniforms#1359]
Hi, we want to implement undo/redo feature. For that we need to know complete model on every change (accessible by `onChangeModel`). But we also need to know which key caused the change. Otherwise we would record every typed letter in an input, which is not how undo/redo should work. To avoid capturing subsequent changes in same field, we can use method `onChange` which provides `key` causing change with new `value`, but now we don't know whole model, so we cannot record it. Now we can only somehow combine key with current model, which causes troubles and bugs especially with nested fields.

Current solution, which I sense is also bug-prone and not quite clean is this:
```js

const handleFieldChange = (key, value) => {
        // This fires after all form.setState() is done
        // so we can catch last model, while knowing which key caused change
        formRef.current.setState(
                () => null,
                () => log("model change", key, value, formRef.current.state.model)
        );
};

return <AutoForm model={model} ref={formRef} onChange={handleFieldChange} />
```

So can we extend onModelChange feature to provide not only new model, but also key and value causing changes?
Thanks.

**Comment by kestarumper** [comment]
Hi @mariusrak,
This would be an exciting improvement. We've brainstormed the possible approaches to this.

At first, we thought that all you need is the `initialModel` and the list of changes `[key, value][]` that you can apply to achieve state at any point in time, but this might not be ideal. However, this approach uses the least duplicated data.

In the end, we compared ourselves to react-hook-form [watch](https://www.react-hook-form.com/api/useform/watch/), and we thought that this is a widely adopted approach so it might be good to implement a similar in ours.

I've added a PR #1363. Let me know what you think.

**Comment by mariusrak** [comment]
Looks great, thanks.
