### ISSUE TITLE
Undocumented JSONSchemaBridge breaking change in v4

### ISSUE THREAD

**Issue by Gwened** [vazco/uniforms#1360]
Migrating from v3 to v4:
Now the JSONSchemaBridge constructor takes an object: {schema, validator...} instead of two parameters.

Either the previous argument structure should remain supported, or this should be mentioned in the breaking changes of the documentation: https://uniforms.tools/docs/migrating-3-to-4/#breaking-api-changes

Version: 4.0.0-alpha.5
Package: uniforms-bridge-json-schema
Commit: https://github.com/vazco/uniforms/commit/1c6987759c1744338eb4171e6d7883de47ebe65b

**Comment by Monteth** [comment]
Hi @Gwened,
Thanks for pointing this out! We've updated the migration guide to mention constructor changes in all bridges. This change is included in PR #1362.
