### ISSUE TITLE
Injecting a variable into a field type

### ISSUE THREAD

**Issue by Gervwyk** [vazco/uniforms#137]
In short: Is there perhaps a way to inject a variable as Autoform prop which is passed to all child components? 

The reason I'm asking:
I'm trying to create a custom field type within the antd module which I'm creating. For one of these custom fields I require a variable to be injected from my app, in this case a set of colors. (Note this is not the default colors, these are colors used to calculate colors for selection)

So in this example I cannot define these colors within the schema since they change with relation to other app variable. However they need to reflect in the component. 

I'm considering copying the collection schema and then adding these colors under:
````
ColorField: {
      type: String,
      label: "Hex color value for chart text.",
      defaultValue: "#434d52",
      uniforms: {
            fieldComponent: 'color',
            colorRatios: [0.35, 0.7, -0.2, -0.4],
            colorModes: ['#222','#444','#888],  // <-- inject these variable in the schema
            info: "Hex color value"
      }
}
````

However since my Autoform creation component is also generic to work for all app 'features' it works on different schemas. Thus I would have to run through the schema to find where to inject the variable. This would be ok for this example but I'm cautious that this might become problematic and slow to do this for all possible future scenarios of this.

I'm also using these fields on various apps so I don't feel like defining them as custom fields within the app is the correct solution.

In another scenario I'm also linking external data fields, which works great if the field component is within the app and I run the field through a composer however I'm still trying to see how this can be built as a field. I'm thinking this might be possible if the composer could also somehow be injected to the app, however in this case this might be doable though the schema definition since the data composer will always be the same for the schema.

**Comment by radekmie** [comment]
Well, kind of. It's not documented, but the `context.uniforms.state` is passed to the fields [[1]](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/components/fields/BaseField.js#L127-L141) [[2]](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/components/fields/BaseField.js#L154-L157) [[3]](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/components/fields/BaseField.js#L219-L242). For example, [bootstrap themes are doing it](https://github.com/vazco/uniforms/blob/master/packages/uniforms-bootstrap3/src/components/forms/BaseForm.js#L20-L25).

I thought about more dynamic _(and public)_ API, but I've got no good enough idea yet. I'm open minded - if you have an idea, then share it here.

**Comment by Gervwyk** [comment]
Great. I used the same solution as you did for grid in bootstrap themes and it works well. So I pass a fieldData object as a prop in Autoform which then renders using the provided data.

For instance in this case the object is:
```
<Autoform fieldData={{'colors' : ['#cc0000', '#000099', '#808080', '#da4264']}} ...
```
The ColorPicker (or other components) then checks if a props.fieldData.colors is defined if not revert to a default set. This only required adding some lines to BaseForm in the antd package I'm working on. Does this make sense in the context of uniforms?

**Comment by radekmie** [comment]
Kind of blackbox passed in the `uniforms` context? Seems reasonable. Also, few already implemented things, like `grid` in bootstrap themes, could use it. I'll think about it and let you know.

**Comment by Gervwyk** [comment]
Yes. So except that you pass the blackbox from the context of the schema, in some cases its also useful to pass the blackbox through the context of the app / form component if that makes sense.

**Comment by radekmie** [comment]
I'll leave it as it is for now, but maybe it's a good idea to create a roadmap... I'll take care of it later this week.

**Comment by radekmie** [comment]
It's been some time, but finally, it's clear. You can achieve this by passing additional data in uniforms context as described above. Yes, there's no need for additional functionality - this is an advanced feature easily doable with only documented API.
