### ISSUE TITLE
reset context.state.changed on submit

### ISSUE THREAD

**Issue by zeroasterisk** [vazco/uniforms#138]
I'm using a `DisplayIf` do decide if a submit button should be visible/enabled...

```jsx
      <DisplayIf condition={(ctx) => (!(ctx.state && ctx.state.changed))}>
        <button className="btn btn-primary disabled" disabled>
          <Fa className="ok" />
          Saved
        </button>
      </DisplayIf>
      <DisplayIf condition={(ctx) => ctx.state && ctx.state.changed}>
        <SubmitBtn formRef={props.formRef} >
          <Fa className="save" />
          Save {props.tabName}
        </SubmitBtn>
      </DisplayIf>
```

This works fine for initial render, but not for view, change, submit... it should reset form state to not-changed.

**Comment by radekmie** [comment]
At first, share some more information: version, how `SubmitBtn` resets the form and your component _(it's just a part of it - some context would be nice)_.

**Comment by radekmie** [comment]
The `onReset`, which is aliased to `reset`, [is doing it](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/components/forms/BaseForm.js#L232-L239).

**Comment by zeroasterisk** [comment]
Yes, I'm only calling `formRef.submit()`... so I should call `formRef.reset()` after?

`formRef.submit().then(() => formRef.reset(), err => console.error(err))`

**Comment by radekmie** [comment]
Yes, [`onSubmit` is not doing a reset](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/components/forms/BaseForm.js#L241-L257).

**Comment by zeroasterisk** [comment]
I tried it out and it works... Sadly, I've done something wrong with my submit handler, the promise is resolving before the save is complete, and I never noticed it because I wasn't resetting my form... but I'll work on that... thanks!
