### ISSUE TITLE
Why use `AutoForm` name instead of `UniForm`?

### ISSUE THREAD

**Issue by thearabbit** [vazco/uniforms#143]
the package name `uinform`, but
```js
import {AutoForm} from 'uniforms-unstyled';
// Why don't
import {UniForms} from 'uniforms-unstyled';
```

**Comment by radekmie** [comment]
I have to add it to the `README.md`, because it's weirdly common question. It was already asked and answered [here](https://github.com/vazco/uniforms/issues/23#issuecomment-224961574).
