### ISSUE TITLE
Can't run demo, missing dependencies in demo/package.json

### ISSUE THREAD

**Issue by macrozone** [vazco/uniforms#144]
Hi, 

I cloned the repo freshly and wanted to start the demo. It seems these dependencies are missing in the demo:

- babel-runtime
- fbjs/lib/invariant
- fbjs/lib/warning

But when i install babel-runtime, I get:

"Error: only one instance of babel-polyfill is allowed"

:-(

**Comment by radekmie** [comment]
OK, I've got three questions: which branch, npm version and node version. On master, node 7.2.0 and npm 4.0.3 it's working.

**Comment by macrozone** [comment]
master branch,
node 4.5.0
npm 2.15.9

... ok i guess at least npm is a little bit old... will try to update

**Comment by radekmie** [comment]
Yeah - `npm` might be the problem, because we are using our peer dependency dependency (`fbjs`).

**Comment by radekmie** [comment]
I've also tested it on node `5.12.0` and npm `3.3.10` - it's working.

**Comment by macrozone** [comment]
thx, @radekmie , its working with latest npm
