### ISSUE TITLE
When app is minified, Incorrect date error is shown

### ISSUE THREAD

**Issue by todda00** [vazco/uniforms#147]
Running in development an error for a required date field when a text string is entered outputs:
[FieldName] must be a Date

When running in --production mode (minified) or deployed to a server:
[FieldName] must be a r

![acelist](https://cloud.githubusercontent.com/assets/8363924/21064271/e7b8ba5e-be27-11e6-9fc1-b0154606a3cf.png)

I have this setup to accept a MM/DD/YYYY string and format it to a date before validation. Here is my schema for this field:
```
'profile.birthdate': {
  type: Date,
  max() {
    return moment().subtract(13, 'years').toDate();
  },
  optional: true,
},
```

And the React side:
```
<TextField
  name="profile.birthdate"
  placeholder="MM/DD/YYYY"
  label="Birth Date (MM/DD/YYYY)"
/>
```

**Comment by radekmie** [comment]
It's one of the most interesting bugs I've seen in a while, really. I try to give it a shot tomorrow, meanwhile - have you even tried to debug it even a little? Also, I'm not sure if this is a SimpleSchema bug or uniforms bug.

Just to be sure - is this SimpleSchema or SimpleSchema2?

**Comment by todda00** [comment]
SimpleSchema1 - 1.5.3

I started digging through the uniforms code looking at the error generation
items, but it was difficult for me to jump in and figure out what it was
all doing. It very well may be a SimpleSchema issue, but I was unable to
find anything related to it. I may be able to isolate it a bit and figure
out what package it is coming from, this one or SS.

**Comment by radekmie** [comment]
OK, I've found it. It's because of [`es5-shims`](https://github.com/meteor/meteor/tree/devel/packages/es5-shim) package. It overrides the native `Date` object, which constructor name is minified.

Solution? I don't know. Why we all have the same minified name? Because Meteor use `.min.js` files if those are available and [here](https://github.com/es-shims/es5-shim/blob/master/es5-shim.min.js) it is.

**Comment by todda00** [comment]
Interesting indeed. My solution to this is to override SimpleSchema's message for expectedConstructor to not include the type name:

```
SimpleSchema.messages({
  expectedConstructor: '[label] is not in a valid format',
});
```

**Comment by radekmie** [comment]
Thanks @todda00 - someone will surely make use of your workaround.
