### ISSUE TITLE
Allow to change the style of + sign when using nested fields

### ISSUE THREAD

**Issue by vladejs** [vazco/uniforms#149]
the default style of the + sign is poor:
```
<span class="label label-default">+</span>
```

I need to add a class to that element in order to change its style, and optionally change its `label-default` class to `label-warning` for example.

**Comment by radekmie** [comment]
There's an [example](https://github.com/vazco/uniforms#props-propagation) of a custom `ListField` in the readme. If you want, you can create a PR for a customization there, but it's fairly easy to create a custom `ListAddField`.

**Comment by vladejs** [comment]
I want to change its style without the need to declare it.
```
<AutoForm
  model={...}
  onSubmit={...}
  plusSignClasses="rounded purple" 
/>
```
Or directly on the schema:
```coffeescript
schema = new SimpleSchema
  images: [ImageSchema]
  uniforms:
    component: ImageComponent
    plusIconClasses: 'purple rounded'
```

**Comment by radekmie** [comment]
@vladejs Submit a PR if you want.
