### ISSUE TITLE
How to add Meteor Reactive data to a Select Field 

### ISSUE THREAD

**Issue by vladejs** [vazco/uniforms#151]
Hello @radekmie, I'am stuck at this use case, which I couldn't find on the docs.

I have a schema which has a category field. That field should get its data from a Meteor Collection. That field should be rendered automatically 'cause iam using `<AutoFields />` component; 

What I want to achieve is the simplest escenario possible: A select field who's values are the `_id`'s, and its labels are a collection attribute, like `name`.

```
new SimpleSchema({
  category: {
    type: String,
    allowedValues: // an array like [{ _id: "123", name: "food" }] coming from a Meteor Collection
  }
})
```
By the way, I use container-component pattern, with the help of react-komposer package. So I feed my components with data comming from a container:
```
// on a file
const ListComponent = props => (<div> props.list.map(...) </div>)

// on another file
import { composeWithTracker } from 'react-komposer'
import ListComponent from 'file/where/dumb/component/is'
import ListCollection from '...'

const composition = (props, onData) => {
  if (Meteor.subscribe('lists').ready()) {
    const list = ListCollection.find().fetch();
    onData(null, list);
  }
}
 
export default composeWithTracker( composition )( ListComponent );
```

**Comment by radekmie** [comment]
Either use a dynamic schema _(i.e. schema computed in a reactive context)_ or use `ListField` directly _(like in your example)_ and pass your data in `allowedValues` property.

**Comment by vladejs** [comment]
I did your second advice and it worked fine, but i am intrigued about how to achieve the same result using a dynamic schema?

I did this and it didn't worked:
```
new SimpleSchema({
  category: {
    type: String,
    uniforms:
      options: () => {
        if (Meteor.subscribe('categories').ready()) {
            const cats = Categories.find().fetch();
            // iterate over cats and format the array as [{label, value}] objects
            return modifiedC;
        }
      }
  }
})
```

**Comment by radekmie** [comment]
For example something like this:

```js
let schema;
Tracker.autorun(() => {
    Meteor.subscribe('categories');

    const options = Categories.find().fetch();

    schema = new SimpleSchema({
        category: {
            type: String,
            uniforms: {
                options
            }
        }
    });
});
```

**Comment by ramintagizade** [comment]
Not possible to add dynamic data when subscriptionsReady to <select> method with Blaze !

**Comment by radekmie** [comment]
@ramintagizade wait, what? It’s a React not Blaze package.
