### ISSUE TITLE
install warning about graphql

### ISSUE THREAD

**Issue by cyclops24** [vazco/uniforms#154]
Hi guys,
Installation return below warning for me:

```
npm WARN uniforms@1.8.0 requires a peer of graphql@^0.8.2 but none was installed.
```

It's also return same error in Firebug console when it's running.
I guess it's related to Meteor.

**Comment by radekmie** [comment]
No, it is not related to Meteor. Starting from [3.0.0](https://github.com/npm/npm/releases/tag/v3.0.0), npm is not installing peer dependencies automatically but warns you to do it. Core uniforms package has 2 _unnecessary_ peer dependencies - `graphql` and `simpl-schema`. If you are not using either of them, then you have a not installed peer dependency. Unluckily, there is no way to silent this warning.

In distant future, schema packages will be separated, so it won't be a problem but for now you have to deal with this warnings.

**Comment by cyclops24** [comment]
@radekmie Thanks for your attention man. 😉

**Comment by sakulstra** [comment]
when trying to use this in combination with shrinkwrap, shrinkwrap errors out:
```
npm ERR! node v4.6.2
npm ERR! npm  v3.10.9

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! peer invalid: graphql@^0.8.2, required by uniforms@1.8.4
npm ERR! peer invalid: simpl-schema@^0.0.4, required by uniforms@1.8.4
npm ERR! 
```

**Comment by radekmie** [comment]
@sakulstra npm/npm#12909
