### ISSUE TITLE
[Question] set submit-button-label in AutoForm

### ISSUE THREAD

**Issue by cyclops24** [vazco/uniforms#155]
Hi @radekmie,
I want to customize submit button in an Autoform. Now it's show "Submit Query" for button label.
I also see [this](https://github.com/vazco/uniforms/issues/28) and [this](https://github.com/vazco/uniforms/issues/39) but can't set submit-button label.
It's my try:
```javascript
import {SubmitField} from 'uniforms-bootstrap3';
const customSubmitField = () =>
        <SubmitField>Login</SubmitField>;
<AutoForm schema={LoginSchema} placeholder={true}
                          getSubmitField={customSubmitField}
                          onSubmit={doc => console.log(doc)}>
```
Can you help me to do this?

**Comment by radekmie** [comment]
If you still want to use fully automatic `AutoForm`, i.e. `<AutoForm schema={...} onSubmit={...} />`, then pass an additional `submitField` prop with your custom `SubmitField`.

Example:
```js
import SubmitField from 'uniforms-unstyled/SubmitField'; // <- !

const MySubmitField = props =>
    <SubmitField value="Submit Label Here" /> // It's <input type="submit" />
;

// Later...

<AutoForm schema={...} onSubmit={...} submitField={MySubmitField} />
```

If you are using _not-so-fully-automatic_ `AutoForm`:
```js
<AutoForm schema={...} onSubmit={...}>
    <AutoField ... />
    {/* ... */}

    {/* Like this */}
    <MySubmitField />

    {/* Or directly */}
    <SubmitField value="Submit Label Here" />
</AutoForm>
```

**Comment by radekmie** [comment]
I'll close it. If you have more questions, just let me know.

**Comment by cyclops24** [comment]
@radekmie Thanks man. I test it and works well.

**Comment by bennycode** [comment]
I tried it like this:

```tsx
import JSONSchemaBridge from 'uniforms-bridge-json-schema';
import {AutoFields, AutoForm, ErrorsField, LongTextField, SubmitField} from 'uniforms-material';
// ...

const strategyAddSchema = {
  title: 'Strategy',
  type: 'object',
  properties: {
    // ...
  },
  required: ['config', 'label', 'name', 'user', 'version'],
};

const strategyAddBridge = new JSONSchemaBridge(strategyAddSchema, () => null);

const strategyAddForm = (
  <AutoForm
    schema={strategyAddBridge}
    onSubmit={async (model: StrategyEntityProps) => {
      // ...
    }}>
    <AutoFields />
    <ErrorsField />
    <SubmitField value={'Test'} />
  </AutoForm>
```

But the submit button still shows text "Submit" instead of "Test". 

![image](https://user-images.githubusercontent.com/469989/110320452-9904e900-8010-11eb-82bb-9c68a0f10b99.png)

@radekmie, have I missed something? 🤔

**Comment by radekmie** [comment]
Hi @bennycode. It depends on your theme - [in `uniforms-material` it looks like this](https://github.com/vazco/uniforms/blob/dda7334f82d0f7bc932656ee3496e6907081d0e0/packages/uniforms-material/src/SubmitField.tsx#L30), hence you should use `label` or `children` props instead of `value`.

**Comment by bennycode** [comment]
`<SubmitField label="Test" />` did the trick! Thank you!!
