### ISSUE TITLE
[Feature Request] Add online demo

### ISSUE THREAD

**Issue by cyclops24** [vazco/uniforms#156]
Hi @radekmie ,
I think an online demo like this in autoform can be very useful:
http://autoform.meteorapp.com/

Do you have any plan about it?

**Comment by radekmie** [comment]
There is already demo project in `demo/` and don't worry - it will be public _(in the future at least)_.

**Comment by cyclops24** [comment]
@radekmie oh excuse me I see it now.
But it seems it's Meteor based. I think if it's only depend on React and simple schema then you can deploy it simply in [github page](https://pages.github.com/) and also every time you change demo app and push it's update auto-magically. I think Meteor deployment a little is complicated and use Meteor for a simple demo app is not best option.

**Comment by radekmie** [comment]
It's based on Meteor to show all possible schemas - SimpleSchema@1 is available only in Meteor environment.

**Comment by cyclops24** [comment]
What is your opinion about split demo to two version. One for SimpleSchema@1 (Based on Meteor) and one other for SimpleSchema@2? If you agree I can plan and work on it (SimpleSchema@2 demo Version) in my free time.

**Comment by radekmie** [comment]
[There are all schemas integrated](https://github.com/vazco/uniforms/blob/master/demo/lib/presets.js).

**Comment by cyclops24** [comment]
@radekmie Thanks for this awesome demo man. It's so good as a start point.
