### ISSUE TITLE
[Feature Request] Please add a gitter chat room

### ISSUE THREAD

**Issue by cyclops24** [vazco/uniforms#157]
Hi @radekmie,
Please add a gitter chat room (and badge to ReadMe) for this awesome project, I think it's increase this package community more and make all of uniforms lover closer to each other.
Thanks man 😉

**Comment by radekmie** [comment]
@cyclops24! You are *very* active, don't you?
:1st_place_medal:

I've asked this question before and... There was no need to do so. Now, when the community is getting bigger and bigger - I'll do it. It might be both useful and issue-solving.

**Comment by cyclops24** [comment]
Thanks for your attention and beautiful medal 😉
