### ISSUE TITLE
Please advise "Bootstrap VS Material-UI"?

### ISSUE THREAD

**Issue by thearabbit** [vazco/uniforms#162]
Excuse me, I base on `Bootstrap` for along time (`AdminLTE, AutoForm, ...`).
Now I tried `Material-UI`, I think that it is difficult and not enough component like `Bootstrap`.
But I plan to `Mobile UI` too.
Which one for  the best of `React`?

**Comment by radekmie** [comment]
It's not an adequate question here - it's your choice. I'd suggest asking it on some forums.

**Comment by thearabbit** [comment]
sorry
