### ISSUE TITLE
Step support for NumField

### ISSUE THREAD

**Issue by Skulmuk** [vazco/uniforms#165]
When using either a NumField or AutoField, the increment/decrement step doesn't seem to be changeable. For instance, my schema has a **Capacity** value which should be a whole number, but using the arrow keys, I can enter 10.01, which is an invalid value in regards to my schema.

Does the ability to define a step size exist? I tried the following but it didn't do anything:

```javascript
capacity: {
    optional: false,
    min: 1,
    type: Number,
    label: 'Capacity',
    uniforms: {
      step: 1,
    },
  },
```

**Comment by radekmie** [comment]
Hey @Skulmuk. It's not configurable right now, but it will be very easy to do so _(for example it is [here](https://github.com/vazco/uniforms/blob/master/packages/uniforms-unstyled/src/NumField.js#L37) in `uniforms-unstyled`)_. Would you like to submit a PR for it?

**Comment by Skulmuk** [comment]
Thanks for the quick reply, @radekmie. I don't have time to raise a PR at the moment - I'm knee-deep in client work. Is this something we'll see included in the near future?

**Comment by radekmie** [comment]
Yeah, sure - I'll do it tomorrow or even today.

**Comment by Skulmuk** [comment]
Thanks - greatly appreciated :)
