### ISSUE TITLE
Safari numeric input not allowing decimals

### ISSUE THREAD

**Issue by todda00** [vazco/uniforms#167]
Strange issue here with Safari and numeric inputs.

In Safari when adding a numeric field using AutoField, the decimal cannot be typed unless its at the beginning of the input. So I cannot type 1.5, but could type .5. but not 0.5 . Oddly, you can type 15 then cursor back and enter a decimal to get to 1.5 . Also, the arrows up and down do work, so if you enter 1, and arrow up, 1.01 is entered (my step is 0.01). Initially I thought this was a Safari oddity with type="number" fields, but I pasted the exact HTML generated from uniforms and added it directly, and Safari allows me to insert decimals.

Schema:
```
UTR: {
    type: Number,
    optional: true,
    min: 1,
    max: 17,
    decimal: true,
    label: 'UTR',
  },
```

Usage:
```
<AutoField name="UTR" grid={{ xs: 6 }} inputClassName="form-control-sm" />
```

This generates the HTML:
```
<input type="number" class="form-control-sm form-control" id="uniforms-0000-0001" max="17" min="1" name="UTR" placeholder="" step="0.01">
```

When I add this HTML directly in the code outside of uniforms it works as expected, but not from the AutoField generated code.
![safari_decimal](https://cloud.githubusercontent.com/assets/8363924/22115972/033cc0f6-de3d-11e6-93ca-197914a2e22c.png)

Chrome and Firefox do not have this issue, decimals can be entered as expected

**Comment by radekmie** [comment]
I'll try to investigate but I can't promise anything - the only Safari I can play with has no developer tools.

**Comment by radekmie** [comment]
Maybe [this](https://github.com/vazco/uniforms/blob/master/packages/uniforms-bootstrap3/src/NumField.js#L18) might cause this issue. If so, it's even weirder that it happens only on Safari.

**Comment by radekmie** [comment]
Yes, that is the cause. Only way I see is to rework `NumField` - it should have internal state of input _(string)_ and call `onChange` only, when parsed value changed, so `1` and `1.2` will be the same.

I'll leave it for now - if you see another way - please, let me know.

**Comment by todda00** [comment]
Created a PR for this, targeting BS3 & BS4 - I don't know if this behavior exists in the other packages, I do not use semantic.

**Comment by radekmie** [comment]
_(ping)_ I didn't have much time recently and I probably won't in the next few days, but I guarantee, that I'll get to it within next two weeks. I'm planning to create another class which will be compatible with `BaseField`.

**Comment by todda00** [comment]
Sounds good, I'll leave you to your vision. Thanks for maintaining such a
wonderful package!

On Sat, Jan 28, 2017 at 12:53 PM, Radosław Miernik <notifications@github.com

**Comment by radekmie** [comment]
Well, it was almost two weeks, so I've implemented a modified version of your solution _(thanks!)_, but it's not a future-proof solution. It's working as expected, but now `NumField` allows some weird inputs like `&()`, but it's browser dependent - it's _quite_ OK on Chrome, Firefox and Safari - if the user will enter correct value, then it works.
