### ISSUE TITLE
How to create an schema which produces a pair of inputs

### ISSUE THREAD

**Issue by vladejs** [vazco/uniforms#171]
Hello, I am trying to create a combination of 2 fields, without the need to create a custom component, like so:
```coffeescript
mother:
  type: Object
  uniforms:
    grid: "8" # col-md-8 for name field and col-md-4 for phone field

 'attorney.$.name':
   type: String

  'attorney.$.phone':
    type: String
```

If I wrap the `attorney` type with: `[Object]`, it will create a field with plus icons, to add or delete items, otherwise, it doesn't work at all.

### Visually, I want to create it like this:

Mother:
  Name: __________________________________   Phone: _______________

Father:
  Name: __________________________________   Phone: _______________

**Comment by radekmie** [comment]
Which theme? Let's assume Bootstrap3.

As I remember, `grid` property changes the proportion between label and input - there is no way to place two fields in a line. I'm not an expert of Bootstrap, so @zeroasterisk - could you help here?

**Comment by vladejs** [comment]
Bootstrap 3, If I should create it the "old way", I would do it like this:

```html
<div class="row">
  <div class="col-md-8">
    <!-- first label+input goes here -->
  </div>
  
  <div class="col-md-4">
    <!-- second label+input goes here -->
  </div>
</div>
```

What do you think? Should I create a custom component for this?

**Comment by radekmie** [comment]
Surely custom `ListItemField` is a solution, but again - let's ask @zeroasterisk - he is the creator of both Bootstrap packages.

**Comment by zeroasterisk** [comment]
I have done this myself with my own custom component, because usually my fields are not nicely nested to play nice with `NestField` or `ListItemField`

```js
import React from 'react';
import { connectField } from 'uniforms';
import { AutoField } from 'uniforms-bootstrap4';
import wrapField from 'uniforms-bootstrap4/wrapField';
import classnames from 'classnames';

const DoubleInputFieldExample = props => (
  // this takes care of the form-group & the label & the wrapper div
  wrapField(props, (
    // therefore by this point, I'm inside the col-xs-9 (right col for an input)
    <div className="wrapper-for-inputs row">
      <AutoField
        label={false}
        name="mother.name"
        className="col-xs-6"
      />
      <AutoField
        label={false}
        name="mother.phone"
        className="col-xs-6"
      />
    </div>
  ))
);
DoubleInputFieldExample.propTypes = {
  onChange: React.PropTypes.func,
  value: React.PropTypes.any,
};
export default connectField(DoubleInputFieldExample);
```

**Comment by zeroasterisk** [comment]
Ad mentioned, It _should_ also be doable with a `NestField` like so:

```js
<NestField label={null} name="mother">
    <div className="row" />
      <TextField name="name" className="col-xs-6" />
      <TextField name="phone" className="col-xs-6" />
   </div>
</NestField>
```

**Comment by zeroasterisk** [comment]
Also - I'm a bit confused by your schema... 

does your data look like this (array of objects):

```
doc = {
  mother: [ 
    { name: 'Joe', phone: '555-555-5555' }
  ]
}
```

or does your data look like this (nested object):

```
doc = {
  mother: {
    name: 'Joe', 
    phone: '555-555-5555',
  }
}
```

**Comment by radekmie** [comment]
OK, I think we are done here. Thanks @zeroasterisk! If you have any more questions @vladejs - write them here.
