### ISSUE TITLE
Meteor auto insert?

### ISSUE THREAD

**Issue by JWDobken** [vazco/uniforms#173]
Quickquestion
With Meteor I would like to insert an autoform and this package gave me quick results, so that is excellent

```
<AutoForm
      schema={Books._collection.simpleSchema()}
       onSubmit={doc => console.log(doc)}
      />
```

However onSubmit did only the expected console.log and no document was inserted in the DB.
Should I still write the insert function myself including the clear form function?

**Comment by radekmie** [comment]
Hey, @JWDobken! It won't be added because of two reasons - firstly, because it is not only a Meteor package and secondly, because it is fairly easy to do it _by hand_ (you can even create custom form).
