### ISSUE TITLE
Access fields from "external" method

### ISSUE THREAD

**Issue by Skulmuk** [vazco/uniforms#175]
I'm using an external package to place an address lookup on my AutoForm, which calls an onChange function. What's the best way of passing data from the function back to the fields of AutoForm? Should I pass something from the form to the method?

**Comment by radekmie** [comment]
I don't really understand, what you exactly want to achieve - could you explain a little bit more?

**Comment by Skulmuk** [comment]
Apologies - I'll attach some code below. I'm using the Geosuggest package:

```
import Geosuggest from 'react-geosuggest';
```

Using this on the AutoForm requires the following:

```javascript
<Geosuggest
  onSuggestSelect={this.onSuggestSelect}
  placeholder="Search for a place or postcode"
  inputClassName="form-control"
  suggestsClassName="list-group"
  suggestItemClassName="list-group-item"
  country="gb"
/>
```

Basically, this is an address lookup which lets me enter a UK postcode and select from a list of potential results. When I run the `onSuggestSelect` method, I parse the selected address into a format which sort of matches my schema:

```javascript
  onSuggestSelect(suggest) {
    const addressData = {};

    Meteor.call('system.googlePlacesLookup', suggest.placeId, (e, r) => {
      if (e) {
        toastr.error(e);
        return;
      }
      const data = _.get(r, 'data', {});
      if (data.result) {
        _.each(data.result.address_components, (comp) => {
          const value = comp.short_name;
          _.each(comp.types, (t) => {
            switch(t) {
              case 'postal_code':
                addressData.postcode = value;
                break;
              case 'route':
                addressData.addressLine1 = value;
                break;
              case 'postal_town':
                addressData.city = value;
                break;
              case 'administrative_area_level_2':
                addressData.county = value;
                break;
              default: break;
            }
          });
        });

        console.log(addressData);
        return addressData;
      } else {
        toastr.error('Lookup completed but no usable address data found.');
      }
    });
  }
```

Instead of `return addressData;`, I'd like to be able to pass `addressData` back to Uniforms to perform validation, etc. and submit it to my database that way.

Does that make sense?

**Comment by radekmie** [comment]
But you want to use this data as options in a (multi)select or you want to set them as a value of a field?

**Comment by Skulmuk** [comment]
I would like to pass the parts of `addressData` as values of particular fields.

**Comment by radekmie** [comment]
Then create custom field, like `GeoField`, which will call `onChange` instead of this `return`.

**Comment by Skulmuk** [comment]
Should I include the fields I'm trying to write to in the custom field? I.e. I have a field called `addressLine1` - should an AutoField with this name be in my GeoField component?

**Comment by radekmie** [comment]
Is this a top-level field or a subfield? If it's a subfield of `address` for example, then `GeoField` will manage whole `address` field with all subfields. If you want to manage few top-level fields, then you have to use `onChange(value, field)` instead of just `onChange(value)`.

**Comment by radekmie** [comment]
OK, I think everything is clear.

**Comment by vpl-webteam** [comment]
@damienrobson can you share the GeoField component snippet? Working with the same npm package and trying to attach that object to a form. Cant figure it out.
