### ISSUE TITLE
How to modify other fields ?

### ISSUE THREAD

**Issue by theodorDiaconu** [vazco/uniforms#176]
I want to click on something and would like to modify the value of the field. I would like to internally access the state of autoform's model and trigger a change. How could this be done ?

Sample:
I click on a checkbox, and I want to add few more items in a multi-select.

**Comment by Gervwyk** [comment]
If I can make a suggestion for you. I'm using [CustomAutoField](https://github.com/vazco/uniforms#example-customautofield) for something like you are describing. Where I then assign:
````
export const determineComponentFromProps = (props) => {
  switch (props.fieldComponent) {
    case 'color':
        return ColorPicker;
    case 'foreignkeymultiselect':
        return ForeignKeyMultiSelectContainer;
    case 'foreignkeycontainer':
        return ForeignKeyContainer;
    case 'htmlstring':
        return HTMLStringField;
    default:
        return null;
  }
}
````
Where the custom field are 'app specific' components I build. These components can have their own state like you describe. See this component as en [example](https://github.com/Gervwyk/uniforms/blob/uniforms-antd-extended/packages/uniforms-antd/src/ColorPickerField.js) although it is an older example and you do not need to use `connectField` if you use CustomAutoField. You provide the props through the schema definition.

Hope this helps. Also not sure if this is the most elegant solution.

**Comment by theodorDiaconu** [comment]
@Gervwyk we need a way that when connecting the field to give us access to the whole form somehow, it's model, and ability to change the model and trigger change events for it to re-render. That would be in my opinion the easiest way to solve this.

**Comment by Gervwyk** [comment]
I hear you. I also need that exact case. Basically a trigger that changes the schema definition by which the form is set up? I need this also for a solution where you select one field and more fields in the schema becomes available. I was considering to build a solution that changes the schema prop to autoform.. but have not got to the details of it. It definitely also something I'm working on soon.

**Comment by theodorDiaconu** [comment]
@Gervwyk by looking here:
https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/AutoForm.js

it seems we've got access to *onChange* in the Form component

Now doing more digging, we have access to uniform context:
https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/BaseForm.js#L46

I think there is a simple way to do what we need. Maybe one of the devs for this can tune-in on this.

**Comment by radekmie** [comment]
Hey @theodorDiaconu.

> I click on a checkbox, and I want to add few more items in a multi-select.

It is really important - does this checkbox is a part of the form? If yes, then use `onChange` of your `AutoForm` and modify your schema/your field `allowedValues` _(or `options`)_. If not, then simply do the same but instead of `onChange` you have to handle this checkbox manually.

---

If your component _can_ be a field, then use `connectField` and use any of [guaranteed props](https://github.com/vazco/uniforms#guaranteed-props).
If you really need a full access to the [context](https://github.com/vazco/uniforms#context-data), then just use it - it's a kind of _low level_ API of this package.
There is no _(yet?)_ something in between - _either you are a field or a full-featured component_.

---

I have a feeling, that your problem might be solved a lot easier with not using `AutoForm` at all and just keeping all the state by yourself. The best would be if you'd say something more.

**Comment by theodorDiaconu** [comment]
@radekmie the foundation idea is that we want ability to manipulate the form model how we want, trigger changes to the model and make it update live.

I solved my problems in hackish ways using react's state and modelTransform on 'submit'. It's no 
problem, hackish ways I can find. But I want it to be elegant. 

How would you solve these problems:
- Have a "Select All" button that will select all checkboxes in a certain field
- Have a radio group and when I select a value, I want to disable other fields.

**Comment by radekmie** [comment]
> @radekmie the foundation idea is that we want ability to manipulate the form model how we want, trigger changes to the model and make it update live.

Both of my solutions described in the second section are doing so. Anyway - answer my first question, because I can't help you without it.

**Comment by theodorDiaconu** [comment]
@radekmie the element may or may not be part of the form I think it is irrelevant. I want control over the form, from the inside and from the outside.

**Comment by radekmie** [comment]
It's important. If this is a part of the form, then you create a custom field and you have access to everything, either through the context or `connectField`. If it's not, then you can't alter the context, so you have to do it by yourself and tell the form, that something changed - update it's model for example.

**Comment by theodorDiaconu** [comment]
We could access the form context through a ref, right ? Thus gaining access to the context passed and everything we need.

**Comment by radekmie** [comment]
Not to the context itself, but to the parts of it, but yes - it's an option.

**Comment by radekmie** [comment]
I understand it is working.
