### ISSUE TITLE
How to dynamically include and exclude values from a SelectField

### ISSUE THREAD

**Issue by GoaGit** [vazco/uniforms#179]
```
// SimpleSchema definition
roles:{
	type: Object,
	blackbox: true
}
```

```
// Example object
roles: {
	scope1: [ 'roleA' ],
	scope2: [ 'roleA', 'roleB' ],
	scope3: [ 'roleA', 'roleB', 'roleC' ]
}

```
**Use case**: assign user to "scope3" and set roles "roleA" and "roleC" with selections from drop down lists ( uniforms <SelectField /> ).

Sketch of using the desired form "SetPermissions" that holds a line for each scope+role assignment. Initially, no scope and roles are assigned to the user.

1) In the first line the selection "scope3" + "roleA" is made (selected from a dropdown list holding values 'roleA', 'roleB', 'roleC')
2) In the second line the selection "scope3" + "roleC" is made (selected from a dropdown list holding values 'roleB', 'roleC', since "role A" was already selected)

* **Value selection**: The appropriate roles are only known after the scope is selected. This means we want to be able to asynchronously lookup the required values for "scope3" and populate the values in the list
* **Value exclusion**: After a selection, the value of that role should be excluded from additional lines where other roles for that scope will be set

**Question**: how can the uniforms package support the implementation to dynamically select and exclude value for a <SelectField> given the particular roles object definition? 

Any pointers or references are appreciated.

**Comment by radekmie** [comment]
Answer is simple - custom field. In short, you have to create a field _(let's call it `AccessField`)_, that will be used like this:

```js
<XForm {...formProps}>
    <AccessField name="roles" />
</XForm>
```

This field will:
1. Asynchronously load available options.
2. Handle the `<select>`s by itself _(go ahead and read the `SelectField` source)_.
3. _(when needed)_ Call `onChange` with correct value `{scopeA: [...], ...}`.

You can try to compose this field from standard ones, but I can say, that it's almost always better to create a _general_ `AccessComponent` which will be _wrappable_ with `connectField` so you can use it inside and outside the form.

**Comment by GoaGit** [comment]
Thank you @radekmie.

We will develop a solution for the use case and use your suggestions.
