### ISSUE TITLE
[Question] How to use existing document for update

### ISSUE THREAD

**Issue by serkandurusoy** [vazco/uniforms#18]
Currently, I am using the `model` attribute

    <AutoForm model={currentDocument} schema={formSchema} onSubmit=(/**/)>

to provide initial values to the form fields so that I can use the form as an *update form*.

Is this the correct approach?

**Comment by radekmie** [comment]
Yes, kind of - it's not *initial value* but *value*. If the `model` prop will change, it will override current `AutoForm` state. Look [here](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/components/forms/AutoForm.js#L26-L28).

**Comment by serkandurusoy** [comment]
Hmm, so that means, if we reactively set model (eg from a collection) than it overrides the complete state of the form, right?

So, to summarize, is this the way you suggest designin update forms or is there something else we need to use?

Basically, I want to update an existing document.

**Comment by radekmie** [comment]
Setting model reactively is not a problem, but if the model will change, it will *reset* the form state to the *database state*. The best option to use `AutoForm` as an update form is to pass non-reactive model.

**Comment by serkandurusoy** [comment]
How do you propose we do that? The only two ways I know it would work properly are getting the model from

* either a non-reactive query (so it is not observed)
* or a method call (so it is not subscribed)

Do you know any other way?

**Comment by radekmie** [comment]
Both seem okay. The first one is in my opinion more intuitive:

```js
const model = Collection.findOne(query, {reactive: false});
```

**Comment by serkandurusoy** [comment]
Yep! That would be my preference as well. Thank you.

As a final feedback, I had to look at the source code to figure out that "model" was the property that I needed to pass on some first form data. Autoform for example uses the "doc" property which is more intuitive. Model gets confused with the "schema" in terms of meaning.

**Comment by radekmie** [comment]
I've chosen `model`, because this package is not only Meteor but also database independent.

**Comment by serkandurusoy** [comment]
But it is the same. A model refers to the "shape/constraints" of a database, not the data it contains. Whereas a doc (nosql) or record (sql) refers to the actual data.

**Comment by matheusjardimb** [comment]
@radekgronski I've spent quite some time looking for this info and I believe it should be part of documentation, considering it's a very common scenario. Am I right?

**Comment by radekmie** [comment]
@matheusjardimb I guess you wanted to ping me _(but of course I might be wrong)_. It is now, in the [Quick start](https://github.com/vazco/uniforms/blob/master/INTRODUCTION.md#quick-start) section, isn't that clear enough?

**Comment by matheusjardimb** [comment]
@radekgronski Somehow I've missed that doc. Thanks anyway :)
