### ISSUE TITLE
AutoForm with multiple SubmitFields

### ISSUE THREAD

**Issue by JWDobken** [vazco/uniforms#180]
Is it possible to have two inline buttons with different actions (`onSubmit` actions)?

**MWE**
```
import { AutoForm, AutoField, SubmitField} from 'uniforms-bootstrap3';
...
<AutoForm
      schema={Items._collection.simpleSchema()}
      onSubmit={doc => this.stopItem(doc)}
      >
      <AutoField name="completedAt" label="Stop/Replace item at:" />
      <SubmitField value="Replace"/>
      <SubmitField value="Stop"/>
</AutoForm>
```

Two buttons are now shown above each other and both result in the same action

**Comment by radekmie** [comment]
If you'll take a look at the [`SubmitField` source](https://github.com/vazco/uniforms/blob/master/packages/uniforms-unstyled/src/SubmitField.js#L5-L13), then you'll see, that it's not doing a single thing. You can either render `<button>`/`<div>`/`<anything>` and on some action do its job and then call submit _(or do it in the reversed order)_ - that's all.

**Comment by JWDobken** [comment]
So... is it possible for the `onSubmit` to know which button is pressed?

**Comment by radekmie** [comment]
No.

**Comment by radekmie** [comment]
I think we can close it. If anything bothers you - just comment here.
