### ISSUE TITLE
Use CustomAutoField example with nested fields?

### ISSUE THREAD

**Issue by Gervwyk** [vazco/uniforms#181]
I'm trying to implement the [CustomAutoField](https://github.com/vazco/uniforms#example-customautofield) example but having trouble with with nested fields since `CustomAuto` is not called for nested fields. Schema definitions like:

````
  'chartCursor.cursorColor':{
      type: String,
      label: 'Cursor color',
      defaultValue: '#888',
      uniforms: {
        fieldComponent: 'color'
      }
    }
````
and 
````
  'bands.$.color':{
    type: String,
    label: 'Band color',
    defaultValue: '#888',
    uniforms: {
      fieldComponent: 'color'
    }
  }
````
Although works well for top level fields. Is there a better way to do this? or why is `CustomAutoField` not executed for nested fields?

I tested this for BS3 and antd theme.

**Comment by radekmie** [comment]
Well, it's not a bug, rather a new feature. Currently, `NestField` _(and others)_ are simply [importing _nearest_ `AutoField`](https://github.com/vazco/uniforms/blob/master/packages/uniforms-unstyled/src/NestField.js#L7) and [using it](https://github.com/vazco/uniforms/blob/master/packages/uniforms-unstyled/src/NestField.js#L27) - [`autoField` prop being used only at the top level](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/QuickForm.js#L53). There is no easy way to do it now, but I'll add it to the roadmap.

**Comment by radekmie** [comment]
Hey, @Gervwyk! It've been a while, but I've finally came to an idea. I'd introduce `autoField` option to `connectField`:

```js
const CustomAuto = props => ...;
const CustomAutoField = connectField(CustomAuto, {autoField: true, ensureValue: false, includeInChain: false, initialValue: false});
```

It will mark this field as an `AutoField` _(or it's replacement)_. This information will be passed down the context, so every field will know, what the current `AutoField` is. There's only one flaw...

```js
<AutoField name="x">
    <Auto name="x" ...>
        <CustomAutoField name="x" ...>
            <CustomAuto name="x" ...>
                ...
            </CustomAuto>
        </CustomAutoField>
    </Auto>
</AutoField>
```

Yep, that's it. We _can't_ replace usage of _default_ `AutoField` with `CustomAutoField`, so it has to be nested.

What do you think?

**Comment by radekmie** [comment]
Other idea.
Introduce `itemProps` in `NestField` like in `ListField`. Then:
```js
const schema = new SimpleSchema({
    tags: {
        type: [String],
        uniforms: {
            itemProps: {
                component: CustomAutoField
            }
        }
    }
});
// Then...
<AutoForm autoField={CustomAutoField} schema={schema} />
```

Will work as expected.

**Comment by Gervwyk** [comment]
Great! The second option seems easy to implement and fits well with current model. Thanks! Guess this one is finally resolved.
