### ISSUE TITLE
SimpleSchema2Bridge: throws error if autoValue calls this.unset()

### ISSUE THREAD

**Issue by macrozone** [vazco/uniforms#182]
On line https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/SimpleSchema2Bridge.js#L104

it calls the autoValue of the schema with a new this-context, but this does not contain this.unset() (or other functions like this.field() and this. siblingField() to access another field).

**Comment by radekmie** [comment]
Yeah, there is no an _easy_ way to do it. I've got two ideas: either try to mock as much as we can or wrap it with `try {...} catch (...) {...}` and leave it as it is right now. What do you think?

For reference:
aldeed/node-simple-schema#27
[Source of `defaultValue` wrapper](https://github.com/aldeed/node-simple-schema/blob/master/lib/SimpleSchema.js#L688-L696)
[Source of `defaultValue` transformation](https://github.com/aldeed/node-simple-schema/blob/master/lib/SimpleSchema.js#L737-L750)
