### ISSUE TITLE
Help, please.  Loading existing record into form for update.  Best practice.

### ISSUE THREAD

**Issue by dude-awap** [vazco/uniforms#186]
Where in the documentation can I learn about loading form fields with values from an existing data record?

**Comment by radekmie** [comment]
Just pass it as a `model` prop. There is an example `PostUpdateForm` in [Quick Start](https://github.com/vazco/uniforms#quick-start) section.

**Comment by dude-awap** [comment]
Sorry, I should have mentioned I am using GraphQL, nor SimpleSchema.  Is it the same?

**Comment by radekmie** [comment]
There is no difference - that is the clue of this package.

**Comment by dude-awap** [comment]
So in [GraphQL definition](https://github.com/vazco/uniforms#graphql-definition) the data model is called `schemaData` and must be passed in like this ...

    const bridge = new GraphQLBridge(schemaType, schemaValidator, schemaData);

..., correct?

**Comment by radekmie** [comment]
No, `model` Is the _value_ of the form, the current state of inputs. There is no way In GraphQL to define additional properties of fields, like labels or placeholders - that is what `schemaData` is for.

**Comment by dude-awap** [comment]
Got it.  It works!

Thanks.
