### ISSUE TITLE
Any reason the material-ui branch was never merged?

### ISSUE THREAD

**Issue by dpankros** [vazco/uniforms#187]
I just forked the repo to change the material BoolField to a toggle and I see that it has been done and is sitting there unmerged.  Is there a reason for this?

**Comment by radekmie** [comment]
There was branch `material-ui` left _(I've removed it already)_, but I don't really get you. Yes, previously we have been using `<Toggle />` for `<BoolField />`, but we changed it in the final implementation.

**Comment by dpankros** [comment]
I must have misread the diff.  I thought someone started to switch from the checkbox TO the toggle.   and then never merged the change into master, but evidently the reverse was true.

Seems to me that you would want to make it a property of the BoolField e.g.
```
<BoolField name='field' useToggle={true} /> //render as a toogle
<BoolField name='field' /> //render as a checkbox
```
(or something like that.)  That's what I was planning to do anyway.  I'll just add it back in my fork.  Thanks!

**Comment by radekmie** [comment]
Maybe you want to submit a PR with this change?

**Comment by dpankros** [comment]
Done.  #189
