### ISSUE TITLE
Multi-select example

### ISSUE THREAD

**Issue by thearabbit** [vazco/uniforms#192]
Could example how to create multi select on "Material-UI"?

**Comment by janowsiany** [comment]
Same as in other packages:
`
new SimpleSchema({
    size: {
        type: [String],
        defaultValue: 'm',
        allowedValues: ['xs', 's', 'm', 'l', 'xl']
    }
})
`

**Comment by thearabbit** [comment]
Thanks for your reply.
I would like to `Multi select` not `checkbox`
([Super SelectField](https://github.com/Sharlaan/material-ui-superSelectField))

**Comment by janowsiany** [comment]
Super SelectField is not part of [material-ui](https://github.com/callemall/material-ui) package, see [list of its components](http://www.material-ui.com/#/components).

**Comment by radekmie** [comment]
@thearabbit you can use [`connectField`](https://github.com/vazco/uniforms/blob/master/API.md#connectfield) to integrate it easily.

**Comment by janowsiany** [comment]
@radekmie @thearabbit I will show an example in [#194](https://github.com/vazco/uniforms/issues/194)

**Comment by thearabbit** [comment]
Thanks I will try soon
