### ISSUE TITLE
Could you detail how to in "uniform-tool" like "autoform-tool"?

### ISSUE THREAD

**Issue by thearabbit** [vazco/uniforms#195]
Could you detail how to in "uniform-tool" like "autoform-tool"?
Such as show `form code, input type, form type...`

**Comment by radekmie** [comment]
Sorry, your question makes no sense to me. What is `uniform-tool` or `autoform-tool`?

**Comment by thearabbit** [comment]
I would like to request you detail about `uniform demo` like [autoform demo of aldded](http://autoform.meteorapp.com/)

**Comment by radekmie** [comment]
[uniforms.tools](https://uniforms.tools/).

**Comment by thearabbit** [comment]
Could you detail such as `form type, fields type...`?

**Comment by radekmie** [comment]
[API.md](https://github.com/vazco/uniforms/blob/master/API.md) & [README.md](https://github.com/vazco/uniforms/blob/master/README.md).
