### ISSUE TITLE
"Unable to resolve some modules" warning

### ISSUE THREAD

**Issue by MacRusher** [vazco/uniforms#196]
Meteor is trying to be overprotective and gives a warning every time some npm package is importing unknown module.

This is an issue with uniforms peer dependencies that are optional like `graphql` or `simpl-schema`.

```
Unable to resolve some modules:

  "graphql" in /home/maciek/vazco/store/mp_vazco_store/node_modules/uniforms/GraphQLBridge.js (web.browser)
  "simpl-schema" in /home/maciek/vazco/store/mp_vazco_store/node_modules/uniforms/SimpleSchema2Bridge.js (web.browser)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save graphql simpl-schema
```

Uniforms are prepared for this missing dependencies, but Meteor does not know that and could show this message every time server restarts, which is very annoying.

Most people just add missing packages to silence the warning, but this is not a good solution for this problem :)

Until there is some other way to silence this message, we could change how this dependencies are imported. I'll prepare a PR with my solution.

**Comment by radekmie** [comment]
I'd love to merge it, but it breaks webpack build. See #150.
