### ISSUE TITLE
uniforms-antd multi-select gives issue caused by empty string in array

### ISSUE THREAD

**Issue by Gervwyk** [vazco/uniforms#199]
When using a multi-select on antd theme. The field renders fine but when a model is given through Autoform and then cleared it gives (pass no / empty model):
`Uncaught Error: must set key for <rc-animate> children`
After debugging, I think this is related to [this](https://github.com/ant-design/ant-design/issues/1851) issue.

I think that it is cause by this line:
https://github.com/vazco/uniforms/blob/master/packages/uniforms-antd/src/SelectField.js#L52
which should not pass empty string in array.

Not sure what would be the best fix, but think it should be filtered in the select field.

**Comment by radekmie** [comment]
@Gervwyk what do you think about:
```diff
-value={Array.isArray(props.value) ? props.value : '' + props.value}
+value={props.fieldType === Array ? props.value || [] : '' + (props.value || '')}
```

**Comment by Gervwyk** [comment]
Logically looks like a good fix..
