### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by serkandurusoy** [vazco/uniforms#20]
The project requires a contribution guide that describes how to

* set up necessary environment
* development dependencies and how to install them (lerna and stuff)

And then we should describe

* hot contribution workflow should be
* base coding style guidelines
* things to watch out for
* things to do etc

**Comment by radekmie** [comment]
I think I will create a [`CONTRIBUTING.md`](https://github.com/blog/1184-contributing-guidelines) - it's a clean way to do it.

**Comment by serkandurusoy** [comment]
Thank you

**Comment by jakobloekke** [comment]
How do I include the local, forked version in my main project?
I tried the usual `npm link` in uniforms and uniforms-semantic, but I can't get it to work. I have no experience with Lerna-projects – what steps are necessary to prepare the project for use?

Here's the error I get:
```
Unable to resolve some modules:

  "/Users/jakobloekkemadsen/web/forks/uniforms/packages/uniforms" in
/Users/jakobloekkemadsen/web/projects/name_of_meteor_project/node_modules/uniforms-semantic/node_modules/uniforms/index.js
(os.osx.x86_64)
```

It feels like some cross-referencing is not set up properly.

**Comment by radekmie** [comment]
@jakobloekke
Unluckily, there's no _easy way_. You can use [relative path in `package.json`](https://github.com/vazco/uniforms/blob/master/docs/package.json#L9-L13), and then _refresh_ it with:

```shell
rm -rf node_modules/uniforms* && npm i
```
