### ISSUE TITLE
Custom fields types

### ISSUE THREAD

**Issue by cesarve77** [vazco/uniforms#201]
First thanks for this repo.
(sorry for my english)

Is possible supply information to how create or extends a custom type, for example a slider, or a custom date picker.

It will very useful to make grow up this project.

bye,

**Comment by radekmie** [comment]
Examples are in the [readme](https://github.com/vazco/uniforms):
* [Example: `CompositeField`](https://github.com/vazco/uniforms#example-compositefield)
* [Example: `CustomAutoField`](https://github.com/vazco/uniforms#example-customautofield)
* [Example: `CycleField`](https://github.com/vazco/uniforms#example-cyclefield)
* [Example: `RangeField`](https://github.com/vazco/uniforms#example-rangefield)
* [Example: `RatingField`](https://github.com/vazco/uniforms#example-ratingfield)

API is in the [API.md](https://github.com/vazco/uniforms/blob/master/API.md#connectfield).

There are also issues, which contains custom fields like [this](https://github.com/vazco/uniforms/issues/194#issuecomment-279455096).
