### ISSUE TITLE
uniforms-semantic: possibility to remove "grouped" class from NestField?

### ISSUE THREAD

**Issue by rereradu** [vazco/uniforms#202]
I'm trying to create a two-column form using a "row" object with `className: "two"` (SimpleSchema2, AutoForm), and two subsequent objects that represent the left and the right columns. 

However, because of the `grouped` class that is added automatically to the NestField generated by the objects, the layout fails to split in two columns. 

Removing this class would solve this issue and would make creating various form layouts much easier. 
For backwards compatibility, there could be an `isGrouped` prop, which could be set to `true` by default, allowing to "toggle" the `grouped` class on or off.

Is there any other way to achieve something similar, using only the schema and the AutoForm?

**Comment by radekmie** [comment]
Hey @rereradu! I have a question: which theme? Also, could you show an example of desired markup/schema?

**Comment by rereradu** [comment]
I'm using the semantic theme.

Here's a sample schema of what I'm trying to obtain:

```
twoColumnLayoutSchema = new SimpleSchema2({
    row : {
        type: Object,
        optional: true,
        uniforms: {
            className: "two",
            label: null
        }
    },
    'row.left' : {
        type: Object,
        optional: true,
        uniforms: {
            label: null,
            className: "grouped"
        }
    },
    'row.left.Name' : {
        type: String,
        max: 50,
        uniforms: {
            className: "wide sixteen",
        }
    },
    'row.left.Surname' : {
        type: String,
        max: 50,
        uniforms: {
            className: "wide sixteen",
        }
    },
    'row.right' : {
        type: Object,
        optional: true,
        uniforms: {
            label: null,
            className: "grouped"
        }
    },
    'row.right.City': {
        type: String,
        max: 100,
        uniforms: {
            className: "wide sixteen",
        }
    },
    'row.right.State': {
        type: String,
        max: 100,
        uniforms: {
            className: "wide sixteen",
        }
    }
})
```

Notice the `className: "grouped"`, which is manually added only to the "right" and "left" column objects, while the row object has `className: "two"`

This is an example markup of what I want to achieve:

  ```
<div class="two fields">
    // First column
    <div class="grouped fields">
        <div class="wide sixteen required field">
            <div class="ui input">
                ....
            </div>
        </div>
        <div class="wide sixteen required field">
            <div class="ui input">
                ....
            </div>
        </div>
    </div>

    // Second colummn
    <div class="grouped fields">
        <div class="wide sixteen required field">
            <div class="ui input">
                ....
            </div>
        </div>
        <div class="wide sixteen required field">
            <div class="ui input">
                ....
            </div>
        </div>
    </div>
</div>
```

I am trying to get this layout using simply `<AutoForm schema={twoColumnLayoutSchema} />` (self-closing tag).

I'm not sure is this is the right way to go about this (my collections would have to contain this right/left structure, not necessarily ideal), or I should give up on the self-closing tag and create the layout inside  the `<AutoForm>` tag. The only problem with this is that my app will has many different forms and it would be much easier to use the self-closing tag.

**Comment by janowsiany** [comment]
@rereradu One tought about this aproach is that any change in the layout with cause changes in the schema and database.
For example when you would like to switch columns and have city and state on the left and name and surname on the right.

**Comment by rereradu** [comment]
You are right. Thinking more and more about this, I realize my approach is not probably the best. I think I will stick to setting up the desired layout (I'm also using the `semantic-ui-react` package) inside the `<AutoForm>`. I am also exploring other options (extending the schema, using `connectField` to create custom fields, etc...).

Nevertheless, I believe allowing to remove the `grouped` class from `NestField` manually could be a useful feature.

**Comment by radekmie** [comment]
@rereradu At the beginning - you can use a simple transformation before passing the model to the form and make use of `modelTransform` _(or do it manually in `onSubmit`)_ to keep DB clean and schema as it is now. Secondly, it's a bad idea to force layout by schema. Have you thought about some _layout schema_? Like, still having single self-closing tag but more with intelligent layout. Still, removing the class from the fields is also a thing to consider... I'll answer you later or tomorrow.

**Comment by radekmie** [comment]
@rereradu OK, I'm also for `grouped` prop on `NestField`. To make it backwards-compatible, default `true` is required. Do you want to submit a PR for it?

**Comment by radekmie** [comment]
@rereradu?
