### ISSUE TITLE
It would be useful make select field searchable in uniforms-antd

### ISSUE THREAD

**Issue by Gervwyk** [vazco/uniforms#203]
Not sure if it makes sense to includes this as an optional, but I think it might as well be always enabled. 

Its real simple. Have a look at:
https://ant.design/components/select/#components-select-demo-search
it suggests to add:
`filterOption={(input, option) => option.props.value.toLowerCase().indexOf(input.toLowerCase()) >= 0}`
to Select props. 

The multi-select option is currently searchable. I have a suspicion that the `transform` option should be included here, since users want to search by label and not by value. However the [selectfield](https://github.com/vazco/uniforms/blob/master/API.md#selectfield) documentation in lacking.

Would be useful since select list are often long (countries).

**Comment by radekmie** [comment]
I'm strongly against setting it as a default, but there should be `filterDOMProps` In the `SelectField`, so you can use it already, like it's used in other fields and themes. Would you like to submit a PR for it?

**Comment by Gervwyk** [comment]
Agreed. Will try some options tomorrow and send PR.

**Comment by radekmie** [comment]
@Gervwyk?

**Comment by Gervwyk** [comment]
Cool. It worked. Check PR.
Schema example for future users:
````
new SimpleSchema({
    size: {
        type: String,
        defaultValue: 'm',
        allowedValues: ['xs', 's', 'm', 'l', 'xl'],
        optional: true,
        uniforms: {
         showSearch: true,
         filterOption: (input, option) => option.props.value.toLowerCase().indexOf(input.toLowerCase()) >= 0
        }
    }
})
````
