### ISSUE TITLE
Fail validation in complex schemas

### ISSUE THREAD

**Issue by cesarve77** [vazco/uniforms#206]
Hi, I'm using SimpleSchema to create a form like this:

```
schema = new SimpleSchema({
    title: {type: String},
    address: {type: Object},
    "address.address": {type: String},
    "address.placeId": {type: String},
    "address.position": {type: Object},
    "address.position.lat": {type: Number, decimal: true},
    "address.position.lng": {type: Number, decimal: true},
})
```
I'm using my custom component to get the address from a map.
![captura de pantalla 2017-02-28 a las 3 27 16 p m](https://cloud.githubusercontent.com/assets/3970983/23392912/919a60fe-fdca-11e6-8ff2-2744fd5f9978.png)

This component return or undefined or a object like 
`{address,placeId,position:{las,lng}}`

The form effectively no allow be submited because the field is required but I'can figuere out how show the message, im using wrapField function

I made this repo for show the problem and the code

https://github.com/cesarve77/uniforms-map

**Comment by radekmie** [comment]
Hey, @cesarve77! I'll give it a shot later, but maybe we can fix it earlier. I don't get this line:
> The problem is no error is no required error is detected by uniforms

**Comment by cesarve77** [comment]
I was playing and I don't now how but is working now.

**Comment by radekmie** [comment]
Well, then let's close it for now and let me know, if it won't be working.

**Comment by cesarve77** [comment]
I had to fire onChange event after mounted the component, to Autoform know the value
