### ISSUE TITLE
LongTextField does not have a "rows" prop

### ISSUE THREAD

**Issue by tab00** [vazco/uniforms#208]
`LongTextField` is meant to render as a textarea, i.e. a multi-row field for user text input. However the API does not have any prop to set the number of rows: https://github.com/vazco/uniforms/blob/10ef9ba2445f4d23051109ab0ac19ba48bc52038/API.md#longtextfield

How can we set the number of rows?

**Comment by janowsiany** [comment]
Hello @tab00 can you specify which package are you talking about?

**Comment by tab00** [comment]
I am using the uniforms-bootstrap4 theme, though is the theme actually relevant?

**Comment by janowsiany** [comment]
Components such as LongTextField are handled differently in each packages, specifically for the package like `bootstrap4` or `material-ui`. However as you pointed rows property is not passed down to textarea input as you can see in the [sources](https://github.com/vazco/uniforms/blob/master/packages/uniforms-bootstrap4/src/LongTextField.js#L10-L17).
Would you like to handle `rows` property there and submit a PR?

**Comment by tab00** [comment]
Would simply adding `rows={props.rows}` in the section that you have referred to fix it?:

```
const LongText = props =>
    wrapField(props, (
        <textarea
            className={classnames(props.inputClassName, 'form-control', {'form-control-danger': props.error})}
            disabled={props.disabled}
            id={props.id}
            name={props.name}
            onChange={event => props.onChange(event.target.value)}
            placeholder={props.placeholder}
            ref={props.inputRef}
            value={props.value}
            rows={props.rows}
        />
   ))

```

**Comment by janowsiany** [comment]
It is that simple.

Don't bother if it will not work in demo app, i see now that it has some [custom styles](https://github.com/vazco/uniforms/blob/master/demo/components/ApplicationPropsField.js#L28-L31) which should only refer to left panel. Make your PR anyway.

**Comment by radekmie** [comment]
@janowsiany - use `filterDOMProps` instead of passing every prop. I'll try to cover it, but as always PRs are encouraged.
