### ISSUE TITLE
[Idea] Better docs, examples and playground

### ISSUE THREAD

**Issue by serkandurusoy** [vazco/uniforms#21]
I would like to keep contributing to uniforms because I think it fills an important gap for meteor developers who transition from blaze to react. The seamless integration with simple schema makes this package the single most important gap-filler that was the lack of an autoform counterpart in react. There are other very powerful form libraries and they can be extended into working with simple schema yadi yada but this is the out of box thing so I think it deserves the attentio!

That all being said, I think the number one hurdle is documentation and examples. For meteor developers who are used to blaze and autoform, react is a whole new paradigm and uniforms' current documentatio can be overwhelming or unclear, although it is quite good if you know what you are dealing with and the source code is quite self-explanatory.

I would like to open up a discussion where we decide how we can *empower* and *encourage* less experienced meteor developers with and to use uniforms.

I think

* a dedicated documentation site (github pages)
* folder of examples that can be copied and run easily
* a playground like autoform.meteorapp.com

would go along way, and I sure would like to contribute to any one and all of them.

Now I know simple schema and some meteor dependencies are hard to get running in a browser-only environment so the playground would require hosting. So for starters, I would like to sponsor a 512mb digitalocean server for that.

So what do you think about the overall idea? Do you think we can tackle these?

**Comment by radekmie** [comment]
Wow, that very kind of you, @serkandurusoy! Yes, you've got me... There *is* already small repo with few examples - I had to test it somewhere, right? - but it's not ready at all... I've planned to make it public but I don't have that much time. For now, I'll add you @serkandurusoy, then we can make it public.

**Comment by serkandurusoy** [comment]
Great! Thank you, I'm very excited about this. I'll take a look at the
examples this week and see what I can contribute.

In the meantime, I'll set up a server and give you access.

Would a clean ubuntu 16.04 64-bit image suffice?

You should email me your public key.

Would you like to use mup to deploy the examples or set up CI?

**Comment by radekmie** [comment]
Hooray! Let's first make something, then host it, okay?

**Comment by serkandurusoy** [comment]
Sure!

I have a few things in mind, I'll note them down and post them over at the
examples repo!

**Comment by zeroasterisk** [comment]
:+1:

**Comment by radekmie** [comment]
I've started to work on documentation. The documentation itself is already implemented (markdown FTW!), but it has to be written (or at least taken from `README.md`). Examples are coming.

**Comment by radekmie** [comment]
Closing in favor of #92 (more about playground is coming).
