### ISSUE TITLE
How to write custom field component?

### ISSUE THREAD

**Issue by thearabbit** [vazco/uniforms#215]
Could example to create custom field for [Bootsrap 3 Datepicker](http://eonasdan.github.io/bootstrap-datetimepicker/)?
```js
const PostSchema = new SimpleSchema({
    publishedDate: {
        type: Date
    }
})
```

**Comment by janowsiany** [comment]
Try [API.md](https://github.com/vazco/uniforms/blob/master/API.md) and [README.md](https://github.com/vazco/uniforms/blob/master/README.md) yourself. Then if you still encounter some troubles you can share your work here and we can help you.

**Comment by janowsiany** [comment]
You can also see this [comment](https://github.com/vazco/uniforms/issues/194#issuecomment-279455096).
