### ISSUE TITLE
how to use "TreeSelect" in "antd"?

### ISSUE THREAD

**Issue by thearabbit** [vazco/uniforms#218]
Could you example, how to use `TreeSelect` in `Antd`?
Thanks for your helping.

**Comment by janowsiany** [comment]
See comments in #215 and #216.

**Comment by thearabbit** [comment]
Thanks for your reply, could you example?

**Comment by janowsiany** [comment]
I beleive that it might be better if you will try yourself and then share your work here and then we can help you.
