### ISSUE TITLE
You are using a whole package of antd, please use...

### ISSUE THREAD

**Issue by thearabbit** [vazco/uniforms#219]
I base on `METEOR@1.4.3.1`.
After I update to `"antd": "^2.7.4",  "uniforms-antd": "^1.13.1"`, I get error
```js
You are using a whole package of antd,
please use....
```
My package
```js
// babelrc
{
  "plugins": [
    [
      "import",
      {
        "libraryName": "antd",
        "style": "css"
      }
    ],
    "transform-class-properties"
  ]
}
```
Please help me.

**Comment by Gervwyk** [comment]
This is what worked for me. 
Firstly ensure that you have (babel-plugin-import) [https://www.npmjs.com/package/babel-plugin-import] installed. In `.babelrc` I only have:
````
{
  "plugins": [
    ["import", {"libraryName": "antd"}]
  ]
}
````
Then when you do imports, always use (for example Icon):
`import Icon from 'antd/lib/icon`
To only import the component you are using. This is all that I can think of now. Let me know if this helps.

**Comment by thearabbit** [comment]
Thanks for your reply. This is my package:
```js
{
  "name": "ant-design",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "antd": "^2.7.4",
    "babel-plugin-import": "^1.1.1",
    "babel-runtime": "^6.23.0",
    "classnames": "^2.2.5",
    "flexboxgrid": "^6.3.1",
    "graphql": "^0.9.1",
    "indexof": "0.0.1",
    "jquery": "^3.1.1",
    "jquery-validation": "^1.16.0",
    "meteor-node-stubs": "~0.2.3",
    "moment": "^2.17.1",
    "react": "^15.4.2",
    "react-addons-pure-render-mixin": "^15.4.2",
    "react-dimensions": "^1.3.0",
    "react-dom": "^15.4.2",
    "react-flexbox-grid": "^0.10.2",
    "react-mounter": "^1.2.0",
    "react-sizeme": "^2.2.0",
    "simpl-schema": "^0.2.2",
    "uniforms": "^1.13.1",
    "uniforms-antd": "^1.13.1"
  },
  "devDependencies": {
    "babel-plugin-import": "^1.1.0",
    "babel-plugin-transform-class-properties": "^6.23.0",
    "babel-polyfill": "^6.23.0"
  }
}
---
{
  "plugins": [
    [
      "import",
      {
        "libraryName": "antd",
        "style": true
      }
    ],
    "transform-class-properties"
  ]
}
```
and then I tied to add `@import '{}/node_modules/antd/dist/antd.less';` to `/client`

**Comment by thearabbit** [comment]
So it mean that we must be need `import ... from 'antd/lib/...` for all.

**Comment by Gervwyk** [comment]
I do not have any `plugins` key in  my `package.json` and have the:
````
{
  "plugins": [
    ["import", {"libraryName": "antd"}]
  ]
}
````
In the `.babelrc` file in the root of my project folder.
 
In my clientroot.less file I have:
````
@import '{}/node_modules/antd/dist/antd.less';
@primary-color: #434d52;
@border-radius-base: 2px;
````
To overwrite less variables.
and yes for all `import ... from 'antd/lib/...` imports.

**Comment by thearabbit** [comment]
Sorry for `plugins key` is in `.babelrc` (not in package.json), I will try soon.
So we can use `import { Menu, Icon } from 'antd';`

**Comment by thearabbit** [comment]
Now it work fine, Very thanks.
Request you to create all of component such as `Date Range, Tree Select....`!

**Comment by Gervwyk** [comment]
In my project, if I have one of:
`import { Menu, Icon } from 'antd';`
instead of:
````
import Menu from 'antd/lib/menu';
import Icon from 'antd/lib/icon';
````
I get the warning that you refer to. If I import the defaults like in the second one, the warning goes away. What exactly the reason is I don't know.

Some of those components you should build as a custom component and render though uniforms. Currently `uniforms-antd` has the base set of components as all the other uniforms themes, I don't think that will change. 
Maybe in the future we can have a standard to publish extra custom components separately? ( @radekmie ) but I not sure how that would work. But that should not be discussed in this issue. 

Glad it worked.

**Comment by radekmie** [comment]
As you can see in the sources, none of `uniforms-antd` components is importing `antd` - every import is a direct one, for example `antd/lib/icon`.

**Comment by salaimuniselvam-s** [comment]
I also have the same issue .. how do i fix it...
