### ISSUE TITLE
Regression in `1.0.0-rc.13`

### ISSUE THREAD

**Issue by radekmie** [vazco/uniforms#22]
Moved from #17:

> @serkandurusoy:
> > @radekmie I think this has created a regression. Now the validation is constantly running and interestingly logging warnings in the console and moving the text cursor to the end of the input!
> > 
> > For example try entering text into the middle of an existing input that does not pass validation
> > 
> > ![image](https://cloud.githubusercontent.com/assets/4649948/15862725/354f4390-2cd9-11e6-8092-5f407d5c81c9.png)
> > 
> > notice also the logs! I'm not logging this and interestingly, I have not even submitted the form and it is not autosave either.
> > @radekmie I confirm that this is a regression. Reverting back to 12 fixes the problem.

**Comment by radekmie** [comment]
@serkandurusoy, I've tried to reproduce this behaviour, but I couldn't. Also, I've checked the whole repository and there's no single warning (even no `console` outside the README). Could you post an example?

**Comment by serkandurusoy** [comment]
@radekmie here's a minimal reproduction repo

https://github.com/serkandurusoy/uniforms-issue22-reproduction

**Comment by radekmie** [comment]
Great! I'll take care of this.

**Comment by radekmie** [comment]
This looks like an React bug itself - [I've created an issue for that](https://github.com/facebook/react/issues/6992).

**Comment by serkandurusoy** [comment]
@radekmie what about the normal text types?

they, too have the cursor moving to the end problem!

The strange thing is, the problem goes away when I revert to rc.12 what do you think about that?

**Comment by radekmie** [comment]
I've made `git bisect` and #19 is the problem. The main change is *dynamic* `type`.

**Comment by serkandurusoy** [comment]
Yeah I'm actually looking at it right now and trying something, I'll let you know in a minute

**Comment by serkandurusoy** [comment]
@radekmie I just pushed an update to my repo and included two custom components (text and email) that does not have dynamic type definition, but it still behaves the same,

* validation gets logged
* the cursor jumps

so it may not be related to #19 but a combination of the other changes with #19 

the cursor jumping might be a clue here about where we set the state of the value/error of the component such that it receives a rerender probably!

**Comment by serkandurusoy** [comment]
Please give me a minute and I'll try something even better, I'll base a custom component on rc.12!

**Comment by serkandurusoy** [comment]
@radekmie please take a look at https://github.com/serkandurusoy/uniforms-issue22-reproduction/tree/rc12-with-dynamic-type

this is basically rc.12 + #19 combined and excluding #17 changes

dynamic type is not a problem

**Comment by serkandurusoy** [comment]
Hmm, why did you remove this line:

https://github.com/vazco/uniforms/commit/4a56596f8a2e296f891316430cdba104cd21f8e6#diff-5d9d3a42e5c2e10ea4135efba1608dc4L82

**Comment by serkandurusoy** [comment]
I now tried rc.14 but did not make a difference in terms of this problem.

**Comment by radekmie** [comment]
I've removed it, because now `setState` is called either in callback of `onValidate` or [directly few lines later](https://github.com/vazco/uniforms/commit/4a56596f8a2e296f891316430cdba104cd21f8e6#diff-5d9d3a42e5c2e10ea4135efba1608dc4R89).

**Comment by serkandurusoy** [comment]
Yeah, that's what I thought but just wanted to make sure.

This is now becoming a mystery!

**Comment by serkandurusoy** [comment]
@radekmie I do confirm that this now solves this problem. thanks!

**Comment by serkandurusoy** [comment]
@radekmie part of the problem (the log messages about invalid inputs seen in the screenshot) started appearing again after the recent updates rc.23 and react 15.2
