### ISSUE TITLE
How to show "*" on required label (antd, bs...)?

### ISSUE THREAD

**Issue by thearabbit** [vazco/uniforms#225]
How to show "*" on required label (antd, bs...)?

**Comment by radekmie** [comment]
It's theme dependent, not configurable.

**Comment by thearabbit** [comment]
could example?

**Comment by radekmie** [comment]
Example of what? It's not configurable - your theme have it or no.

**Comment by davidworkman9** [comment]
This is easily solved in bootstrap 3 with CSS.

```
.form-group.required .control-label:before {
    content: "* ";
    color: red;
}
```
