### ISSUE TITLE
Stick select dropdown to container form - uniforms-antd

### ISSUE THREAD

**Issue by Gervwyk** [vazco/uniforms#228]
Would like to fix attaching select options dropdown to the form container. Like in:
http://codepen.io/anon/pen/xVBOVQ?editors=001
with `getPopupContainer={() => document.getElementById('area')}` on select component.

However, I need to set the reference to some value / container? Any idea how?
Wouldn't it make sense to have an id prop on the form container?

I'll create a PR once we decide how to implement.

**Comment by radekmie** [comment]
You can already set `id` on form - where's the problem?

**Comment by Gervwyk** [comment]
The Select field should always be attached to the form container. if one does not, the dropdown does not stick to the form when scrolling. So its not a matter of assigning an id once, there should always to an id or some reference to attach the dropdown container to the form. 

Is there a better way to do this rather than by id?
( see `getPopupContainer` field in https://ant.design/components/select/#Select-props)

**Comment by radekmie** [comment]
I don't see another way than somehow marking the form itself. I think this is rare enough problem, that you can do it on your own by passing your form an id and using `getPopupContainer={() => document.querySelector('#id')}`.

**Comment by Gervwyk** [comment]
I think its a very normal use case. If you have a form and a select field in a modal or any other floated container while scrolling, this will be a problem. And attaching it to the `form` container does make sense since the `Select` will always be in the form.

**Comment by radekmie** [comment]
I mean, it's quite rare to have a need for own form node reference. I've looked again into the documentation - you can have one function for each select, which will traverse up the DOM tree until the first form element.

**Comment by Gervwyk** [comment]
Ok. I guess a function like (this)[https://gomakethings.com/climbing-up-and-down-the-dom-tree-with-vanilla-javascript/]. So do you think it should not be handled by default since I can't think of a scenario where this behaviour is not desired?

**Comment by radekmie** [comment]
As you are interested in any `<form>` tag, function:

```js
const getPopupContainer = x => {
    while (x && x.tagName.toLowerCase() !== 'form') {
        x = x.parentElement;
    }

    return x;
};
```

Would be enough. I don't think we should include it in the package. Real life example? I have a form with only one field - select - for managing rest of the view. The form is ~50px tall, so this would break my form.

**Comment by Gervwyk** [comment]
Cool. Ok. but the dropdown is attached to the select like it would be normally if you where to not scroll. Not sure how having it would break someting? 

Another example of it breaking:
Say I have my form on a container with z-index > z-index body container, then the dropdown renders behind the form container. Attaching it to the form solves this else you must set z-index on select.

So its an issue for both scrolling and z-index settings. Should I include a screenshot?

**Comment by Gervwyk** [comment]
I guess unless  having it would break if you hide overflow on the form container..

**Comment by radekmie** [comment]
No, I get it. I just don't want to include it in the package - it's easily achievable.

**Comment by Gervwyk** [comment]
Ok. Agreed.

**Comment by radekmie** [comment]
Then I'm closing it but if needed, we can reference this issue.
