### ISSUE TITLE
Installation with latest material-ui not working

### ISSUE THREAD

**Issue by h2s20** [vazco/uniforms#231]
I am using the latest version of material-ui: "material-ui": "^0.17.0" and therefore I can't install uniforms-material because its dependency is material-ui@^0.16.7.

After trying to install I get the following error:
npm WARN uniforms-material@1.14.0 requires a peer of material-ui@^0.16.7 but none was installed.

**Comment by radekmie** [comment]
You _can_ install it - it's just a warning from npm. I haven't tried it with `material-ui@0.17`, that's why it's not said to be compatible _(yet)_. Anyway - is it working correctly? @janowsiany would you have some time to take a look at it?

**Comment by h2s20** [comment]
Ah, sorry, thougt it hasn't been installed but it is indeed just a warning.

Yes, at first glance I would say that it is working.

**Comment by radekmie** [comment]
@h2s20 maybe you want to take care of it? Running tests on updated version should be enough if they'll pass. If not, it shouldn't be much to do, according to the [release changelog](https://github.com/callemall/material-ui/releases/tag/v0.17.0).

**Comment by h2s20** [comment]
I'd like to help and please tell me if I am doing something wrong as  I am a hobbyist and not used to git and this is my very first PR.

I cloned uniforms, changed the dependency to 0.17.0, installed the latest version of material-ui and then I ran npm test. All tests passed.
Then I forked uniforms and only changed the line with the dependency and made a PR.

If you wanted me to do something different, or if I forgot somesthing - please tell me.

**Comment by radekmie** [comment]
Wow, @h2s20 I'm glad to hear it! I've already reviewed and commented on your PR.
