### ISSUE TITLE
[question] how to use external component with uniform

### ISSUE THREAD

**Issue by saeedjalali1** [vazco/uniforms#233]
Hi @radekmie,
I want using some other package like [drag and drop package](http://okonet.ru/react-dropzone/) ,[react-select](http://jedwatson.github.io/react-select/) and some other package or component (for example date picker). can you help me and show an example for this purpose. My other question is how to fill this component when using for updating forms (with set value)? 

Thanks a lot for your attention.

**Comment by janowsiany** [comment]
Hello there, it is the same as writing custom components in packages like `antd` or `material-ui`. 
See #215 and #216 as examples and starting points. You want to visit [README](https://github.com/vazco/uniforms/blob/master/INTRODUCTION.md#fields) and [API](https://github.com/vazco/uniforms/blob/master/API.md#connectfield) also.

If you will still encounter some problems please feel free to share you work here so we can help you.
