### ISSUE TITLE
problem with "multi select" on Material?

### ISSUE THREAD

**Issue by thearabbit** [vazco/uniforms#236]
- I try to upgrade `"uniforms": "^1.15.0"`, `"material-ui": "^0.17.1"`.
```js
// schema
categories: {
        type: [String],
        allowedValues: [
            "news",
            "image",
            "video"
        ]
    },

// Component
<SelectField
                        name="categories"
                        multiple={true}
                        hintText="Select a name"
                    />
```
- It show `Unknown prop `hintText` on <div> tag. Remove this prop from the element. For details...`
![image](https://cloud.githubusercontent.com/assets/4495160/24131513/a9a3b198-0e21-11e7-9207-21e3c3742cab.png)

- Multi Select on `"material-ui": "^0.17.1"`
![image](https://cloud.githubusercontent.com/assets/4495160/24131581/0663413c-0e22-11e7-965b-272b7e9ed032.png)

**Comment by radekmie** [comment]
I'll get to it soon.

**Comment by radekmie** [comment]
OK, now I get it. It's reasonable, that this warning shows up - there's no support for the multi-select within `SelectField` - there's only checkboxes _fallback_. @janowsiany, do you want to implement this?

**Comment by janowsiany** [comment]
I will handle this later today.
