### ISSUE TITLE
How to use "Semantic UI" with "Meteor JS"?

### ISSUE THREAD

**Issue by thearabbit** [vazco/uniforms#237]
I would like to try `Semantic UI` of `Uniforms` with `Meteor JS`.
Which I should use 
```js
meteor add semantic:ui
// or
npm install semantic-ui --save
// or
npm install semantic-ui-react --save
```
Please advise

**Comment by janowsiany** [comment]
If you want to use [uniforms-semantic](https://github.com/vazco/uniforms/tree/master/packages/uniforms-semantic), you need to use [Semantic UI](https://github.com/Semantic-Org/Semantic-UI) package. 
Currently uniforms does not have integration with [Semantic UI React](https://github.com/Semantic-Org/Semantic-UI-React).

**Comment by radekmie** [comment]
@thearabbit in short, you have to include semantic CSSs - either from CDN, npm package _(there are both CSS and LESS versions)_ or Meteor package.

**Comment by thearabbit** [comment]
Thanks @janowsiany  & @radekmie, I will try with `npm install semantic-ui --save`.
It show , Which one?
```js
Set-up Semantic UI
❯ Automatic (Use defaults locations and all components)
  Express (Set components and output folder)
  Custom (Customize all src/dist values)
```

**Comment by radekmie** [comment]
It's up to you - you can read more about it on their website.

**Comment by thearabbit** [comment]
Excuse me, If this success, I would like to ask you about add it to meteor
```js
// client/main.js
import .......
```
Please help me.

**Comment by MacRusher** [comment]
Detailed information about how to integrate Semantic UI with Meteor can be found here: https://github.com/Semantic-Org/Semantic-UI-Meteor
Note that instructions for Meteor <1.3 will still work, and may be considered easier to use.

There are few other ways to add SUI to your app (e.g. from CDN), uniforms to work just require the CSS code and are agnostic about how you add it to your app.
