### ISSUE TITLE
Autosave=true triggering validation immediately

### ISSUE THREAD

**Issue by todda00** [vazco/uniforms#238]
If autosave={true}, the form is validated immediately. 

If the autosave is enabled after it is rendered (like the uniforms.tools demo is) then validation does not occur until after the first change, but if its enabled at the time of form render, the validation occurs immediately. 

I have tried multiple schemas, and allowed AutoForm to use default field components both with the same results.

Using bootstrap4, Simple Schema 2

**Comment by janowsiany** [comment]
Hello there, thanks for reporting. This may be closely related with #204. Let me investigate this later today, ok?

**Comment by todda00** [comment]
Sure thing, no rush - I put a workaround in place which works by not setting autosave until onChange is triggered the first time:

```
const autosave = this.state[`autosave-${key}`] || false;
<AutoForm
  onSubmit={input => this.handleSaveShop({ input, uq, location })}
  schema={formSchema}
  model={shop}
  className="form-inline"
  onChange={() => this.setState({ [`autosave-${key}`]: true })}
  autosave={autosave}
>
```

**Comment by radekmie** [comment]
@todda00 could you share an example of schema what behaves like this?

**Comment by todda00** [comment]
This is the simpler of the 2 I tested it with:

```
export const schema = new SimpleSchema({
  _id: { type: String, regEx: SimpleSchema.RegEx.Id, optional: true },
  title: String,
  industry: String,
  sampleLink: { type: String, optional: true },
  introText: { type: String, optional: true },
  standardQuestions: { type: String, optional: true },
  minimumReimbursement: Number,
  cost: Number,
  published: {
    type: Boolean,
    defaultValue: false,
  },
});
```

**Comment by radekmie** [comment]
Thank you. I'm guessing right now, but it's caused by `defaultValue` - I'll get to it soon.

**Comment by todda00** [comment]
I had that thought as well, but I removed the defaultValue from the schema and it still validates immediately.

**Comment by radekmie** [comment]
Do you know that moment, when you start debugging something and result in rewriting a part of the core functionality? No? We are not similar then. It's fixed now and will be released soon, but it's worth mentioning, that uniforms will be faster now. Like, really faster for bigger forms.

_All tests are passing, I hope everything works..._
