### ISSUE TITLE
What do you think about "React Toolbox"?

### ISSUE THREAD

**Issue by thearabbit** [vazco/uniforms#240]
When I tried `React`  with `Material UI and React Toolbox`,  I thinks that `React Toolbox` is easy to understand than.
What do you thinks about `React Toolbox`?

**Comment by radekmie** [comment]
As I understand, you are asking about our opinion. It's not a place to do so, really.

**Comment by janowsiany** [comment]
@thearabbit If you want to integrate [react-toolbox](https://github.com/react-toolbox/react-toolbox) with uniforms, feel free to [contribute](https://github.com/vazco/uniforms/blob/master/CONTRIBUTING.md). I will gladly help you with this work, just submit PR and share your work.
