### ISSUE TITLE
Wrapper div has no height or width, try overriding style with `containerStyle` option on "Antd"

### ISSUE THREAD

**Issue by thearabbit** [vazco/uniforms#242]
I tried `antd`, show
```js
Wrapper div has no height or width, try overriding style with `containerStyle` option
```
but my ui work fine.

**Comment by Gervwyk** [comment]
Could you please give some more information? What does you schema look like? 
Trying to figure out where you saw this warning? I haven't seen it before. 
Please be as descriptive as possible when logging an issue.

**Comment by radekmie** [comment]
@thearabbit?

**Comment by radekmie** [comment]
No response so far, so I'm closing.
