### ISSUE TITLE
Improve Meteor demo with sample methods

### ISSUE THREAD

**Issue by Floriferous** [vazco/uniforms#243]
If I'm not mistaken, the meteor demo doesn't actually save the form to a collection, it stores it in the state of one of the top-level components. It would be really useful to make this package even more plug-n-play by providing sample onSubmit/onChange functions that handle inserts, updates, and upserts.
Especially for AutoForm with autosave which gives the full model back, instead of the individual field that has been changed, it would be handy to have a simply optimized method to look up and use.

I understand that this is a much more meteor-agnostic package than aldeed's autoform, which does this out of the box, so it is not a question to integrate this into the package, but I'm sure an example setup like this probably already exists on someones computer to merge into the repo :)

**Comment by janowsiany** [comment]
Hello there, thanks for submitting your issue! You are completly right as there is no onSubmit handler on demo form. Form state is just stringified `onChangeModel` and displayed to the user.

Regarding adding such examples to the demo app, i am not convinced if it is necessary, as handling inserts, updates or upserts is not in the competence of this package and actually it is super simple.

So lets consider demo app source code. So to handle insert you need to do following steps:
In `main.js` file add following lines:
```js
import {Mongo} from 'meteor/mongo';

...some code...

export const Demos = new Mongo.Collection('demos');

Demos.allow({
    insert: () => true
});
```
and in `/components/ApplicationPreviewField.js` file those ones:
```js
import {Demos} from '../main';

...some code...

// Change this \/
<Form key={this.props.value.schema} onChangeModel={this.onModel} {...props} />
// Into this \/, generally just adding onSubmit property
<Form key={this.props.value.schema} onChangeModel={this.onModel} onSubmit={model => Demos.insert(model)} {...props} />
```
This should result in creating new Demo entity in Demos collection.
If you have any further questions, please feel free to ask. I will wait a day or two for others to express themselves, then i will close this issue if there will not be any remarks.

**Comment by radekmie** [comment]
Hey, @Floriferous!
As you've already noticed, it's a completely agnostic package, therefore it won't be included in the demo _(to be honest, the only reason why the demo is built using Meteor is that the old version of SimpleSchema is a Meteor only package)_. I've received a lot of feedback recently, on what is needed in the documentation, and I'm planning to create an examples section - a set of files with complete drop-in examples, just like these in the documentation - this will be surely included.

**Comment by Floriferous** [comment]
@janowsiany Thanks a lot for this! Follow-up: How would you implement an autosaving form that only updates the field that is currently being edited, instead of updating the entire model every time? Doesn't seem trivial to me.

@radekmie Fantastic, looking forward to those examples! Indeed, I saw the meteor demo, so I thought it'd be obvious to complete it.

**Comment by radekmie** [comment]
@Floriferous there is already a form like this. It's the [`ModifierForm`](https://github.com/vazco/uniforms/blob/master/INTRODUCTION.md#example-modifierform) example in the documentation.

**Comment by janowsiany** [comment]
I am closing this as I beleive the answer was given. If @Floriferous have further questions please feel free to ask them here.
