### ISSUE TITLE
Support for GraphQL nested schema

### ISSUE THREAD

**Issue by DimitryDushkin** [vazco/uniforms#244]
I didn't managed to work nested GraphQL schema. Is it expect behaviour? Do we need PR here?)

For example:

**Scheme**
```graphql
input UserInput {
  name: UserNameInput
}

input UserNameInput {
  firstName: String
  lastName: String
}
```

**Component**
```jsx
<AutoForm schema={ new GraphQlBridge(graphqlSchema.getType('UserInput'), () => {} } >
   { /* it's getting error */ }
  <TextField name='name.firstName' />
   
  { /* it's also getting error */ }
   <NestField name='name'><TextField name='firstName' /></NestField>
</AutoForm>
```

**Comment by radekmie** [comment]
Well, it's working with `type UserInput ...`. It's not a bug, but a field for an enhancement. If you'd like to implement it, I'd love to see _(and merge)_ it.

**Comment by radekmie** [comment]
@DimitryDushkin?

**Comment by DimitryDushkin** [comment]
@radekmie I think issue can be closed. Not sure when I'll be able to make a PR.

**Comment by radekmie** [comment]
I think I'll be able to do it, but I'm just asking if it is really needed.

**Comment by DimitryDushkin** [comment]
It is definitely not critical. Thank you.

**Comment by DimitryDushkin** [comment]
❤️
