### ISSUE TITLE
Show only "DatePicker" or "TimePicker" on "Material"

### ISSUE THREAD

**Issue by thearabbit** [vazco/uniforms#245]
Show only "DatePicker" or "TimePicker"  (not dateTimePicker)
```js
// Schema
publishedDate: {
        type: Date,
    },
// Form
<DateField name="publishedDate" />
```
Please help me.

**Comment by radekmie** [comment]
There's no such possibility yet, because it's not compatible with any native JS type. If you want to have such field, create a custom one. Also, if you have an idea, on how to handle it in all themes _(we have to be consistent between themes)_ then let me know.

**Comment by thearabbit** [comment]
Thanks 👍

**Comment by thearabbit** [comment]
Now could I use this opt?

**Comment by radekmie** [comment]
It's not released yet.
