### ISSUE TITLE
Custom Theme Documentation

### ISSUE THREAD

**Issue by rafinskipg** [vazco/uniforms#252]
There is a need for a documentation on how to roll your own custom theme (like bootstrap3, antd, etc). And maybe a list of custom fields developed by the comunity (uniforms [bootstrap-datetimepicker](https://github.com/iMasterAle/react-datetimepicker-bootstrap) for example)

**Comment by radekmie** [comment]
This is the thing I heard the most - there's no _direct_ documentation on how to handle custom theme and/or custom fields _gracefully_. I'll start _(on a new branch probably)_ to work on it this weekend, create a local roadmap, so everybody could participate.

**Comment by radekmie** [comment]
Closing in favor of #259.
