### ISSUE TITLE
Applying custom fields or components

### ISSUE THREAD

**Issue by ericmcgregor** [vazco/uniforms#258]
Sorry for another question, but maybe you could help explain how to apply something like a composit field or custom auto field to alter pieces of the AutoForm without having to manually re-create the whole form?

I have three use cases:
1) I want to create a custom structure for the key "description" in my schema.  I would like to assign a new form component to that key that has the standard text box and some extra markup with extra help text or a dropdown button or whatever.

2) I'd like a custom form component for all keys that use a number. 

3) I'd like to replace the existing submit component with one  that has a cancel button and a reset button.

I see in your documentation you have CompositeField, and i understand how that works.  I also see the CustomAutoField, but don't quite understand what that is doing.  But neither of these show me how to replace something in the AutoForm without having to re-create the whole thing.

Is this even possible?  I really like the simplicity of having the autoform and just passing in the schema.  having to markup the entire form again only to alter a few pieces seems like it defeats the purpose in some respects for me.  I'm really sorry about not understanding this as well as i should.  I just would have assumed that, because it's so modular in design, there would be a way to feed in custom pieces and assign them to specific keys or schema types.  I actually think it's outlined somewhere, but i just can't see it.  thank you for any response.  again, sorry.

**Comment by radekmie** [comment]
0. `CompositeField` is just an example, not a _standard_ name or a rule.
1. Create a `DescriptionField` with such surroundings and use it through schema definition or custom `AutoField`.
2. Custom `AutoField`.
3. Either use `submitField` prop on your form or create custom `AutoForm` wrapper:

```js
const MyAutoForm = props =>
    <AutoForm autoField={CustomAutoField} {...props}>
        <AutoFields />
        <ResetField /> // This one is not a standard field.
        <ErrorsField />
        <SubmitField />
    </AutoForm>
;
```

I hope you got the idea.

4. Custom `AutoField`.

What is the `AutoField`? It's just a field, which renders a correct field, choosing it from its props. How to create one? Either go to the [documentation](https://github.com/vazco/uniforms/blob/master/INTRODUCTION.md#example-customautofield) or directly to the [source](https://github.com/vazco/uniforms/blob/master/packages/uniforms-unstyled/src/AutoField.js) and write yours. How to use it? Look into documentation, API or at the third point.
