### ISSUE TITLE
Could example use `Select Options` from `Mongo of Meteor`?

### ISSUE THREAD

**Issue by thearabbit** [vazco/uniforms#261]
I would to get `options data` from `Mongo Meteor` to `Select Options`
```js
<SelectField
                        name="parent"
                        options={MongoData}
                    />
```
Please help me.

**Comment by rafinskipg** [comment]
Hi @thearabbit 

You can use a dynamic schema or the options as you stated there:

```javascript
let data = [{label: 'hey', value: 'asdasd'}]
<SelectField options={data}/>
```

if you are using a schema, try doing this:

```
let mySchema = new SimpleSchema({
    items: {
       type: 'String',
       uniforms: {
           options: getOptionsFromDb() // Returns an array of label/value
       }
    }
```
And set the schema in the form `<AutoForm schema={mySchema} />`

**Comment by thearabbit** [comment]
Thanks for your reply.
But I not clear how to get `data from mongo` put to `Schema`.
I base on `Meteor` and use `createContainer`.
Could example for fullly?

**Comment by janowsiany** [comment]
Hey @thearabbit, please read [docs](https://guide.meteor.com/react.html#using-createContainer) first, then share your work related to this issue which actually is irrelevant to responsibilities of this package.

Closing this, but if you want to share your code related with this issue please feel free to do it here.

**Comment by rafinskipg** [comment]
Hi @thearabbit I use meteor too. 

Just fetch the data and pass it to the new schema, or the field.

Fetching data from mongo:

```
myCollection.find().fetch().map(function(item){
   return  { label: item.name, value: item._id}
})
```

Passing it to a react element (one of multiple ways)

```
<myReactElement options: { this.getData()} />
```

**Comment by lmaddio** [comment]
I am having problems using uniforms fields
I have:
```
const Address = new SimpleSchema({
    path: {
        type: String,
        label: "Direccion"
    },
    cp: {
        type: String,
        label: "Codigo postal"
    },
    location: {
        type: String,
        label: "Localidad",
        uniforms: {
            options: function() {
                return Locations.find().map((l,i)=>{
                    return { label: l.name, value: l._id };
                });
            }
        }
    }
});
```

this gives me:
` Error: Invalid definition for location field: "uniforms" is not a supported property`

I am using Meteor with npm: "uniforms": "^1.17.2" and "uniforms-unstyled": "^1.17.2"

**Comment by radekmie** [comment]
@lmaddio [_**Note:** remember to import uniforms packages first._](https://github.com/vazco/uniforms/blob/master/INTRODUCTION.md#simpleschema-definition)
