### ISSUE TITLE
Allow using "custom" simpleschema attribute.

### ISSUE THREAD

**Issue by rafinskipg** [vazco/uniforms#263]
Right now the "conditional require" provided by simpleschema `custom` attribute does not work.

https://github.com/aldeed/meteor-simple-schema#make-a-field-conditionally-required

Changes should be done here, maybe
https://github.com/vazco/uniforms/blob/fde6cefa7c998bb10d74486ea607c6608bc265c3/packages/uniforms/src/SimpleSchemaBridge.js#L167

**Comment by janowsiany** [comment]
`custom` validators are supported, please forgive me for the confusion.
