### ISSUE TITLE
AutoField with ErrorField

### ISSUE THREAD

**Issue by gemmi-arts** [vazco/uniforms#264]
Hi,

Is there any option to combine AutoField with ErrorField?
I don't want to write each time or create second component:
```
               <AutoField name="name" floatingLabelText="Name" />
                <ErrorField name="name" />
```

I would like to keep errors next to the field.

**Comment by radekmie** [comment]
Most themes have `showInlineError` prop for both forms and fields. Does it suffice your needs?

**Comment by gemmi-arts** [comment]
@radekmie  Exactly, I missed that. Thank you very much!
