### ISSUE TITLE
UMD build

### ISSUE THREAD

**Issue by oldrich-s** [vazco/uniforms#265]
Is it possible to compile the project into one file UMD? As it is now, the `npm run build` command builds each file separately but does not merge it into  a single file that could be referred from HTML.

**Comment by radekmie** [comment]
Yes, it is possible. UMD with ES6 code or already ES5 one?

**Comment by czb** [comment]
Perfect :+1: I would say that the end result could be something like this:

https://unpkg.com/react@15.4.2/dist/react.js

Probably one UMD file per each Uniforms project?

**Comment by radekmie** [comment]
Yes, combining all of them is not necessary. Would you like to help on this? I think [rollup](https://github.com/rollup/rollup) should do the job and be easy to configure.

**Comment by czb** [comment]
Well I prefer `TypeScript` which can also bundle to a single UMD file and provides types. But that would require converting the files into TS files which I do not know if it is something you would want to do :)

**Comment by radekmie** [comment]
Not now, but adding types is already on the roadmap - I'm still not sure if it will be TypeScript or Flow _(do not start another thread about it, please)_, but if it will be TS, then I'll surely ask you to help :D

Meanwhile, I'd stick with rollup.

**Comment by radekmie** [comment]
@czb would you like to do it?

**Comment by czb** [comment]
I might try it with typescript. It should be possible to compile es6 js to es5 js similarly to what babel does plus bundle it, all in one command. I will look at it at the weekend.

**Comment by radekmie** [comment]
@czb?

**Comment by czb** [comment]
Well i looked at it but got quickly lost in the bundle process :)

**Comment by radekmie** [comment]
At the TypeScript, Rollup or something else?

**Comment by czb** [comment]
I have tried both TypeScript and Rollup. Rollup needs to be hooked up to Babel => I have no idea how to do it. TypeScript compiles into either multiple UMD files or single AMD or SystemJS file. This is probably not what you want.

**Comment by radekmie** [comment]
> TypeScript compiles into either multiple UMD files or single AMD or SystemJS file. This is probably not what you want.

You want it :)

> Rollup needs to be hooked up to Babel => I have no idea how to do it.

[rollup-plugin-babel](https://github.com/rollup/rollup-plugin-babel)?

**Comment by radekmie** [comment]
I found another problem - there's no possibility to create a _single_ bundle, because it will either include **both** `graphql` and `simpl-schema` or none of them, but then using uniforms will be... Harder, because no automatic schema detection will take place.

**Comment by radekmie** [comment]
_Quite_ a long time later, still no actions here. We are _slowly_ moving to TypeScript, which may help. In the end, I'm closing. Feel free to comment or file a pull request.
