### ISSUE TITLE
Problem with Antd 2.90??? 

### ISSUE THREAD

**Issue by thearabbit** [vazco/uniforms#266]
modules.js?hash=8e2b47f…:4261 Warning: DOMWrap: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.
printWarning @ modules.js?hash=8e2b47f…:4261
warning @ modules.js?hash=8e2b47f…:4285
createClass @ modules.js?hash=8e2b47f…:2887
meteorInstall.node_modules.rc-menu.lib.DOMWrap.js @ modules.js?hash=8e2b47f…:41712
fileEvaluate @ modules-runtime.js?hash=2b888cb…:207
require @ modules-runtime.js?hash=2b888cb…:130
meteorInstall.node_modules.rc-menu.lib.MenuMixin.js @ modules.js?hash=8e2b47f…:41307
fileEvaluate @ modules-runtime.js?hash=2b888cb…:207
require @ modules-runtime.js?hash=2b888cb…:130
meteorInstall.node_modules.rc-menu.lib.Menu.js @ modules.js?hash=8e2b47f…:41020
fileEvaluate @ modules-runtime.js?hash=2b888cb…:207
require @ modules-runtime.js?hash=2b888cb…:130
meteorInstall.node_modules.rc-menu.lib.index.js @ modules.js?hash=8e2b47f…:40967
fileEvaluate @ modules-runtime.js?hash=2b888cb…:207
require @ modules-runtime.js?hash=2b888cb…:130
meteorInstall.node_modules.antd.lib.menu.index.js @ modules.js?hash=8e2b47f…:27748
fileEvaluate @ modules-runtime.js?hash=2b888cb…:207
require @ modules-runtime.js?hash=2b888cb…:130
Mp.importSync @ modules.js?hash=8e2b47f…:358
meteorInstall.imports.ui.layouts.App.js @ App.js:1
fileEvaluate @ modules-runtime.js?hash=2b888cb…:207
require @ modules-runtime.js?hash=2b888cb…:130
Mp.importSync @ modules.js?hash=8e2b47f…:358
meteorInstall.imports.startup.client.routes.js @ routes.js:1
fileEvaluate @ modules-runtime.js?hash=2b888cb…:207
require @ modules-runtime.js?hash=2b888cb…:130
Mp.importSync @ modules.js?hash=8e2b47f…:358
meteorInstall.imports.startup.client.index.js @ index.js:1
fileEvaluate @ modules-runtime.js?hash=2b888cb…:207
require @ modules-runtime.js?hash=2b888cb…:130
Mp.importSync @ modules.js?hash=8e2b47f…:358
meteorInstall.client.main.js @ main.js:1
fileEvaluate @ modules-runtime.js?hash=2b888cb…:207
require @ modules-runtime.js?hash=2b888cb…:130
(anonymous) @ app.js?hash=3ad9dfe…:1509
modules.js?hash=8e2b47f…:49463 Wrapper div has no height or width, try overriding style with `containerStyle` option
render @ modules.js?hash=8e2b47f…:49463
(anonymous) @ modules.js?hash=8e2b47f…:20442
measureLifeCyclePerf @ modules.js?hash=8e2b47f…:19721
_renderValidatedComponentWithoutOwnerOrContext @ modules.js?hash=8e2b47f…:20441
_renderValidatedComponent @ modules.js?hash=8e2b47f…:20468
performInitialMount @ modules.js?hash=8e2b47f…:20008
mountComponent @ modules.js?hash=8e2b47f…:19904
mountComponent @ modules.js?hash=8e2b47f…:12796
performInitialMount @ modules.js?hash=8e2b47f…:20017
mountComponent @ modules.js?hash=8e2b47f…:19904
mountComponent @ modules.js?hash=8e2b47f…:12796
mountComponentIntoNode @ modules.js?hash=8e2b47f…:24958
perform @ modules.js?hash=8e2b47f…:13758
batchedMountComponentIntoNode @ modules.js?hash=8e2b47f…:24980
perform @ modules.js?hash=8e2b47f…:13758
batchedUpdates @ modules.js?hash=8e2b47f…:22647
batchedUpdates @ modules.js?hash=8e2b47f…:12428
_renderNewRootComponent @ modules.js?hash=8e2b47f…:25174
_renderSubtreeIntoContainer @ modules.js?hash=8e2b47f…:25255
render @ modules.js?hash=8e2b47f…:25276
(anonymous) @ modules.js?hash=8e2b47f…:6179
modules.js?hash=8e2b47f…:45700 Warning: `Select[multiple|tags|combobox]` is deprecated, please use `Select[mode]` instead.

**Comment by radekmie** [comment]
You've updated to React 15.5.0 and AntD is using currently deprecated API. It's not related to uniforms.

**Comment by thearabbit** [comment]
Oh, thanks 👍
