### ISSUE TITLE
The errorMessage is shown in grey before validation fails

### ISSUE THREAD

**Issue by Gervwyk** [vazco/uniforms#267]
When using errorMessage prop, the error message is shown in grey before the validation fails on all themes. 
Using this schema: 
```
new SimpleSchema({
    STRING: {
         type: String,
         regEx: /^[A-Z]*$/,
         uniforms: {
             errorMessage: "ERROR here"
          }
     }
})
```

Do we really want to show the error before validation? It would be nice if we could have the error only show when validation fails or make it optional somehow.

**Comment by radekmie** [comment]
Indeed, a lot of fields are checking for `errorMessage` instead of `error` - it's reasonable to change it, because it will allow customization like this. Would you submit a PR for it?

**Comment by Gervwyk** [comment]
I'll make a PR later today. Do we want this optional? Or should we only show the message on error? If optional by what prop / value?

**Comment by radekmie** [comment]
I see this in this way: [`uniforms-semantic/NumField`](https://github.com/vazco/uniforms/blob/master/packages/uniforms-semantic/src/NumField.js#L59-L63)

```diff
-        {!!(errorMessage && showInlineError) && (
+        {!!(error && showInlineError) && (
             <div className="ui red basic pointing label">
                 {errorMessage}
             </div>
         )}
```

**Comment by Gervwyk** [comment]
Ok great. I agree. I'll change on all themes and submit PR.
