### ISSUE TITLE
ListField material buttons

### ISSUE THREAD

**Issue by gemmi-arts** [vazco/uniforms#270]
Hi,

I have a field with a list of email addresses (material style).
```
<ListField initialCount={1} name="emails">
        <ListItemField name="$">
             <AutoField name="address" floatingLabelText="email" />
        </ListItemField>
</ListField>
```

Is there an option to change ListDelField (or ListAddField) according to my preferences? eg.
`<ListDelField name="$" iconVisible icon={DeleteIcon} children=''/>`

**Comment by janowsiany** [comment]
Hello, `ListDelField` should handle setting an icon and its visibility. However, currently there is no way to pass those props via schema or `<ListField />`.
To accomplish the result what you expect you need to write your own customized `ListField` and `ListItemField`. It is not that hard, just change [this line](https://github.com/vazco/uniforms/blob/master/packages/uniforms-material/src/ListField.js#L37) to use you custom `ListItemField` like:
```js
  <MyCustomListItemField key={index} label={null} name={joinName(name, index)} {...itemProps} />
```
and then in `MyCustomListItemField.js`, about [here](https://github.com/vazco/uniforms/blob/master/packages/uniforms-material/src/ListItemField.js#L25):
```js
  <ListDelField name={props.name} icon={Clear} iconVisible={true} />
```
I am aware that it is not very user-friendly and this issue relates to #185 and we still did not decided how to handle this problem.

**Comment by radekmie** [comment]
@janowsiany no, #185 is not related. In `uniforms-bootstrap3` we have already `removeIcon` prop, [which is passed to `ListDelField`](https://github.com/vazco/uniforms/blob/master/packages/uniforms-bootstrap3/src/ListItemField.js#L12). The only problem I see is that it's called `removeIcon` in `uniforms-bootstrap3` and `icon` in `uniforms-material`.

**Comment by gemmi-arts** [comment]
Thank you,
I will create my custom component as @janowsiany suggested.
