### ISSUE TITLE
Delay form submission on submitField

### ISSUE THREAD

**Issue by macrozone** [vazco/uniforms#271]
I want to show a nice little animation when the submitbutton is clicked.

For normal buttons, i can delay the onClick a bit, so that the animation is visible.

But this is not easy on a submitfield, because it has no onClick and only the type="submit"

is there a way to delay the form submission in the submitfield?

**Comment by radekmie** [comment]
There is a way. In short: use form `ref`. Just render your animated button and after animation finishes, trigger `form.submit()`.

**Comment by macrozone** [comment]
thx @radekmie ! but how can i access form-ref in submitfield...?

**Comment by radekmie** [comment]
```js
const ExampleForm = props => {
    let ref;
    return (
        <AutoForm {...props} ref={form => ref = form}>
            {/* ... */}
            <SubmitField type="button" onClick={() => ref.submit()} />
        </AutoForm>
    );
};
```

This `type="button"` disables default _submit-on-click_ logic.

**Comment by radekmie** [comment]
@macrozone?

**Comment by macrozone** [comment]
Hi @radekmie , sorry for the late response.

Would it make sense to inject a submit function to connectField? so that every field can submit, if it likes.

**Comment by radekmie** [comment]
It is already on a roadmap, but definitely not now. As it is working now, I'm closing.
