### ISSUE TITLE
Uniform antd theme, layout props

### ISSUE THREAD

**Issue by darwis059** [vazco/uniforms#273]
on antd documentation Form component has layout property to choose form layout ('horizontal'|'vertical'|'inline')

is this property already implemented on uniform antd?
i tried adding `<AutoForm layout="horizontal" ...` to my form, but i got unknown prop warning.

**Comment by darwis059** [comment]
i manage to change layout by adding wrapperCol and labelCol props one each AutoField. another problem is, i cant add wrapperCol props tu SubmitForm Component, so my submit button doesn't aligned with form input.
i have another question. how to properly  create edit form?
i create edit form by passing document to model props, but data.field from onSubmit function is undefined if no  changes made on form field.

**Comment by radekmie** [comment]
It should be present - can you share an example?

**Comment by darwis059** [comment]
i found the problem, i load form component without waiting document populated from backend

**Comment by radekmie** [comment]
As I've found in [`<Form />` source](https://github.com/ant-design/ant-design/blob/master/components/form/Form.tsx#L185-L190), it's possible to do it with `className` only - for example `ant-form-inline`.

If you want, submit a PR with this change - meanwhile it has a simple workaround.
