### ISSUE TITLE
Can't change value when use `<AutoField name="paidAmount" value={123}/>`

### ISSUE THREAD

**Issue by thearabbit** [vazco/uniforms#277]
I can't change value with `onKeyUp`, when set default value on field
```js
<AutoField
                name="paidAmount"
                value={123}
                onKeyUp={(event) => this.handlePaidAmountKeyUp(event)}
                {...formItemLayout}
            />
```

![untitled](https://cloud.githubusercontent.com/assets/4495160/25224059/75138150-25e7-11e7-9d6b-d94cc21a9cdd.png)

**Comment by janowsiany** [comment]
Could you please tell us what you want to achive? The value of this field should be changed by `onChange` call inside `AutoField`

**Comment by thearabbit** [comment]
Thanks for your reply. but it set to default value after changed,
```js
<AutoField
                        name="paidAmount"
                        value={order.total} // 100 $
                        onChange={(value) => console.log(value)}
                        {...formItemLayout}
                    />
``` 
for example total amount = 100 $, and then I change to paid only = 50 $.
But after changed (loss focus) the text box = 100 $ (old value).

**Comment by thearabbit** [comment]
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/4495160/25226475/47e3b15c-25ef-11e7-87e2-c9cdd55058fc.gif)

**Comment by janowsiany** [comment]
If you want it to work properly please don't override `onChange` property on `AutoField`.
If you want to hook on `onChange` then you need to write a wrapper for Autofield like:
```js
const PaidAmountField = ({onChange, ...props}) => 
  <Autofield {...props} onChange={value => {console.log(value); onChange(value+2)}} />
```

**Comment by thearabbit** [comment]
Could provide full example? I don't understand
```js
handlePaidAmountChange = (value) => {
        this.setState({balance: this.props.order.total - value});
    };
-------
 <AutoField
                        name="paidAmount"
                        value={defaultValue}
                        onChange={(value) => this.handlePaidAmountChange(value)}
                    />
<AutoField
                        name="balance"
                        value={this.state.balance}
                    />
```

**Comment by thearabbit** [comment]
Now I would like to close this and reopen new with specific title.
