### ISSUE TITLE
Problem with `inputRef`

### ISSUE THREAD

**Issue by thearabbit** [vazco/uniforms#279]
```js
componentDidMount() {
        this.balanceRef.focus();
    }
------
 <AutoField
                        name="balance"
                        inputRef={(ref) => {
                            this.balanceRef = ref
                        }}
 />
```
Get error
```js
Uncaught TypeError: this.balanceRef.focus is not a function
    at OrderPayment.componentDidMount
```

**Comment by janowsiany** [comment]
Please **share the whole** example with both schema and `OrderPayment` component. My first guess is that `OrderPayment` is a [functional component which does not have an instance](https://facebook.github.io/react/docs/refs-and-the-dom.html#refs-and-functional-components).

**Comment by thearabbit** [comment]
Oh I use this form in `Antd Modal` like this
```js
<Modal
      title="Payment"
      key={this.state.modalKey}
      visible={this.state.visibleModal}
      onCancel={this.handleModalCancel}
       footer={null}
>
        <OrderPayment order={order} handleModalCancel={this.handleModalCancel}  />
</Modal>
--------------
export default class OrderPayment extends Component {
    componentDidMount() {
        this.balanceRef.focus();
    };
   
   render(){
      return(
        ..........
        <AutoField name="balance" inputRef={ref => this.balanceRef = ref}/>
     );
   }
```

**Comment by janowsiany** [comment]
Ok so generally it is a problem of `ant-design` package itself and its internals, especially `rc-dialog` from which they use their Modals. So if you take a look [here](https://github.com/react-component/dialog/blob/master/src/Dialog.tsx#L76-L106) they handle focus by their own and i could not find a way to prevent this or to change this behaviour.
So my suggestion is to use this hacky solution:
```js
componentDidMount () {
        setTimeout(() => this.balanceRef.focus(), 0)
}
```
Checked it myself and it is working, let me know if it does for you, so far i am closing,

**Comment by thearabbit** [comment]
very thanks 👍
but now I still have problem with #278, could you help me?
