### ISSUE TITLE
Enable setting of submit-button-label in AutoForm

### ISSUE THREAD

**Issue by macrozone** [vazco/uniforms#28]
Currently you can't define the label for the submit-button in a AutoForm or QuickForm unless you implement your own QuickForm.

E.g. like this:

````
import {QuickForm} from 'uniforms';

import BaseForm    from './BaseForm';
import AutoField   from '../fields/AutoField';
import ErrorsField from '../fields/ErrorsField';
import SubmitField from '../fields/SubmitField';

const Quick = parent => class extends QuickForm.Quick(parent) {
    static Quick = Quick;

    getAutoField () {
        return AutoField;
    }

    getErrorsField () {
        return ErrorsField;
    }

    getSubmitField () {
        return () => <SubmitField value={this.props.submitLabel} />;
    }
};

export default Quick(BaseForm);
````

Now I can use `<AutoForm submitLabel="Send" schema={...} />`

In my code i have a slightly different SubmitField-component with a button instead of a <input type="button" />, because <button> supports children. So in my code i have:

``````
getSubmitField () {
        return () => <SubmitField>{this.props.submitLabel}</SubmitField>;
    }
``````

where submitLabel could also be a react-component.

Maybe we can add a similar property like `submitLabel` to the unstyled/bootstrap/semantic-implementations. (not sure if submitLabel is the right word, though). 

Another solution would be to have a component that renders all fields but the submit button (similar to aldeed:autoform's afquickfiels: https://github.com/aldeed/meteor-autoform#afquickfields)

That would enable to have half-automatic forms

**Comment by radekmie** [comment]
Separate prop for submit button label seem to be an overkill, but `Auto`/`Errors`/`SubmitField` configurable by props (eg. `<QuickForm autoField={() => <p>Example</p>}`) is quite neat option. Does it makes sense for you?

---

*Side note:* You can inherit `AutoForm`, not `QuickForm` to override `getSubmitField`.

**Comment by macrozone** [comment]
Hi @radekmie, looks like a good option that does not need much code. I like that.

I also like the other approach with something like afquickfields. I will open a new issue for that.
