### ISSUE TITLE
Uniforms GraphQL Example with Date type

### ISSUE THREAD

**Issue by zeroasterisk** [vazco/uniforms#280]
I am trying to come up with more Uniforms examples and eventually a few components to share out (my go-to workshop-training material)... 

But I can not figure out how to make a GraphQL Date field.

I see your demo GraphQL here:
https://github.com/vazco/uniforms/blob/master/demo/imports/lib/presets.js#L46-L53

I've gotten that and various permutations to work, but I can not get the Date format to work yet...

It needs to be a custom Scaler (no problem):
http://graphql.org/learn/schema/#scalar-types

But where do I stitch in the serializer and deserializer?

**Comment by radekmie** [comment]
Have you tried it with a `DateField` or `AutoField`? See [this](https://github.com/vazco/uniforms/issues/118#issuecomment-256252304) comment.

**Comment by radekmie** [comment]
For more detailed answer, see #281.

**Comment by zeroasterisk** [comment]
Sorry, you're right, it worked fine, I must have been messing something up.
