### ISSUE TITLE
Add support for GraphQLID 

### ISSUE THREAD

**Issue by TimMikeladze** [vazco/uniforms#281]
It seems that the GraphQLBridge does not support ID types, resulting in this error `Uncaught Error: Unsupported field type: ID`

Here is a link to what I believe is the relevant code (I haven't really investigated too deep)
https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/GraphQLBridge.js#L185

I think an additional case for IDs should be added `fieldType.name === 'ID' ? String` since GraphQL IDs are strings but not meant to be human readable.

Let me know if my proposed solution is along the right lines or if not point me the right way please. I'll gladly send a PR.

Thanks.

**Comment by radekmie** [comment]
It was already asked few times and I'm still thinking about a more general solution, like providing own mapping in that case. For now, you can extend the `GraphQLBridge` with your own type deduction.

**Comment by radekmie** [comment]
> The ID scalar type represents a unique identifier, often used to refetch an object or as the key for a cache. The ID type is serialized in the same way as a `String`; however, it is not intended to be human‐readable. While it is often numeric, it should always serialize as a `String`.
> -- [Source](https://facebook.github.io/graphql/October2016/#sec-ID)

In this case, I think it's reasonable to threat `GraphQLID` as `String`.
