### ISSUE TITLE
Customize List Field component

### ISSUE THREAD

**Issue by betinafarias** [vazco/uniforms#282]
Hi, 

I have a question about how do I customize the "Remove" and "Add" buttons of List Field component?

I'm not sure if I misunderstood the documentation or if it is actually an issue.

Thank you, guys :)

![image](https://cloud.githubusercontent.com/assets/11333676/25354337/fb1582f2-2908-11e7-918d-c40d2e01835b.png)

**Comment by radekmie** [comment]
Hey, @betinafarias. What exactly you'd like to customise? If it's not possible to do it with styles, you can either pass your layout to the default `ListField` _(it's a limited solution)_ or create custom `ListField`.

**Comment by betinafarias** [comment]
I'd like to do something similar to this image below:
![](https://puu.sh/vwNcp/581f6bb7ae.png)

Which approach that you suggested do you think can be the best for this solution?

Can you give me some example? I did not find anything like it in the docs.

Thank you!

**Comment by radekmie** [comment]
At first, you can try this:

```js
<ListField name="friends">
    <ListItemField name="$">
        <NestField>
            {/* Any structure here */}
            <TextField name="name" />
            <NumField  name="age" />
        </NestField>
    </ListItemField>
</ListField>
```

And if you need some special add/remove buttons, then also define own `ListItemField`. How? Take a look at the built-in one. Then, wrap it in something like `MyListField`.
