### ISSUE TITLE
Upgrade to Meteor 1.5 beta breaks on this package

### ISSUE THREAD

**Issue by todda00** [vazco/uniforms#285]
I am not sure if this is a Meteor issue which will be resolved, or something has to be fixed in this package, but when upgrading an app I wanted to play around with code splitting under the new Meteor 1.5 beta, the client errors out on this package:

`modules.js?hash=4f8db53…:33757 Uncaught SyntaxError: Unexpected token ...`
the file in question is:
`node_modules/uniforms-bootstrap4/src/AutoFields.js`
`const AutoFields = ({autoField, element, fields, omitFields, ...props}, {uniforms: {schema}}) =>`

**Comment by radekmie** [comment]
You should use transpiled, not source files. How do you import uniforms?

**Comment by todda00** [comment]
I am importing from npm like this:
```
import React from 'react';
import { AutoForm, AutoField, ErrorsField, SubmitField } from 'uniforms-bootstrap4';
```

**Comment by radekmie** [comment]
My guess is the `module` or `jsnext:main` field in package.json. Could you try for example `semantic-ui-react`package? It's also using these fields.

**Comment by radekmie** [comment]
Also, see this [comment](https://github.com/meteor/meteor/pull/8327#issuecomment-298783127).

**Comment by benjamn** [comment]
The `module`/`jsnext:main` logic was [reverted](https://github.com/meteor/meteor/pull/8327/commits/269e10caa6c72312e7032f4c23b4f06f974320d4) in `1.5-beta.19`, if you want to try updating to that.

**Comment by todda00** [comment]
beta 1.9 resolved this issue, still get get my app to run under it, but it got past this error at least.
