### ISSUE TITLE
How to call Meteor.call in Asynchronous Validation

### ISSUE THREAD

**Issue by mattscooter** [vazco/uniforms#286]
Hi,

I am trying to figure out how to do Asynchronous validation using the onValidate method of the form. 

I've looked at the example in the docs and believe I have everything setup correctly but can't get my asynchronous validation to work using a Meteor.call.

My meteor call method returns true or false depending on whether the shortname is unique or not.  In the callback I am calling the callback to add the error but the validation error is not appearing on the form. 

Here is the contents of my onValidate function.

    const onValidate = (model, error, callback) => {
      if (error) {
        return callback();
      }

      Meteor.call('organisation.shortnameUnique',
        { shortname: model.shortname, shortid: model.shortid },
        (err, result) => {
          if (!result) {
            console.log ('calling callback');
            callback({ name: 'shortname', type: 'notUnique' });
          }
        },
      );
    };

I can see that the "calling callback" is logged on the console when the shortname is not unique so I believe this should be working. 

If I move the call to the callback function out of the meteor call callback and just call it in the function body then I am getting the validation error to always fire so I know this part is working.  I just can't seem to get it to work inside the meteor.call callback. 

I think my head is going to explode from too too many callbacks and calls!

Any hints on what I might be doing wrong?

**Comment by radekmie** [comment]
You have to call it anyway, not only if no error occurred. In other words, call it with error if it occurred and without one if everything is OK.

**Comment by radekmie** [comment]
Also, this isn't the SimpleSchema error format - it should be in a shape of ValidationError - instead of `{name, type}` do `{details: [{name, type}]}`.

**Comment by mattscooter** [comment]
Thank you!  

It was the format of the error that I was passing back that was causing my problems.   I knew I was doing something wrong!

So if I wanted to merge any the existing errors with my asynchronous validation error do I have to merge in the error.details with my new error and call the callback function?

**Comment by radekmie** [comment]
Exactly.

**Comment by mattscooter** [comment]
Fantastic!  Thank you so much. I think I have it all working now.
