### ISSUE TITLE
Bootstrap 4 does not provide any icons on default

### ISSUE THREAD

**Issue by DavidSichau** [vazco/uniforms#287]
The Field ListAddField in the bootstrap 4 package adds `<i class="octicon octicon-plus"></i>` to add an field.

See: https://github.com/vazco/uniforms/blob/master/packages/uniforms-bootstrap4/src/ListAddField.js#L27

However if the octicon icons are not available this is simply not rendered visible which makes it hard to click on.

Would it be possible to change this to somethink which does not require any additional libary?

**Comment by radekmie** [comment]
Yes, it is possible, but to be honest, I've never used it without these icons. If you want, go ahead and submit a PR with it - I've never been a bootstrap master, so I don't know, what possibilities we have. Let's ping @zeroasterisk, creator of both bootstrap themes.

**Comment by zeroasterisk** [comment]
i have long been bothered by the icons... ideally, I'd like a configuration globally, or at least at the form level, which communicated the "icons" to use for plus/minus.

you could pass in `plus: <i className="octicon octicon-plus"/>` or `plus: "+"` or whatever...

**Comment by DavidSichau** [comment]
I simply have solved it for the moment to be usable with fontawesome by redefining the styles:

```
.octicon {
  display: inline-block;
  font: normal normal normal 14px/1 FontAwesome;
  font-size: inherit;
  text-rendering: auto;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
.octicon-plus:before {
    content: "\f0fe";
}
.octicon-dash:before {
  content: "\f146";
}
```
However the solution proposed by @zeroasterisk  seems to be the ideal way to solve this issue.

**Comment by radekmie** [comment]
So, as we don't have any built-in icons, I'd state two things:
* if you want to change it globally _(and a bad pattern is not an issue)_, then do something like this:
```js
ListAddField.defaultProps.addIcon = <MyIconJSX />;
```
* if you want to introduce a better _(in terms of developer UX)_ solution _(including changes in documentation)_ - go ahead, I'd love to see your points here

**Comment by arichter83** [comment]
This worked for me:


```
.octicon {
  display: inline-block;
  font-style: normal;
  font-size: 20px;
  font-weight: 400;
  border: 1px solid #000;
  width: 25px;
  height: 25px;
  background-color: #DDD;
  cursor: pointer;
}

.octicon:hover {
  background-color: #CCC;
}

.octicon-plus:before {
  content: "+";
}
.octicon-dash:before {
  content: "-";
}

```

**Comment by refactorized** [comment]
This is now even worse because octicons are no-longer delivered as a font + css but are expected to be placed directly in the markup as svgs.  This can still be accomplished via css but not easily with the main @primer/octicons package.
