### ISSUE TITLE
Meteor with React warning

### ISSUE THREAD

**Issue by aleksandrenko** [vazco/uniforms#290]
console warning:
Warning: Unknown props `denyInsert`, `denyUpdate` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by Date)
    in Date (created by DateField)
    in DateField (created by AutoField)
    in AutoField
    in form (created by AutoValidatedQuickUnstyledForm)
    in AutoValidatedQuickUnstyledForm (created by AppRouter)
    in div (created by AppRouter)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by AppRouter)
    in AppRouter

Autoform elements:
            <AutoForm schema={schema.POICategory} onSubmit={doc => console.log('submit doc', doc)} model={model} />

Used schema: 
const CategorySchema = new SimpleSchema({
    name: {
        type: String,
        label: 'Name'
    },
    createdAt: {
        label: 'Created at',
        type: Date,
        autoValue: function () {
            if (this.isInsert) {
                return new Date;
            }
        },
        denyInsert: true,
        denyUpdate: true
    }
});

export default CategorySchema;

**Comment by radekmie** [comment]
Use [`filterDOMProps.register`](https://github.com/vazco/uniforms/blob/master/API.md#filterdompropsregister):

```js
import filterDOMProps from 'uniforms/filterDOMProps';

filterDOMProps.register(
    'denyInsert',
    'denyUpdate'
);
```
