### ISSUE TITLE
reset form on submit without ref

### ISSUE THREAD

**Issue by macrozone** [vazco/uniforms#291]
I can't use ref, because my form is wrapped with a HOC, so I don't get the right ref. 

Maybe two possible solution:

- define a property "resetOnSubmit"
- pass the ref as second param to onSubmit, so that you can reset when needed

what you guys think?

**Comment by radekmie** [comment]
It sounds like a good idea, though I'm not sure on how to handle it. On one hand, it's achievable with the current API, but it will require some _(boiler?)_ code. On the other hand, it's not that hard to add it - [one line](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/BaseForm.js#L250). What do you think?

**Comment by radekmie** [comment]
_I've decided to not add it - I'm not against it, it will be probably included in the future, but definitely not now._

**Example solution:**

```js
class ClearableAutoForm extends AutoForm {
    onSubmit () {
        // If you don't care about this Promise
        return super.onSubmit(...arguments).then(() => this.reset());

        // If you do care about this Promise
        return super.onSubmit(...arguments).then(result => {
            this.reset();
            return result;
        });
    }
}
```
