### ISSUE TITLE
SelectField won't change value unless no value has been set

### ISSUE THREAD

**Issue by martinhbramwell** [vazco/uniforms#292]
I would really appreciate help on StackExchange with the problem I describe there : [Vazco Uniforms : SelectField won't change value unless no value has been set](https://stackoverflow.com/questions/44263067/vazco-uniforms-selectfield-wont-change-value-unless-no-value-has-been-set).

I am using Vazco "Uniforms" successfully in my Meteor project.  However, I'm unable to understand the behavior of SelectField.

I have a form that serves both to add new records and to edit existing ones.  The form is for adding/editing a book and uses a SelectField for choosing from a short list of Authors.

When I **add** a new book, Author selection works fine.

When I try to **edit** an existing record, the displayed Author remains the same, even though `console.log` output during the onChange validation event shows that the underlying selection does change.  If I try to submit after altering the selection, the GraphQL model reports that *Author ID is not provided*!

The problematic form file is published on GitHub [here][1]

The composer for "Add" is [here][2].

The composer for "Edit" is [here][3].

Validations andd submit handlers are [here][4].

I'm using :

    "uniforms": "^1.18.0",
    "uniforms-bootstrap3": "^1.18.0"

But an older version of my code has the same problem, using :

    "uniforms": "^1.10.0",
    "uniforms-bootstrap3": "^1.10.0"

I'd really appreciate some hints as to where I went wrong with this.

P.S.  Am I right that you prefer to discuss support issues on Stack Exchange?

  [1]: https://github.com/warehouseman/meteor-mantra-kickstarter/blob/trunk/.pkgs/mmks_book/src/client/components/uniform.jsx
  [2]: https://github.com/warehouseman/meteor-mantra-kickstarter/blob/trunk/.pkgs/mmks_book/src/client/composers/add.js
  [3]: https://github.com/warehouseman/meteor-mantra-kickstarter/blob/trunk/.pkgs/mmks_book/src/client/composers/edit.js
  [4]: https://github.com/warehouseman/meteor-mantra-kickstarter/blob/trunk/.pkgs/mmks_book/src/client/actions/books.js

**Comment by janowsiany** [comment]
First of all:
I think it would be much better to keep model **only** inside component state. Check out [here](https://github.com/warehouseman/meteor-mantra-kickstarter/blob/trunk/.pkgs/mmks_book/src/client/components/uniform.jsx#L36-L37).
```js
constructor(...args) {
    ...
    this.state = {
      model: {}
    };
    ...
  }
componentWillMount() {
    this.componentWillReceiveProps(this.props);
}
componentWillReceiveProps({model}) {
    this.setState({model});
}
```
and then:
```js
<AutoForm 
    schema={this.bridge}
    onSubmit={model => this.setState({model})}
    onSubmit={doc => this.submitForm(doc)}
    model={this.state.model}
    validate="onChange"
/>
```
Let me know if it helped you.

**Comment by radekmie** [comment]
@martinhbramwell I don't really understand, what is not working, really. There's no `Author ID` field too.

About Stack Exchange - I'm OK with both, but I check GitHub a lot more frequently.

**Comment by radekmie** [comment]
I still haven't heard anything from you, @martinhbramwell, so I'll close it. Meanwhile, I think I found your bug: in [`create`](https://github.com/warehouseman/meteor-mantra-kickstarter/blob/trunk/.pkgs/mmks_book/src/client/actions/books.js#L60) there's `authorId: book.author` and in [`update`](https://github.com/warehouseman/meteor-mantra-kickstarter/blob/trunk/.pkgs/mmks_book/src/client/actions/books.js#L79) there's `authorId: book.author._id`.
