### ISSUE TITLE
`validate="onSubmit"` disables the submit button after initial click

### ISSUE THREAD

**Issue by purplecones** [vazco/uniforms#293]
```jsx
const PersonSchema = new SimpleSchema({
  firstName: String,
  lastName: String,
});

<AutoForm schema={PersonSchema} validate="onSubmit" onSubmit={model => console.log({model})} />
```

![2017-06-01 14 45 53](https://cloud.githubusercontent.com/assets/136654/26695503/182e149c-46d9-11e7-9ea2-8e389eca1dbb.gif)

Anyone else come across this? It would be best if the submit button stay enabled at all times when `validate="onSubmit"`.

**Comment by radekmie** [comment]
Hey, @purplecones!
It should stay disabled as long as the form is not valid, but as I see, the form is not *recovering* from the invalid state... Which version are you using? I'll try to investigate it. And by the way - `onSubmit` is the default value.

**Comment by purplecones** [comment]
Thanks @radekgronski. I'm using version `^1.18.1`. If I omit `validate="onSubmit"` it behaves differently and successfully recovers the submit button. 

```jsx
<AutoForm schema={PersonSchema} onSubmit={model => console.log({model})} />
```

I think it uses `"onChangeAfterSubmit"` if I don't specify.

![2017-06-02 07 03 08](https://cloud.githubusercontent.com/assets/136654/26723286/cc135200-4761-11e7-9d90-a72ea8c9cfcb.gif)

**Comment by radekmie** [comment]
Oh, my fault. Yeah, it's a dead lock. I'm not sure on how to handle it... How about simply removing error on first change? What do you think?

**Comment by purplecones** [comment]
Hmm. I haven't dug into the code yet but what if the submit button just stays enabled? This way user can trigger a validation at any point instead of on every change.

My use case is that I want to catch most of the validations on the client but during submit I can potentially have the server return additional errors. For this reason I would not want to call the server on every form change, just on submit.

**Comment by radekmie** [comment]
It makes sense. I don't really remember, why we are disabling this button but it is like this since... Ever I think. As a workaround, use `disabled={false}` on the `SubmitField`.

It's already on the roadmap, that rejected promise from `onSubmit` should be treated as a validation error. It would greatly simplify this case.

**Comment by purplecones** [comment]
I'm using `onSubmitFailure` and it works great! If only I can get submit button to work. It seems like it doesn't matter if `disabled={false}` is passed.

Doing it this way:
```jsx
<AutoForm schema={PersonSchema} validate="onSubmit" onSubmit={model => console.log({model})}>
      <TextField name="firstName" />
      <TextField name="lastName" />
      <ErrorsField />
      <SubmitField disabled={false} />
</AutoForm>
```
doesn't resolve the issue. I'll try and figure out how the forms work.

**Comment by radekmie** [comment]
It depends on your theme, but it should work in all of them - I'll fix it later.

**Comment by purplecones** [comment]
Thanks @radekgronski. How soon until this is published? It seems that the npm package is still on `1.18.1`

**Comment by radekmie** [comment]
It will be probably this Wednesday - I always wait a little until publish to make less granular versioning.

And by the way - actually, @purplecones, it's @radekmie.

**Comment by purplecones** [comment]
oh sorry!

**Comment by purplecones** [comment]
@radekmie this fix introduced a UX issue where all the errors are cleared after the first onChange event.

![2017-06-07 11 25 58](https://user-images.githubusercontent.com/136654/26886740-2a52dca8-4b74-11e7-8007-6e2fa3973b26.gif)

In case where there are a lot of errors, the user will not have them memorized. As soon as the user starts fixing one error, the remaining errors disappear.

**Comment by radekmie** [comment]
@purplecones: indeed. In this case, I'd rather suggest using `disabled={false}` - this change is really useful, because current version achieves a dead lock. On the other hand, `SubmitField` can't access validation mode of the form _(it's not in the context)_. Suggestions?

**Comment by radekmie** [comment]
I've decided to revert this and leave setting `disabled={false}` as an only option for now.

**Comment by purplecones** [comment]
@radekmie I tried that and it didn't work. See above.

```jsx
<AutoForm schema={PersonSchema} validate="onSubmit" onSubmit={model => console.log({model})}>
      <TextField name="firstName" />
      <TextField name="lastName" />
      <ErrorsField />
      <SubmitField disabled={false} />
</AutoForm>
```
I'm using the unstyled flavor.

**Comment by radekmie** [comment]
@purplecones: I've tried a minute ago and it's working. Try this, and let me know how it's working:

```js
<AutoForm schema={PersonSchema} validate="onSubmit" onSubmit={model => console.log({model})}>
    <AutoFields />
    <ErrorsField />
    <SubmitField />
    <SubmitField disabled />
    <SubmitField disabled={false} />
</AutoForm>
```

**Comment by waheed25** [comment]
validate="onSubmit" didn't work ...i want to disable submit button after initial click but it remains enable.
<AutoForm
                                validate="onSumit"
                                schema={schema} style={marginBottom}
                                onSubmit={(docs)=>this.onSubmit(docs)}
                                placeholder={true}
                                label={false}
                                submitField={MySubmitField}
                              >

**Comment by radekmie** [comment]
@waheed25: How your `MySubmitButton` differ from the default one? The default one is disabled only when the validation failed.

**Comment by waheed25** [comment]
yeah its default behaviour is disable only in failed validation but i want to implement the behaviour like that site http://app.mevris.io 
if we enter the wrong input that button will enable after some duration

**Comment by radekmie** [comment]
Then use `disabled` prop as shown few comments up.

**Comment by waheed25** [comment]
but how to set duration???

**Comment by radekmie** [comment]
There's no built in option to do so: implement a timer yourself and pass it's state.

**Comment by waheed25** [comment]
thank u .
i will try
