### ISSUE TITLE
Support for Inferno.js

### ISSUE THREAD

**Issue by vladejs** [vazco/uniforms#295]
I know this sounds crazy, since this is just a React library, but I have to ask: Is there any chance uniforms could be ported to Inferno.js?

I know Inferno support React apps by just adding `inferno-compat`, but performance isn't the same.

Inferno.js is the fastest library out there, and has nearly identical API to React.

I am holding in creating my next app in Inferno.js just because uniforms :)

**Comment by radekmie** [comment]
Have you tried it? I mean, I won't rewrite it using Inferno, but if I can help with compatibility, I would.

**Comment by vladejs** [comment]
No I haven't, but I think I don't need to, because without the `inferno-compat` module, aka, on a pure Inferno app, the simplest statement: `import React from react` wont work.

**Comment by radekmie** [comment]
In Webpack you can alias modules.

**Comment by vladejs** [comment]
Yeah, and Inferno documentation recommends to alias `React`  to `inferno-compat`, and it works.
But I'm aimed at the possibility to use uniforms on an Inferno app that doesn't rely on that compatibility layer.

Do you recommend to alias directly `React` to `Inferno`?

I haven't tried that.

**Comment by radekmie** [comment]
I'm not recommending anything as I'm not using Inferno actively. If you want, try it - if something won't work and I can change something in uniforms to make it work _(without breaking compatibility!)_, then I'll do.

**Comment by vladejs** [comment]
Thank you

**Comment by radekmie** [comment]
Hey, @vladejs. Have you tried it?

**Comment by vladejs** [comment]
I tried, with no luck. I suppose we have to stick with `inferno-compact`.

(Webpack Example)[https://github.com/zeit/next.js/tree/v3-beta/examples/using-inferno]

**Comment by radekmie** [comment]
So it **is** working with `inferno-compat`? I was pretty sure that it won't work with _plain_ `inferno`.

**Comment by vladejs** [comment]
haven't tested yet, but using next.js (see link above) you can actually
develop using react and build to production with inferno-compat


2017-07-05 13:22 GMT-05:00 Radosław Miernik <notifications@github.com>:

**Comment by radekmie** [comment]
Sounds good. I'm closing this issue then.
