### ISSUE TITLE
showInlineError not working

### ISSUE THREAD

**Issue by serkyen** [vazco/uniforms#297]
showInlineError is not working for me. 

I have tried with both antd and semantic ui. 

I can see here ([uniforms tool](https://uniforms.tools/)) that it is supposed to work with both of these but it's not for me...

```
<AutoForm
  schema={schema}
  onSubmit={doc => {
   Meteor.call('contacts.insert', doc, (err,res) => {
      if (err) {
         console.error(err);
      }
    })
}}
onSubmitSuccess={() => browserHistory.replace('/contacts')}
onSubmitFailure={() => alert('Promise rejected!')}
>
<TextField showInlineError={true} name="title" placeholder/>
<TextField showInlineError={true} name="firstName" placeholder />
<TextField showInlineError={true} name="lastName" placeholder />
<ErrorsField />
<SubmitField value="Create Contact"/>
</AutoForm>
```

Upon submission, I can see the ErrorsField is outputting all the errors at the bottom, but nothing inline. 

Furthermore, the ErrorsField list only shows one error at a time, even if there are two. Once I fix one of them, then it switches to the other one.

What could I be doing wrong?

**Comment by radekmie** [comment]
Hi, @serkyen. Which schema are you using _(I guess it's QraphQL)_?

**Comment by serkyen** [comment]
Hi, @radekmie, this is what I have in package.json
`"simpl-schema": "^0.2.3",`
Thanks

**Comment by radekmie** [comment]
@serkyen: I've checked this and it's working correctly. Do you have something special or unusual in your schema?

**Comment by serkyen** [comment]
@radekmie Here is my schema.js

```
import SimpleSchema from 'simpl-schema';

export const schema = new SimpleSchema({

  title: {
      type: String,
      optional: true,
      max: 4,
  },
  firstName: {
      label: "First Name",
      type: String,
      //optional: true
  },
  lastName: {
      type: String,
      optional: true
  },
  addresses: {
    type: Array,
    minCount: 1,
    maxCount: 2,
    optional: true
  },
  // 'addresses.$': Object,
  // 'addresses.$.street': String,
  // 'addresses.$.city': String,
  'addresses.$': Object,

  "addresses.$.desc": {
      type: String,
      optional: true,
      label: 'Description (Home, Work etc.)'
  },
  "addresses.$.address": {
      type: String,
      optional: true
  },
  "addresses.$.city": {
      type: String,
      optional: true
  },
  "addresses.$.state": {
      type: String,
      optional: true
  },
  "addresses.$.zip": {
      type: String,
      optional: true
  },
  createdBy: {
    type: String,
    optional: true
  },
  createdAt: {
    type: Date,
    optional: true
  },
  updatedAt: {
    type: Date,
    optional: true,
  },
  category: {
    type: String,
    label: "Category",
    optional: true,
  },
  company: {
    type: String,
    label: "Company",
    optional: true
  },
  email: {
    type: String,
    label: "Email",
    regEx: SimpleSchema.RegEx.Email,
    optional: true
  },
  phone: {
    type: String,
    label: "Home Phone",
    // regEx: SimpleSchema.RegEx.Phone,
    optional: true
    //min: 0
  },
  work: {
    type: String,
    label: "Work Phone",
    // regEx: SimpleSchema.RegEx.Phone,
    optional: true
    //min: 0
  },
  mobile: {
    type: String,
    label: "Mobile Phone",
    // regEx: SimpleSchema.RegEx.Phone,
    optional: true
    //min: 0
  },
  dob: {
    type: Date,
    label: "Date of birth",
    optional: true,
  },
  note: {
    type: String,
    label: "Note",
    optional: true
  },

  discount: {
    type: Boolean,
    label: "Discount",
    optional: true,
  },
  discountValue: {
    type: Number,
    label: "Percentage",
    optional: true,
  },
  archived: {
    type: Boolean,
    optional: true
  }

});
```

**Comment by radekmie** [comment]
OK, there's nothing unusual with your schema. I've tested it and it worked - I've triggered all three possible validation errors: `title` length, `firstName` existence and `email` format.

**Comment by serkyen** [comment]
Hmm that is very unusual. What else could it be if it's not the schema?

**Comment by radekmie** [comment]
I have no idea at the moment. If you can, please try to create as small as possible case, where it's not working - I'll do it too but probably not today - I'll take it from there.

**Comment by serkyen** [comment]
Ok I will do it as soon as I can and let you know. 
Thanks for your help.

**Comment by radekmie** [comment]
I found something, but it's probably not your case: error won't pop out, if you turn on `showInlineError` on a field with an error - it will be shown after any change.

**Comment by purplecones** [comment]
@radekmie does `showInlineError` work with `uniforms-unstyled`.

**Comment by radekmie** [comment]
@purplecones: no, it's not.

**Comment by radekmie** [comment]
Hey, @serkyen. I've tried it today and I'm still able to see these inline errors. If you can provide a reproduction - let me know. I'm closing for now.

**Comment by serkyen** [comment]
@radekmie, Ok no problem. I will do it as soon as I have time. Thanks
