### ISSUE TITLE
uniforms-bootstrap4 errorsfield not red

### ISSUE THREAD

**Issue by ggerber** [vazco/uniforms#301]
I notice that the errorsfield is red when using uniforms-antd in the demo, but not when using uniforms-bootstrap4. Is it standard styling for bootrap4 to not use a color? Without a background color of sorts the errorsfield blends in with the rest of the form making it less intuitive to see that it is actually a list of validation errors.

**Comment by radekmie** [comment]
I think it should be red - inputs borders are. Maybe you'd like to submit a PR with it? I'm not an expert in bootstrap though (nor 3 or 4) so let's ask @zeroasterisk.

**Comment by zeroasterisk** [comment]
Error state for Bootstrap 4 is basically just: `form-group has-danger`
http://v4-alpha.getbootstrap.com/components/forms/#validation

Which is being set here:
https://github.com/vazco/uniforms/blob/a8e026ef7d1b02fdd1d216509f5394afbe37a2db/packages/uniforms-bootstrap4/src/wrapField.js#L47

@radekmie this looks correct to me... I'll look into it more and let you know...

**Comment by radekmie** [comment]
@zeroasterisk yep, it's working in the `wrapField` - this issue is concerned on `<ErrorsField />`.

**Comment by zeroasterisk** [comment]
oh... hmmm... ok - I can make a PR which would "style" the `<ErrorsField />` if you like.

I'd probably do it as an outline card: 
http://v4-alpha.getbootstrap.com/components/card/#outline-cards

Is that too opinionated, or ok?

**Comment by radekmie** [comment]
@ggerber what do you think? I'm OK with both.

**Comment by ggerber** [comment]
Hi Radoslow,
I am a novice ito UI's.
But my opinion:
Cardlayout with red boder and black normal text is too vague.
Cardlayout with red background could be too loud for some people
Cardlayout with red border and red bold text may be a good compromise.
Kind regards
