### ISSUE TITLE
modelTransform does not alter form state - can we alter form state?

### ISSUE THREAD

**Issue by zeroasterisk** [vazco/uniforms#302]
I have been using `modelTransform` to take a set of UI elements and derive values based on certain settings.

simplified example:

```js
modelTransform = (mode, model) => {
  const outputModel = cloneDeep(model);
  if (model.one === "on" && model.two === "on") { outputModel.three = "on"; }
  return outputModel;
}
```

I was originally doing this via complicated onchange handlers in fields, but they got convoluted as my derived logic became bigger.

### the problem: changes are not applied to form state

The problem is that while `modelTransform` works great, when submitting and validating, it does not apply to `form.state.model`.  

So in the above example, `three="on"` is never set in the form state.

So if I have a field for `three` in the UI it isn't modified, doesn't know about the transform.

### suggestions/ideas

1. maybe we could expose a different mode to set onto state `transformModel('state', model)`
2. maybe we could expose a different transform function for `transformBeforeSetState()`
3. maybe we could just run the transform on state, after every set-state (possibly expensive)

Or... maybe there's some other existing functionality I don't know about that will allow me to transform a model and update form state.

Or... maybe I'll have to over-ride onChange with my own custom Form (if so, I might need help or an example to do so)

???
https://github.com/vazco/uniforms/blob/0f733f7147cecbe0ba1d49adbe3e03d3ca83bf61/packages/uniforms/src/BaseForm.js#L215

**Comment by radekmie** [comment]
Let me emphase it - `modelTransform` was **not** designed _(and implemented too)_ to do such things - you should use a _controlled form_ so a one with a `onChange` handler and a state managed by you. In such case, 99% of time `<AutoForm />` is not necessary - `<ValidatedQuickForm />` will suffice.

It was designed to allow three different things _(only two at the beginning)_ - to allow the displayed/submitted/validated differ from the internally kept one. In other words, it's only a _view_ transformation, not a _mutating_ one.

IMHO using a form with `onChange` is quite self-explanatory - treat it in the same way as the `<input />`, where `model` is the `value` and `onChange` is... itself.

The line you've marked is used only to detecting changes to let fields know about it.

**Comment by zeroasterisk** [comment]
I see in your documentation an example for [Modifier form](https://github.com/vazco/uniforms/blob/master/INTRODUCTION.md#example-modifierform) where you are making your own custom form...

If I make a generic example, can you review it, and perhaps we should add it to documentation?

I'm imagining I will be something like:

```js
const MyForm = parent => class extends parent {
  onChange (key, value) {
    // do my think to make a new state
    const changesToState = myFunctionToCreateNewState(this.state, key, value);
    this.setState(changesToState);
    // do the uniforms thing to know it's parts and peices
    super.onChange(key, value);
  }
}
export default Modifier(BaseForm);
```

**Comment by radekmie** [comment]
To be honest in that case I've never used `<AutoForm />` _(and told my colleagues to do so)_ but use `<ValidatedQuickForm />` and manage state on your own - that's your _wrapped_ form.

Now I'm thinking about simply extend `<AutoForm />` - it should do the job. Example:

```js
class MyForm extends AutoForm {
    onChange (key, value) {
        if (key === 'key_to_intercept') return;
        if (key === 'key_to_translate') return super.onChange('another_key', value);
        
        if (key === 'key_to_mutate') {
            super.onChange('another_key1', value * 2);
            super.onChange('another_key2', value / 2);
            return;
        }

        super.onChange(key, value);
    }
}
```

_(I haven't tested it - if it's not working, please let me know)_

**Comment by zeroasterisk** [comment]
Yes, you are right, that's easy enough:

```js
// example where we know the logic inside onChange and manipulate field by field
class CustomAutoFormIsolated extends AutoForm {
    onChange (key, value) {
        if (this.state.changed !== null && key !== 'three') {
            const model = cloneDeep(super.getModel('form'));
            set(model, key, value); // have to set the changed value here too (setState not done)
            // example where we procedurally replace the model when certain combinations exist
            // no direct access to state, but logic must know field-by-field changes
            if (model.one === 'on' && model.two === 'on') {
                super.onChange('three', 'on');
            }
        }
        super.onChange(key, value);
    }
}


// example where we have a function which transforms the whole model
//   in this case it mutates, but it doesn't have to
const mutateModel = model => {
    if (model.one === 'on' && model.two === 'on') {
        model.three = 'on';
    }
};

class CustomAutoFormWholeReplacement extends AutoForm {
    onChange (key, value) {
        super.onChange(key, value);
        if (this.state.changed !== null && key !== 'three') {
            const model = cloneDeep(this.state.model);
            set(model, key, value); // have to set the changed value here too (setState not done)
            // example where we pass the whole model through a transformer function
            // requires direct state manipulation
            mutateModel(model);
            this.setState({model, modelSync: model});
        }
    }
}
```

For the full example see: https://github.com/zeroasterisk/uniforms/commit/3912be6b1cd883333c5636cf8a358eea515e2770
https://github.com/zeroasterisk/uniforms/tree/example-custom-form-state
cd demo and start it up
![ss](https://media.giphy.com/media/3o7btPTXLFcMt4Pcbu/giphy.gif)

**Comment by radekmie** [comment]
I think we can close it, right?

**Comment by zeroasterisk** [comment]
For sure - unless you want to add this (or something like it) on the docs.

**Comment by radekmie** [comment]
I'll surely do. By the way - my example was fully working, right? I don't really get, why you've made it so complicated.
