### ISSUE TITLE
cdn link for uniforms

### ISSUE THREAD

**Issue by ggerber** [vazco/uniforms#306]
Hi,
Is it possible to provide a cdn link for uniforms with subresource integrity check?
This will help reduce the initial client bundle size, by allowing users to include the library by inserting a link in the html head.

**Comment by radekmie** [comment]
It is impossible before #265. On the other hand - why do you need a CDN? If you are using Webpack or Meteor 1.5 then you can use dynamic `import` to do it.

**Comment by ggerber** [comment]
I am new to cdn, but the benefits over dynamic import as I understand is
that cdn is a distributed system: allowing less internet hops for the
client, allowing the client browser to download libraries in parallel using
multiple connections and reducing the upload bundle size (bandwidth)
required by the meteor server. One can probably create a cdn of the meteor
app as well, winning back some of the benefits above.

**Comment by radekmie** [comment]
Yep, it's true but you've mentioned only reducing initial bundle size. Nevertheless, it's impossible right now, because there's no bundling system. Maybe you'd like to help us with it?

**Comment by radekmie** [comment]
As soon as #265 will be ready, simply using [unpkg](unpkg.com) will do the job. Therefore, I'll close it.
