### ISSUE TITLE
Add a component that renders a list of fields

### ISSUE THREAD

**Issue by macrozone** [vazco/uniforms#31]
I think it would be nice to have a `<AutoFieldList />`-component that renders a list of fields automatically
similar to aldeed:autoform's https://github.com/aldeed/meteor-autoform#afquickfields:

`````
<AutoForm>
  <AutoFieldList />
  <SubmitField value="send" />
</AutoForm>
``````

This allows us to easly change the style or behavior of the submit button or to add more elements inside the form without loosing the "auto-form-magic".

you could also omit fields:

`````
<AutoForm>
  <AutoFieldList omitFields={["userId", "title"]}/>
  <SubmitField value="send" />
</AutoForm>
``````

or include only some fields:

`````
<AutoForm>
  <AutoFieldList fields={["title", "text"]}/>
  <SubmitField value="send" />
</AutoForm>
``````

or group some fields:

`````
<AutoForm>
  <div class="col-xs-6">
      <AutoFieldList fields={["title", "text"]}/>
  </div>
  <img class="col-xs-6" src="funnycatpicture.jpg" />
  <div class="col-xs-12">
      <AutoFieldList fields={["comment"]}/>
  </div>
  <SubmitField value="send" />
</AutoForm>
``````

What do you think?

Should be easy to develop, right? AutoFieldList (or however it will be named) could receive the schema-definition by context.

**Comment by radekmie** [comment]
Great idea, @macrozone!

How about `AutoFields`? `AutoFieldList` might be confused with `ListField` (and it's _family_). In spite of all, that's a great idea! I'll do it later today.

**Comment by macrozone** [comment]
Also thought about `AutoFields`, but it may be get confused with `AutoField` ;-)

**Comment by radekmie** [comment]
Check it out. I'll publish new version later. Let  me know, if there are some errors.

**Comment by vladejs** [comment]
It doesn't work for me:
```
<AutoForm
                schema={ ProductSchema }
                onSubmit={this.onSubmit.bind(this)}
                grid={2} inlineErrors
                model={this.props.model}
                submitField={this.getCustomSubmit.bind(this)}
            >
                <AutoFields />
            </AutoForm>
```

The error is:
```
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `_class`
```

I'am using `1.0-rc30`

**Comment by radekmie** [comment]
Well... It turned out, that `AutoFields` component is not exported... Shame. I'll fix it ASAP.
