### ISSUE TITLE
Loading Meteor Collection Data into a Select Field

### ISSUE THREAD

**Issue by serkyen** [vazco/uniforms#312]
I am having an issue with populating a SelectField with data from a Meteor Collection. I am going to omit a whole bunch of code to keep it simple as I don't think any of the other code is relevant but let me know if you want to see more code.

I am not sure what the correct way to do this is but I tried doing it through the schema like this...

**schema.js**
```
category: {
    type: String,
    label: "Category",
    optional: true,
    uniforms: {
      options: () => {
          return Categories.find({collection:Session.get('context')}).map((l,i)=>{
            return { label: l.name, value: l._id };
          });
      }
    }
  },
```
**EditContact.js**
```
<AutoForm
    schema={schema}
...
<SelectField name="category" placeholder />
...
</Autoform>
```

-------------------------

I also tried like this...

**EditContact.js**
```
import {catsList} from '../helpers';
...
<AutoForm
    schema={schema}
...
<SelectField options={catsList()} name="category" placeholder />
...
</Autoform>
```

**helpers.js**
```
export function catsList() {
    return Categories.find({collection:Session.get('context')}).map((l,i)=>{
      return { label: l.name, value: l._id };
    });
}
```

Both these ways work however, the issue is that if I click on the navigation menu to go to this page, then the select field is populated correctly...
![image](https://user-images.githubusercontent.com/16330002/28255999-2183ca0e-6b01-11e7-8b92-b74789208363.png)

But if I then reload the page, the field is not populated...
![image](https://user-images.githubusercontent.com/16330002/28256009-339656a8-6b01-11e7-954c-2f55d216866a.png)

So it looks like something to do with the order things are loaded. 

Any help would be very appreciated.
Thanks

**Comment by serkyen** [comment]
Another thing...probably related to this is when I first drop down the select field, I see the proper 'name' values appear in the list...
![image](https://user-images.githubusercontent.com/16330002/28256234-95292c36-6b03-11e7-9643-95febd2cab6e.png)

If I select one of them, it fills the field with the value (instead of name)...
![image](https://user-images.githubusercontent.com/16330002/28256247-b101d0f2-6b03-11e7-9c34-2302d6c99e8e.png)

If I then click it again, the list is empty...
![image](https://user-images.githubusercontent.com/16330002/28256252-c5df56b6-6b03-11e7-8513-26060f80ce30.png)

If I navigate away from the edit contact form, and come back again, I see this...
![image](https://user-images.githubusercontent.com/16330002/28256256-da9018b6-6b03-11e7-8498-5c62a80f25bb.png)

Then If I select and change it, it changes to the 'value again'...
![image](https://user-images.githubusercontent.com/16330002/28256266-efe9336e-6b03-11e7-8b3c-96f39d8b639a.png)

Thanks

**Comment by radekmie** [comment]
It's because your form is not reactive. You should wait for subscriptions before rendering it or use a wrapper with `Tracker.autorun` _(like `react-komposer`)_ to keep it reactive.

**Comment by serkyen** [comment]
Hi @radekmie, Thank you for your response.
Can you give me a clue as to how I can wrap the form with Tracker.autorun. 

I have used Tracker.autorun in a few places already but it is usually wrapping a state in ComponentDidMount. 

How can I wrap the form with it? Or how can I make the form wait for subscriptions?

I have a component that renders like this...
 
```
class EditContact extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            title: '',
            firstName: '',
            lastName: '',
            error: ''
        };
    }


    renderForm(doc) {

        if (!doc) {

            return (
              <p>Doc not specified</p>
            )

        } else {

              return (
                      <div>

                        <AutoForm
                          schema={schema}
                          validate="onChange"
                          onSubmit={doc => {
                            Meteor.call('contacts.update',  doc._id, doc, (err,res) => {
                              if (err) {
                                console.error(err);
                                message.error("Something went wrong...please contact Cakenote Technical Support for assistance.");
                              } else {
                                message.success("Contact updated.");
                              }
                            })
                          }}
                          onSubmitSuccess={() => browserHistory.replace('/contacts')}
                          model={doc}
                          >

                            <Row gutter={16}>

                              <Col xs={24} sm={24} md={8} lg={8}  xl={8}>
                                  <TextField showInlineError={true} name="firstName" placeholder />
                                  <TextField showInlineError={true} name="lastName" placeholder />
                                  <TextField name="email" placeholder />
                                  <SelectField name="category" placeholder /> {/*options={catsList()}*/}
                                  <TextField name="company" placeholder />
                              </Col>

                              <Col xs={24} sm={24} md={8} lg={8}  xl={8}>
                                  <NumField name="phone" placeholder />
                                  <NumField name="work" placeholder />
                                  <NumField name="mobile" placeholder />
                                  <DateField name="dob" placeholder />
                                  <LongTextField name="note" placeholder />
                              </Col>

                              <Col xs={24} sm={24} md={8} lg={8}  xl={8}>
                                  <ListField name="addresses" />
                              </Col>

                            </Row>

                            <Row>
                                <Col span={24}>
                                  <ErrorsField />
                                  <SubmitField value="Update Contact"/>
                                </Col>
                            </Row>

                        </AutoForm>

                      </div>
                  )
        }
    }

    render() {
      return (
        <div>
          {this.renderForm(this.props.doc)}
        </div>
      )
    }
};

EditContact.propTypes = {
  doc: React.PropTypes.object,
  singleViewDocId: React.PropTypes.string,
}

export default createContainer(() => {
  const singleViewDocId = Session.get('singleViewDocId');
  const subscription = Meteor.subscribe('contacts');
  const loading = !subscription.ready();
  const doc = Contacts.findOne(singleViewDocId)

  return {
    loading,
    singleViewDocId,
    doc
  };
}, EditContact);


```


Sorry, I am still learning react and am finding it really hard to grasp things like this after coming from Blaze.

Thank you

**Comment by radekmie** [comment]
Maybe try to _force_ wait for this subscription with `const doc = !loading && Contacts.findOne(singleViewDocId);`? I haven't worked `createContainer`, but it looks fine. What's the problem?

**Comment by serkyen** [comment]
Ok I tried that, but still exact same results :(
I am using createContainer because that's what I learned in a course I did on Udemy, but as mentioned, I don't fully understand it yet. 
It seems to me that the doc should already be reactive shouldn't it? 
Any other suggestions?

**Comment by radekmie** [comment]
Two more suggestions:
* You are not waiting for the proper subscription: you should wait for the `Categories` subscription.
* Try to keep with `options={categories}`, where `categories` are computed in `createContainer` and passed as a prop.

**Comment by serkyen** [comment]
Hi @radekmie, thank you so much for those suggestions. 
I can't believe I missed subscribing to the Categories...SMH. I did that now and also did your second suggestion. It is all working now :) 
Thanks!
