### ISSUE TITLE
Filenames with a colon cause trouble on Windows.

### ISSUE THREAD

**Issue by ArchiCroc** [vazco/uniforms#313]
I tried to fork this repo to work on a pull request and I had an issue with the file "uniforms/packages/uniforms/__mocks__/meteor/aldeed:simple-schema.js" because I use Windows and colons ":" are not allowed in filenames.

Would it be possible to rename that file to aldeed_simple-schema.js and add a regex to jest's moduleNameMapper field to map the module to it?  That seemed to fix it for me Locally. I can submit a PR if that's the best solution.

**Comment by radekmie** [comment]
Good catch! Yep, I definitely agree for a PR with a fix you've described.
