### ISSUE TITLE
Is uniforms supported in react native???

### ISSUE THREAD

**Issue by waheed25** [vazco/uniforms#315]
i just want to know uniforms are supported in react native or not???

**Comment by radekmie** [comment]
Hey @waheed25. I've never tried React Native so I don't even know if it may work. If the only difference is the DOM then there's no theme for it (yet?). But you can use uniforms to create one - a lot of users are creating custom themes. Overriding `BaseForm.render` and creating custom fields would suffice.

**Comment by waheed25** [comment]
thanks for your quick reply.
is there any example of usage in react native???

**Comment by radekmie** [comment]
As I said, I'm not familiar with it. _Normal_ usage should do the job but as I said - if _normal_ DOM is not supported, you have to create a custom theme.

**Comment by macrozone** [comment]
i should try that definitly, because most react-native form-libraries are just awefull. :-(

**Comment by copleykj** [comment]
I hate to revive old issues, but it would be super nice to have this support in RN so maybe we can get a discussion started..

Right now from what I see the only real issue holding back RN support is the user of DOM (`<form />`) elements in the BaseForm component. 

I'm in the process of working on a theme for Native Base but I'll need to see about tackling the DOM issue before I'll be able to have it working.

**Comment by radekmie** [comment]
No problem, @copleykj. [My comment](https://github.com/vazco/uniforms/issues/315#issuecomment-316663929) is still true: it works. Here's an example:

```js
import {ScrollView} from 'react-native';
import {ValidatedForm as base} from 'uniforms/ValidatedForm';

class ValidatedForm extends base {
  render() {
    <ScrollView {...this.getNativeFormProps()} />
  }
}
```

In the same way you do `Auto`/`Quick`/any other form component. Fields are also natural: simply copy [`AutoField`](https://github.com/vazco/uniforms/blob/master/packages/uniforms-unstyled/src/AutoField.js) into your project and _fill the gaps_ - implement needed components. Really, it _just works_.

The only problem is the `onSubmit`. It's not supported in React Native, so you have to use `ref` and call `submit` manually.

**Comment by copleykj** [comment]
@radekmie hadn't thought about just creating a new class and just overriding the render, that's perfect thanks.

**Comment by Roshdy** [comment]
Can you please post a working example. I'm completely lost. I've been trying for 3 days now with no luck.

**Comment by radekmie** [comment]
Hi @Roshdy. I saw you've already filed #810 - I'll answer there.
