### ISSUE TITLE
How to enter secure password entry validation 

### ISSUE THREAD

**Issue by waheed25** [vazco/uniforms#317]
Now i am entring password in a field that is string type but i want to know how can i implement secure text entry field for password input

**Comment by radekmie** [comment]
You mean a _dotted_ input? Yes, simply pass `type="password"` to `TextField` somehow (schema, props) just like in native `<input>`.

**Comment by waheed25** [comment]
yes ...you are right  type="password" to TextField somehow (schema, props) just like in native <input>.

**Comment by radekmie** [comment]
Then that's it.

**Comment by waheed25** [comment]
i want know than what is prop used in uniforms to enter dotted input????

**Comment by radekmie** [comment]
> simply pass `type="password"` to `TextField`

**Comment by waheed25** [comment]
it didn't work

**Comment by radekmie** [comment]
In which theme?

**Comment by waheed25** [comment]
would schema be look like this: 
 `password: {

    type:"password",
    label: "Password",
    max: 100

  }`

**Comment by radekmie** [comment]
I guess it's SimpleSchema? If so, use `{type: String, label: 'Password', max: 100, uniforms: {type: 'password'}}`. It's in the docs.

**Comment by waheed25** [comment]
in bootstrap 4

**Comment by waheed25** [comment]
thanks it worked
