### ISSUE TITLE
How to increase Submit button Size

### ISSUE THREAD

**Issue by waheed25** [vazco/uniforms#319]
i have customized the submit button label but i want to increase size of the button too .i tried with styles height and width but it didn't work how can i do that??

**Comment by radekmie** [comment]
Which theme? What have you tried? What does it mean _it didn't work_? You couldn't _target_ it with CSS?

**Comment by waheed25** [comment]
i am using bootstrap 4 theme .
i used styles={{width:100,height:100}}
but button remains same size

**Comment by waheed25** [comment]
const MySubmitField = props =>
  <SubmitField value="Login" styles={{width:100,height:100}}} /> like that
;

**Comment by radekmie** [comment]
As you can easily see in the [source](https://github.com/vazco/uniforms/blob/master/packages/uniforms-bootstrap4/src/SubmitField.js#L35), `style` prop is passed to the wrapper, not the button.
