### ISSUE TITLE
How to set individual label for every field 

### ISSUE THREAD

**Issue by waheed25** [vazco/uniforms#320]
now i am hide the label using prop
like that
<AutoForm
                                validate="onSubmit"
                                schema={schema}
                                onSubmit={(docs)=>this.onSubmit(docs)}
                                placeholder={true}
                                label={false}
                                submitField={() => MySubmitField(this.state.disable)}
                              >
but i want to write some text in the checkbox field but with label={false } it only shows check box and when i set label={true} it show label of all the fields but i want to show label of only checkbox field .how is it possible?? here is my schema
Remember: {
    type: Boolean,
    label:'Remember me',
    defaultValue: false,
    
  },

**Comment by radekmie** [comment]
If you want to disable all but one labels then disable it in the form with `label={true}` and enable in this single field with `label={true}`.

For the future, please read the documentation (it is there) and format your code properly.
