### ISSUE TITLE
How to make hyper links in a form

### ISSUE THREAD

**Issue by waheed25** [vazco/uniforms#321]
i just want to know can i make hyper links in uniforms i am asking this because i searched the whole documentation but i  didn't find it in the documentation

**Comment by radekmie** [comment]
What do you mean?

```js
<AutoForm {...props}>
    <a href="..." />
</AutoForm>
```

Like this?

**Comment by waheed25** [comment]
yes almost like that .
There is a field of terms and condition with a checkbox i want to make the word terms and condition hyper linked when user clicks on terms and condition it will redirect to terms and condition page .
previously i handle this with react router link but now i implement uniforms but i don't know how to implement this functionality in uniforms

**Comment by radekmie** [comment]
And what's the problem? I cannot see any problem in there.

**Comment by waheed25** [comment]
AutoForm {...props}>
    <a href="..." />
</AutoForm> 
this is not working

**Comment by radekmie** [comment]
I've tried it now and it is working.

**Comment by waheed25** [comment]
`  <AutoForm
                                validate="onSubmit"
                                schema={schema}
                                onSubmit={(docs)=>this.onSubmit(docs)}
                                placeholder={true}
                                label={true}
                                submitField={() => MySubmitField(this.state.disable)}
                                boolField={MyBoolField}
                              >
                                <a href="google.com" />
                              </AutoForm>
`
here is my code

**Comment by radekmie** [comment]
You know that an empty `<a>` will render same as a empty `<p>`?

**Comment by waheed25** [comment]
the simple issue that i want to make a boolean field with label a link i wants when user clicks on label than it will redirect

**Comment by radekmie** [comment]
Then write your `BoolField` with a correct `a`. I'll close it as it's not related to uniforms.
