### ISSUE TITLE
Selecting an item from select box doesn't change value

### ISSUE THREAD

**Issue by mgscreativa** [vazco/uniforms#325]
Hi! I have an issue with Select elements. I'm loading the form like this
```
<AutoForm
  schema={DevicesSchema}
  onSubmit={data => handleSubmit(data, device, history)}
  model={device}
/>
```
If I load the AutoForm component with an empty **model**, all select elements get rendered and I can see the select options just fine, but when clicking a select option, the value displayed for the element doesn't change!

On the other hand, if I load the AutoForm with an instantiated **model** (ie: got subscription data from meteor backend) all select elements get rendered and I can see the select options just fine and when clicking a select option, the value displayed for the element changes...

Did I miss something here?

This is the output html code for a SelectField element
```
<div class="col-sm-6 field form-group required">
  <label for="uniforms-0000-0001" class="control-label">Tipo</label>
  <select class="form-control" id="uniforms-0000-0001" name="type">
    <option value="" disabled="" hidden="">Seleccione una opción</option>
    <option value="Bicicleta Fija">Bicicleta Fija</option>
    <option value="Caminador Super">Caminador Super</option>
    <option value="Caminando en el Aire">Caminando en el Aire</option>
  </select>
</div>

```
Thanks in advise!

**Comment by radekmie** [comment]
Can you post the relevant part of your schema? Can you reproduce it in the demo?

**Comment by mgscreativa** [comment]
My schema looks like this

```
const DevicesSchema = new SimpleSchema({
  number: {
    type: Number,
    label: 'Número de dispositivo',
  },
  type: {
    type: String,
    label: 'Tipo de dispositivo.',
    allowedValues: ['Bicicleta Fija', 'Caminador Super', 'Caminando en el Aire'],
  },
});

export default DevicesSchema;
```

The demo works just fine with this schema, because I can't set the **model** param. If I remove the model param in my project selects work as expected, but the issue raises with empty models

**Comment by radekmie** [comment]
First post:
> If I load the AutoForm component with an empty model, all select elements get rendered and I can see the select options just fine, but when clicking a select option, the value displayed for the element doesn't change!

Second post:
> The demo works just fine with this schema, because I can't set the model param. If I remove the model param in my project selects work as expected, but the issue raises with empty models

How is it then?

**Comment by mgscreativa** [comment]
Hi @radekmie! The issue arises when I declare **model** prop

```
<AutoForm
  schema={DevicesSchema}
  onSubmit={data => handleSubmit(data, device, history)}
  model={device}
/>
```
This fails with select inputs if **device** model is empty (ie: displaying the form to create a new device)

If I try to edit an existing device, it works. All selects work as expected...

**Comment by radekmie** [comment]
By _empty_ you mean `{}`, right? If so, then it's the same as not providing `model` at all.

**Comment by mgscreativa** [comment]
Yep, empty as {}

So if I set the model to an empty object AutoForm or SelectField will fail as described above?

**Comment by radekmie** [comment]
I don't know, how it fails. You mean that it shows a value but doesn't select it?

**Comment by mgscreativa** [comment]
Sorry, I will investigate my code because on a fresh test project it works...

**Comment by mgscreativa** [comment]
I finally found the issue. In my project device is the **model** I send to AutoForm, so, as this device object comes from a Meteor subscription I have to define defaultProps in the react component where I implement AutoForm. So if I define device like this, I can click the options in the select boxes, but after clicking the value is not changed
```
DeviceEditor.defaultProps = {
  device: null,
};
```
If I define device as empty object like this, it works...
```
DeviceEditor.defaultProps = {
  device: {},
};
```
Maybe it would be good to point this in the QuickStart model comment https://github.com/vazco/uniforms/blob/master/INTRODUCTION.md#quick-start

**Comment by mgscreativa** [comment]
I just created a demo repo for you to try https://github.com/mgscreativa/meteor-autoform-select-issue

Access it with admin@admin.com and password then go to this url http://localhost:3000/documents-autoform

**Comment by radekmie** [comment]
@mgscreativa: thanks for your investigation. It's clearly stated in the [API docs](https://github.com/vazco/uniforms/blob/master/API.md#baseform) that `model` have to be an object (I know, `null` is an object too so I've said some more about its structure):

```
    // Form model.
    //   An object with {field: value} structure. It doesn't matter, if it has a
    //   prototype or not, but keep in mind that in onSubmit or in onChangeModel
    //   you'll receive a plain object. If you treat form as an input, then
    //   this is a value.
    model={{fieldA: 1}}
```
