### ISSUE TITLE
Unknown props `unique`

### ISSUE THREAD

**Issue by stolinski** [vazco/uniforms#327]
Schema looks like this.
```
export const AffiliatesSchema = new SimpleSchema({
  ref: {
    type: String,
    label: 'Referal ID',
    unique: true,
    index: true,
  },
  name: {
    type: String,
  },
  paypalEmail: {
    type: String,
    label: 'Paypal Email',
  },
  email: {
    type: String,
    label: 'Paypal Email',
  },
  rate: {
    type: Number,
    label: 'Link',
  },
});

```

Full error here. Looks like the index & unique are getting passed into a div. Using Simple Schema.
```
modules.js?hash=9b97f35d4b954b60ead2275fde86130a4f2554c6:3944 Warning: Unknown props `unique`, `index` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by Text)
    in Text (created by TextField)
    in TextField (created by AutoField)
    in AutoField
    in form (created by AutoValidatedQuickUnstyledForm)
    in AutoValidatedQuickUnstyledForm (created by Affiliator)
    in div (created by Affiliator)
    in Affiliator (created by Route)
    in Route (created by AdminLayout)
    in Switch (created by AdminLayout)
    in section (created by AdminLayout)
    in AdminLayout (created by ReactMeteorDataComponent)
    in ReactMeteorDataComponent (created by LoadableComponent)
    in LoadableComponent (created by Route)
    in Route (created by MainLayout)
    in Switch (created by MainLayout)
    in main (created by MainLayout)
    in div (created by MainLayout)
    in MainLayout (created by Route)
    in Route (created by App)
    in Switch (created by App)
    in App
    in ScrollToTop (created by Route)
    in Route (created by withRouter(ScrollToTop))
    in withRouter(ScrollToTop)
    in Router (created by BrowserRouter)
    in BrowserRouter
    in Provider
```

**Comment by radekmie** [comment]
Hi, @stolinski. For such case use [`filterDOMProps.register`] (https://github.com/vazco/uniforms/blob/master/API.md#filterdompropsregister). Example:

```js
filterDOMProps.register('unique');
```

It's because all [additional options](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/SimpleSchemaBridge.js#L173-L223) are [passed down to the component](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/BaseField.js#L193).

**Comment by CaptainN** [comment]
The suggested fix seems inappropriate. Why would the `unique` and `index` flags get passed to the DOM elements at all?

**Comment by radekmie** [comment]
No, we are _not mixing SimpleSchema props with DOM props_ - these are simply passed to the component to make use of it. If you really need it, simply create your own bridge class. And yes, uniforms make use of `uniforms` key in the schema field definition.

**Comment by CaptainN** [comment]
Hmm, maybe I misunderstood the warning message. Copied below:

```
modules.js?hash=3840e0140dc7a879517da577c5c5ba42dd22b8dc:27461 Warning: Received `true` for a non-boolean attribute `index`.

If you want to write it to the DOM, pass a string instead: index="true" or index={value.toString()}.
    in div (created by Text)
    in Text (created by TextField)
    in TextField (created by DeckForm)
    in form (created by AutoValidatedQuickBootstrap3Form)
    in AutoValidatedQuickBootstrap3Form (created by DeckForm)
    in DeckForm (created by LoadableComponent)
    in LoadableComponent (created by DeckEditor)
    in div (created by DeckEditor)
    in div (created by DeckEditor)
    in DeckEditor (created by ReactMeteorDataComponent)
    in ReactMeteorDataComponent (created by LoadableComponent)
    in LoadableComponent (created by Editor)
    in div (created by Editor)
    in div (created by Editor)
    in div (created by Editor)
    in Editor (created by Connect(Editor))
    in Connect(Editor) (created by Connect(Connect(Editor)))
    in Connect(Connect(Editor)) (created by ReactMeteorDataComponent)
    in ReactMeteorDataComponent
    in Provider
```

**Comment by CaptainN** [comment]
Is `index` maybe used for something else in TextField?

**Comment by CaptainN** [comment]
BTW, the solution does work - though it makes an interesting problem (I use Loadable to load all the uniforms - so it all get loaded later). Is it safe to re-register the same props all the time?

**Comment by radekmie** [comment]
It is passed to component but component pass it through. No, `index` is not used there. Yes, it is safe to call `filterDOMProps.register` multiple times - I think you should read [`filterDOMProps`](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/filterDOMProps.js) and [`TextField`](https://github.com/vazco/uniforms/blob/master/packages/uniforms-unstyled/src/TextField.js) sources - it's 90 lines total.

**Comment by CaptainN** [comment]
Okay great. Thanks so much for this awesome project - it saves me a ton of time, and I really appreciate it's existence.

**Comment by ayhid** [comment]
Hello  I am running into the same problem, is there any examples showing the filterDOMProps usage?

Thanks a lot

**Comment by radekmie** [comment]
@ayhid what problem exactly? Using `filterDOMProps` [documented](https://github.com/vazco/uniforms/blob/master/API.md#filterdomprops).
