### ISSUE TITLE
Issue when assigning custom component to key on schema file

### ISSUE THREAD

**Issue by vladejs** [vazco/uniforms#328]
Hello, this worked for me before. I started a new project last week and my old code doesn't work. I've see several issues asking the use of custom components, but whatever I do I got always an error. This is my use case:

My schema definitions are under `/lib`  folder, and my components under `/client` folder, which means I have to do `Meteor.isClient` before using a custom component on the schema:

```
import {SimpleSchema} from 'meteor/aldeed:simple-schema';
import {Meteor} from 'meteor/meteor';

import nothing from 'uniforms/nothing';
import LongTextField from 'uniforms-bootstrap3/LongTextField';

let FieldDate = nothing;

if (Meteor.isClient) {
 FieldDate = require('/client/imports/modules/main/components/field_date').default;

  console.log(FieldDate); // returns function _class() {// 57, _classCallCheck3.default)(this, _class);
}

export default new SimpleSchema({
  _id: {
    type: String,
    optional: true,
    uniforms: () => nothing
  },

  dob: {
    type: Date,
    label: 'Date of Birth',
    optional: true,
    uniforms: () => FieldDate
  },
});
```

Notice I am using `FieldDate` the same as I use `nothing`, but when rendering the form with `<AutoForm />` I got the error:

> Warning: uniforms(...): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.

My `FieldDate` component was created using `connectField` helper:

```
import React from 'react';
import { connectField } from 'uniforms';

class FieldDate extends React.Component {
  constructor(props) {
    super(props);
  }
  render() {
    return (
      <div>
        FieldDate
      </div>
    );
  }
}

export default connectField(FieldDate);
```

I don't know what changed (apart of doing the `Meteor.isClient` check). 3 Months ago a similar code worked for me.

Uniforms/Uniforms-bootstrap3 versions 1.19.1

Any help will be appreciated.

**Comment by radekmie** [comment]
I'm sure it wasn't working then. `() => nothing` **is** a component, because `nothing` is a JSX node, not a function returning it and `() => FieldDate` **is not** a component - it's a function returning a component. Simply change it to `uniforms: FieldDate`, that's all.

**Comment by vladejs** [comment]
I meant that it was working then because I tried both my snippet and yours. In fact, yours was the first I tried, and on the server's console I saw following error:
```
Error: Invalid definition for dob field.
...
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

What I suspect is that `aldeed:simple-schema` package doesn't understand `uniforms` key on the server (remember, the schema file is on a shared folder because it's used on the server as well).

In that case, how can I solve the problem without duplicating the file and placing the one with `uniform`  keys client only?

**Comment by radekmie** [comment]
Many, many ways. For example use `unforms: {yourCustomKeyHere: 'FieldDate'}` and a custom `AutoField` which will map these strings properly. Other way is to extend/override schemas options on client.

**Comment by vladejs** [comment]
It looks like either way there is no way to have everything on a single place/object.
Is there any documentation on how to approach one (preferably the best) way to do it?

**Comment by radekmie** [comment]
Yes, at least two are needed. And no, there's not because it's up to your project needs.

**Comment by vladejs** [comment]
mmm. I thought this is a common pattern on meteor apps:
- You create your schema in a shared place
- Uses the schema on the client
- Uses it on the server to check on methods

The easiest way for me is an approach that doesn't create redundancy, ie, extending the schema on the client.

Anyway, it would be great to have a technical snippet on how you would approach this problem.

Thanks for your time.
