### ISSUE TITLE
Custom Upload Image Field Using Ant Design

### ISSUE THREAD

**Issue by serkyen** [vazco/uniforms#330]
I am trying to implement an upload field using Ant Designs Upload component and Slingshot. 
I have successfully managed to do it with a plain 'input type=file', however, when I try to do it using Ant Designs Upload component, I am having trouble returning the url. Here is the code...

```
import React, { Component } from 'react';
import Upload from 'antd/lib/upload';
import Icon from 'antd/lib/icon';
import Modal from 'antd/lib/modal';
import { BaseField, connectField } from 'uniforms';

class UploadImage extends Component {
  state = {
    previewVisible: false,
    previewImage: '',
    fileList: []
    // [{
    //   uid: -1,
    //   name: 'xxx.png',
    //   status: 'done',
    //   url: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
    // }],
  };

  handleCancel = () => this.setState({ previewVisible: false })

  handlePreview = (file) => {
    this.setState({
      previewImage: file.url || file.thumbUrl,
      previewVisible: true,
    });
  }

  uploadFile = (file) => {

    const uploader = new Slingshot.Upload(Session.get('lowerCaseContext'));
    const image = file
    uploader.send(image, function(error, url) {
      if (error) {
        throw new Meteor.Error('upload-file-fail', error);
      } else {

        var urlFirstPart = url.substring(0, url.lastIndexOf('/') + 1);
        var urlLastPart = url.substr(url.lastIndexOf('/') + 1)
        url = urlFirstPart + encodeURIComponent(urlLastPart);
        const file = {
          url: url,
          // fileName: image.name,
        }

        return file;
      }
    });
  }

  handleChange = ({ fileList }) => this.setState({ fileList })

  render() {
    const { previewVisible, previewImage, fileList } = this.state;
    const uploadButton = (
      <div>
        <Icon type="plus" />
        <div className="ant-upload-text">Upload</div>
      </div>
    );
    return (
      <section>
        <Upload
          name="uploadFile"
          data={this.uploadFile}
          listType="picture-card"
          fileList={fileList}
          onPreview={this.handlePreview}
          onChange={this.handleChange}
        >
          {fileList.length >= 3 ? null : uploadButton}
        </Upload>
        <Modal visible={previewVisible} footer={null} onCancel={this.handleCancel}>
          <img alt="example" style={{ width: '100%' }} src={previewImage} />
        </Modal>
      </section>
    );
  }
}

export default connectField(UploadImage);
```

Here are the _relevant_ parts I have in the schema...

```
const FileSchema = new SimpleSchema({
  url: {
    type: String,
    optional: true,
  },
  // fileName: {
  //   type: String,
  // },
});

export const schema = new SimpleSchema({
...
image: {
    type: FileSchema,
    uniforms: {
      component: UploadImage,
    },
    optional: true
  },
...
```

Then I use it in the form like this...
`<AutoField name="image" />`

![image](https://user-images.githubusercontent.com/16330002/29263294-83b0c562-811b-11e7-9218-02d0b5b9097e.png)

After selecting an image to upload, it successfully gets uploaded to S3, and I can see the preview on the form, but after I click to submit the form, I get this error...

> Exception from Tracker recompute function:
> Cannot read property '_currentElement' of null
>     at ReactCompositeComponentWrapper._updateRenderedComponent (printer.js:170)
>     at ReactCompositeComponentWrapper._performComponentUpdate (printer.js:170)
>     at ReactCompositeComponentWrapper.updateComponent (printer.js:170)
>     at ReactCompositeComponentWrapper.receiveComponent (printer.js:170)
>     at Object.receiveComponent (printer.js:170)
>     at ReactCompositeComponentWrapper._updateRenderedComponent (printer.js:170)
>     at ReactCompositeComponentWrapper._performComponentUpdate (printer.js:170)
>     at ReactCompositeComponentWrapper.updateComponent (printer.js:170)
>     at ReactCompositeComponentWrapper.performUpdateIfNecessary (printer.js:170)
>     at Object.performUpdateIfNecessary (printer.js:170)

If I check the document in the collection, the 'image' portion is not there at all.
![image](https://user-images.githubusercontent.com/16330002/29263368-c42298dc-811b-11e7-94e2-8a3ff48df5b0.png)

Any help would be very much appreciated.
Thank you

**Comment by radekmie** [comment]
I've read it few times and I'm not sure, where that React error comes from. About the _empty model_ - it is empty, because your field should call `onChange` to populate it.

**Comment by serkyen** [comment]
I suspected that was the issue...I have a problem though.

Where this way was working (the way without antd), you can see the id, value, onChange and name are brought in as props...

```
const UploadField = ({id, value, onChange, name,
  // ...props
}) =>

  <section>
      <input type="file"
        name="uploadFile"
        onChange={event => uploadFile(event, onChange)}
      />

      <img width="150" src={value.url} />
      <p>{value.name}</p>
  </section>
;
```

How can I bring these props in to the new component (which I posted in my initial question), because it is a different type of component? Where do I declare these props?

Sorry, I know this is more of a React question.

**Comment by serkyen** [comment]
Ok I have got it working now. 
Thank you for pointing me in the right direction.

**Comment by krish512** [comment]
@serkyen can you share your updated working code?
