### ISSUE TITLE
How would I go about hiding the submit button in a form and triggering onsubmit?

### ISSUE THREAD

**Issue by steve-ross** [vazco/uniforms#331]
I'm trying to put a form in a dialog and want to use the dialog buttons instead of the built in form submit button. Any way to pull this off?

**Comment by radekmie** [comment]
Hi @steve-ross. Yes, it is possible in two steps:
1. Use empty submit button (check out `submitField` prop) or use `<AutoFields />` instead.
2. Use `ref` to receive form ref and trigger `form.submit()` manually.

[Form `ref` docs](https://github.com/vazco/uniforms/blob/master/API.md#baseform).
[Form `submitField` docs](https://github.com/vazco/uniforms/blob/master/API.md#quickform).

**Comment by steve-ross** [comment]
@radekmie I can't seem to get this to work using an auto form and a ref... seems to work with baseform but then I'd have to manually handle all the validation errors, right? Is it supposed to work on AutoForm?

**Comment by steve-ross** [comment]
also when i make it a 'baseform' I can't type into any of the fields :/

**Comment by steve-ross** [comment]
Got the ref to submit the form using validatedform but, still can't type into the form fields or make a selection in a drop down. Really strange.

Here is a screen cast of the un-clickable form inputs:

http://d.pr/i/5Bjnqc/3JKSYkNJ

**Comment by steve-ross** [comment]
Nevermind... for some reason i switched back to autoform and its working now

**Comment by radekmie** [comment]
About that _un-inputable-inputs_ - only `<AutoForm />` handles the form - in every other form you have to do it manually with `onChange` and `model`.

**Comment by steve-ross** [comment]
FYI for anyone who might find this ticket... this is more helpful than the link to 'refs': https://github.com/vazco/uniforms/blob/master/INTRODUCTION.md#methods

**Comment by steve-ross** [comment]
@radekmie Starting on a new project and getting a weird result when using a ref... I see the promise but, it never resolves. Any ideas? I literally copied my code from another project and updated react / uniforms etc and it doesn't work.

**Comment by steve-ross** [comment]
@radekmie nevermind. Figured out that if you don't pass required params to the meteor method it silently fails. 👎

**Comment by radekmie** [comment]
@steve-ross what do you mean by required params? It would rather fail with an error, because you tried to do something with that param.

About that promise - is it still happening?
