### ISSUE TITLE
Material ui stepper and Files (Images) storage with meteor file

### ISSUE THREAD

**Issue by danyhiol** [vazco/uniforms#332]
I have a collection with `node simpl schema`. In this collection, I have an image and video fields of type array for storing images file. I'm trying to find a way to do this using `uniforms` and `Meteor file` but have not found any.

```
imageLink: {
  type: Array,
  regEx: SimpleSchema.RegEx.Url,
},
"imageLink.$":{
  type: String
},
videoLink: {
  type: Array,
  regEx: SimpleSchema.RegEx.Url,
},
"videoLink.$":{
  type: String
}
```

The second problem I'm facing is how to used` material ui` `stepper` with this module? Is that even possible? Since you can't define separate instances of the same `AutoForm` with different fields.

```
getStepCntent(stepIndex) {
  switch (stepIndex) {
    case 0:
      return <AutoForm schema={ shema }> field2, field2</AutoForm>;
    case 1: 
      return <AutoForm schema={ shema }> field3, field4</AutoForm>;
    default:
      return <AutoForm schema={ shema }> field5, field6</AutoForm>;
    }
}
```
I also want to show inline `error` and stop `stepper` of stepping tho the next stepper if there is an error.
Any help will be more than welcome.

**Comment by radekmie** [comment]
Hi @danyhiol. If you want to receive an answer then ask some questions. Nobody will write code for you, really. Here are few answers/tips that could help:
* In this case (or in general, a form with steps) can be implemented in many ways (as always). I'd suggest two:
    * Have a separate form and schema for each step.
    * Render the steps within the form and use `<AutoFields />` to render fields.
* For inline errors, use `showInlineErrors` and/or `<ErrorsField />`.

**Comment by danyhiol** [comment]
@radekmie thanks for your response. I never taught of embedding stepper in AutoForm. How about using Meteor file? The problem is that with meteor file, it creates another separate collection and my question is to know if there is a way to link uniforms and Meteor File.

**Comment by radekmie** [comment]
I've never worked with it. It'll probably require a container to fetch this reactive data. There were some file upload examples (even complete solutions) - look for them in the issues.

**Comment by danyhiol** [comment]
I found some solution here using `meteor file`. But i could not find a way to define `stepper` in `AutoForm` since the `getStepContent()` function is define outside `react render()` .
