### ISSUE TITLE
Display checkboxes horizontally instead of vertically

### ISSUE THREAD

**Issue by danyhiol** [vazco/uniforms#333]
Is there a way to have a checkboxes schema displayed in column? 
[] [] [] []
instead of:
[]
[]
[]
[]
I'm using simple schema and AutoFor alway's displaying all checkboxes vertically.

**Comment by radekmie** [comment]
Probably not. Which theme?

**Comment by danyhiol** [comment]
Ohh forgot. Meterial Ui.

**Comment by radekmie** [comment]
[It's rendered using a `<List />` component](https://github.com/vazco/uniforms/blob/master/packages/uniforms-material/src/SelectField.js#L33-L59). I'm not an expert in `material-ui` but it's probably doable with some styling.

**Comment by danyhiol** [comment]
Yes it's a List. `Material ui  **@next**` offer the possibility to used `Grid`. But is not compatible with `uniforms`. 
Another question i've is: can one mix node simple schema options with uniforms?
```
...
uniforms: {
  option: function() {
    if (this.field('FieldName').value == "Some String") {
      return [
        {label: "label1", value: "value1"},
        {label: "label2", value: "value2"},
        {label: "label3", value: "value3"},
      ]
    }
}
```
This is not working. Do you have any advice to can give me?

**Comment by radekmie** [comment]
It's `options`, not `option`.

**Comment by danyhiol** [comment]
Typo error. I'm getting: `Uncaught TypeError: this.field is not a function`.

**Comment by radekmie** [comment]
It's true - [there's no context in this place](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/SimpleSchema2Bridge.js#L164-L183). Please, keep it separated and ask such questions in separate issues or on Gitter.
