### ISSUE TITLE
Uncaught Error: Unsupported field type: Boolean  at invariant 

### ISSUE THREAD

**Issue by cesarve77** [vazco/uniforms#335]
if I use type Boolean in my graphql schema and AutoField i get this error in my browser : 
Uncaught Error: Unsupported field type: Boolean  at invariant 

example: 
```
const type=buildSchema(`
     type SignUp {
         name:          String!
         familyName:    String!
         email:         String!
         password:      String!
         terms:         Boolean!
     }
 # This is required by buildASTSchema
 type Query { anything: ID }
 `).getType('SignUp')


const schema = new GraphQLBridge(type, function (model) { .....
```
example :  

`  <AutoField       name="terms" type='checkbox'  label="I agree to adhere with  terms "/>`

I can solved this problem 
1) Or using Int in the schema
2) or  using CheckBox component instead of AutoField
3) or adding property component=CheckBox in AutoField

Maybe adding this line code to https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/GraphQLBridge.js

can solve the issue

` getType (name) {
        const fieldType = this.getField(name).type;

        if (fieldType instanceof graphql.GraphQLList)            return Array;
        if (fieldType instanceof graphql.GraphQLObjectType)      return Object;
        if (fieldType instanceof graphql.GraphQLInputObjectType) return Object;
        if (fieldType instanceof graphql.GraphQLScalarType) {
            if (fieldType.name === 'Int')    return Number;
            if (fieldType.name === 'Float')  return Number;
            if (fieldType.name === 'String') return String;
        ++if (fieldType.name === 'Boolean') return Boolean;
        }

        return fieldType;
    }
`

**Comment by radekmie** [comment]
I'm surprised that it came out that late. Do you want to submit a PR with it?

**Comment by cesarve77** [comment]
Sure. I will tomorrow i live in Australia and is time to sleep
