### ISSUE TITLE
Missing dependencies in uniforms-bootstrap3

### ISSUE THREAD

**Issue by davidworkman9** [vazco/uniforms#336]
uniforms-bootstrap3 tries to import from fbjs but doesn't declare it as a dependency.

**Comment by radekmie** [comment]
Have you encountered any problems? It's a dependency of React therefore we can use it.

**Comment by davidworkman9** [comment]
Using the beta version of Meteor 1.6 I needed to explicitly install it, I thought it was just an upgrade of uniforms that caused the issue but maybe it's a bug in Meteor.

**Comment by radekmie** [comment]
I'll check it later too.

**Comment by davidworkman9** [comment]
Weird, I tried it again with the latest beta and it's still happening for me.

NPM: v5.3.0
Meteor: v1.6-beta.24
Node: v8.4.0

**Comment by radekmie** [comment]
I have no idea why. I'll keep you updated if something pop out.

**Comment by radekmie** [comment]
Hey, @davidworkman9. I've tested it again, with few npm versions - including Meteor 1.5.2, 1.5.2.2 and 1.6-rc.3 - it's all working. If you are still having (reproducible) problems, we'll try to fix it.
