### ISSUE TITLE
What's your recommendation for multi-selects

### ISSUE THREAD

**Issue by zeroasterisk** [vazco/uniforms#34]
I'm considering wrapping http://alsoscotland.github.io/react-super-select/react-super-select-examples.html#multiselect but my first attmpts have failed.

Again, this should return an array of values... 

How do you setup a schema for this?  `type: [Number]` and `uniform.options` ?

**Comment by radekmie** [comment]
Yes, `type: [something]` and `uniforms.options` is a good way to do it, but you can also use `uniforms.transform` (or `transform` prop directly). Eventually, you'll need to create a wrapper to map values from that select to your desired values.

**Comment by radekmie** [comment]
**tl;dr;**
To have a custom multi-select, you have to create your custom wrapper. If you'll face any problems, comment here, ask me directly or create an issue.

**Longer version**
Multiple selects are a hard topic in general - even Bootstrap and Semantic have no special CSS-only theming for it. Of course, they have alternatives (Semantic have it built-in and there are many community packages to do it in Bootstrap), but they either require jQuery or are very opinionated. I've implemented multi-checkbox _fallback_ to close #33. I think it will cover most cases.
