### ISSUE TITLE
Please update documentation

### ISSUE THREAD

**Issue by vfonic** [vazco/uniforms#340]
Hi,

I really like the idea of uniforms. However. I have a really hard time using the package. Whenever I need something specific, I get stuck and spend hours trying to figure out how to achieve it.

For example: I have an array of objects (SimpleSchema): Something like this:
```js
const PostSchema = new SimpleSchema({
  authors: {
    type: [AuthorSchema],
  },
});
```

I use uniforms-unstyled and want to customize add/remove buttons:
```jsx
<AutoForm model={post} schema={PostSchema} onSubmit={this.handleSubmit}>
  {/* can't find any reference to itemProps in the documentation either */}
  <ListField name="authors" label="Authors" itemProps={{ component: AuthorField }} initialCount={9} />
</AutoForm>
```

I went to https://github.com/vazco/uniforms/blob/master/INTRODUCTION.md and tried to figure out how to use `ListAddField`. But it's only mentioned in a single place. I started digging through the source code, but I still can't figure it out. I'm spending enormous amounts of time trying to figure out something that's probably something simple, but just not documented or I can't find it in documentation.

Can you point me to where I can read more about how to use these components?

I'm willing to help and write documentation myself. But I'll need your help to first figure out how to use the package better. :)

Thanks!

**Comment by radekmie** [comment]
Hey @vfonic! I really appreciate that kind of issues!

Both `ListAddField` and `ListDelField` are kind of special. `ListAddField` have to be a child of `ListField` and used with `name="$"`, because it operates on the last index. `ListDelField` is a _helper_ field that can be used within `ListItemField` and no name (so the same name as the item itself), because it operates on the same index as the item.

I'd love someone to get the documentation both readable and useful. As an author, I'll never know if something is explained enough or in a correct order because I understand it from the other point of view.

If you need more in-detail information, ask here, on Gitter or write me directly.

**Comment by vfonic** [comment]
Can you please briefly explain me how `initialCount` works?

I went through the source code for `ListField`. It uses `initialCount` in a single place:
https://github.com/vazco/uniforms/blob/master/packages/uniforms-unstyled/src/ListField.js#L24
```
<ListAddField name={`${name}.$`} initialCount={initialCount} />
```

So then I looked into `ListAddField` and `initialCount` is not used anywhere:
https://github.com/vazco/uniforms/blob/master/packages/uniforms-unstyled/src/ListAddField.js

But somehow magically, it works. :)
How?

**Comment by vfonic** [comment]
@radekmie Thanks a lot Radosław!

I'll join gitter, I guess the communication will be faster. :)

**Comment by radekmie** [comment]
It's not used by fields, but bridges (can and most of them do) make use of it in `getInitialValue`. For example [`SimpleSchemaBridge#getInitialValue`](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/SimpleSchemaBridge.js#L152-L170).

**Comment by radekmie** [comment]
Hey @vfonic! Are you still working on it? There's another issue for the documentation (in general) and I'd like to make a small cleanup of issues.

**Comment by vfonic** [comment]
Hi @radekmie I'm still using uniforms, but still kind-of "tapping in the dark". :) I don't fully understand/know the API or how is everything connected together, but I'm at the level where I create my own components, by looking at the similar code from existing uniforms components.

I'm really out of time...until maybe mid November, maybe later. Feel free to close this issue if you're keeping track of missing pieces in the documentation somewhere else.

**Comment by radekmie** [comment]
I’ll close it then. You can add your suggestions in #259.
