### ISSUE TITLE
new feature

### ISSUE THREAD

**Issue by cesarve77** [vazco/uniforms#341]
First sorry for my english.

Like on onValidate pass a callback to onSubmitFailure for attach error to form fields after response of the server

e.g.
```
<ValidatedForm  {...props} onSubmitFailure={(err,callback)=>{
        if (isErrorAttachableToAField(err){
                 callback({details: [{name: determineField(err), message: err.message}]})
        }else{
               showGeneralNotification({ message: err.message})
        }
}} />
```

Now is posible just on onValidate function (below code) .
But above code can represent a cleaner code and is suitable for all cases, when is a general error and when the error can be attached to a input element like uniqueID. If i have to handle  both cases in onValidate then onSubmitFailure does not hace much sense.

 

```
<ValidatedForm {...props} onValidate={(model, error, callback)=>{
        const promise = this.saveOnDB(model)
        promise.then((res) => {
            showGeneralNotification({ message: 'success'})
            callback(null)
        }).catch((err) => {
             if (isErrorAttachableToAField(err){
                 callback({details: [{name: determineField(err), message: err.message}]})
        }else{
               showGeneralNotification({ message: err.message})
        }
}) />
```

I'ii happy to contribute por please give me some clues.

**Comment by radekmie** [comment]
It's already on the [roadmap](https://github.com/vazco/uniforms/projects/1):

> Accept rejected promise from `onSubmit` as a validation error.

**Comment by cesarve77** [comment]
Maybe create a method for attach custom errors to the form.
This will solve this issues and others similar cases.

**Comment by radekmie** [comment]
There's no need for such method - you can simply pass your `error` as a prop.

**Comment by cesarve77** [comment]
what do you suggest?

**Comment by radekmie** [comment]
Suggest for what? Right now, you can pass an `error` prop. There's an idea (the roadmap one) to treat rejected `onSubmit` as a validation error.

**Comment by cesarve77** [comment]
never mind, my english is bad and i get confuse

2017-08-29 20:00 GMT+10:00 Radosław Miernik <notifications@github.com>:
