### ISSUE TITLE
SelectField value not being set in submission document

### ISSUE THREAD

**Issue by tab00** [vazco/uniforms#343]
I use a `SelectField` like this:

```
<AutoForm
    schema={Collection1.schema}
    onSubmit={doc => console.log(doc)}
>
    <SelectField name="field1" onChange={(value) => { this.setState({ stateVar: value }) }} value={this.state.stateVar} />
```

`this.state` was initialized in the constructor:
```
  constructor(props) {
    super(props);
    this.state = {
      stateVar: "N",
    };
  }
```

If `field1` is not set as optional in the schema, then validation fails with the "required" error message.
if `optional: true` is set for `field1`, the `console.log` shows no `field1` in the submission document.

How can this problem be fixed?

**Comment by janowsiany** [comment]
Hello @tab00, please see [this comment](https://github.com/vazco/uniforms/issues/299#issuecomment-310189096).
Moreover i would rather pass `field1` value thorugh `model` property on `AutoForm` like:
```js
<AutoForm model={{field1: 'N'}} schema={schema} onSubmit={model => console.log(model)} />
```
so you will not need `value` property on `SampleField`:
```js
<SampleField name="field1" />
```

**Comment by tab00** [comment]
But if I insist on using `value` on the field instead of passing `model` into the `AutoForm` then shouldn't it just work? Is this a bug that should be fixed?

**Comment by tab00** [comment]
Another problem is that for `SelectField`s whose values were not explicitly set, and are not optional, you'd expect their first item values to be included in the submission document, but they don't go through.

**Comment by radekmie** [comment]
@tab00: If you want to use both `value` and `onChange` on field, not `_Form`, then use this field directly, without uniforms. About that `SelectField`: there's `defaultValue` for such cases.

**Comment by tab00** [comment]
> If you want to use both value and onChange on field, not _Form, then use this field directly, without uniforms.
Can I use `onChange` without `value`, yet still have the `SelectField` value and text change to the selected item (as intuitively expected)?

I want to use uniforms for the connection with my existing schemas for validation etc..

> About that SelectField: there's defaultValue for such cases.
What if we don't know in advance what any of the values are going to be (as they may come from the database)? The user is going to naturally think that the first item that is displayed in the dropdown list is the selected one. So that should be the one that goes through when the user presses Submit. At the moment it doesn't.

**Comment by radekmie** [comment]
If you pass `onChange` to a field, then your form won't know about it - only one `onChange` callback can be passed to it.

Then use `model`.

**Comment by tab00** [comment]
Let's forget about `onChange` for the moment. Why aren't `SelectField` values being included in the submission document even though they appear selected by default on form load (as they were the first items in each list)?

**Comment by tab00** [comment]
Select values and labels can be obtained from the database and mapped to an options array:

`const optionsArray = this.props.items.map(item => ({ value: item._id, label: item.name }))`

and then passed into a `SelectField`:

```
<AutoForm
  schema={schema}
  onSubmit={doc => console.log(doc)}
>
  <SelectField name="itemId" options={optionsArray} />
```

If the field `itemId` is not optional in the schema, the first item in the array will appear selected on the form.

After pressing Submit (without changing the selection), that value should be included in the submission document, but it is not. Is it a bug?

**Comment by radekmie** [comment]
If it's a required field, then submit should fail. If it's not, then your schema `clean` provides some value there. By default schema is cleaned before validation - are you cleaning it after submit too?

**Comment by tab00** [comment]
>If it's a required field, then submit should fail.

Yes, submission was failing with "Required" error messages, so I added `optional: true` in the schema to all the fields that caused the errors in order to see the submission document contents. But those errors should not occur if the first items in the dropdown list had been selected (which happens by default on form load).

Without `optional: true` in the schema, the first items in each `SelectField` is a real item, not "Please select one" or anything like that. So there should be no "Required" error messages.

**Comment by tab00** [comment]
I've just made a new minimal app to reporduce the error:

```
import React, { Component } from 'react';
import { Meteor } from 'meteor/meteor';

class App extends Component {
    handleSubmit(doc) {
        console.log(doc)
    }

    render() {
        import { AutoForm, AutoField, SelectField, HiddenField, LongTextField, SubmitField, ErrorsField } from 'uniforms-bootstrap4';

        const optionsArray = [{ label: "label 1", value: "value 1" }, { label: "label 2", value: "value 2" }]

        return (
          <div className="container">
          <AutoForm
                schema={itemsSchema}
                onSubmit={doc => this.handleSubmit(doc)}
            >
                <SelectField name="itemId" options={optionsArray} />

                <ErrorsField />

                <SubmitField />
            </AutoForm>
            </div>
        )
    }
}


import { createContainer } from 'meteor/react-meteor-data';
export default createContainer((props) => {
    return {}
}, App)


import SimpleSchema from 'simpl-schema'
const itemsSchema = new SimpleSchema({
    itemId: {
        type: String,
    },
});
```

Please reopen this issue, as it was closed prematurely.

**Comment by radekmie** [comment]
Well, it's because some themes (namely `uniforms-antd` and `uniforms-material`) are handling `undefined` differently - it's an intermediate state. In other themes `undefined` selects first option. I still don't get why you don't want to use `model`?

OK, I'll reopen.

**Comment by tab00** [comment]
> I still don't get why you don't want to use model?

Because it should just work with simple and straightforward code as shown above.

If there is only one item in the dropdown list then the form can never be submitted, even though the one and only item appears selected. This is a more serious problem than if there are multiple items, as when there are at least 2 items the user can select the other item, then back to the first to get the form to submit.

**Comment by radekmie** [comment]
> Because it should just work with simple and straightforward code as shown above.

That's not how it works.

[Here's](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/SimpleSchemaBridge.js#L152-L170) the code, which calculate the initial value of a field within SimpleSchema. As you can see, there's no connection between `props` and this value (excluding `initialCount`). I don't think it makes sense to make `defaultValue` or `initialValue` work from `props`.

`SelectField` in bootstrap, semantic and unstyled have no intermediate state - it's a fact, even a bug. You'd like to think about it? I'd love to see a PR for it, really.

**Comment by radekmie** [comment]
Let's make it clear: it's all about no intermediate state in few themes (including the native `<select>` tag). I'll close it as if the theme (or browser) does not support such feature, we shouldn't try to fake it anyhow. As a workaround, I'd suggest an _empty string means no value_ solution but it's not good in some cases - in such cases you have to think out something else.

**Comment by kletkeman** [comment]
This is closed ... but just in case someone comes surfing through as I did ...

I solved the rather unpleasant "initial value" behaviour by adding pushing a string to the front of the array and then implementing a custom check and error message ...

Schema entry:
```
 const getScriptNames = () => {
    const names = Scripts.find().fetch().map(s => s.name);
    return ["please select a script ..."].concat(names);
 }

... and then ...

    "script": {
        type: String,
        allowedValues() {
            const names = getScriptNames(); // just returns array of names from a collection
            return names;
        },
        uniforms: {
            disabled: false,
            checkboxes: false,
            id: "selectfield", // I use this as a trick for easy pseudo-class-like styling
        },
        custom: function() {
            if (this.isSet) {
                if (!this.value || this.value === "please select a script ...") return "selectScript";
            }
            return true;
        }
    },

... and finally (all in the same file) ...

TasksSchemaEdit.messageBox.messages({
    en: {
        selectScript: 'A script must be selected',
    },
});
```
This pretty much just works to replace that behaviour with something that looks completely normal ...
