### ISSUE TITLE
defaultValue in schema prevents HiddenField value from being set in submission document

### ISSUE THREAD

**Issue by tab00** [vazco/uniforms#344]
I was finding that some `HiddenField` values were not being included on form submission, whereas other `HiddenField` values were.

I examined the schema field definitions and found that when I removed `defaultValue` from the schema field definitions they became included in the submission document.

Please fix this so that `defaultValue` in the schema does not cause this problem.

**Comment by radekmie** [comment]
Could you provide a reproduction? Any `defaultValue` should not be used, as `HiddenField` is designed to work with provided `value` prop.

**Comment by tab00** [comment]
I've just tried it again in my main app to make sure that this is a real error, and I was able to reproduce it again. just that one line in the schema field definition really made the difference. The error actually was not a client-side "Required", but a server-side "Required". But looking at the submission document in the console, the field key and value was not in it when `defaultValue` was used in the schema, and existed when `defaultValue` was removed.

The strange thing though is that I have not been able to reproduce this yet in a new minimal app. Maybe there is some other interference.

**Comment by tab00** [comment]
The schema field definition:
```
    isCredited: {
        type: Boolean,
        //defaultValue: false, //defaultValue was preventing uniforms from including this in submission document
        autoform: {
            omit: true
        }
    },
```

The JSX:
```
                  <HiddenField name="isCredited" value={false} />
```

**Comment by radekmie** [comment]
I'll close it then. If you'll be able to reproduce, we'll reopen it.
