### ISSUE TITLE
Textfield type="password" not working for antd style

### ISSUE THREAD

**Issue by purplecones** [vazco/uniforms#345]
The `'uniforms-antd/TextField` does not properly pass the `type` prop. See below.

For demonstration, I imported both antd and unstyled versions. The antd does not mask the input field as expected.  

```jsx
import AutoForm from 'uniforms-antd/AutoForm';
import TextField from 'uniforms-antd/TextField';
import TextField2 from 'uniforms-unstyled/TextField';

<AutoForm schema={loginFormSchema} onSubmit={submitLogin}>
 <TextField name="email" />
 <TextField name="password" type="password" />
 <TextField2 name="password" type="password" />
 <SubmitField>Submit</SubmitField>
</AutoForm>
```
![2017-09-11 10 40 16](https://user-images.githubusercontent.com/136654/30280410-aa704754-96dd-11e7-8bd2-f68494630c6b.gif)

**Comment by radekmie** [comment]
Yep, it's filtered with `filterDOMProps`. Would you submit a PR for it?

**Comment by purplecones** [comment]
Looks like the the transpiled files were not updated. 

```javascript
// uniforms-antd/Textfield.js | lines 33 - 45
var Text = function Text(props) {
    return (0, _wrapField2.default)(props, _react2.default.createElement(_input2.default, (0, _extends3.default)({
        disabled: props.disabled,
        id: props.id,
        name: props.name,
        onChange: function onChange(event) {
            return props.onChange(event.target.value);
        },
        placeholder: props.placeholder,
        // missing 'type' prop here 
        ref: props.inputRef, 
        value: props.value
    }, (0, _filterDOMProps2.default)(props))));
};
```

**Comment by radekmie** [comment]
Yep, my fault. I've published fixed `1.20.3`. Sorry!

**Comment by purplecones** [comment]
All good now! thanks

**Comment by jchristman** [comment]
I believe I'm having this same issue in uniforms-material, but I can't for the life of me figure out why. I don't think it's filtered by filterDOMProps based on my reading of the code, but the screenshots below show that it's somehow getting filtered out...

<img width="1440" alt="screen shot 2018-06-10 at 12 08 29 am" src="https://user-images.githubusercontent.com/4226546/41198256-456a0746-6c43-11e8-982e-4b0b16b8ebf2.png">
<img width="1440" alt="screen shot 2018-06-10 at 12 08 43 am" src="https://user-images.githubusercontent.com/4226546/41198257-4575d1fc-6c43-11e8-84e3-bf084d988891.png">

I'm using the following code to generate the form:

```js
import React from 'react';
import Autoform from 'uniforms-material/Autoform';
import TextField from 'uniforms-material/TextField';
import SubmitField from 'uniforms-material/SubmitField';

import { LoginSchema } from '/lib/schemas.js';

const onSubmit = (doc) => {
  Meteor.loginWithPassword(doc.email, doc.password, (err) => {
    if (err !== undefined) {
      console.log(err);
    } else {
      console.log('Login success! Redirect!');
    }
  });
};

const Login = (props) => (
  <div className='login-modal'>
    <Autoform schema={LoginSchema} placeholder={true} label={false} onSubmit={onSubmit}>
      <TextField name='email'/>
      <TextField name='password' type='password'/>
      <SubmitField/>
      <p>Don&apos;t have an account? <a href='/signup'>Register</a></p>
    </Autoform>
  </div>
);

export default Login;
```

**Comment by jchristman** [comment]
Thanks for the quick add for that! Much appreciated!

**Comment by ziedmahdi** [comment]
Hi,

This is may not be the same issue as described above but it's definitely similar.

On https://uniforms.tools if you check the example forms and type something in the password field, the text is shown or it should be hidden.

![image](https://user-images.githubusercontent.com/5032634/65779696-28318000-e140-11e9-9897-6f294be8f0b0.png)

Is this intentional?

Thank you.

**Comment by radekmie** [comment]
Hi @ziedmahdi. No, it's not intentional - it's a bug. Thanks for the report, we'll get to it soon.

**Comment by alihuber** [comment]
Cloud it be that this issue reappeared? This is happening to me with semantic and uniforms-bridge-simple-schema-2, v3.6.1:

<img width="1136" alt="Bildschirmfoto 2021-10-05 um 20 03 16" src="https://user-images.githubusercontent.com/1455187/136078252-7818152c-5834-404c-a472-88427f5bc8df.png">

<img width="959" alt="Bildschirmfoto 2021-10-05 um 20 02 56" src="https://user-images.githubusercontent.com/1455187/136078390-36bb273b-6098-42a4-8cac-ede0d8176da2.png">

Even on the playground it seems to work with JSONSchema, but not SimpleSchema, regardless of the chosen theme.

**Comment by wadamek65** [comment]
Hi @alihuber ,

Thanks for your comment. It does indeed seem like the same problem is present in simple schema bridges. I've managed to write a test to reproduce this bug and filed an issue for it here: https://github.com/vazco/uniforms/issues/1039 If you have any other remarks please post them there.
