### ISSUE TITLE
Changing Bootstrap3 Autoform props causes fields with falsy values to be disabled

### ISSUE THREAD

**Issue by BudgieInWA** [vazco/uniforms#347]
I am using a Bootstrap3 AutoForm in meteor, inside a container.

When I construct an `AutoForm` with props `{disabled: true, model: undefined, ...}` then change the props to `{disabled: false, model: {...}, ...}`, all truthy fields are rendered enabled and all falsy fields are rendered disabled. React Dev Tools reports that the `AutoField` and the `TextField` (or `BoolField`, etc.) sees `this.context.uniforms.state.disabled` as false, but the `Text` (or `Bool`, etc.) sees it as true.

This does not happen when the `disabled` prop is not provided to the AutoForm at all, but the model still changes.

For those who know the meteor ecosystem, and to show context, here is Meteor setup:

```
MyComponent = ({doc}) => <AutoForm disabled={doc === undefined} model={doc} schema={mySchema} />;

MyContainer = createContainer(({_id}) => 
  Meteor.subscribe('myCollectionItem', _id);
  return {
    doc: MyCollection.findOne(_id),
  };
});
```

Also, the document might already be subscribed to by some other part of my app when MyContainer is used. This leads to two possible paths for rendering the form:

1. MyComponent is created with props `{ doc: undefined }` then the props are updated to `{ doc: {...} }`. This happens when the the doc was not previously subscribed to, so the doc is not found on the first run.
1. MyComponent is created with props `{ doc: {...} }` in the first place. This happens when the doc was already subscribed to.

When I navigate to a page with MyComponent from another page that subscribes to the doc, the form is rendered with all fields enabled. When I refresh the page, the form briefly renders completely disabled (as expected: we are waiting for the subscription to fill, so `doc` is undefined), then (when the subscription fills  so `doc` is an object) the form renders fields with truthy values enabled and falsy values disabled.

**Comment by radekmie** [comment]
Hi, @BudgieInWA! Thank for such detailed report. I'll definitely take a look at it later.
