### ISSUE TITLE
Support for Material UI v1

### ISSUE THREAD

**Issue by cvburgess** [vazco/uniforms#349]
When using Uniforms-Material with a Material-UI v1 project I get the following error.

`Module not found: Can't resolve 'material-ui/RaisedButton' in '.../node_modules/uniforms-material'`

Is there any plan to support Material UI v1?

**Comment by radekmie** [comment]
Is it released already? It's still in beta I think. Right now I'm quite focused on React@16, but yes, it is a plan to support it. Maybe @janowsiany will say something more.

**Comment by janowsiany** [comment]
Yes i am planning to submit this as part of Hacktoberfest so stay tuned. Also if you have something done already then i would be love to see that so we could work it out together. Another question which comes to my mind is what about backward compatibility? I mean migration to material-ui@1.x.x is definately a breaking change for `uniforms-material` package.

**Comment by cvburgess** [comment]
If you need help, please let me know - happy to contribute.

**Comment by cvburgess** [comment]
Any progress on this or ways I can help? My team would really like to see this implemented for a project we are building out. I could open a PR with an initial stab at it if that helps.

**Comment by janowsiany** [comment]
@cvburgess There is an unexpected slippage but i would expect a PR for this at the beginning of the next week.

**Comment by janowsiany** [comment]
@cvburgess you can check progress https://github.com/janowsiany/uniforms/tree/material-ui-next, perfectly if you also give a feedback. I will submit PR here by Tuesday.
Most components are ported already. Some layout issues still need to be fixed. 
If you want to run demo, then you need to:
- remove `muiTheme` from `Application.childContextTypes` and `Application.getChildContext`
- drop `react-tap-event-plugin` dependency

**Comment by cvburgess** [comment]
@janowsiany I'm running into this issue https://github.com/npm/npm/issues/2974 because uniforms uses Lerna. Any idea how i can install your WIP branch?

**Comment by janowsiany** [comment]
@cvburgess Sorry for the delay. I beleive that the easiest way would be to `clone` my fork of uniforms, then `checkout material-ui-next` branch and then in the top directory run `npm install` this way you would be able to install `uniforms-material` as a local package. Check how it is done in demo app.

**Comment by cvburgess** [comment]
@janowsiany I was able to install it locally but I got tons and tons of errors once it got to webpack. When is this supposed to go live?

**Comment by radekmie** [comment]
@cvburgess Definitely not sooner than 1.0.0 release.

**Comment by ipchikin** [comment]
@radekmie Is that possible to install it like npm i -S uniforms-material@next?

**Comment by radekmie** [comment]
@ipchikin no, we do not do pre-releases. However, there surely will be an alpha/beta/rc version.

**Comment by cvburgess** [comment]
@janowsiany - getting some errors with `type: Number` inputs when changing the value: 

```
NumField.js:107 Uncaught TypeError: Cannot read property 'value' of undefined
    at Num.onChange (NumField.js:107)
    at Object.onChange (NumField.js:68)
    at Input._this.handleChange (Input.js:461)
    at Object.executeOnChange (LinkedValueUtils.js:130)
    at ReactDOMComponent._handleChange (ReactDOMInput.js:239)
    at HTMLUnknownElement.boundFunc (ReactErrorUtils.js:63)
    at Object.ReactErrorUtils.invokeGuardedCallback (ReactErrorUtils.js:69)
    at executeDispatch (EventPluginUtils.js:83)
    at Object.executeDispatchesInOrder (EventPluginUtils.js:106)
    at executeDispatchesAndRelease (EventPluginHub.js:41)
```

Great work on the update so far!

**Comment by cvburgess** [comment]
Also, when passing `options` via SimpleSchema2 the following React error occurs:

```
warning.js:33 Warning: Unknown prop `options` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by FormControl)
    in FormControl (created by withStyles(FormControl))
    in withStyles(FormControl) (created by TextField)
    in TextField (created by Select_)
    in div (created by Grid)
    in Grid (created by GridWrapper)
    in GridWrapper (created by withStyles(GridWrapper))
    in withStyles(GridWrapper) (created by Select_)
    in Select_ (created by Select_Field)
    in Select_Field (created by AutoField)
    in AutoField (created by AutoValidatedQuickMaterialForm)
    in form (created by AutoValidatedQuickMaterialForm)
    in AutoValidatedQuickMaterialForm (created by SlaDetail)
    in div (created by Paper)
    in Paper (created by withStyles(Paper))
    in withStyles(Paper) (created by SlaDetail)
    in div (created by Grid)
    in Grid (created by GridWrapper)
    in GridWrapper (created by withStyles(GridWrapper))
    in withStyles(GridWrapper) (created by SlaDetail)
    in div (created by Grid)
    in Grid (created by GridWrapper)
    in GridWrapper (created by withStyles(GridWrapper))
    in withStyles(GridWrapper) (created by SlaDetail)
    in div (created by SlaDetail)
    in SlaDetail (created by _class)
    in _class (created by withStyles(_class))
    in withStyles(_class) (created by RouterContext)
    in div (created by Main)
    in Main (created by BranchedMain)
    in BranchedMain (created by RouterContext)
    in div (created by UserDataPreloader)
    in UserDataPreloader (created by _class)
    in _class (created by RouterContext)
    in div (created by App)
    in div (created by App)
    in App (created by _class)
    in _class (created by withStyles(_class))
    in withStyles(_class) (created by RootedStyle)
    in RootedStyle (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in MuiThemeProvider (created by MuiThemeProviderWrapper)
    in MuiThemeProviderWrapper
```

**Comment by TimoRuetten** [comment]
Hm its sad that you don't prerelease it. We are currently using 1.0 of material ui in our project. Sadly its not possible to use uniform yet. It would be nice if you would provide a doc how to add custom themes. With this everyone could build own themes easily.

**Comment by radekmie** [comment]
@TimoRuetten: a custom theme is simply a set of your fields. Simply copy one of the default ones and fill your own components.

**Comment by TimoRuetten** [comment]
Hm. You're right. I was thinking of AutoForm from meteor which had its own API for own themes as far as I remember. I will check it out and will check if its faster for us to do it this way. Thanks :)

**Comment by radekmie** [comment]
Theres no need for such API as you’ll use components directly or through `<AutoField />`.

**Comment by ipchikin** [comment]
@radekmie Is there an alpha/beta/rc version now?

**Comment by radekmie** [comment]
No, material-ui is still in beta.

**Comment by mattblackdev** [comment]
ahhhh this is so exciting!! :)

**Comment by titeya** [comment]
For testing with the v1.0.0-rc.0 release :
[https://www.npmjs.com/package/uniforms--material-ui](https://www.npmjs.com/package/uniforms--material-ui)

**Comment by raedle** [comment]
@titeya Thanks for sharing. I added a PR to fix issue with arrays/lists in AutoForm
