### ISSUE TITLE
React 16: Invalid value for prop `transform` on <div> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM.

### ISSUE THREAD

**Issue by davidworkman9** [vazco/uniforms#350]
Since upgrading to React 16 I now get the following error on AutoFields with a transform prop:

`Invalid value for prop 'transform' on <div> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM.`

**Comment by radekmie** [comment]
Hello. Integration with React 16 is of course planned - thanks for the report. Which component and theme gives you this warning?

**Comment by davidworkman9** [comment]
So far this is the only issue I've ran into! It's the AutoField component with bootstrap 3.

**Comment by zeroasterisk** [comment]
@radekmie I've been thinking about changing `filterDOMProps` to a whitelist vs. a blacklist -- you'd have to register any other keys you want to pass through... it'd be a breaking change, but i think much cleaner --- I ended up with a LOT of these warnings to try to cleanup, because `wrapField` (etc) puts the whole `filterDOMProps(props)` into a `<div>`

**Comment by radekmie** [comment]
@zeroasterisk I disagree - in my cases I’d have to register hundreds of props per app as in many places fields are simply wrappers.

**Comment by zeroasterisk** [comment]
fair enough

**Comment by vfonic** [comment]
I just upgraded to React 16 and I'm seeing the same error now. Here's the component I'm rendering:

```jsx
             <RadioField
               name="_showPremium"
               className="input-row"
               allowedValues={[false, true]}
               transform={v => [<span key={v} />, (v ? 'Premium' : 'Free')]}
             />
```

**Comment by radekmie** [comment]
Nice found @vfonic! Could you file a PR with this fix?

**Comment by vfonic** [comment]
I hope I understood correctly what you meant. (Edited the file through github UI, relying on CI for tests :) )
https://github.com/vazco/uniforms/pull/399

**Comment by radekmie** [comment]
Exactly what I meant.
