### ISSUE TITLE
SelectField inside ListField

### ISSUE THREAD

**Issue by xbklairith** [vazco/uniforms#352]
I try to make SelectField inside  ListField(Array) but it's doesn't work
Is is possible to declare schema like below ?
```javascript
...
     playsong: {
        type: Array,
        defaultValue: 'goodsong.wav',
        minCount: 1,
        maxCount: 3,
        allowValues: ['music1.mp3', 'goodsong.wav', 'saygoodbye.wav']
    },
...
```

**Comment by janowsiany** [comment]
Hey, check this schema:
```js
size: {
    type: [String],
    defaultValue: 'goodsong.wav',
    allowedValues: ['music1.mp3', 'goodsong.wav', 'saygoodbye.wav'],
    minCount: 1,
    maxCount: 3
}
```
If you will encounter any other related issues please respond here. Until then i am closing.

**Comment by xbklairith** [comment]
@janowsiany 
Still not work
`type: [String]` and `allowedValues` seem to be conflicted in rendering.

**Comment by janowsiany** [comment]
Could you confirm you are using `uniforms-antd`? Also check [this tool](https://uniforms.tools/) if you can reproduce this there!

**Comment by xbklairith** [comment]
@janowsiany
I have checked already, also not work in demo.
and looking into source code.

https://github.com/vazco/uniforms/blob/2d411706f59cab485b25fcc46237dea01f28c8f1/packages/uniforms-antd/src/AutoField.js#L25

``` javascript
if (props.allowedValues) {
    if (props.checkboxes && props.fieldType !== Array) {
        props.component = RadioField;
    } else {
        props.component = SelectField;
    }
} else {
    switch (props.fieldType) {
        case Date:    props.component = DateField; break;
        case Array:   props.component = ListField; break;
        case Number:  props.component = NumField;  break;
        case Object:  props.component = NestField; break;
        case String:  props.component = TextField; break;
        case Boolean: props.component = BoolField; break;
    }
    invariant(props.component, 'Unsupported field type: %s', props.fieldType.toString());
}
```
if `allowedValues` and `Array` are passing into `AutoFrom` then a component will render `SelectField`  instead of `ListField` as expected.

**Comment by janowsiany** [comment]
@xbklairith Please share your schema and specify if you are using `SimpleSchema` or `SimpleSchema2` also which theme package you are using. Are you encountering some specific error, check the console?
Those are correct schemas whic work in [here](https://uniforms.tools/):
```js
new SimpleSchema({
    playsong: {
        type: [String],
        defaultValue: 'goodsong.wav',
        allowedValues: ['music1.mp3', 'goodsong.wav', 'saygoodbye.wav'],
        minCount: 1,
        maxCount: 3
    }
})
```
```js
new SimpleSchema2({
    playsong: {
        type: Array,
        minCount: 1,
        maxCount: 3
    },
    'playsong.$': {
        type: String,
        allowedValues: ['music1.mp3', 'goodsong.wav', 'saygoodbye.wav']
    }
})
```
