### ISSUE TITLE
SimpleScheme create SelectField with label and value

### ISSUE THREAD

**Issue by DanielLourie** [vazco/uniforms#356]
idType: {
      type: String,
      defaultValue: '',
      allowedValues: ["test1", "test2"]
    }

Trying to create for example the value "1" to be returned/submitted if "test1" is selected in the dropdown. 

Cant get it working with AutoFields

thanks

**Comment by radekmie** [comment]
Then you should use `options` or `transform`: [API](https://github.com/vazco/uniforms/blob/master/API.md#selectfield).
