### ISSUE TITLE
"Each child should have a key prop" warning when using React 16

### ISSUE THREAD

**Issue by MacRusher** [vazco/uniforms#359]
In React 16 using field components directly from package results in a warning.

Below stacktrace is for `TextField` from `uniforms-semantic`, but the same warning is thrown for other field components and themes.
```
Warning: Each child in an array or iterator should have a unique "key" prop. See https://fb.me/react-warning-keys for more information.
    in div
    in div (created by Text)
    in Text (created by TextField)
    in TextField (created by Register)
    in div (created by GridColumn)
    in GridColumn (created by Register)
    in div (created by GridRow)
    in GridRow (created by Register)
    in div (created by Grid)
    in Grid (created by Register)
    in form (created by AutoValidatedQuickSemanticForm)
    in AutoValidatedQuickSemanticForm
```

I'm using uniforms@1.21.0 and react@16.0.0

Warning is not thrown when the same field component is loaded directly from app (builded during app build and not by uniforms itself)

It has probably something to do with `babel-plugin-transform-react-inline-elements` used by uniforms.

Related thread: https://github.com/facebook/react/issues/10352

**Comment by radekmie** [comment]
As discussed (and tested) internally: I'll simply remove this plugin.
