### ISSUE TITLE
Creating inline forms

### ISSUE THREAD

**Issue by noahprince22** [vazco/uniforms#361]
Is it possible to create forms like this:

<img width="1104" alt="screen shot 2017-10-29 at 9 00 24 pm" src="https://user-images.githubusercontent.com/4604046/32151620-51c4ddec-bcec-11e7-8122-5402a9faf327.png">

I found the `grid` prop, but that doesn't seem to do what I want. 

If not, what's the best way to still use the uniforms schema and validation and create this form? It looks like if I forked uniforms-bootstrap4 I could edit `wrapField.js` and introduce some of my own props that would make this possible; but I don't want to fork the library if this feature already exists.

**Comment by noahprince22** [comment]
Wrapping the fields in `col` divs seems to have worked. Going to close this. Feel free to comment if there's a more elegant way.

**Comment by radekmie** [comment]
Hello, @noahprince22. It’s perfectly fine to use uniforms with custom layout. And no, you don’t have to fork it - most of projects have a lot of custom fields (many of them do not use any theme at all) - that’s kind of the _elegant way_.
