### ISSUE TITLE
Name prop for NestField is mandatory and should not be.

### ISSUE THREAD

**Issue by LucianHij** [vazco/uniforms#363]
Name prop for NestField is mandatory and should not be.

**Comment by radekmie** [comment]
Why it should not? Maybe you don’t use it in a proper way?

**Comment by LucianHij** [comment]
<ListField name="authors" disabled>   // Additions are disabled...
    <ListItemField name="$" disabled> // ...deletion too
        <NestField disabled={false}>  // ...but editing is not.
            <TextField name="name" />
            <NumField  name="age" />
        </NestField>
    </ListItemField>
</ListField>

This is The example from the documentaion, and here there it is not a name prop on nestfield. If i use it like that i get an error that name prop is required. If I put any name (except name="") i get another error that author.$.<nestFieldName> doesn't exist. For now i have name="" because i don't like to have errors in the console, but I think this should be made optional. Please tell me if i use it wrong, i followed The example from the docs.

**Comment by LucianHij** [comment]
"<ListField name="authors" disabled>  
    <ListItemField name="$" disabled> 
        <NestField disabled={false}> 
            <TextField name="name" />
            <NumField  name="age" />
        </NestField>
    </ListItemField>
</ListField>"

**Comment by LucianHij** [comment]
ListField name="authors" disabled
    ListItemField name="$" disabled
        NestField disabled={false}
            TextField name="name"
            NumField  name="age" 
        NestField
    ListItemField
ListField
I tried to copy paste The example in previous comm... I can't delete The comments.

**Comment by LucianHij** [comment]
`<ListField name="authors" disabled>   // Additions are disabled...
    <ListItemField name="$" disabled> // ...deletion too
        <NestField disabled={false}>  // ...but editing is not.
            <TextField name="name" />
            <NumField  name="age" />
        </NestField>
    </ListItemField>
</ListField>`

This is The example from the documentaion, and here there it is not a name prop on nestfield. If i use it like that i get an error that name prop is required. If I put any name (except name="") i get another error that author.$."nestFieldName" doesn't exist. For now i have name="" because i don't like to have errors in the console, but I think this should be made optional. Please tell me if i use it wrong, i followed The example from the docs.

**Comment by LucianHij** [comment]
Please delete all The comments except the Last one... The git markdown won...

**Comment by radekmie** [comment]
Hi @LucianHij! Thanks for reading docs so thoroughly, really! Indeed, there's a typo in the docs: it should have `name=""`. Why? It's because `<NestField />` kind of _scopes_ fields inside of it. In this very example, it is used as a bypass of `<ListItemField />` `disabled` prop. I'll push an update soon.
