### ISSUE TITLE
BoolField onClick, onChange double call.

### ISSUE THREAD

**Issue by LucianHij** [vazco/uniforms#364]
On `BoolField` if you have a method on `onClick` (i tested on `onClick` and `onChange`), a simple method like 
```js
handleClick() {
        console.log(this.state);
        const currentState = this.state.checked;
        this.setState({
            checked: !currentState
        })
    }
```

The checked prop will always have the same value  because the `BoolField` call the `handleClick` twice.

**Comment by radekmie** [comment]
Why would you do it? If you want to listen to changes of your field, use `onChange` on the form.

**Comment by LucianHij** [comment]
Hmm. The scenario is the following:
I have a checkbox with the function from the comm Called on an event. I need to know if The checkbox is checked because if it is checked a dropdown appear and if its not The dropdown has display none. 

But what i do not understand is if i have onchange event with any function on it, why that function is called twice on one click on the checkbox. It is the normal behaviour?

**Comment by LucianHij** [comment]
But I will try with on Change on the form, but I do not really know how exactly can do this :D... I am New to react-meteor

**Comment by radekmie** [comment]
Then use `onChange={(key, value) => ...}` on your form, store it somewhere and display your dropdown or not. This question was asked already few times, so search for it here or in the Gitter room.

**Comment by LucianHij** [comment]
Yes... But The error with the BoolField still remains :(

**Comment by radekmie** [comment]
I've checked it on the unstyled theme and it called `onClick` once. It might be a problem with your code. If you could provide a reproduction, it would be great.

**Comment by LucianHij** [comment]
```javascript
handleClick() {
        console.log(this.state.checked);
        const currentState = this.state.checked;
        this.setState({
            checked: !currentState
        })
    }
    render() {
        const {model} = this.state;
        const states = this.getOptions(TaskStatesEnum);

        return (
            <Container className="page-container">
                {
                    this.state.error
                        ?
                        <div className="error">{this.state.error}</div>
                        :
                        <AutoForm model={model} schema={ActionSchema} onSubmit={this.onSubmit.bind(this)} ref="form">
                    
                            <AutoField name="title"/>
                            <ErrorField name="title"/>

                            <LongTextField name="description"/>
                            <ErrorField name="description"/>

                            <BoolField value={this.state.checked} name="state" label="Changes the status of the Account?" onClick={this.handleClick}/>
```

This is the code, and on ```onChange``` it doesn't reproduce, but on click it does, in the ```console.log()``` i will have 2 values.

**Comment by radekmie** [comment]
OK, it turned out to be a React thing. I couldn't reproduce it earlier, because I was clicking the box and not the label. Try this code:

```js
<div onClick={event => console.log(event)}>
  <input type="checkbox" id="x" />
  <label htmlFor="x">Label</label>
</div>
```

When you click on the box, you'll see only one event; clicking on the label triggers two - one for input and one for label (check `event.target`).

**Comment by LucianHij** [comment]
Ah, ok then. Thank you very much!
