### ISSUE TITLE
How can we integrate this with Styled Components?

### ISSUE THREAD

**Issue by theodorDiaconu** [vazco/uniforms#367]
I am using this package in almost every app due to its simplicity. I am now exploring the possibility of shifting to styled-components. Do you have any plans of providing support for it?

It would be interesting to make a uniforms-unstyled accept a component prop and instead of using <input> use that passed component. That would not be hard to do, but are there any better ways for this?

**Comment by radekmie** [comment]
Hi @theodorDiaconu. So, on one hand, it's already on the [roadmap](https://github.com/vazco/uniforms/projects/1#card-1085563), on the other - I don't see a need for it. You'd like to pass only the `<input>`, `<label>`, wrapper, all of them? Most of the time, creating own/project theme is the easiest and most suitable option.

**Comment by theodorDiaconu** [comment]
Yes you're right, I can just go ahead and create my own theme and use it in there, it's much more simple than to complicate it with a ton of props.
