### ISSUE TITLE
How to show only inline errors

### ISSUE THREAD

**Issue by vladejs** [vazco/uniforms#368]
After setting my AutoForm component `showInlineError` to true, I keep seeing the block error list at the end. I'm using semantic ui package and this is the definition:
```
<AutoForm
        schema={userSchema}
        onSubmit={submit}
        showInlineError
      />
```
I'm using it outside meteor via `simpl-schema` node package
I made a reproduction deployment and this is the URL to showcase it:

https://out-pzyhgsugtx.now.sh/

**Comment by radekmie** [comment]
Yes, it's correct. If you want to hide the `<ErrorsField>`, either pass custom children - in your case `<AutoFields>` and `<SubmitField>` - or pass `errorsField={() => null}` (or any other component).

**Comment by radekmie** [comment]
It would really complicate this [very simple component](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/QuickForm.js). I don't think that `errorsField={() => null}` is a big change.
