### ISSUE TITLE
Atmosphere.js

### ISSUE THREAD

**Issue by revengelesly** [vazco/uniforms#371]
Thank you very much. I was wondering why this package isn't published on atmospherejs

**Comment by radekmie** [comment]
Hi @revengelesly. One, because it's not only a Meteor package. Two, because:

> With the release of version 1.3, Meteor has full support for npm. In the future, there will be a time when all packages will be migrated to npm, but currently there are benefits to both systems.
> [Source](https://guide.meteor.com/atmosphere-vs-npm.html).
