### ISSUE TITLE
Update to support Antd v3.0

### ISSUE THREAD

**Issue by corymsmith** [vazco/uniforms#372]
Antd 3.0 was just released a couple days ago: https://ant.design/changelog#3.0.0

**Comment by radekmie** [comment]
Hello @corymsmith!

It looks like no big _(very big)_ changes were made. Have you tried it already with `uniforms-antd`?

cc: @Gervwyk

**Comment by corymsmith** [comment]
Had some warnings around `peerDependencies` since its `2.x` but then didn't have time to fully test it out unfortunately.

**Comment by radekmie** [comment]
Would you? It would be great to see, if the only problem is the version constraint.

**Comment by Gervwyk** [comment]
I'll also try updating over the weekend or definitely next week. Will let you know if all goes well.

**Comment by Gervwyk** [comment]
I've tested and all looks well thus far, a few major changes so its definitely a breaking change if you use card and table (might not be a breaking change in form context - will investigate).
Except for importing into meteor. https://forums.meteor.com/t/antd-3-0-is-out/40926/13?u=mrmsupport
I'll recommend waiting from meteor 1.6.1 to fix bug before updating. I'll also continue with testing after 1.6.1. If someone want to try on beta in the mean time, that would be great. I'll have time for it in a week or two, by which 1.6.1 is hopefully up.

**Comment by radekmie** [comment]
Well, the only problem I found was this:

> 🗑 Input's type prop has dropped textarea support, please use Input.TextArea instead.

It's included in `v1.23.0-rc.1`. Check it out and let me know if everything is OK.

**Comment by pozylon** [comment]
I just tested rc.1 with antd 3.1.1 on a fairly complex form, no issues since.
