### ISSUE TITLE
After connectField: __WEBPACK_IMPORTED_MODULE_.moment... is not a function 

### ISSUE THREAD

**Issue by k** [vazco/uniforms#375]
After calling `connectField` on a React component that uses *moment.js* imported by
```js
import moment from 'moment';
```
I get this error in [storybook](https://storybook.js.org/):

```
__WEBPACK_IMPORTED_MODULE_0_moment___default(...)(...).seconds(...).minutes(...).hours(...).date(...).month is not a function
TypeError: __WEBPACK_IMPORTED_MODULE_0_moment___default(...)(...).seconds(...).minutes(...).hours(...).date(...).month is not a function
    at serializableDateToMoment (http://localhost:5000/static/preview.bundle.js:227956:102)
    at http://localhost:5000/static/preview.bundle.js:322834:94
    at MapProps (http://localhost:5000/static/preview.bundle.js:5693:22)
    at http://localhost:5000/static/preview.bundle.js:120085:16
    at measureLifeCyclePerf (http://localhost:5000/static/preview.bundle.js:119855:12)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (http://localhost:5000/static/preview.bundle.js:120084:14)
    at ReactCompositeComponentWrapper._constructComponent (http://localhost:5000/static/preview.bundle.js:120059:21)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:5000/static/preview.bundle.js:119967:21)
    at Object.mountComponent (http://localhost:5000/static/preview.bundle.js:37300:35)
    at ReactCompositeComponentWrapper.performInitialMount (http://localhost:5000/static/preview.bundle.js:120150:34)
```

This worked before using it with `connectField` so it makes me think that there is an bug in `connectField`. Some other relevant info:

1. I'm using it in `uniforms-antd`, `Autoform`
1. I am using vanillajs versions of the repos, not `jsnext` or `module` of both uniforms and uniforms-antd
1. Version of storybook: 3.3.0-alpha.1
1. Storybook .babelrc:
```json
{
    "presets": [
        [
            "babel-preset-env",
            {
                "loose": true,
                "modules": false
            }
        ],
        "babel-preset-react",
        "babel-preset-stage-1"
    ],
    "plugins": [
        "babel-plugin-transform-decorators-legacy",
        [
            "import",
            {
                "libraryName": "antd",
                "style": "css"
            }
        ],
        [
            "babel-plugin-transform-runtime",
            {
                "helpers": false,
                "polyfill": false,
                "regenerator": true
            }
        ],
        "glamorous-displayname"
    ],
    "ignore": [".spec.js", ".test.js", "-test.js", "/__tests__/"]
}

```

**Comment by k** [comment]
Update: 
I noticed the errors only occur when I try to use the options in the second argument of `connectField`

**Comment by radekmie** [comment]
Hi @k. Could you post a code which is working and the one which is not? I'm not sure, what exactly is causing this error, but almost sure that is not the `connectField`.

---

Are you sure, you are using `moment` correctly? According to docs, `.date()` returns a `Number`, but `.date(Number)` a `moment` instance - maybe this is the case? I'm asking because I'm not sure about these `(...)` in your stack trace.

**Comment by radekmie** [comment]
Ping @k.

**Comment by radekmie** [comment]
No response so far; I assume it's working. I'm closing but if it's not working - we'll continue digging in.

**Comment by k** [comment]
So I stopped running into the issue, I think it was because I was using `connectField` incorrectly. I also needed to use `wrapField` inside the render method of the component I was connecting.
