### ISSUE TITLE
All fields get cleared on a graphql subscription update

### ISSUE THREAD

**Issue by tab00** [vazco/uniforms#377]
In a React component I have an AutoForm that displays on top and data below that gets updated from a subscription.

After adding the AutoForm, I noticed that whatever I typed in any of the fields it got cleared when the data was updated.

I then tested by adding a plain HTML `input ` in the AutoForm, as well as another one outside the AutoForm. The one inside kept getting cleared on data update whenever I tried to type in them, whereas the one outside was never cleared.

So there is something happening inside AutoForm that is clearing its own fields.

Here is the `render` code:
```
  render() {
    import { AutoForm, AutoField, SubmitField, ErrorsField } from 'uniforms-unstyled';
    import { Tasks } from '/imports/api/client/Tasks.js';

    const TaskInsertForm = ({ model }) =>
      <AutoForm schema={Tasks.schema} onSubmit={doc => this.handleSubmit(doc)} model={model}>
        <h2>New Task</h2>

        <input type="text" name="fieldInsideAutoForm" />

        <AutoField name="text" />

        <ErrorsField />

        <SubmitField />
      </AutoForm>


    return (
      <div className="container">
            <div>
              <input type="text" name="fieldOutsideAutoForm" />

              <TaskInsertForm />
            </div>

        <ul>
          {this.props.tasksLoading
            ? <div>Tasks loading</div>
            : this.renderTasks()}
        </ul>
      </div>
    );
  }
```

**Comment by radekmie** [comment]
Hi, @tab00. It's because you are creating new `TaskInsertForm` component on each `render` - `<input />` inside has a new parent each time.

**Comment by tab00** [comment]
OK I separated it into two components, which makes more sense, and it's working now. Thank you.
