### ISSUE TITLE
Bootstrap 4 inline errors

### ISSUE THREAD

**Issue by umbra268** [vazco/uniforms#380]
Bootstrap v4 beta 2 has changes to how form validation should occur and the current approach of using has-danger no longer works.

The current version of Bootstrap v4 is beta 3 and it doesn't look like they'll revert to previous behaviour.

While it might be too much of a change to switch to HTML5 validation like bootstrap now perfers, it appears that has-danger can be replaced with is-invalid and the inline error text's class can be changed to invalid-feedback as in the server-side validation example below.
 
More details:
https://getbootstrap.com/docs/4.0/components/forms/#server-side
https://getbootstrap.com/docs/4.0/components/forms/#validation
https://getbootstrap.com/docs/4.0/migration/#forms-1

**Comment by radekmie** [comment]
Hi @umbra268. So they've changed it again. @zeroasterisk?

**Comment by radekmie** [comment]
Anyway, @umbra268 - would you like to send a PR with needed changes? I'm not using Bootstrap theme and I'm even less motivated as they change it in every version (and still no 4.0 release date).

**Comment by radekmie** [comment]
It finally got released! [Source](https://blog.getbootstrap.com/2018/01/18/bootstrap-4/).
