### ISSUE TITLE
Subclassing Validated Form to make a StepForm

### ISSUE THREAD

**Issue by k** [vazco/uniforms#383]
I am looking to make a multi-step form similar to https://preview.pro.ant.design/#/form/step-form/info. I am using a GraphQLBridge, and have successfully made forms using a GraphQLBridge before. Unfortunately I'm having trouble figuring out the partial validation. What I did was subclass AutoForm:

```js
class StepForm extends AutoForm {
    onNext() {
        this.validate(); // This does not update the components with an *error*
         // I want to validate only a subset of the schema here
   }
    render() {
         <Steps {...}>{...}</Steps>
         <this.props.steps[this.state.currentStep] />
        <Button>Next</Button>
    }
    ...
}
```

Unfortunately with the above method I could *not* get the validation to show errors on the antd components *except* when triggering a submit. Triggering a `validate` or manually setting the `error` and `validate` state did not cause the error message to show on the failing component. Does anyone know how to manually trigger the validate?

Alternatively I could have it so the StepForm is not a subclass of BaseForm and instead is a component that swaps out the components in an Auto or ValidatedForm.

Provided they both work, which is the better approach? Or is there a simpler approach that I am not seeing?

**Comment by radekmie** [comment]
Hey, @k. Few things here:
- if you could provide a minimal (or at least small) reproduction of `validate` not working, please do - I’m using it in few places successfully but maybe your case is a corner one
- subclassing `AutoForm` in such case might be not a good choice as the step validation is now somehow bound to this form
- I’d suggest using a series of forms; simply have a set of schemas which will validate separate steps and pass previously submitted model as a base one to the next step - I’ve done similar thing few times and it worked out pretty well

**Comment by k** [comment]
I like the series of forms idea, that seems like it will be much easier to implement.

I have an example pushed to a branch, I'll compile when I time to revisit this since that task was basically refactoring to use uniforms.

**Comment by radekmie** [comment]
So solved.
