### ISSUE TITLE
Automatically trigger loading state on antd button when promise is returned from `onSubmit`

### ISSUE THREAD

**Issue by k** [vazco/uniforms#384]
In order to make the AutoForm more useful, it would be convenient if a promise-like object was returned from `onSubmit`, that the loading state would be triggered on the generated `SubmitField`

**Comment by radekmie** [comment]
Hey @k. It’s easy to do it on your own - either by creating custom form or a very simple wrapper. Also, it makes more sense in some themes than others like unstylish one. Therefore I’d keep it out of the core and let you tailor it to your needs.

**Comment by k** [comment]
That's fair. I recently discovered `AutoFields` which made it a lot easier to fill in the gaps when rendering a `SubmitField` in an `AutoForm` 👍
