### ISSUE TITLE
Minor issue with the 'placeholder' passing props

### ISSUE THREAD

**Issue by Vandell63** [vazco/uniforms#385]
Hey there,
I actually merge the new material ui. So i create custom component with the connectField() but i saw that the 'placeholder' field DO NOT pass from simpleschema like this : 
```
  textField: {
    type: String,
    label: 'Text Field',
    uniforms: {
      component: TextField,
      helperText: 'This is a helper Text',
      leftIcon: 'account_circle',
      placeholder: 'This is the placeholder text for this input',
    },
  },
```
So i replace it by `placeHolder` and add this to the registration `filterDOMProps.register('placeHolder', 'leftIcon');`
Waiting for a minor fix. But it's ok for now :+1:

**Comment by Vandell63** [comment]
I generate all field with only one line of code from the Autoform 'uniforms/unstyled'. I was thinking that all uniforms props from 'simpl-schema2'  will passing down to the children component. 
```
            <AutoForm
              schema={textSchema}
              onSubmit={this.onSubmitForm}
              showInlineError
              ref={(testForm) => {
                this.testForm = testForm;
              }}
              errorsField={() => null}
              submitField={() => <button type="submit" className="hide" />}
            />
```
Then with `connectField` get back the 'placeholder' props to my TextField attribute. Do i missed something ? or maybe missing to had 'placeholder' to the register ?

**Comment by radekmie** [comment]
By default, placeholders are disabled. Simply pass `placeholder={True}` or simpler `placeholder` and that's all. [API](https://github.com/vazco/uniforms/blob/master/API.md#baseform).

**Comment by Vandell63** [comment]
Oh sry did'nt see this ! Thx you :) :+1:
