### ISSUE TITLE
allowedValues error in react 15.6 and 16.2

### ISSUE THREAD

**Issue by jasperswart** [vazco/uniforms#389]
Warning: React does not recognize the `allowedValues` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `allowedvalues` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

I have only tested this issue with json-schema. 

If I change in getProps:

        const ready = {
            allowedValues,
            ...(fieldType === 'number' ? {decimal: true} : {}),
            options: opts || options,
            label: label === true ? fieldName.charAt(0).toUpperCase() + fieldName.slice(1).toLowerCase() : label || '',
            required: isRequired
        };

into 

        const ready = {
            allowedvalues: allowedValues,
            ...(fieldType === 'number' ? {decimal: true} : {}),
            options: opts || options,
            label: label === true ? fieldName.charAt(0).toUpperCase() + fieldName.slice(1).toLowerCase() : label || '',
            required: isRequired
        };

it is fixed

**Comment by radekmie** [comment]
Hi @jasperswart, sorry for the delay. It's a problem with a custom field or a builtin one?

Also, ping @janowsiany.

**Comment by janowsiany** [comment]
I will check it by the weekend.

**Comment by janowsiany** [comment]
@jasperswart i can not reproduce this with demo app. Could you provide the schema which causes this message? It would be cool if you could provide more details like which theme are you using, or if it is a custome field, can you share the code?

**Comment by radekmie** [comment]
Ping @jasperswart.

**Comment by radekmie** [comment]
No response so far, closing.
