### ISSUE TITLE
Graphql playground not working

### ISSUE THREAD

**Issue by sabativi** [vazco/uniforms#390]
When choosing graph on the playground https://uniforms.tools/, I get a white screen.

chrome console shows : 
![screen shot 2018-02-09 at 12 58 55](https://user-images.githubusercontent.com/2357779/36026835-173c5eb8-0d99-11e8-976c-e283fc62ac66.png)

**Comment by radekmie** [comment]
Thanks @sabativi. I'm into it.

**Comment by radekmie** [comment]
Fixed.
