### ISSUE TITLE
Difficulties to load data into SelectField with GraphQL

### ISSUE THREAD

**Issue by danilomiranda** [vazco/uniforms#394]
I'm  having difficulties to load data into SelectField from another collection using GraphQL Schema.
@radekmie there's some tutorial that cover this? I can't find it.

I defined tha query `patients` in resolver, schema and refer it to SelectField, I got the follow error: 
```Uncaught TypeError: Cannot read property 'map' of undefined`.```

**Comment by radekmie** [comment]
Hi @danilomiranda. No, there's no such tutorial. All you should care about it the `allowedValues` property - simply pass an array there and it'll work.

**Comment by danilomiranda** [comment]
But I need to load those allowedValues from DB, how can I do that?

**Comment by radekmie** [comment]
Pass an empty array at the beginning, load them and pass as a prop when loaded.

**Comment by danilomiranda** [comment]
I'll try it. Thanks
