### ISSUE TITLE
Bootstrap4 radio inline option has no effect

### ISSUE THREAD

**Issue by ChristopherLivett** [vazco/uniforms#397]
When creating a component with <RadioField name="myField" inline /> and a set of allowedValues in the schema, it is being displayed horizontally rather than vertically.

This can be reproduced on https://uniforms.tools/ by changing the rating schema to
```
    rating: {
        type: Number,
        allowedValues: [1, 2, 3, 4, 5],
        uniforms: {
            checkboxes: true,
            inline: true,
        }
    },
```

Switching to bootstrap3 shows radio buttons inline, but bootstrap4 does not.

**Comment by radekmie** [comment]
@janslowik: you've updated this theme lastly. Maybe you'd like to give it a shot?

**Comment by radekmie** [comment]
It turned out to be a problem with the demo - it was using an outdated package. Sorry for the inconvenience, @ChristopherLivett!

**Comment by danilomiranda** [comment]
Hey @radekmie 
I'm facing the same problem in my application.
packages:
"uniforms": "^1.23.2",
"uniforms-bootstrap4": "^1.23.2"
FORM
```
<AutoForm
      schema={schema}
      model={model}
      onChangeModel={onChange}
    >
        <RadioField name="CA1A" />

    </AutoForm>);
```
SCHEMA
```
  CA1A: {
    type: String,
    optional: true,
    uniforms: {
      checkboxes: true,
      label: 'Radio',
      options: [{
        label: 'Some Option',
        value: 'Some Option',
      }, {
        label: 'Other',
        value: 'Other',
      }],
    },
  },
```

**Comment by radekmie** [comment]
Hi @danilomiranda. You don’t have an `inline` option set.

**Comment by danilomiranda** [comment]
I put inline option, no effect
try this
```
<RadioField name="CA1A" inline={false} />
```
and this 
```
 CA1A: {
    type: String,
    optional: true,
    uniforms: {
      checkboxes: true,
      label: 'Radio',
      inline: true,
      options: [{
        label: 'Some Option',
        value: 'Some Option',
      }, {
        label: 'Other',
        value: 'Other',
      }],
    },
  },
```
Same problem

**Comment by radekmie** [comment]
Wait, so you want to make it inline or not? Your example is not consistent.

**Comment by danilomiranda** [comment]
Ouch, my bad. i posted on the wrong issue
My problem is that the check are not marking  when we click on it

**Comment by danilomiranda** [comment]
@radekmie Should I post my issue here? https://github.com/vazco/uniforms/issues/396

**Comment by radekmie** [comment]
If it’s related. If not, file another or simply ask on Gitter.
