### ISSUE TITLE
NestField component does not set form-control bootstrap class for label

### ISSUE THREAD

**Issue by mpowaga** [vazco/uniforms#398]
This is the case for both `uniforms-bootstrap3` and `uniforms-boostrap4` packages. See [NestField.js:23](https://github.com/vazco/uniforms/blob/master/packages/uniforms-bootstrap3/src/NestField.js#L23):

```javascript
{label && (
  <label>
    {label}
  </label>
)}
```

**Comment by radekmie** [comment]
Hi @mpowaga. I guess it should, right? Would you submit a PR with a fix or maybe suggest correct classes for both themes?

**Comment by radekmie** [comment]
I finally found some time to look into it, and it looks OK to me right now. Also, I've tried to add the `form-control` class to the `<label>` tag and it styled it as an input. Are you sure it's really needed?

**Comment by radekmie** [comment]
I assume it's not needed.
