### ISSUE TITLE
How do I access validation errors for a specific field (not a form)

### ISSUE THREAD

**Issue by zeroasterisk** [vazco/uniforms#4]
I prefer to put validation errors with the field, not a list at the top of the form.

I can not seem to get any custom fields access to the `error` & `schema`
see: https://github.com/zeroasterisk/uniforms for a bootstrap4 UI, where I'm trying to update display

**Comment by radekmie** [comment]
You mean something like [semantic-ui labels](http://semantic-ui.com/elements/label.html#pointing) (`semantic`) or text nearby field (`unstyled`)?

**Comment by radekmie** [comment]
I've added an `errorMessage` prop in `1.0.0-rc.6` - it's field's scoped error message.

**Comment by vladejs** [comment]
How can I implement this with `<AutoForm/>`? Is there some `inlineErrors={true}` prop?

**Comment by radekmie** [comment]
It's only an available property - it's not built in in standard components - you can use it to design your own.

**Comment by zeroasterisk** [comment]
it is on the bootstrap UI

**Comment by radekmie** [comment]
I thought it is not... It's even better.
