### ISSUE TITLE
Documentation for GraphQLBrdige 

### ISSUE THREAD

**Issue by theodorDiaconu** [vazco/uniforms#401]
https://github.com/vazco/uniforms/blob/master/API.md#graphqlbridge

How does the schema data look and what options does it accept. Can we have custom validation rules inside the schemaData ?

**Comment by radekmie** [comment]
There are no detailed docs, so here's a set of answers.

> How does the schema data look and what options does it accept.

Basically, it's `{fieldName: fieldProps}`, so every field from `schemaData` is passed as an additional prop. [Source](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/GraphQLBridge.js#L121-L124).

> Can we have custom validation rules inside the schemaData ?

I think it should be clear now: no. If your field doesn't do such, based on props, the only validation happen in your validator.

**Comment by theodorDiaconu** [comment]
Understood! Thank you. 

But in theory, we could have our components / connected fields accept a validate function right ? Or do you see validation as a layer on top of connected fields and that would mean mixing up concerns ?

Or maybe schemaValidator can also be an object something like
```js
{
    id: Function,
    xxx: Function
}
```

But then again, one could implement his own function to do that... 

Cheers!

**Comment by radekmie** [comment]
All fields are schema independent. All schemas are field independent too. Obviously, you can pass a validation to your field component but it ties field with an additional logic. Anyway, it won’t happen in the core, but I can imagine few situations, where it can make some sense.

**Comment by theodorDiaconu** [comment]
The only concern that I'm having with the absence of field-level validation, is that sometimes it may be hard to separate concerns. Take a weird example where I have 5 inputs and each gets async validated independently. My issue is that if I use (https://github.com/vazco/uniforms/blob/master/INTRODUCTION.md#asynchronous-validation) is impossible. We need something like this for sure, do you know if there's a hack/work-around for this with any of the schemas ?

I believe this would be a good feature. Look here:
https://react-form.js.org/#/async-validation

This is so nice.

**Comment by radekmie** [comment]
There is some kind of that already on the roadmap: _Allow setting validation error directly from a field._. I think it would be enough, as you can set an error and then _remove_ it asynchronously.
