### ISSUE TITLE
Set init value for BaseField 

### ISSUE THREAD

**Issue by jy4618272** [vazco/uniforms#408]
jsonschema like this :
firstName: {
  type: 'string'
 },
lastName: {
  type: 'string',
  default: "baz"
}
================================================
onChange (key, value) {
  if (key === 'firstName') {
    console.log(this.getModel().lastName);
    return;
  }
  super.onChange(key, value);
}

but we got undefined value from the this.getModel().lastName，is this a bug?

==============================================
this is hotfix
import set from 'lodash/set';
......
getFieldProps (name, options) {
......
  let value;
        if (props.value === undefined || options.overrideValue) {
            value = get(context.model, name);

            if (value === undefined && !changed && !options.explicitInitialValue) {
                value = context.schema.getInitialValue(name, props);

                //NOTE : set init value
                set(context.model, name, value);
            }
        }
......
}

**Comment by jy4618272** [comment]
yes, default: 'value' always works. i wanna get lastName's default value from another field (firstName) change event. but this.getModel().lastName return undefined.

export default class ChainForm extends AutoForm {
    onChange (key, value) {
        if (key === 'firstName') {
            console.log("lastName:" + this.getModel().lastName)
        }
     }
}

**Comment by radekmie** [comment]
In your code, you override the `onChange` but not call `super.onChange`. Initial values are set using `onChange`, so you've blocked it completely.

**Comment by radekmie** [comment]
I assume it's solved.
