### ISSUE TITLE
Is there a typehead "plugin"?

### ISSUE THREAD

**Issue by thebarty** [vazco/uniforms#411]
Hi guys,

I'd love to have a typehead field using uniform and SimpleSchema2. Something like https://twitter.github.io/typeahead.js/examples/

Any suggestions on how to do this?

**Comment by radekmie** [comment]
Hi @thebarty. That plugin you've mentioned is a jQuery, not React plugin. And no, there are no such components in the standard themes. Anyway - integration with outside components is documented in the [docs](https://github.com/vazco/uniforms/blob/master/INTRODUCTION.md), there's a plenty of issues with such examples. You can look (and ask) for these on our [Gitter channel](https://gitter.im/vazco/uniforms).
