### ISSUE TITLE
[Question] How to access validation-errors AFTER hitting submit-button

### ISSUE THREAD

**Issue by thebarty** [vazco/uniforms#413]
Hi guys,

I'd like to use https://www.npmjs.com/package/react-toastify to show the current errors in a message-box.

The problem is that `onSubmitFailure()` is NOT called if an validation-error occurs. Now I am kind of lagging a `onSubmitValidationFailure()`-hook to hook into…

Something like this would be awesome to have:

```
import { toast } from 'react-toastify'

const onSubmitValidationFailure = (errors) => {
  const allErrorsAsString = _.pluck(errors, 'message').join(' ')
  toast.errors(allErrorsAsString)
}
<AutoForm
  onSubmitValidationFailure={(errorsArray) =>  }
/>
```

How do you guys do this?

**Comment by radekmie** [comment]
There's a `onValidation` prop documented [here](https://github.com/vazco/uniforms/blob/master/INTRODUCTION.md#asynchronous-validation).

```js
<AutoForm {...props} onValidation={onValidation} />

function onValidation(model, error, callback) {
    if (error) {
        // Trigger toast.
    }

    callback();
}
```

**Comment by thebarty** [comment]
@radekmie : Yeah, thats a beginning, but using this method is called on every new validation, which might happen much more often than hitting the submit button (p.e. when letter and the email is still invalid). I need a way to only catch those error "onSubmit".

aldeed:autoform had some nice hooks for doing this kind of stuff...

**Comment by radekmie** [comment]
In this case, you can simply create a subclass of `AutoForm` and provide a custom `onSubmit` method. If you'll need some help with it, look into other issues, source and of course our Gitter room.
