### ISSUE TITLE
ErrorsField compatible with react@0.14.x 

### ISSUE THREAD

**Issue by janslowik** [vazco/uniforms#42]
I used uniforms with old version of react because of other project dependencies. Most of feature works well despite the uniforms need react@15. However I got error when tried to use `ErrorsField`.

> No `render` method found on the returned component instance: you may have forgotten to define `render`, returned null/false from a stateless component, or tried to render an element whose type is a function that isn't a React component.

Is it possible to provide functionality of uniforms with older version of react.

**Comment by radekmie** [comment]
I've fixed in on `devel` branch. It would be great, if you could test it and let me know, if it works correctly.
