### ISSUE TITLE
placeholder without label not displayed

### ISSUE THREAD

**Issue by scheiblr** [vazco/uniforms#421]
Hello guys,

I just had the following effect:
```
<AutoForm placeholder={true} label={false} schema={bridge}>
```
 does not show the placeholder. Only if label is true, placeholders are present. To me that is very unfortunate, because there is the use-case that placeholders replace labels. 

Kind regards

EDIT: This affects the JsonSchema version.

**Comment by radekmie** [comment]
I confirm that. It also affects `GraphQLBridge`.
