### ISSUE TITLE
IE11 array.find issue

### ISSUE THREAD

**Issue by thebarty** [vazco/uniforms#423]
Hi guys,

just tested my site in IE11 and ran into a problem. IE11 is complaining that `.find()` is NOT available in this line
https://github.com/vazco/uniforms/blob/32123a70740cfcd895caf91bf5baeca378f69e4a/packages/uniforms/src/createSchemaBridge.js#L34

Seems like `array.find` is NOT supported by IE11 https://github.com/vazco/uniforms/blob/32123a70740cfcd895caf91bf5baeca378f69e4a/packages/uniforms/src/createSchemaBridge.js#L34

Also, I ran into a simple-schema issue https://github.com/aldeed/simple-schema-js/issues/267

**Comment by radekmie** [comment]
Hi @thebarty. You should use polyfills for such usecases as we don't provide them by default (not everyone needs them). I think that the most common is the [`babel-polyfill`](https://babeljs.io/docs/usage/polyfill/).
