### ISSUE TITLE
Is it possible to programatically associate an error with a field?

### ISSUE THREAD

**Issue by BudgieInWA** [vazco/uniforms#424]
I have a number of situations where I am doing server side validation of form content and the errors that I generate refer to a specific field in the form. Take the example of checking that a new username is unique. I can trigger the server side validation in `onValidate` or `onSubmit` and return an error that the form then stores in its state (as far as I can tell, replacing the `error` prop value). Is it possible to associate the error (or a list of errors) with specific form fields so that the "username is taken" error can be automatically displayed on the username field (using `showInlineError`)?

**Comment by radekmie** [comment]
Hi @BudgieInWA. Yes, it's definitely possible. It's not clearly stated in the docs (just a bit in the [API docs](https://github.com/vazco/uniforms/blob/master/API.md#baseform)), but both `error` prop and `onValidate` error should be _compatible_ with your schema. An error is _compatible_, if `Bridge.getError` (and `getErrorMessage` and `getErrorMessages`) recognize it correctly. Then, using the `showInlineError` will render it correctly, as when the error is not recognized, no field knows about it, only the `ErrorsField` shows something.
