### ISSUE TITLE
object spread and class properties

### ISSUE THREAD

**Issue by ColinRyan** [vazco/uniforms#429]
Hey guys,

I'm trying to get this project to work with my parcel setup but I keep getting errors with object spread and static class properties.

I have babel plugins that process such syntax in my own code fine but it fails the moment I try to import anything uniforms related.

I don't think it's an issue with uniforms but I'm wondering if someone here may have seen something similar before.

Anything helps :) 

thanks!

**Comment by radekmie** [comment]
Hi @ColinRyan. Yep, as I've tried Parcel last time I've also had some problems with Babel plugins. Anyway, I'll close it as it's not uniforms related.
