### ISSUE TITLE
Unable to set wrapperStyle props in a  uniforms-antd CustomForm

### ISSUE THREAD

**Issue by PatrickIl** [vazco/uniforms#430]
I am getting the following warning, when setting the wrapperStyle props on a TextField: 'Warning: Unknown prop `wrapperStyle` on <input> tag. Remove this prop from the element'. I double checked in 'uniforms-antd', the wrapField.js registers only 'colon', 'labelCol', and  'wrapperCol' But it does not register wrapperStyle. 
This is my first time with uniforms. What is the best way to deal with this?
Thanks,

**Comment by radekmie** [comment]
Hi @PatrickIl. Could you post a smallest possible reproduction? And what uniforms version are you on?

**Comment by PatrickIl** [comment]
Hi,
Thanks for helping out.
Here's my version of uniforms:
"uniforms": "^1.18.2",
"uniforms-antd": "^1.24.3",
"uniforms-semantic": "^1.18.2",
"uniforms-unstyled": "^1.24.3"

I took a copy of  'uniforms-example-app-master', from github and modified the file 'CustomForm.js', from the component directory. My goal is to display the field label on the left side of the text or input field and also remove the default ''12px'' bottom margin of each Form Item, using uniforms ant design components or styling. I modified the CustomForm.js to import component from 'uniforms-antd' instead of 'uniforms-semantic', and I'm passing to first TextField a formItemLayout object, which defines labelCol, wrapperCol, and wrapperStyle. I also wanted to style the field title or label, but I did find something like labelStyle. 
I have attached my modified version of CustomForm.js. You just need to replace the one in imports/components/ into a copy of 'uniforms-example-app-master' from github and run the application to reproduce the problem. When you run example with the attached file
[CustomForm.js.zip](https://github.com/vazco/uniforms/files/2045178/CustomForm.js.zip)
, select the CustomizedForm Tab, from the Simple uniforms demo window, and you will see in the Console (Developer Tools) the warning and notice that wrapperStyle is not accepted.

**Comment by radekmie** [comment]
So the issue is, that there's no `labelStyle`. All the other are used in the [`wrapField`](https://github.com/vazco/uniforms/blob/master/packages/uniforms-antd/src/wrapField.js). If you want to make the label bold, you can either use `label` prop directly (with some `styling`), do some styles or create custom field components.

**Comment by PatrickIl** [comment]
Sorry, that's not the issue. Forget about the labelStyle. Using the wrapperStyle is throwing the warning, because it is not being recognized. You can find out yourself by running my modified CustomForm.js  uniforms-example-app-master.

**Comment by PatrickIl** [comment]
I have attached another modified CustomForm.js file. This one does not have the labelStyle, which I am aware that it does not exist. In this file, I am trying to use wrapperStyle, and it is not being recognized. 
Thanks a million, for your help!!!
[CustomForm.js.zip](https://github.com/vazco/uniforms/files/2048290/CustomForm.js.zip)

**Comment by radekmie** [comment]
Indeed, it's our prop but it's not filtered out. OK, I'm of course reopening. Would you submit a PR for that?

**Comment by PatrickIl** [comment]
PR submitted.
Thanks
