### ISSUE TITLE
why the QuickForm render twice ?

### ISSUE THREAD

**Issue by jy4618272** [vazco/uniforms#435]
i follow this demo code :
export default class JSONForm extends Component {
    constructor(props) {
        super(props);

        this.state = {}
    }

    render() {

        const schema = {
            title: 'Person',
            type: 'object',
            properties: {
                firstName: {
                    type: 'string'
                },
                lastName: {
                    type: 'string'
                },
                age: {
                    description: 'Age in years',
                    type: 'integer',
                    minimum: 0
                }
            },
            required: ['firstName', 'lastName']
        };

        const validator = new Ajv({allErrors: true, useDefaults: true}).compile(schema);

        const schemaValidator = model => {
            validator(model);

            if (validator.errors && validator.errors.length) {
                throw {details: validator.errors};
            }
        };

        const bridge = new JSONSchemaBridge(schema, schemaValidator);

        return (
            <div>
                <ChainForm schema={bridge} />
            </div>
        )
    }
}

and then console.warn("QuickForm render") in QuickForm render. 

![image](https://user-images.githubusercontent.com/1615285/41135604-f21bb1dc-6b04-11e8-8eab-3273fe6b899e.png)

**Comment by radekmie** [comment]
Hi @jy4618272. It's an implementation detail, related to initialisation of a model. Is it a problem for you? I mean, why does it matter?

**Comment by radekmie** [comment]
No answer so far, closing.
