### ISSUE TITLE
ListField is not working for me

### ISSUE THREAD

**Issue by TimoRuetten** [vazco/uniforms#437]
I am a bit confused. I am using uniforms in combination with material-ui (NOT the new 1.0 version). When defining an Array in my schema the "Add" button does nothing. Clicking on it will not cause and error but also will do nothing.

This is my schema:

```javascript
...
  media: {
    type: Array,
    optional: true,
  },
  'media.$': {
    type: Object,
  },
  'media.$.type': {
    type: String,
    allowedValues: [
      'image'
    ],
  },
...
```

This is my form:

```javascript
...
<AutoField name="media" />
....
```

Any other form type is working. But here there is a "Add" btn rendered, but the click will do nothing.

**Comment by radekmie** [comment]
Hi @TimoRuetten. What form component are you using?

**Comment by TimoRuetten** [comment]
Hey @radekmie 

I am using this:

```javascript
import AutoForm from 'uniforms-material/AutoForm';
```
btw: I tried also to rebuild the ListField:

```javascript
<ListField name="media">
                <ListItemField name="$">
                  <NestField disabled={false} name="">
                      <AutoField name="type" />
                  </NestField>
              </ListItemField>
```

All components I am importing are connected with the material-ui theme:
```javascript
import AutoForm from 'uniforms-material/AutoForm';
import AutoField from 'uniforms-material/AutoField';
import ErrorsField from 'uniforms-material/ErrorsField';
import ListField from 'uniforms-material/ListField';
import NestField from 'uniforms-material/NestField';
import ListItemField from 'uniforms-material/ListItemField';
```

All version:
```javascript
"uniforms-material": "^1.24.1"m
"material-ui": "^0.20.0",
```

**Comment by radekmie** [comment]
Well, it's working for me. Can you provide a runnable reproduction? Maybe using [codesandbox.io](https://codesandbox.io/) or similar service. A repo is also OK.

**Comment by TimoRuetten** [comment]
@radekmie Thats very strange! I'll do this tomorrow because will leave office now.

**Comment by TimoRuetten** [comment]
Hey @radekmie 
Here the problem is reproduced. Its also not working for me:

https://codesandbox.io/s/3qykx4y675

**Comment by TimoRuetten** [comment]
I guess the problem was the missing injectTapEventPlugin. I will test this now and tell you if this was the problem.

**Comment by TimoRuetten** [comment]
Seems to be a strange bug. Its not working in codesandbox until I've added the tap-event-plugin. Strange is, that I am using this plugin in my app also and here its not working. Its in combination with meteor - but I dont think this should be a problem at all. I'll try to find the bug - as I can see in codesandbox everything is fine with your package so far. Thanks!

**Comment by radekmie** [comment]
I've also checked that - without the `injectTapEventPlugin` it's not working at all. Good luck there!

**Comment by janowsiany** [comment]
Hey, i think i forgot to upgrade `unifoms-material` when [v.0.20.0](https://github.com/mui-org/material-ui/releases/tag/v0.20.0) was released, sorry.

**Comment by TimoRuetten** [comment]
Hey @radekmie - just in case that you also want to check it:

https://github.com/TimoRuetten/UniformTestListFields

I've made a very small repo to test this and in this example the list field is also not working (without an error) - maybe you see the issue here ? I have no idea whats the problem in there ...

**Comment by janowsiany** [comment]
@TimoRuetten the problem is that `uniforms-material` version before upgrade to `material-ui@^1.0.0` used to define its constraints as `"material-ui": ">=0.16.7 <1.0.0",` see [here](https://github.com/vazco/uniforms/blob/b09cfe1836357b4edaffdcb010002830af8d1cf1/packages/uniforms-material/package.json#L25). However since v.0.20.0 there is a breaking change in `material-ui` package which was not addressed in `uniforms-material`. THe issue is that all `onTouchTap` should be switched to `onClick`. Is it clear? I am not sure how can we handle this now? We already support `^1.0.0`.

**Comment by TimoRuetten** [comment]
Ah okay. So I guess the best for me would be just to upgrade to material-ui 1.0 - which isnt a problem for me at all. :) Thanks

**Comment by TimoRuetten** [comment]
@janowsiany after updating to version 1.0 (material-ui/core) its working fine :) Thanks a lot. I was close to getting insane because of this error!
