### ISSUE TITLE
Installation problems?

### ISSUE THREAD

**Issue by HenrikGr** [vazco/uniforms#439]
I started to test uniforms and uniforms-material and did, npm install uniforms uniforms-material, and tested with a jsonSchema and it seems to work nice so far.

But, i do get some nasty messages in the console such as;

./node_modules/uniforms/GraphQLBridge.js
Module not found: Can't resolve 'graphql' in

./node_modules/uniforms/SimpleSchemaBridge.js
Module not found: Can't resolve 'meteor/aldeed:simple-schema' in 

./node_modules/uniforms/SimpleSchemaBridge.js
Module not found: Can't resolve 'meteor/check' in 

Do I have to install these?
I do intend to use only jsonSchema and no other schemas.

I'm using create-react-app, the latest and do not use Meteor.

Best Regards
Henrik Grönvall

**Comment by radekmie** [comment]
Hi @HenrikGr. No, it’s not a problem. These are just warnings from Webpack - you can simply ignore them. If you want some more in-depth answer, look for it in the issues - it was asked few times already.

**Comment by alexesDev** [comment]
@HenrikGr just add ignore for meteor deps:
```js
plugins: [
  new webpack.IgnorePlugin(/(aldeed:simple-schema|meteor\/check)/),
],
```
