### ISSUE TITLE
Upload field error

### ISSUE THREAD

**Issue by mixcas** [vazco/uniforms#45]
I'm trying to make an upload field for images.

This is my component:
```js
import React from 'react';

import { BaseField, connectField } from 'uniforms';

import '/imports/lib/slingshot.js';

const uploadFile = (event, onChange) => {
  const uploader = new Slingshot.Upload("imageUpload");

  const image = event.currentTarget.files[0];

  // TODO: Disable input
  // TODO: Show "Loading…" or somthing

  uploader.send(image, function(error, url) {
    if (error) {  
      throw new Meteor.Error('upload-file-fail', error);
    } else {
      const file = {
        url: url,
        name: image.name,
      }
      onChange(file);
    }
  });
};

const FieldUpload = ({
  id,
  value,
  onChange,
  name,
  ...props
  }) =>

  <section {...props}>
    <input type="file"
      name="uploadFile"
      onChange={event => uploadFile(event, onChange)}
    />
    <img src={value.url} />
    <p>{value.name}</p>
  </section>
;

export default connectField(FieldUpload);
```

And this is my form schema:
```js
import FieldUpload from '/imports/components/fields/FileUpload.jsx';

const FileSchema = new SimpleSchema({
  url: {
    type: String,
  },
  fileName: {
    type: String,
  },
});

const UploadSchema = new SimpleSchema({
  file: {
    type: FileSchema,
    uniforms: {
      component: FieldUpload,
    },
  },
});

export const FormSchema = new SimpleSchema({
  name: {
    type: String,
  },

  avatar: {
    type: UploadSchema,
  },

  photos: {
    type: [UploadSchema],
    minCount: 1,
    maxCount: 3,
  }
});
```

If I try to submit a form with all it's fields empty, the returned errors are:

> Url is required
> File name is required
> Url is required
> File name is required
> Name is required

How can I return a more sensible error? like. 
> Avatar is required
> Photos is required

Ideally:
> Photos are required

**Comment by radekmie** [comment]
Well, it's not a problem of uniforms, but SimpleSchema itself. Currently, I could imagine only one (easy) solution - pass an `onValidate` prop to you `<AutoForm />` (it's described [here](https://github.com/vazco/uniforms#asynchronous-validation)) and manually create correct [`ValidationError`](https://github.com/meteor/validation-error/) (SimpleSchema uses it internally).

Something like:

```js
const onValidate = error => {
    if (!error) {
        return;
    }

    if (error.details.some(fieldError => fieldError.name === 'url') {
        return new ValidationError([{name: 'photos', type: 'required'}]);
    }
};
```

should be sufficient for a quick-and-dirty solution (go ahead and develop it to some more general).

Also, you can [define your own error messages](https://github.com/aldeed/meteor-simple-schema#customizing-validation-messages).

---

You've got a typo in your first snippet - there's `url` and `fileName` in your schema, but there's

```js
      const file = {
        url: url,
        name: image.name,
      }
```

in your component.
