### ISSUE TITLE
How to give AutoField a hint of the field's schema? 

### ISSUE THREAD

**Issue by znat** [vazco/uniforms#450]
Use case:
The user selects the type of object he wants to add to an array in the schema. A dropdown allows to pick from "text","image","carousel".

The array item schema is not constrained at the db level (blackbox), but I would like to use schemas to generate forms. So, I am wondering how can I hint `AutoField` with a schema when there is not schema specification for that field in the schema supplied to `AutoForm`?

**Comment by radekmie** [comment]
Hi @znat. We are not covering this case at all, but maybe `component` parameter is enough for you? You can specify the component at the field level. In this case, maybe custom `AutoField` or simply a logic to pick the component is enough?

A completely different approach might be to dynamically create schemas or create a custom bridge/schema for this task.

**Comment by znat** [comment]
Thank you for your reply @radekmie. using the `component` parameter should work, thanks for the tip :)
