### ISSUE TITLE
Inconsistency

### ISSUE THREAD

**Issue by v3yr0n** [vazco/uniforms#452]
Hey, 

I'm having a (very) weird issue. 
I have a form - SalesForm - that extends from AutoForm. 
Inside that class I override onChange

When I console.log(this) and I check the this.state.model properties i get the updated values of the form, which is correct. 
When I console.log(this.state.model) and check it's properties they are not the same the console.log(this)

Any idea?

![issue](https://user-images.githubusercontent.com/864980/43067773-4a69639c-8e60-11e8-8b72-3fe3a175c1b3.png)

**Comment by radekmie** [comment]
Hi, @v3yr0n. I don't see your code, but there are few common problems. If you simply `console.log` the component instance, you won't see a snapshot, but the state at the moment you'll inspect it - better use `debugger`, log primitives or use `JSON.stringify`.

Answering your question: `setState` is asynchronous and that's _probably_ the issue. Also, are you calling the `super.onChange`?

**Comment by v3yr0n** [comment]
Hey @radekmie I've just added the console.log results. Please check the duration property of event.services[0] the correct one is 120 and thats the result of console.log(this). The 75 is the old value and it only shows when i console.log(this.state.model)

**Comment by v3yr0n** [comment]
And yes, I'm calling super.onChange(key, value) before I console.log()

**Comment by radekmie** [comment]
As I said, you are inspecting the current state and not the snapshot - that's how the devtools work. Use `debugger` to stop after the `console.log` and inspect it at this very moment.

**Comment by v3yr0n** [comment]
i'll do it and let you know. Thanks!

**Comment by radekmie** [comment]
You'd have to show the code. Take a look into the `AutoForm` and `BaseForm` sources, it might give you an idea.

**Comment by v3yr0n** [comment]
@radekmie I can show you some code, but I doubt it helps :)
What I need is a way to wait for the state to be updated. I know that setState has a callback, but uniforms is setting the state, not me. How can I wait for the state to be update?

Thanks!

**Comment by radekmie** [comment]
You have to describe, what exactly you want to do - all you've said is true, but gives me 0 information on your problem.

**Comment by v3yr0n** [comment]
@radekmie thanks for your time
here's the code: 

`export default class SalesForm extends AutoForm {

    onChange(key, value){

        const durationRegex = RegExp(/event\.services\.([^\.]+)\.duration/);
        if (durationRegex.test(key)){
            const { services } = this.state.model.event;
            let totalDuration = 0;
            services.map(function(item){
                totalDuration += parseInt(item.duration);
            });
            console.log(totalDuration);
            super.onChange(key, value);
        }
    }
}`

What i want to do is sum all duration values of all services inside the event object. 
because the item.duration is not updated with the right value the sum is not correct, and that's why I need to wait for the state to update.

Thanks!

**Comment by radekmie** [comment]
In this case, I'd suggest not to use the `AutoForm` at all - you want to manage your model on your own. Another option is to use `modelTransform` and compute the sum of durations on the fly.

**Comment by radekmie** [comment]
Ping @v3yr0n.

**Comment by radekmie** [comment]
No answer so far, closing.
