### ISSUE TITLE
uniform-semantic select field

### ISSUE THREAD

**Issue by TimoRuetten** [vazco/uniforms#453]
It seems that not all semantic-ui form elements are included. e.g. the select field is missing.

Is this a problem with the version of sementic-ui ? Will this be fixed or should I write my own components for semantic-ui ?

**Comment by TimoRuetten** [comment]
Edit:

```javascript
...
import SelectField from 'uniforms-semantic/SelectField';
...
<SelectField
    name="type"
/>
...
```

Will lead in this HTML output:

```html
<div class="required field"><label for="uniforms-0002-0000">Type</label><select id="uniforms-0002-0000" name="type"><option value="a">a</option></select></div>
```

Nut it should lead in this HTML output:


```html
<div class="field"><label>Type</label><div role="listbox" aria-expanded="false" class="ui selection dropdown" tabindex="0"><div class="default text" role="alert" aria-live="polite">Type</div><i aria-hidden="true" class="dropdown icon"></i><div class="menu transition"></div></div></div>
```

**Comment by TimoRuetten** [comment]
I've changed the SelectField to this:
```javascript
import { Select } from 'semantic-ui-react';
const renderSelect = ({
  allowedValues,
  disabled,
  id,
  inputRef,
  label,
  name,
  onChange,
  placeholder,
  required,
  transform,
  value,
}) =>
  (
    <Select
      id={id}
      disabled={disabled}
      ref={inputRef}
      required={required}
      fluid
      value={value}
      options={allowedValues.map(value => ({ value, text: transform ? transform(value) : value }))}
      label={label}
      placeholder={placeholder}
      onChange={(e, { value }) => {
        onChange(value);
      }}
    />
  );

```

Works fine for me. Maybe you should also change it in your version.

**Comment by radekmie** [comment]
Hi @TimoRuetten. To make it clear: all Bootstrap and SemanticUI themes are not using their npm packages. And yes, it's strongly suggested to build own fields.

**Comment by TimoRuetten** [comment]
Yes get your point. But even if its not using the npm packages the correct semantic ui select field is not the normal html based <select>.

See here:
https://semantic-ui.com/collections/form.html#dropdown

But anyways you're right it would be recommended to build own fields :-) Thanks for your work on this package!

**Comment by TimoRuetten** [comment]
Ahh! Got it! understandable :) Thanks 👍
