### ISSUE TITLE
New feature, split fields in columns

### ISSUE THREAD

**Issue by cesarve77** [vazco/uniforms#455]
The main idea is pass a new property to called "col" and be able to split the fields inside the form in columns, like this:

![image](https://user-images.githubusercontent.com/3970983/43870504-246c4fac-9bbb-11e8-9d97-75b91bdf66dd.png)

### My proposal for antd is something like this:
 
```
new SimpleSchema({
    "field1": {type: String, optional: true, uniforms: {col: 6}}, //or
    "field2": {type: String, optional: true, uniforms: {col: {span: 6}}},
    "field3": {type: Date, optional: true, uniforms: {col: {span: 6}}},
    "field4": {type: Date, optional: true, uniforms: {col: {span: 6}}},
    "field5": {type: Date, optional: true, uniforms: {col: {span: 12}}},
    "field6": {type: Date, optional: true, uniforms: {col: {span: 12}}},
})

```

And it can be done just changing AutoField

### Minimal antd example

```
+ import {Col} from "antd";
.
.
.
- return createElement(props.component, this.props);
+ const col=(typeof col !== 'object')  ?  {span: col} : col
+       return (
+           <Col {...col}>
+              {createElement(props.component, this.props)}
+           </Col>
+        )
```

If it sounds good to you I'll be more than happy to work in a pull request.

**Comment by radekmie** [comment]
Hi @cesarve77. If it's really so easily doable, I'd rather don't do it - if all it needs is a custom `AutoForm`, everyone can manage it on their own, with a small, custom field.

Can you also post such a field, just to let me check that?

**Comment by cesarve77** [comment]
Sure.
A fields will looks like  <TextField col={6} />

I can 't see it clear with custom AutoForm, and with a custom AutoField we will face the same problem than https://github.com/vazco/uniforms/issues/454 and we will need a custom AutoFields, ListFields, ListItemField and NestField.

Sorry for my englsih

**Comment by cesarve77** [comment]
With my proposal the only AutoField need to be changed, no the fields definition.

The problem with a custom  AutoField, it that you need a custom AutoFields, ListFields, ListItemField and NestField (https://github.com/vazco/uniforms/issues/454).

I'm working In a project similar to [Vulcan](http://vulcanjs.org) but instead of smart forms I want to use Uniforms, i'm trying to keep the maintainability with other packages as easy as possible. I don't want to create an AutoFields, ListFields, ListItemField and NestField for each style.

A work around -> https://github.com/vazco/uniforms/issues/454#issuecomment-412422861

**Comment by radekmie** [comment]
To do such thing you’ll need to override all of the fields anyway, as, for example, `ListField` has own sub fields and none of them is the `AutoField` (`ListAddField` and `ListDelField`).

**Comment by radekmie** [comment]
I think it's already clear.
