### ISSUE TITLE
form reset does not change this.state.changed of form back to false

### ISSUE THREAD

**Issue by macrozone** [vazco/uniforms#457]
reproduction:

- this.state.changed is false initially,
- change something in the form, this.state.changed is now true
- call formRef.reset(), this.state.changed is still true

**Comment by radekmie** [comment]
Hi @macrozone. Can you provide an example? `reset` is an asynchronous function, so maybe this is the case.

**Comment by macrozone** [comment]
that should be not a problem, because reset still would need to call setState({changed: false}) at some point and this would cause a rerender.
Also submitting a form does not set the state back to false as it should in my opinion

**Comment by radekmie** [comment]
But it [does](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/BaseForm.js#L227-L233). Still, this value can be changed again afterward, by any field with a default value.

**Comment by radekmie** [comment]
Ping @macrozone.

**Comment by macrozone** [comment]
@radekmie i have to revisit that. 

I think `change` should stay false until the user purposely changes a fields value, no matter of default values. 

I now did a short debugging session and i noticed the following:

- after `reset()` , Autoform.onChange is immediatly called with the model's values.
- onChange then always sets `changed: true` even if nothing changes
- on the other hand, `changedMap` is still an empty object

so maybe remove state.changed and instead use a function that checkes whether changedMap is empty or not?

**Comment by radekmie** [comment]
Such maps are quite expensive, especially with bigger forms (both map size and queries amount increases). What you are saying in points 2 and 3 is a bug. Can you provide a complete reproduction or even a PR with failing test?

**Comment by macrozone** [comment]
@radekmie ok will do! 

checking if the map is empty should be fast on the other hand ;-)

**Comment by macrozone** [comment]
Ok i tried, but i can't reproduce it on tests, maybe it has to do with some re-renders?

on my app, i use now this workaround:

```
formHasChanged() {
      return !isEmpty(this.state.changedMap);
}
```

**Comment by radekmie** [comment]
I guess so. As I said, it is computed that way and all the tests are showing that it's working correctly. I'll close it for now, but if you'll come up with a reproduction - we'll reopen and help that.
