### ISSUE TITLE
Custom form component and typescript support?

### ISSUE THREAD

**Issue by avkonst** [vazco/uniforms#466]
I am evaluating your library. It looks very impressive. I wonder if you have got typescript bindings and how could I add custom form field? For example, my graphql schema has got Location type with 2 numeric properties: latitude and longitude. The library renders input field to enter numbers, but I have got my own external map component, where I can move a marker to define the location.

**Comment by radekmie** [comment]
Hi @avkonst. These are actually two separate questions.

First, no, there's no TypeScript I know about. If you are willing to somehow contribute here (or on DefinitelyTyped), let me know, preferably in a separate issue.

Two, yes, you can: it's the core of uniforms! Check out the `connectField` in the docs, like [`RangeField`](https://github.com/vazco/uniforms/blob/master/INTRODUCTION.md#example-rangefield), in the issues or on the [Gitter channel](https://gitter.im/vazco/uniforms). It's the easiest way to create a custom field.
