### ISSUE TITLE
Reseting the form on submit

### ISSUE THREAD

**Issue by guciek27** [vazco/uniforms#47]
Hello,
Is there a way to reset the form on submit? and if not than what would be your suggestion on doing that?

**Comment by radekmie** [comment]
No, there's no special API for that, but you can do it by setting your `model` prop to your desired _after reset state_ - [`AutoForm` will respect that](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/components/forms/AutoForm.js#L23-L29). If you have a good use case for exposing such API, leave a comment here and let's discuss it.

**Comment by guciek27** [comment]
The workaround with `model` prop does not work. When a form has more than one field in it the value of the second field gets removed when I start typing in the first one. 

We need that for a invite forms where after clicking invite the form is cleared.

**Comment by radekmie** [comment]
Okay, it might be a problem with absent initial values. Give me some time to think this up. Also, every idea is welcome.

**Comment by serkandurusoy** [comment]
aldeed:autoform has this form reference and a reset() method attached to
it. it is very handy in managing the form lifecycle. we could use something
similar here.

**Comment by radekmie** [comment]
Yes, it's achievable to do it with `ref`, but I don't like them, really (I know, it's a trivial reason, but maybe I'll come up with a different approach).

**Comment by radekmie** [comment]
Usage is covered in [`README.md`](https://github.com/vazco/uniforms#reset-form).

**Comment by serkandurusoy** [comment]
Cool! Thanks!

On Tue, Jun 28, 2016 at 12:15 AM, Radosław Miernik <notifications@github.com

**Comment by guciek27** [comment]
@radekmie,
Let me know once the change is released :) 
Thanks!

**Comment by radekmie** [comment]
I've just released `1.0.0-rc.22`.
