### ISSUE TITLE
IE Egde Basefrom.js

### ISSUE THREAD

**Issue by Blurri** [vazco/uniforms#473]
Hi,
We discoverd a problem with uniforms in IE Edge.  In the BaseForm.js in the constructor.
```
 this.getModel = (mode = null, model = getModel(mode)) =>
            mode !== null && this.props.modelTransform
                ? this.props.modelTransform(mode, model)
                : model
        ;
```
For some reason in the Edge browser "this" inside the function is undefined. We could fix it with optional chaining. But im not sure if this is the solution. In all other browsers we don't get this problem.
It looks like its more a bug in IE Edge but i thought I post it here anyway, hope thats ok.

**Comment by Blurri** [comment]
sorry i

**Comment by radekmie** [comment]
Hi @Blurri. Can you specify the exact error and Edge version? Also, are you sure you are using the transpiled sources? You can take a look at it at [unpkg.com](https://unpkg.com/uniforms@1.25.0/BaseForm.js).

**Comment by Blurri** [comment]
Hi,

Thanks for the response. The bug was in version 15,16 and 17. The error message is
```
unable to get property 'props' of undefined or null reference
````
You could see it on https://www.velomittwoch.ch/de/login (our production app).
But I just saw that we import the BaseForm directly from the `/node_modules/uniforms/src` folder.
So we dont use the transpiled source and our babel config creates a diffrent code. 
I guess we can close the issue because its our mistake.

sorry for the noise but thanks for the quick help

**Comment by radekmie** [comment]
No problem! Thanks for the report anyway - this could be a bug.

**Comment by macrozone** [comment]
@Blurri can you reopen?

its this issue or similar: https://github.com/babel/babel/issues/8019

I opened up a new one: https://github.com/babel/babel/issues/8825

@radekmie workaround would be to maybe get props from `this` before the arrow function or remove the arrow function there and use a class property

**Comment by radekmie** [comment]
@macrozone: neither _getting the `props` before_ nor _removing the arrow function and use a class property_ won't work: the first one won't, as `props` may change, second, because it is already in the prototype and we are using it without `this` (note the default argument).

If you want, I'll surely accept a PR for that. If not, we have to wait for Babel to patch it.

**Comment by macrozone** [comment]
@radekmie 

ok then the old school `const that = this`... but yeah, should be fixed by babel.

in the meantime, i disabled modern compilation for edge:

```
setMinimumBrowserVersions({
  edge: Infinity,
});
```
