### ISSUE TITLE
Cannot use Get fieldName function and error

### ISSUE THREAD

**Issue by DevKitu** [vazco/uniforms#476]
Hey, 
I am new in React Meteor and Uniforms. I like Uniform because it handle my validation. 
1. How can I get the server side validation error and display them to the user?
2. I need to get the fieldName of the field that is being type and use the onChange function to call a handeChange which will set my value to only on the field that is being changed with the this.setState: 
 handleChange = (event) => {
        const isCheckBox = event.target.type === "checkbox";

        this.setState({

            [event.target.name]: isCheckBox 
            ? event.target.checked
            : event.target.value
        });

    };

So, the question is how can I access the "this.target.name" when using AutoField?

3. I think there is a bug in the system: When I use AutoForm, I did not define any field value and everything worked well (i could see my Form and their Fields) and then I decided to change and try the ValidatedForm, then I put in my AutoField values BUT when I change back to AutoForm and remove all the AutoFields inside; I could not see the AutoForm fields anymore, until i call <AutoFields/>, then only it works. My understanding is that the AutoForm should work the same way on both situation. 
4. My AutoForm does not reset the fields after successful submission, I call a modal that I define on top of my code like this: 
var initData ={
            taskTitle:'',
            text: '', 
            taskId:'',
            creator:'',
            responsible:'',
            status:'',
            comments:'',
            priority:'',
            category:'',
            createdAt:'',
            targetCompletionDate:'',
}
<AutoForm
                      
                        schema={TasksSchema}
                        model={initData}
                        ...
/>
But it does not work still even when i remove model. 

Maybe my questions are very basics, then please just give me some guide lines.

Thanks

**Comment by radekmie** [comment]
Hi @DevKitu. Glad to hear that! Now, let's get to your questions:

1. Every uniforms form is validated with your schema, so server-side validation is simple: just use your schema. If still in doubt, check your schema documentation.
2. There's no need for such function! To be honest, it wouldn't be possible to implement one, as the field component may trigger `onChange` at any time. In short, if you are using `onChange` on a form component, its signature is `onChange: (key, value) => void`.
3. I'm not really sure what you mean here... Maybe [this table](https://github.com/vazco/uniforms/blob/master/INTRODUCTION.md#forms-components) will answer your question.
4. (1) Yep, there's no reset after submitting as a default. You can call `form.reset` to do so. (2) How it doesn't work? Is there an error or incorrect/unexpected behavior?

**Comment by DevKitu** [comment]
Hello @radekmie , Thanks for the quick reply. I appreciate that. 
1. I will check the simpl schema and meteor to handle this then. 
2. When i use just the form component from material ui, i am able to get the [event.target.name], and this return the Name of the field being changed. So, let me reformulate my question here: Can I use event.target to target a field that is being changed while using the AutoFields? 
Maybe I did not ask properly this question. 
3. What i mean here is the following: 
a. first i call : 
    <AutoForm
                      
                        schema={tasksSchema}
                        model={initData}
                        showInlineError={ true }
                        onSubmit={this.handleSubmit} 
                        validate="onSubmit"
                        onSubmitSuccess={() => console.log("Submit Success")}
                        onSubmitFailure={() => console.log("Submit Failed")}
           
                />
    without any AutoFields defined, When I render this, I get the complete form with all fields. 
 b. then , i changed to : 
     <ValidatedForm
                      
                        schema={tasksSchema}
                        model={initData}
                        showInlineError={ true }
                        onSubmit={this.handleSubmit} 
                        validate="onSubmit"
                        onSubmitSuccess={() => console.log("Submit Success")}
                        onSubmitFailure={() => console.log("Submit Failed")}
           
                >
                    <TextField .... /> .  // defined my fields here
       </ValidatedForm>

c. I then decided to return to my AutoForm, and call it like it is in (a), this AutoForm does not render any fields, until i define all fields individually. 
Why AutoForm does not render like before and now it require the fields to be specified?

4. Thanks, I was not sure how to implement it but after reading this post : https://github.com/vazco/uniforms/issues/291. I was able to do it with the form.reset. With the Model, there is no error message but the form just does not take the model or reset. I will try some more debugging. 

Thanks. And for the second question, if it is clear to you now, a short example will be great.

**Comment by DevKitu** [comment]
I get the answer to question 2 while going through the document, here is it: 
I call 
 onChange={(key, value) => this.handleChange(key, value)}
in the AutoForm and in my handleChange, I have : 
handleChange = (key, value) => { 

      event.preventDefault();
      console.log(key, value);
   }

Then I get the key which exactly my: [event.target.name] and the value is my event.target.value. 
While reading and trying to understand the question 4, I get the answer for question 2 as well. 
Thanks for the reference to the documents.

**Comment by radekmie** [comment]
1. Good luck!
2. I'm still not sure if I understand your question correctly, but it's OK, as long as it works for you.
3. It's because `QuickForm` (and therefore `AutoForm`) automatically renders fields if and only if no `children` are provided. [Source](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/QuickForm.js#L32-L52).
4. Maybe it's related to default values? If you struggle with debugging, feel free to reach me on Gitter or file an issue.

**Comment by radekmie** [comment]
No response so far, I assume everything is clear.
