### ISSUE TITLE
Not able to set decimal to false

### ISSUE THREAD

**Issue by mariusrak** [vazco/uniforms#477]
My NumField has always prop decimal set to true. How is this value defined? I didn't set it anywhere. I even tried to set ` { type: Number, uniforms: { decimal: false } },` in my schema, but the setting is ignored.

**Comment by radekmie** [comment]
Hi @mariusrak. I guess you are using `simpl-schema` with `SimpleSchema2Bridge`? If so, try `type: SimpleSchema.Integer` ([docs](https://github.com/aldeed/simple-schema-js#type)). If not: which version, theme and schema are you using?

**Comment by mariusrak** [comment]
Yeah, sorry I didn't include this info. But You were right and the solution works. Thank You :)
