### ISSUE TITLE
Access sibling fields in SimpleSchema without meteor

### ISSUE THREAD

**Issue by Roshdy** [vazco/uniforms#478]
Is it possible to access SimpleSchema instance | context without using meteor?

## Meteor Example
```
new SimpleSchema({
  countryCode: {
    label: i18n.t('country'),
    type: String,
    allowedValues: country_codes
  },
  city: {
    label: i18n.t('city', { lang }),
    type: String,
    allowedValues: function() {
      return cities_list[this.field('countryCode').value()];
    }
  }
}
```

How to accomplist that with pure react app? 
**Note**: `this` only maps to field name outside meteor (i.e. `this = {key: "city"} `)

**Comment by radekmie** [comment]
Hi @Roshdy. In uniforms implementation, no SimpleSchema contexts are being used. From the docs, I can't see that using `this.field` is possible in `allowedValues` (it is in `autoValue` and `custom`).

A solution to your problem would be a dynamic field and passing `allowedValues` as a prop.

**Comment by Roshdy** [comment]
@radekmie Ok i'll give it a try, and maybe share a working snippit if i reached one.

**Comment by radekmie** [comment]
Good. Let's close it for now. If you'll encounter any problems - feel free to write them here (if related) or create another issue.
