### ISSUE TITLE
How to set fullWidth to FALSE in uniforms-material

### ISSUE THREAD

**Issue by Roshdy** [vazco/uniforms#479]
Is there anyway i can get rid of the **_fullWidth_** property for **_FormControl_**, I tried everything I can think off
```
const theme = createMuiTheme({
  overrides: {
    MuiFormControl: {
      root:{
        width: 200
      },
      fullWidth: false
    }
  }
});
```
I tried `<AutoField name={'personalInfo'} fullWidth={false} />`

Also tried to pass it as a property for uniforms object in SimpleSchema
```
name: {
  type: String,
  label: i18n.t('name', { lang }),
  uniforms: {
    fullWidth: false
  }
},
```

Nothing seems to be working. I'm still getting **_MuiFormControl-fullWidth_** class generated!

### Note: 
I managed to get override it on the field level within `withStyles()(MyComponent)` like so
```
const styles = theme => (
  ...
  textField: {
    width: 200
  }
);
uniforms: {
  className: classes.textField
}
```
Which produced something like: `MuiFormControl-root-133 MuiFormControl-marginNormal-134 MuiFormControl-fullWidth-136 KYCStepper-textField-31`
which still has the **_fullWidth_** class!

**Comment by janowsiany** [comment]
Hey, did you tried [uniforms.tools](https://uniforms.tools/#?preset=Welcome!&props=%7B%22autosave%22%3Afalse%2C%22autosaveDelay%22%3A100%2C%22disabled%22%3Afalse%2C%22label%22%3Atrue%2C%22placeholder%22%3Afalse%2C%22schema%22%3A%22new%20SimpleSchema(%7B%5Cn%20%20%20%20date%3A%20%7B%5Cn%20%20%20%20%20%20%20%20type%3A%20Date%2C%5Cn%20%20%20%20%20%20%20%20defaultValue%3A%20new%20Date()%2C%5Cn%20%20%20%20%20%20%20%20uniforms%3A%20%7B%20fullWidth%3A%20false%20%7D%5Cn%20%20%20%20%7D%2C%5Cn%20%20%20%20name%3A%20%7B%5Cn%20%20%20%20%20%20%20%20type%3A%20String%2C%5Cn%20%20%20%20%20%20%20%20label%3A%20%5C%22Name%5C%22%2C%5Cn%20%20%20%20%20%20%20%20uniforms%3A%20%7B%20fullWidth%3A%20false%20%7D%5Cn%20%20%20%20%7D%2C%5Cn%20%20%20%20adult%3A%20%7B%5Cn%20%20%20%20%20%20%20%20type%3A%20Boolean%5Cn%20%20%20%20%7D%2C%5Cn%5Cn%20%20%20%20size%3A%20%7B%5Cn%20%20%20%20%20%20%20%20type%3A%20String%2C%5Cn%20%20%20%20%20%20%20%20defaultValue%3A%20'm'%2C%5Cn%20%20%20%20%20%20%20%20allowedValues%3A%20%5B'xs'%2C%20's'%2C%20'm'%2C%20'l'%2C%20'xl'%5D%5Cn%20%20%20%20%7D%2C%5Cn%5Cn%20%20%20%20rating%3A%20%7B%5Cn%20%20%20%20%20%20%20%20type%3A%20Number%2C%5Cn%20%20%20%20%20%20%20%20allowedValues%3A%20%5B1%2C%202%2C%203%2C%204%2C%205%5D%2C%5Cn%20%20%20%20%20%20%20%20uniforms%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20checkboxes%3A%20true%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%2C%5Cn%5Cn%20%20%20%20friends%3A%20%7B%5Cn%20%20%20%20%20%20%20%20type%3A%20%5BObject%5D%2C%5Cn%20%20%20%20%20%20%20%20minCount%3A%201%5Cn%20%20%20%20%7D%2C%5Cn%5Cn%20%20%20%20'friends.%24.name'%3A%20%7B%5Cn%20%20%20%20%20%20%20%20type%3A%20String%2C%5Cn%20%20%20%20%20%20%20%20min%3A%203%5Cn%20%20%20%20%7D%2C%5Cn%5Cn%20%20%20%20'friends.%24.age'%3A%20%7B%5Cn%20%20%20%20%20%20%20%20type%3A%20Number%2C%5Cn%20%20%20%20%20%20%20%20min%3A%200%2C%5Cn%20%20%20%20%20%20%20%20max%3A%20150%5Cn%20%20%20%20%7D%5Cn%7D)%22%2C%22showInlineError%22%3Afalse%7D&theme=material)? It seems to work there.

**Comment by Roshdy** [comment]
Actually the schema structure in the playground is very minimal. I'm using a very deep structured schema with multiple sub schemas, and those have sub schemas as well.

I attached a screenshot showing `fullWidth={false}`, yet, it's taking the full width!

The schema attached goes along the structure:
 ```
  GeneralInfoSchema = new SimpleSchema({ idType: {},.... })
  personalInfoSchema = new SimpleSchema({ generalInfo: GeneralInfoSchema, ... })
  actualAutoFormSchema = new SimpleSchema({
      personalInfo: {
        type: personalInfoSchema,
        label: false,
        uniforms: {
          fullWidth: false,
          className: classes.container
        }
      },
      ...
  })
```

_personalInfoSchema // =  new SimpleSchema({ ... generalInfo: new SimpleSchema({..._

and i call it like this `<AutoField name={'personalInfo'}/>`

### Note: 
className{classes.container} doesn't get added to FormControl wrapper for personalInfo

![image](https://user-images.githubusercontent.com/996233/47785393-a2336c00-dd19-11e8-85bc-bb91c4066871.png)

**Comment by radekmie** [comment]
Hi @Roshdy. As you can see in the [source of `SelectField` in `uniforms-material`](https://github.com/vazco/uniforms/blob/master/packages/uniforms-material/src/SelectField.js), the `fullWidth` prop is simply passed to the Material-UI - there are no styles involved. If you can provide a small runnable reproduction, which clearly shows the issue - I'm happy to work with that.

**Comment by Roshdy** [comment]
Actually i managed to make it work using AutoField**s**  instead of AutoField.

I have another issue with rendering FormControl as the parent for AutoFields lvl3 sub schemas tho, but that's off topic.
I'll give a same working code for the solutions shall anyone face the same problem
Thank you for your support, I'll be around for a while until I'm done with my project 😁

**Comment by radekmie** [comment]
I understand it's clarified and solved now, so I'm closing.
