### ISSUE TITLE
Allow passing props to material-ui's InputLabel

### ISSUE THREAD

**Issue by Floriferous** [vazco/uniforms#481]
We're using the material-ui variant of uniforms, and we've had the issue where we want to use `displayEmpty` of the Select, which conflicts with the InputLabel, as can be seen in this issue: https://github.com/mui-org/material-ui/issues/12336

The `shrink` prop on `InputLabel` would fix it, but there's currently no way to customize it, as all `SelectField` props are spread on the `Select` component only.

Not sure what's best, picking all props that should be on InputLabel (`shrink` `required` `disableAnimation` for example), or spread a new prop `labelProps` ?

**Comment by radekmie** [comment]
Hi @Floriferous. Sounds good, as long as each `InputLabel` will be handled, not only the `SelectField` one. In this case, `labelProps` would be better, as there might be conflicts in prop names. Would you like to submit a PR for that?

**Comment by radekmie** [comment]
Closed in #485.
