### ISSUE TITLE
DisplayIf only works once

### ISSUE THREAD

**Issue by Roshdy** [vazco/uniforms#483]
I have the following setup:

```
// DisplayIf.jsx
import BaseField  from 'uniforms/BaseField';
import connectField from 'uniforms/connectField';
import nothing    from 'uniforms/nothing';
import {createElement} from 'react';
import filterDOMProps from 'uniforms/filterDOMProps';
filterDOMProps.register('subComponent', 'condition');

class CompositeField extends BaseField {
  shouldComponentUpdate() {
    console.log(arguments);
    return true;
  }
};
const DisplayIf = (props, {uniforms}) => (
  props.condition(uniforms)? createElement(props.subComponent, props) : nothing
);
DisplayIf.contextTypes = BaseField.contextTypes;

export default connectField(DisplayIf, {baseField: CompositeField, includeInChain: false });
```

```
// Main schema ==> info.personalInfo
// personalInfo ==> subSchema
// surveyInfo ==> sub-subSchema
surveyInfo = new SimpleSchema({
  isForeignTax: {
    type: Boolean,
    label: i18n.t('isForeignTax', { lang }),
    // allowedValues: yesNo,
    uniforms: {
      fullWidth: false,
      appearance: "toggle"
    }
  },
  foreignTaxList: {
    type: Array,
    maxCount: 3,
    uniforms: {
      component: DisplayIf,
      condition: context => context.model.personalInfo.surveyInfo.isForeignTax,
      subComponent: List,
      paperClass: classes.listPaper,
      className: classes.list
    }
  },
  "foreignTaxList.$": {
    type: String
  }
});
```

### Problem:

- Initially `foreignTaxList` is not rendered (correct behavior)
- First time `isForeignTax` is toggled --> `foreignTaxList` is rendered (correct behavior)
- **From here on (unexpected)** when `isForeignTax` is toggled back to false --> `foreignTaxList` is not re-rendered **[`DisplayIf` doesn't get called]**!
- If I click on the '+' on the list, the `DisplayIf` get's called, so it disappears (partly correct)
- When i re-enable `isForeignTax` toggle (set to true), nothing happens **[`DisplayIf` doesn't get called]** and I can never display the list until I refresh

What am I doing wrong?

I tried extending `BaseField` like you mentioned [here](https://github.com/vazco/uniforms/issues/108#issuecomment-251303797), but `console.log(arguments)` doesn't get called in the same scenarios mentioned earlier (extending has no benefit at all in my case)

**Comment by Roshdy** [comment]
it's worth noting that after submit (failure submit), the auto validation makes it work perfectly

**Comment by Roshdy** [comment]
Another weird behavior, I linked the `model` to `redux`, now it workes perfectly!
But the model still holds the data for ommited field `foreignTaxList` :(

**Comment by radekmie** [comment]
Hi @Roshdy. Why is your `DisplayIf` using `connectField`? It's not a field, at all.

It works with Redux you say - how were you using it before? Within an `AutoForm`?

Yes, it keeps this value, cause `DisplayIf` is only not rendering it, if needed.

**Comment by Roshdy** [comment]
Hi @radekmie 

I'm using `connectField` to get the `uniforms` context & `props`
It's implemented as so:

```
import BaseField  from 'uniforms/BaseField';
import connectField from 'uniforms/connectField';
import nothing    from 'uniforms/nothing';
import {createElement} from 'react';
import filterDOMProps from 'uniforms/filterDOMProps';
filterDOMProps.register('subComponent', 'condition');

const DisplayIf = (props, {uniforms}) => (
  props.condition(uniforms)? createElement(props.subComponent, props) : nothing
);
DisplayIf.contextTypes = BaseField.contextTypes;

export default connectField(DisplayIf, {includeInChain: false });
```
I tried using AutoForm before yes, without doing anything with the form's data, but since the actual usage at the end of the project I'll be using redux. So i integrated redux state with the form model, and now it works fine!
I don't know if that is a workaround or a requirement for it to work. 
Currently my problem has vanished after using `model=redux.state`

**Comment by radekmie** [comment]
Using `contextTypes` is enough to get the context. It doesn't need field related props too, therefore `connectField` not needed. If it's still relevant, please prepare a reproduction: used form component is crucial here. If not, I guess everything is clear.

**Comment by radekmie** [comment]
No answer so far, closing.
