### ISSUE TITLE
Select existing object instead of editing in NestedField

### ISSUE THREAD

**Issue by narigondelsiglo** [vazco/uniforms#484]
I have a collection of trips, one of vehicles, and another one with passengers.
In trip schema I have nested vehicle property and passengers collection.

I would like to show the users some sort of Select2 control, so them can select an existing vehicle (which is copied to the master object I'm editing), instead of showing vehicle's edit form nested.

Is there a way to do this?

Thank you, this software is GREAT!

**Comment by radekmie** [comment]
Hi @narigondelsiglo. If I understand you correctly, you'd like to fill `SelectField` values with some DB references (ID, etc.), right?

If not, please explain it a bit more in detail.

If so, it was asked a few times already and you can look for it in some older issues. In short, you download and prepare the data by yourself and use it in `allowedValues` or `options`.

**Comment by radekmie** [comment]
No answer so far, closing.

**Comment by narigondelsiglo** [comment]
Hi, thanks for the quick answer! 

What I am looking for is a control which loads the options dynamically, because in some cases I will need to handle thousands of records. The select2 or whatever control with autocomplete fits right, but what I was asking is for a uniform implementation.
Take for example an Invoice which has an array of Products: the products live in a collection with it's own (living, continuosly mutating) data, the price for example. On the other hand in my Invoice I copy the products objects with the price at the time the invoice was generated.

Didn't have time to answer earlier, but I will take your comments, and search closed issues (again) looking for an example solution.

Thank you again! great project!

**Comment by radekmie** [comment]
If it's about integration with other components: simply use [`connectField`](https://github.com/vazco/uniforms/blob/master/API.md#connectfield) (there are many examples in the docs and issues).
