### ISSUE TITLE
Placeholder stuck

### ISSUE THREAD

**Issue by gemmi-arts** [vazco/uniforms#486]
Hello,

I don't know why but sometimes my select placeholder stuck like on example bellow.
Do have any ideas why it happens?

![uniforms](https://user-images.githubusercontent.com/8410173/48427527-36b1bb80-e769-11e8-9f29-a522de41efa1.gif)

**Comment by radekmie** [comment]
Hi, @gemmi-arts. I've tried to reproduce this behavior but I couldn't either on [uniforms.tools](https://uniforms.tools), nor in a project when it's used. Can you provide a reproduction?

**Comment by gemmi-arts** [comment]
Hi @radekmie 
I couldn't find time to reproduce me example by I found another related bug.

Please change uniforms.tools field type to Number and provide Euler's number (e). 
(uniforms-material)

<img width="546" alt="zrzut ekranu 2018-11-21 o 08 33 45" src="https://user-images.githubusercontent.com/8410173/48825611-2e104500-ed68-11e8-97bb-92a4a081cb2d.png">

**Comment by radekmie** [comment]
Indeed, it's having some problems with parsing, so there's `''` in the state, but _something_ in the input. And to be exact, it's not Euler's number, but an exponent.

**Comment by radekmie** [comment]
As I've checked, it's normal behaviour among browsers, as `e` is a _valid_ number, but not a value. You can read about it in the Material-UI [docs](https://material-ui.com/demos/text-fields/#limitations):

> The input label "shrink" state isn't always correct. The input label is supposed to shrink as soon as the input is displaying something. In some circumstances, we can't determine the "shrink" state (number input, datetime input, Stripe input). You might notice an overlap.
>
> To workaround the issue, you can force the "shrink" state of the label.

Therefore I suggest using the `shink` prop and closing this issue.
