### ISSUE TITLE
"Can't perform a React state update on an unmounted component" after unmounting in onSubmit

### ISSUE THREAD

**Issue by pixlol** [vazco/uniforms#490]
Hi,

I am using a quite simple ValidatedForm in a component, which unmounting from the parent component is triggered by the onSubmit handler.
I always get an "Can't perform a React state update on an unmounted component" warning when I submit the form. It looks like this is triggered by the setState in line 156 of ValidatedForm.js.

Am I doing something wrong? Is there a way to prevent this setState from happening?

My code looks like this:
```
<ValidatedForm schema={this.createSchema()}
  validate="onChange"
  model={this.state.mapping}
  onChange={this.handleFormChange}
  onSubmit={this.handleFormSubmit}
  >
```

Thanks for input regarding this issue and for the great package in general!

**Comment by radekmie** [comment]
Hi @pixlol. Indeed, if you unmount it right after submit, that `setState` is neither needed nor valid.

**Comment by pixlol** [comment]
Well, I do some validation on the formData and error display first in the submit handler. But this should not be the problem right?

**Comment by pixlol** [comment]
Great! Thank you very much!
