### ISSUE TITLE
How to trim values with SimpleSchema2

### ISSUE THREAD

**Issue by sabativi** [vazco/uniforms#494]
Hello,

I am using this package to handle all my forms, it is top notch.

One question remaining is that I found that fields are not trim by default, whereas I thought that it was done automatically with SimpleSchema.

For example this schema

```
const loginSchema = new SimpleSchema({
  email: {
    type: String,
    label: "Votre adresse email",
    regEx: SimpleSchema.RegEx.EmailWithTLD
  },
  password: {
    type: String,
    label: "Votre mot de passe"
  }
});
```

and this Form

```
<AutoForm
           showInlineError
            schema={loginSchema}
            onSubmit={this.handleSubmit}
            onSubmitFailure={error => {
              log.error(error.reason);
            }}
          >
            <AutoField name="email" />
            <AutoField name="password" type="password" />
</AutoForm>
```

When I type an email with an extra space, my API return user not found because of the extra space.

My question is : is there any way to handle this correctly ?

Thanks

**Comment by radekmie** [comment]
Hi @sabativi. As it's schema-dependent, it's not done in the core. In SimpleSchema, both old and new one, there's a `schema.clean(model)` method. More info about it is in the documentation of these packages. From the uniforms site, you can do it manually in the submit handler (remember not to mutate the argument), or with `modelTransform`:

```js
<AutoForm modelTransform={modelTransform} {...props />

function modelTransform(mode, model) {
  // It's not mutating by default in SimpleSchema@2, but not in @1.
  return mode === 'submit' ? schema.clean(model) : model;
}
```

**Comment by sabativi** [comment]
This is awesome, thank you so much.
