### ISSUE TITLE
Ability to pass variant prop to Material-UI SelectField to support other field types

### ISSUE THREAD

**Issue by skirunman** [vazco/uniforms#495]
Material-UI 3 now supports Selects with both the new Outlined and Filled text field variants when used with [Select React component](https://material-ui.com/api/select/), see [demo](https://material-ui.com/demos/selects/#simple-select).

However, it does not seem that Uniforms MUI SelectField supports ability to pass in the `variant` prop such as `variant="outlined"` like you can with `fullWidth` or `required` props. The MUI [FormControl component](https://material-ui.com/api/form-control/) supports the `variant` prop so maybe just adding this prop to `SelectField` with logic for `input` is what is required. 

If there is another way to support using these field variants today please let me know or if this will require a PR.

**Comment by radekmie** [comment]
Hi @skirunman. Yes, it should be included in the theme. The reason for it is that most of the fields are rendering at least two elements. Therefore there's at least a bunch of props passed into a _wrong_ component. As @janowsiany already made a PR which cannot be merged yet (but we are working on it), a smaller one is also welcome.

**Comment by skirunman** [comment]
@radekmie Would it be possible to release this now as `uniforms-material 2.0.0`, i.e. a breaking change release for those users that are using React 16.2+? [React 16.2 has been out for over a year](https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html) so I'd assume most active developers are already using a version of React with support for `Fragments`. Thanks!

**Comment by radekmie** [comment]
Well, it's definitely _possible_. The thing is, I wanted to keep version 2 for a major release of the core package and then switch to independent versioning (and increase minimum versions a lot). For now, let's keep it as it is.

**Comment by skirunman** [comment]
I'd argue that it makes sense to decouple the versioning of the theme packages from the core package and it sounds like you agree, but want to wait until a major update to the core. 

But if you don't want to do that now any suggestions on how to "fix" this issue as `uniforms-material 1.29.0` does really support the latest versions of Material-UI. Material-UI is changing rapidly, including breaking API changes and versions of React supported, so we really need some way to stay up to date with the latest versions with ideally not having to fork our own version. Thanks!
