### ISSUE TITLE
create form from graphql mutation type?

### ISSUE THREAD

**Issue by macrozone** [vazco/uniforms#499]
I am playing around with building forms from graphql schemas. An obvious usecase would be to create  a form based on a mutation, but the examples only mentions forms from types.

If your mutation has only one argument and if this argument is an object, its possible to do this. Consider the following schema:

```

type Mutation {
  addAddress(address: Address, isPublic: Boolean): String
}

input Address {
  street: String,
  verified: Boolean,
  number: Int,
  city: String,
  contact: User
}

input User {
  firstname: String,
  lastname: String
}

```

you then can create your bridge:

```
new GraphQLBridge(buildASTSchema(parse(schemastring)).getMutationType().getFields()["addAddress"].args[0].type, ....)
```

(This will be the same as 

```
new GraphQLBridge(buildASTSchema(parse(schemastring)).getType("Address"), ....)
```
)

But as mentioned, this will only make a form for the first argument of `getMutationType().getFields()["addAddress"]`

ideally, you could create a form on submit that gives you an object with all arguments, that can be easily passed to apollo's mutate or so. Maybe the resulting object could look like this (taken from the schema above):

```
 "address": {
        "street": "Römerstrasse",
        "number": 12,
        "city": "Baden",
        "contact": {
            "firstname": "Marco",
            "lastname": "Wettstein"
        },
        "verified": true
    },
    "isPublic": true
```

It would be neat, if we could autogenerate a form only by providing the name of the mutation. Any idea how to continue this idea?

**Comment by radekmie** [comment]
Hi, @macrozone. I see, that more or less you've already answered your question. Just to make it clear - I'd suggest creating a function for it:

```js
function mutationArgsType (schema, mutation) {
  const mutations = schema
    .getMutationType()
    .getFields();

  const mutationType = mutations[mutation];
  // An additional check here would be nice.
  const mutationArgs = mutationType.args;

  const fields = mutationArgs.reduce(
    (fields, arg) => Object.assign(fields, {[arg.name]: arg}),
    {}
  );

  return {getFields: () => fields};
}

new GraphQLBridge(mutationArgsType(buildASTSchema(parse(schema)), 'addAddress'));
```

**Note:** It's assuming certain shape of `graphql` and `uniforms` packages internals and may break in the future releases.

**Comment by macrozone** [comment]
maybe we should add it as helper function then, so that it does not break ;-)

**Comment by radekmie** [comment]
I'd say it's not needed in the core at all. It should be documented though.
