### ISSUE TITLE
Bootstrap forms

### ISSUE THREAD

**Issue by achtan** [vazco/uniforms#5]
add support for bootstrap forms

**Comment by radekmie** [comment]
[It's currently in progress.](https://github.com/vazco/uniforms/pull/2)

**Comment by zeroasterisk** [comment]
@achtan you're more than welcome to assist if you like

**Comment by radekmie** [comment]
There's already `bootstrap4` integration in `1.0.0-rc.4` and `bootstrap3` is planned within close future (thanks @zeroasterisk).

**Comment by zeroasterisk** [comment]
1.0.0-rc.5 is released for bootstrap4 and bootstrap3
https://www.npmjs.com/package/uniforms-bootstrap3/
https://www.npmjs.com/package/uniforms-bootstrap4/
