### ISSUE TITLE
Wrapping <ListDelField /> will cause error

### ISSUE THREAD

**Issue by TimoRuetten** [vazco/uniforms#503]
Hi!

I build a customized <ListField /> for my form and was causing this error:

"Uncaught TypeError: Cannot read property 'map' of undefined"
"The above error occurred in the <ListDelField> component"

I was going crazy because I did not understand where the problem was. This was the structure:

```html
<ListField
  name="url.urls"
  disabled={false}
  label={false}
>
  <ListItemField
    name="$"
    disabled={false}
    label={false}
  >
    <div style={{ float: 'right' }}>
      <ListDelField
        name=""
      />
    </div>
    <NestField disabled={false} name="">
      <Segment>
        <FormInputs.Group>
          <FormInputs.Item inline>
            <FormInputs.Label center>Request type</FormInputs.Label>
            <FormInputs.Input>
              <SelectField name="requestType" />
            </FormInputs.Input>
          </FormInputs.Item>
          <FormInputs.Item inline>
            <FormInputs.Label center>Uri</FormInputs.Label>
            <FormInputs.Input>
              <TextField name="uri" />
            </FormInputs.Input>
          </FormInputs.Item>
        </FormInputs.Group>
      </Segment>
    </NestField>
  </ListItemField>
</ListField>
```

I was trying and trying and ended up in removing the wrapping <div> around <ListDelField />. After doing this the error disappears. When I add again the wrapping <div> the error comes back. I am a bit confused why this happens? 

The <ListDelField /> includes the parent as far as I can see. So I tried to add also the 'name=""' property to the div just in case "includeParents" only reads out the properties from the direct parent but this does not work at all.

Dont know if I am missing here something or if this is an error. Maybe some of you could clearify this?

**Comment by TimoRuetten** [comment]
Edit: I also thought that maybe the <ListItemField /> only wants 1 component to render as its Child. But Also this does not work when I wrap the whole content of <ListItemField /> with a div so only 1 child gets rendered the same error comes up.

**Comment by radekmie** [comment]
Hi @TimoRuetten. Can you maybe format the code better? I can't really see, what is the structure there.

**Comment by TimoRuetten** [comment]
@radekmie Sorry for that. Did forget to specifiy that its html.

**Comment by TimoRuetten** [comment]
Hey @radekmie I forgot to say that the error only shows up when I click on the "add" button - not when rendering the form.

**Comment by TimoRuetten** [comment]
Of course @radekmie . Thanks.

Here you go:

- React:  ^16.4.2
- uniforms":  ^1.25.0,
- uniforms-semantic":  ^1.25.0

Schema:

```javascript
const Url = new SimpleSchema({
  uri: {
    type: String,
  },
  requestType: {
    type: String,
    allowedValues: [
      'GET',
      'POST',
    ],
    defaultValue: 'GET',
  },
  body: {
    type: String,
    optional: true,
  },
  header: {
    type: Array,
    optional: true,
    minCount: 0,
  },
  'header.$': {
    type: Array,
    minCount: 2,
    maxCount: 2,
  },
  'header.$.$': {
    type: String,
  },
  formValues: {
    type: Array,
    optional: true,
    minCount: 0,
    custom() {
      if (this.siblingField('requestType').value === 'GET' && this.value && this.value.length) return 'notAllowed';
      return false;
    },
  },
  'formValues.$': {
    type: Array,
    minCount: 2,
    maxCount: 2,
  },
  'formValues.$.$': {
    type: String,
  },
});
const Endpoint = new SimpleSchema({
  urls: {
    type: Array,
  },
  'urls.$': {
    type: Url,
  },
  format: {
    type: String,
    allowedValues: ['json', 'xml', 'csv'],
    defaultValue: 'json',
  },
  itemsKey: {
    type: String,
    optional: true,
  },
});

const ImportEndpointUrlSchema = new SimpleSchema({
  type: {
    type: String,
    allowedValues: [
      'google-drive',
      'url',
    ],
    defaultValue: 'url',
  },
  url: {
    type: Endpoint,
    optional: true,
    custom() {
      if (this.field('type').value === 'url' && (!this.value || !this.value.length)) return 'required';
      return false;
    },
  },
  googleid: {
    type: String,
    optional: true,
    custom() {
      if (this.field('type').value === 'google-drive' && (!this.value || !this.value.length)) return 'required';
      return false;
    },
  },
});
```

The FormInput.Group / Item / Label .. components are only styled div wrapper without any kind of logic. UI only.

**Comment by TimoRuetten** [comment]
Edit:
Here is a more clean react render return without the addition components wrapping anything:


```html
<AutoForm
          schema={importEndpointUrlsSchema}
          model={{}}
          onSubmit={this.handleSubmit}
        >
<ListField
  name="url.urls"
  disabled={false}
  label={false}
>
  <ListItemField
    name="$"
    disabled={false}
    label={false}
  >
    <div style={{ float: 'right' }}>
      <ListDelField
        name=""
      />
    </div>
    <NestField disabled={false} name="">
      <AutoField name="requestType" />
      <AutoField name="uri" />
    </NestField>
  </ListItemField>
</ListField>
</AutoForm>
```

**Comment by radekmie** [comment]
OK, found it. There is a problem with this structure. The thing is, that both `ListField` and `ListItemField` are using the `includeInChain` option, which is a special case of deriving names. To fix it, either move `ListDelField` under the `NestField` or use `<ListDelField name="url.urls.$" />` - both works. I hope this solves your problem.

It's a complex solution, therefore hard to debug. It should be simplified if possible, or at least documented... Definitely something worth a note.

**Comment by TimoRuetten** [comment]
Thanks for the quick response @radekmie . The first solution you provided to move ListDelField under the NestField I already tried. This will cause another problem: when the del fields uses parent.change method to set the new array value the parent <AutoForm /> will receive the changes and onChange get triggered. But: Then the <ListDelField /> does NOT get rerendered. So if you have more then 1 items in your array the second will not get removed. Sometimes it worked but at the very end it was always impossible to remove the last item because parent.value gets not updated in <ListDelField />. 

Rly weird and I do not fully understand why this happens. I will try the second solution you provided. But with this solution its important that the name does not get changed depending on the parent, correct? So I would have to modify the connectField options.

**Comment by radekmie** [comment]
The first situation you've mentioned is happening because `NestField` is not being updated, when it's parent changed. A workaround can include a variant of it, with slightly changed `shouldComponentUpdate`.

> But with this solution its important that the name does not get changed depending on the parent, correct? So I would have to modify the connectField options.

I'm not sure if I understand you correctly. It will work as long as it's not nested (the whole `ListField`) or it's nested in a field with `includeInChain: true` option (e.g. `NestField`).

**Comment by radekmie** [comment]
No answer so far, I'm closing. Feel free to comment anyway.
