### ISSUE TITLE
uniforms-material SelectField not displaying "required" asterisk on label 

### ISSUE THREAD

**Issue by skirunman** [vazco/uniforms#512]
Using SelectField in uniforms-material I try to pass the `required` prop to show an asterisk on the label. However, it is not displayed. Maybe`required` is not being passed correctly to [underlying MUI TextField](https://github.com/vazco/uniforms/blob/master/packages/uniforms-material/src/SelectField.js#L55).

I verified that both `select` and `required` props are passed correctly to MUI TextField on [MUI doc website](https://material-ui.com/demos/text-fields/), which does display the asterisk correctly on the label. May want to double check this works correctly with other fields built on MUI TextField like DateField.

SelectField was refactored in PR https://github.com/vazco/uniforms/pull/505.

**Comment by skirunman** [comment]
@radekmie Glad this was merged, what is timeframe to release? Thanks.

**Comment by radekmie** [comment]
@skirunman there's no rigid release schedule. Most probably this week.

**Comment by skirunman** [comment]
@radekmie Great, thanks.
