### ISSUE TITLE
Show versions running in playground

### ISSUE THREAD

**Issue by skirunman** [vazco/uniforms#513]
In the [demo playground ](https://uniforms.tools/) it would be very helpful to show the version of `uniforms` and the various wrapper packages such as `uniforms-material` that are actually deployed and running. This will help avoid any issues reported that are not related to a specific or the latest version.

**Comment by radekmie** [comment]
Hi @skirunman. It won't be a problem in the new docs (#259, branch [`new-docs`](https://github.com/vazco/uniforms/tree/new-docs)), as it'll be automatically deployed, along with the documentation itself.

**Comment by skirunman** [comment]
I still think you should show the version number in the docs. This seems to be a standard practice and is done for both Meteor and Material-UI.

**Comment by radekmie** [comment]
I'm pretty sure it'll be easy to do it (both `package.json` version and the commit) as a Docz plugin.
