### ISSUE TITLE
NumField - AutoForm

### ISSUE THREAD

**Issue by khaledbk** [vazco/uniforms#516]
`
import AutoForm from 'uniforms-material/AutoForm';`

`import NumField from 'uniforms-material/NumField';
`

Hi, Im trying to use the `AutoForm` . In this form i use the `NumField` . The problem that i have is that the `NumField` convert this field value to a string type, is there any solution to have a `Int` type instead of a string in the model of the Form ?

**Comment by simplecommerce** [comment]
From our tests, this is what we have found out.

We are using the material-ui package for uniforms.
On AutoForm we have put his code: 

```
onChange={(key, value) => {
  console.log(key, value);  
})
```

We can see the log of the key being changed, and its numeric.

And with modelTransform we did a console.log of the model received, and the number changes to a string.

The versions used are: 

"uniforms": "^1.31.0",
"uniforms-material": "^1.31.0"

With 

"@material-ui/core": "^3.9.2",

I have tried to figure out where the bug occurs, but can't seem to find where it actually changes in your code.

**Comment by radekmie** [comment]
Hi @khaledbk and @simplecommerce. As GraphQL schema (which I assume, based on your screenshot) is not related here, here's the issue: [`NumField#33`](https://github.com/vazco/uniforms/blob/master/packages/uniforms-material/src/NumField.js#L33). In all other themes, either the UI component takes care of it (AntD) or there's an additional wrapper (like in [`uniforms-unstyled`](https://github.com/vazco/uniforms/blob/master/packages/uniforms-unstyled/src/NumField.js)). Would you like to submit a PR for it?

**Comment by simplecommerce** [comment]
Hi @radekmie appreciate your response, although I am not quite I understand what the issue is?

We have been using this package and have implemented it for a while now and never had this problem until today with the NumField? 

So I am wondering what changed exactly or how to fix it?

Thanks!

**Comment by radekmie** [comment]
It looks like it was broken since #427, when the `Num` class got removed. Maybe it changed with the newer version of MUI? I'm not sure. Anyway, the thing that needs to be done is to bring back the `Num` class. If you are still not sure about it, I'll get to it tomorrow.

**Comment by simplecommerce** [comment]
Ok thanks for letting me know, I wasn't sure if it was was actually a bug
or not. But yeah it would be best if you take care of it, i am not even
sure how to do a PR, sorry about that we are still new to this and github
lol.
