### ISSUE TITLE
Currently not usable with CRA

### ISSUE THREAD

**Issue by s1rd4v3** [vazco/uniforms#518]
I recently tried out your great uniforms package together with CRA (first used it together with Meteor). It turns out that you are using an experimental babel plugin "classProperties" which results my app to crash with the following error: 

```
SyntaxError: #MYPROJECTFOLDER#/node_modules/uniforms/src/AutoForm.js: Support for the experimental syntax 'classProperties' isn't currently enabled (11:17):

   9 | const Auto = parent =>
  10 |   class extends parent {
> 11 |     static Auto = Auto;
     |                 ^
  12 | 
  13 |     static displayName = `Auto${parent.displayName}`;
  14 | 

@babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.
```

Is there a way i can get alternative source files for uniforms as CRA [does not support experimental babel plugins](https://github.com/facebook/create-react-app/issues/4648#issuecomment-398540069)

**Comment by radekmie** [comment]
Hi @s1rd4v3. Of course there is! By default uniforms ship transpiled files on the top-level (`uniforms/AutoForm`) and the original sources in the `/src` directory (`uniforms/src/AutoForm`). It's happening because of the `jsnext:main`, but it's useful if your bundler supports it (better tree shaking out of the box).

As a workaround for now (maybe I'll have to change that) use `import X from 'uniforms/X'` instead of `import {X} from 'uniforms'` (same goes for the theme packages).

**Comment by s1rd4v3** [comment]
thanks for the quick reply! Amazing support 👍. Works with your proposal.
I know they are just warnings but is there a way to get rid off those GraphQL and Meteor "Module not found" messages?

```
Module not found: Can't resolve 'graphql' in '#PROJECTPATH#/node_modules/uniforms'

./node_modules/uniforms/SimpleSchemaBridge.js
Module not found: Can't resolve 'meteor/aldeed:simple-schema' in '#PROJECTPATH#/node_modules/uniforms'

./node_modules/uniforms/SimpleSchemaBridge.js
Module not found: Can't resolve 'meteor/check' in '#PROJECTPATH#/node_modules/uniforms'

**Comment by radekmie** [comment]
It's a known issue, regarding the static analysis of your bundler. We are working on it literally right now.

**Comment by s1rd4v3** [comment]
thanks a lot for your help 🥇

**Comment by raedle** [comment]
@s1rd4v3 You can work around it temporarily by using [react-scripts-rewired](https://www.npmjs.com/package/react-scripts-rewired) instead of CRA `react-scripts`. To suppress the warnings, I have the following `webpack.config.extend.js` configuration

```
const webpack = require('webpack');

/**
 * Uniforms causes a compiler warning when `npm start` the client project.
 *
 * Compiled with warnings.
 *
 * ./node_modules/uniforms/SimpleSchemaBridge.js
 * Module not found: Can't resolve 'meteor/aldeed:simple-schema' in '/Users/raedle/Projects/surveyr/client/node_modules/uniforms'
 *
 * ./node_modules/uniforms/SimpleSchemaBridge.js
 * Module not found: Can't resolve 'meteor/check' in '/Users/raedle/Projects/surveyr/client/node_modules/uniforms'
 *
 * Search for the keywords to learn more about each warning.
 * To ignore, add // eslint-disable-next-line to the line before.
 *
 * @param {*} webpackConfig The webpack config.
 */
const ignoreMeteorWarnings = (webpackConfig) => {
	webpackConfig.plugins.push(new webpack.IgnorePlugin(/(aldeed:simple-schema|meteor\/check)/));
	return webpackConfig;
};

/**
 * Project's customized Webpack Configuration Extension
 * ----------------------------------------------------
 *
 * this file is heavily inspired by `react-app-rewired` mechanism.
 *
 * it simply gives you the chance to hook into the default Webpack
 * configuration as it is provided by `create-react-app`, and to
 * change it so to match your project's needs.
 *
 * If you want to check out the default values look into:
 * `./node_modules/marcopeg-react-scripts/config/webpack.config.${env}.js`
 *
 */
module.exports = (webpackConfig, webpackEnv, { paths }) => {
	// Uniforms causes a compiler warning when `npm start` the client
	// project. This will suppress the warnings.
	webpackConfig = ignoreMeteorWarnings(webpackConfig);

	return webpackConfig;
};
```
