### ISSUE TITLE
AutoForm does not correctly validate fields with initial value

### ISSUE THREAD

**Issue by abuddenb** [vazco/uniforms#52]
Hello there,

I'm trying to pass data to hidden fields in an AutoForm by setting the value prop:

```js
<AutoField name="graphics_title" value="somestring" />
```

These fields fail validation until they're manually changed. What am I doing wrong?

**Comment by radekmie** [comment]
Actually, it's not implemented right now to do so - [initial values are taken from your schema](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/helpers/connectField.js#L22-L29). It seems reasonable, to cover your case - given value (if present on first render) should be treated as initial. I'll do it later today.

**Comment by radekmie** [comment]
Also, you've mentioned hidden fields... It would be great, to add dedicated component to achieve it. I'm curious, how you deal with those. Would you like to create another issue for that?

**Comment by abuddenb** [comment]
I did this:

```
const Hidden = props =>
    <input type="text" name={props.name} value={props.value} onChange={event => props.onChange(event.target.value)}/>;

const HiddenField = connectField(Hidden, {
    baseField: BaseField,
    initialValue: true
});
```

**Comment by radekmie** [comment]
Okay. How about a _really_ hidden field? By _really_ I mean _invisible_ - `type="hidden"`. Also with an option to switch to `noDOM` mode. Would you like to create another issue? I can also do it by myself.

**Comment by abuddenb** [comment]
Done: #53.

I'm new to React from Meteor. When you implement initial values, will it matter if the initial value comes from a reactive collection? Ex:

`<HiddenField name="graphics_id" value={this.context.graphic._id? this.context.graphic._id : ''}/>`

this.context.graphic._id will be an empty string when the page first loads.

**Comment by radekmie** [comment]
Yes, it will matter - initial values are calling `onChange` **only** after their first render.

**Comment by abuddenb** [comment]
So will `onChange` detect the updated initial value?

**Comment by radekmie** [comment]
No. If it will change, it won't be initial value at that time. You have to either wait with render or (what you probably want), use upcoming `HiddenField`, that will automatically call `onChange`, when its value will change.

**Comment by serkandurusoy** [comment]
changing the "visibility" of a field or its container using css causes some
browsers to completely ignore that field!

that's why there is a type=hidden in the html spec.

On Tue, Jun 28, 2016 at 10:56 PM, Radosław Miernik <notifications@github.com
