### ISSUE TITLE
i8n

### ISSUE THREAD

**Issue by adrianschneider94** [vazco/uniforms#521]
Great package! Really!

Are there any plans on internationalisation?

Best wishes!

**Comment by radekmie** [comment]
Hi @adrianschneider94. What exactly you'd like to internationalize? All visible texts are configurable, most of them are based on your schema, which is schema-dependent. Components are both configurable (like labels or icons) and replaceable (more text, different layout per language).

**Comment by adrianschneider94** [comment]
@radekmie
Oh, sorry — I should have been more specific. The validation errors.

**Comment by radekmie** [comment]
These are also coming from the schema (or the validator directly). It's all schema-dependent, for example, [ajv-i18n](https://github.com/epoberezkin/ajv-i18n) can be used with [ajv](https://github.com/epoberezkin/ajv) and `JSONSchemaBridge`.

**Comment by adrianschneider94** [comment]
Yeah, I just recognized...
I was too quick with opening an issue.
Sorry for that.
Thanks for the fast response!
