### ISSUE TITLE
SubmitField doesn't respect children

### ISSUE THREAD

**Issue by ChakirMrabet** [vazco/uniforms#523]
For Material-UI, This:

```javascript
<SubmitField>SAVE</SubmitField>
```
Still makes the button to show up with the text "SUBMIT", even though from the `SubmitField` source code I see that your intention was to show `children` when defined. 

I think you have an error in your `SubmitField`  code, this:

```javascript
....
const SubmitField = ({children, disabled, inputRef, label, value, ...props}, {uniforms: {error, state}}) => (
  <Button
    disabled={disabled === undefined ? !!(error || state.disabled) : disabled}
    ref={inputRef}
    type="submit"
    value={value}
    {...filterDOMProps(props)}
  >
    {label || children}
  </Button>
);
SubmitField.contextTypes = BaseField.contextTypes;

SubmitField.defaultProps = {label: 'Submit', variant: 'contained'};

export default SubmitField;
```

Should be this:

```javascript
...
const SubmitField = ({children, disabled, inputRef, label, value, ...props}, {uniforms: {error, state}}) => (
  <Button
    disabled={disabled === undefined ? !!(error || state.disabled) : disabled}
    ref={inputRef}
    type="submit"
    value={value}
    {...filterDOMProps(props)}
  >
    {children ? children : label}
  </Button>
);
SubmitField.contextTypes = BaseField.contextTypes;

SubmitField.defaultProps = {label: 'Submit', variant: 'contained'};

export default SubmitField;
```
`{label || children}` will be always `label` since it's defined as default.

I've tested and works.

**Comment by radekmie** [comment]
Hi @ChakirMrabet. Indeed, there is a small inconsistency, especially between packages, as AntD and Material have their own components, and the rest is using simple `<input type="submit">`. Anyway, you can workaround this with `label=""` and using `children`, or using `label` directly.

It should be changed for the next version though. If you'd like to submit a PR for it, go ahead - just do it to branch `v2`.

**Comment by radekmie** [comment]
It'll be part of the v2 release.
