### ISSUE TITLE
Submission error appears briefly, then disappears

### ISSUE THREAD

**Issue by Floriferous** [vazco/uniforms#526]
I'm having an issue where an error thrown inside the `onSubmit` promise appears briefly (<500ms) and then disappears.

When I log `context.uniforms.error` I can see it is set correctly, but very quickly is set back to `null`.

I don't have a reproduction atm, but what could cause this to happen? Where is the submission error saved and overwritten, I can't find it in the source code?

**Comment by radekmie** [comment]
Hi @Floriferous. It's very possible, that its props changed - just look at [the code](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/ValidatedForm.js#L78-L97). Can you check that?

**Comment by radekmie** [comment]
Two weeks later and no response. If you'll find something @Floriferous, feel free to write it here.
