### ISSUE TITLE
Optimal simple schema initialization

### ISSUE THREAD

**Issue by Floriferous** [vazco/uniforms#527]
I'm not sure where it's mentioned that you should import `uniforms` before using simple schema for the `uniforms` key to work, but it seems you can simply do `import 'uniforms/SimpleSchema2Bridge';`, which also works.

This removes a big chunk from your bundle initially, if you don't load any uniforms form on your first page.

Maybe this can be added to the readme somewhere?

**Comment by radekmie** [comment]
Hi @Floriferous. It's already clear in v2, as it's a separate package and the migration guide includes this info. If you think it's not enough - PRs with docs change are welcome.
