### ISSUE TITLE
no input possible in <TextField> when wrapped inside Pose component

### ISSUE THREAD

**Issue by monkeydri** [vazco/uniforms#528]
[Pose](https://popmotion.io/pose) is a  library to make animations. It uses props passed to Pose components as triggers for styles. Pose components are created from standard HTML and React components with the `posed` method.

```js
import posed from 'react-pose';
const Field = posed.li({ open: { opacity: 1 }, closed: { opacity: 0 }});
```
When wrapped inside a Pose component such as `Field`, `TextField` does not allow keyboard input, it works ok for `NumField`.

```js
import SimpleSchema from 'simpl-schema';
import AutoForm from 'uniforms-unstyled/AutoForm';
import NumField from 'uniforms-unstyled/NumField';
import TextField from 'uniforms-unstyled/TextField';

const schema = new SimpleSchema(
{
	delay:
	{
		type: Number,
		min: 0,
		max: 62
	},
	email:
	{
		type: String,
	}
});
```

```jsx
<AutoForm schema={schema}>
	<Field>
		<NumField name="delay"/>
	</Field>
	<Field>
		<TextField name="email"/>
	</Field>
</AutoForm>
```

If putting `<TextField>`s as direct children of `<AutoForm>` both form works well.

Tried several things but I am starting to lose my hair on this issue...

**edit** : I updated the issue to narrow the issue to `<TextField>` rather than `<AutoField>`. Original title : no input possible in <AutoField> of type text when wrapped inside Pose component.

**Comment by monkeydri** [comment]
from React Dev tool the difference between the two corresponding `<input>`s (for `<NumField>` and `<TextField>`) is that the `onChange` method does not seem bounded for `<TextField>` :

- `<TextField>` => onChange: onChange()
- `<NumField>` => onChange: bound onChange()

**Comment by monkeydri** [comment]
After looking at the source code for [TextField](https://github.com/vazco/uniforms/blob/master/packages/uniforms-unstyled/src/TextField.js) and [NumField](https://github.com/vazco/uniforms/blob/master/packages/uniforms-unstyled/src/NumField.js) I start to wonder if this is not related to class-properties.

I am using [CRA](https://github.com/facebook/create-react-app) and class-properties [are not enabled](https://github.com/facebook/create-react-app/issues/4648) for 3rd party code. Therefore I had to import using relative module path (see #518) :

> use import X from 'uniforms/X' instead of import {X} from 'uniforms'

**Comment by monkeydri** [comment]
Well it works after refactoring  [TextField](https://github.com/vazco/uniforms/blob/master/packages/uniforms-unstyled/src/TextField.js) similary to [NumField](https://github.com/vazco/uniforms/blob/master/packages/uniforms-unstyled/src/NumField.js), will submit a PR.

**Comment by radekmie** [comment]
Hi @monkeydri. Nice investigation! I'd like to check it by myself anyway, as it sounds pretty weird.

**Comment by monkeydri** [comment]
Turned out as soon as the `setState` call is added (inside `<TextField>` own `onChange` method) it works.

So my guess would be that it is not a bind onChange problem but rather something not being updated (no re-`render`), perhaps because Pose components use `PureComponent` or something.

**Comment by radekmie** [comment]
OK, I've found it. The problem is completely different (but, unfortunately, your workaround works (*)). The problem is because uniforms are still using the old context API and `react-pose` is using `PureComponent`. It's one of the reasons, which _caused_ the new context API. The old context API have to go through the whole tree _somehow_. It works for `NumField`, because it's refreshing automatically (by `setState`) and then pulling the latest context. It's not working in the `TextField` (and almost every other field) as it's updating the context and the update is not _coming back_ from the form. 

(*) Unfortunately, because it only _seems_ OK. I'll have to reject your PR, as it's a hacky workaround, which I'm now trying to get rid of.

It'll definitely won't be a problem when uniforms will switch to the new context API, but it'll take some time.

**Comment by radekmie** [comment]
OK, I have a workaround ([codesandbox.io sample](https://codesandbox.io/s/ox9ooljqo9)):

```js
const Model = ({children}, {uniforms: {model}}) => children(model);
Model.contextTypes = BaseField.contextTypes;

function App() {
  return (
    <AutoForm schema={schema}>
      <Model>
        {model => (
          <React.Fragment>
            <Field>
              <NumField name="delay" />
            </Field>
            <Field>
              <TextField name="email" />
            </Field>
          </React.Fragment>
        )}
      </Model>
    </AutoForm>
  );
}
```

Yes, it is hacky. And yes, it's not the most performant solution. But it works. The key problem here (again) that uniforms are not using the new context API. For now, it's a working and mostly clean workaround - you can just wrap it inside one component.

**Comment by monkeydri** [comment]
> (*) Unfortunately, because it only _seems_ OK. I'll have to reject your PR, as it's a hacky workaround, which I'm now trying to get rid of.

No problem ! I know it was hacky, I did not really understand it. I pushed it so I could use quickly in my project (deadline is yesterday...) and the PR was more the the record.

Thanks for your super quick feedback !
