### ISSUE TITLE
Provide HiddenField component

### ISSUE THREAD

**Issue by abuddenb** [vazco/uniforms#53]
It would be useful in my application to provide support for `<input type="hidden"/>`

Example:

```js
<HiddenField name="graphics_id" value={this.context.graphic._id ? this.context.graphic._id : ''} />
```

**Comment by serkandurusoy** [comment]
You can provide `type="hidden"` to your `TextField` and it will become
hidden :)

**Comment by abuddenb** [comment]
I did that, as well as setting label={false}. There are issues with setting an initial value as well.

**Comment by serkandurusoy** [comment]
yes setting initial value is problematic.

but you can use the "model" attribute on the autoform for doing that.

```js
<AutoForm model={ {name: "Serkan"} } />
```

sets the "name" field's initial value to "Serkan"

**Comment by abuddenb** [comment]
Just out of curiosity, how did you figure that out? It's not in the documentation. You had to search through the code, didn't you?

**Comment by zeroasterisk** [comment]
```js
import React from 'react';
import { connectField } from 'uniforms';

const HiddenInput = props => (
  <input
    disabled={props.disabled}
    id={props.id}
    name={props.name}
    onChange={event => props.onChange(event.target.value)}
    placeholder={props.placeholder}
    type={props.type || 'hidden'}
    value={props.value}
  />
);

export default connectField(HiddenInput);
```

**Comment by radekmie** [comment]
@zeroasterisk, this won't work as intended, because that `onChange` event won't be called when `value` prop will change - you will have to change it directly in `model`.
