### ISSUE TITLE
[help] handle errors when manually submitting form.submit()

### ISSUE THREAD

**Issue by monkeydri** [vazco/uniforms#530]
I am using `<AutoForm>` with `<AutoField>`s inside and a custom submit button that triggers `form.submit()` (where form is a ref to `<AutoForm>`).

I read the docs 10 times and checked many issues but can't get it it working.

As soon as the `form.validate()` method is called, an error is thrown (when form is invalid) :

 `Unhandled Rejection (ClientError): {some-field} must be ...`

if I call `form.submit()` and use the `onValidate = (model, error, callback) => {` prop on `<AutoForm>` as described in [API](https://github.com/vazco/uniforms/blob/master/API.md#validatedform) and [Intro](https://github.com/vazco/uniforms/blob/master/INTRODUCTION.md#asynchronous-validation) I can then catch the error but it feels rather hacky or to the least not the way to go (because as I understand it `onValidate` is meant to do extra validation, ex. check if username does not already exists in DB) and also it is unreliable because it is first called with no errors whereas my form is definitely invalid.

I know I could use a `<SubmitField>` but I could not get it working plus I just would like to call `form.submit()` or `form.validate()` and get errors from it.

From [API/ValidateForm](https://github.com/vazco/uniforms/blob/master/API.md#validatedform) :

```
 // Validate form with the current model.
        //   Returns a Promise, which rejects with an validation error or
        //   resolves without any value. Note, that it resolves/rejects AFTER
        //   the component is rerendered.
        form.validate();
```

From [API/BaseForm](https://github.com/vazco/uniforms/blob/master/API.md#baseform) :

```
        // Submit form.
        //   It's a programatic equivalent of a submit event. Returns a promise,
        //   which will either resolve with submitted form or reject with
        //   validation error in ValidatedForm. You can also use onSubmitFailure
        //   and onSubmitSuccess instead of doing form.submit().then().
        form.submit();
```

Both methods are available to `<AutoForm>` because :
> Note: All ValidatedQuickForm props are also accepted and all methods are available.

while for `<ValidatedQuickForm>` :
> Note: All QuickForm props are also accepted and all methods are available.

> Note: All ValidatedForm props are also accepted and all methods are available.

while for `<QuickForm>` :
> Note: All BaseForm props are also accepted and all methods are available.

However it seems that `form.submit()` and `form.validate()` do not return promises, I used the usual `.then` and tried to check for an error there to no avail.

Do you have an example for using those methods ?

**Comment by radekmie** [comment]
Hi @monkeydri. Both `form.submit` and `form.validate` are just aliases for [`form.onSubmit`](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/BaseForm.js#L107) and [`form.onValidate`](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/ValidatedForm.js#L58) respectively, which definitely return promises. These should work as you've said. Examples are _somehow_ part of the tests: [`submit`](https://github.com/vazco/uniforms/blob/master/packages/uniforms/__tests__/BaseForm.js#L281-L375) (which is not called directly, but triggered with `simulate`) and [`validate`](https://github.com/vazco/uniforms/blob/master/packages/uniforms/__tests__/ValidatedForm.js#L41-L123).

Can you maybe prepare a reproduction (preferably on [codesandbox.io](https://codesandbox.io/))?

**Comment by monkeydri** [comment]
Here you go : https://codesandbox.io/s/8yzmnx3ln0

It seems to work as expected (*) so I am probably doing it wrong in my project. Will check again and get back to you.

(*) except for `submit()` which do not return the from values (so called model or doc) in the promise

**Comment by radekmie** [comment]
Yes, `submit` is not resolving with `model`, but it's maybe a misleading text in the docs. This promise resolves with the value that your `onSubmit` returned. This value is then passed to `onSubmitSuccess` and its result is finally resolving the `submit` promise. Below code may demonstrate it more clearly:

```js
// Somewhere in the constructor.
// this.form = React.createRef();

// const X = Symbol(); // Any value.
// const Y = Symbol(); // Any value.

<AutoForm
  ref={this.form}
  onSubmit={model => X}
  onSubmitSuccess={arg => { console.assert(arg === X); return Y; }}
/>
<button onClick={() => this.form.current.submit().then(arg => console.assert(arg === Y) )} />
```

**Comment by monkeydri** [comment]
Ah alright it makes sense ! (I just saw your message before editing mine).
