### ISSUE TITLE
AutoField does not look for schema defaultValue if value prop is passed (even null or undefined)

### ISSUE THREAD

**Issue by monkeydri** [vazco/uniforms#531]
Hi Radosław ! Yes another (minor) potential issue ;-)

In React when prop value is falsy (null, undefined...) it is *usually* considered as if the prop was not passed at all. Well it does not seem to be the case for the `<AutoField>`'s  `value` prop.

- schema :
```js
const schema = new SimpleSchema({
  delay: {
    type: Number,
    min: 2,
    max: 62,
    defaultValue: 2,
    label: "number without inital value"
  },
  duration: {
    type: Number,
    min: 2,
    max: 62,
    defaultValue: 2,
    label: "number with inital value"
  },
  email: {
    type: String,
    regEx: SimpleSchema.RegEx.Email,
    defaultValue: "default-mail@example.com",
    label: "mail without inital value"
  },
  userEmail: {
    type: String,
    regEx: SimpleSchema.RegEx.Email,
    defaultValue: "default-mail@example.com",
    label: "mail with inital value"
  }
});
```
- intial values for some fields only :

```js
const initialValues = {
  duration: 60,
  userEmail: "user-mail@example.com"
};
```

- `<AutoForm>` with `<AutoField>`s
```jsx
      <AutoForm schema={schema}>
        {Object.keys(schema.schema()).map(name => (
          <AutoField
            name={name}
            value={initialValues[name]}
          />
        ))}
      </AutoForm>
```
At first I thought that I should explicitly return undefined or null to `value` prop if no corresponding value in `initialValues` but the bug remained :

```jsx
value={initialValues[name] ? initialValues[name]: null}
value={initialValues[name] ? initialValues[name]: undefined}
```
So it looks like if one of the `<AutoField>`s have the `value` prop set then `<AutoForm>` would consider all the others `<AutoField>`should have one. hence this (kind of ugly) workaround :

```jsx
 value={initialValues[name] ? initialValues[name]: schema.schema()[name].defaultValue} 
```

https://codesandbox.io/s/3q4924m471

**Comment by radekmie** [comment]
Hi @monkeydri. It's true - any `value` is respected, even falsy ones. It's a design choice - [every prop is passed down to the field](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/BaseField.js#L225-L260). Your code though can be simplified though. To set default values in the form, use `model` prop of the form:

```js
<AutoForm model={defaultModel} schema={schema} />
```

As long as the `model` is not changed, `AutoForm` will use internal one and treat the props one as a default.

Also: instead of manually iterating over schema fields and constructing `<AutoField />`, use `<AutoFields />` - it's exactly what it's for.

**Comment by monkeydri** [comment]
Thanks again @radekmie it works great !

> Also: instead of manually iterating over schema fields and constructing `<AutoField />`, use `<AutoFields />` - it's exactly what it's for.

Yes I know (I used it at first) however I am already mapping over the schema keys anyway (to add placeholder values from another dictionary with same keys) like that : `placeholder={placeholderValues[name]}` that's why, because to my (limited) knowledge there is no way to define placeholder values in [simpl-schema](https://github.com/aldeed/simple-schema-js/).

**Comment by radekmie** [comment]
Any schema can define any additional props. In SimpleSchema it's `uniforms` property on the field definition:

```js
new SimpleSchema({
  field: {
    type: String,
    uniforms: {
      placeholder: 'Example'
    }
  }
});
```

**Comment by monkeydri** [comment]
oh man, you're the man ! I can't thank you enough, welcome `<AutoFields>` ;-)
