### ISSUE TITLE
DateField shows wrong date if not in UTC timezone

### ISSUE THREAD

**Issue by macrozone** [vazco/uniforms#532]
The DateField uses `toISOString` wich always returns the date in the 0-offset timezone and then strips away the timezone information, so this information is lost. It will therefore show the wrong date. See this example: 

https://uniforms.tools/#?preset=Welcome!&props=%7B%22autosave%22%3Afalse%2C%22autosaveDelay%22%3A100%2C%22disabled%22%3Afalse%2C%22label%22%3Atrue%2C%22placeholder%22%3Afalse%2C%22schema%22%3A%22new%20SimpleSchema(%7B%5Cn%20%20%20%20date%3A%20%7B%5Cn%20%20%20%20%20%20%20%20type%3A%20Date%2C%5Cn%20%20%20%20%20%20%20%20defaultValue%3A%20new%20Date(%5C%222019-04-23T00%3A00%3A00%2B02%3A00%5C%22)%5Cn%20%20%20%20%7D%2C%5Cn%5Cn%20%20%20%20adult%3A%20%7B%5Cn%20%20%20%20%20%20%20%20type%3A%20Boolean%5Cn%20%20%20%20%7D%2C%5Cn%5Cn%20%20%20%20size%3A%20%7B%5Cn%20%20%20%20%20%20%20%20type%3A%20String%2C%5Cn%20%20%20%20%20%20%20%20defaultValue%3A%20'm'%2C%5Cn%20%20%20%20%20%20%20%20allowedValues%3A%20%5B'xs'%2C%20's'%2C%20'm'%2C%20'l'%2C%20'xl'%5D%5Cn%20%20%20%20%7D%2C%5Cn%5Cn%20%20%20%20rating%3A%20%7B%5Cn%20%20%20%20%20%20%20%20type%3A%20Number%2C%5Cn%20%20%20%20%20%20%20%20allowedValues%3A%20%5B1%2C%202%2C%203%2C%204%2C%205%5D%2C%5Cn%20%20%20%20%20%20%20%20uniforms%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20checkboxes%3A%20true%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%2C%5Cn%5Cn%20%20%20%20friends%3A%20%7B%5Cn%20%20%20%20%20%20%20%20type%3A%20%5BObject%5D%2C%5Cn%20%20%20%20%20%20%20%20minCount%3A%201%5Cn%20%20%20%20%7D%2C%5Cn%5Cn%20%20%20%20'friends.%24.name'%3A%20%7B%5Cn%20%20%20%20%20%20%20%20type%3A%20String%2C%5Cn%20%20%20%20%20%20%20%20min%3A%203%5Cn%20%20%20%20%7D%2C%5Cn%5Cn%20%20%20%20'friends.%24.age'%3A%20%7B%5Cn%20%20%20%20%20%20%20%20type%3A%20Number%2C%5Cn%20%20%20%20%20%20%20%20min%3A%200%2C%5Cn%20%20%20%20%20%20%20%20max%3A%20150%5Cn%20%20%20%20%7D%5Cn%7D)%22%2C%22showInlineError%22%3Afalse%2C%22asyncOnSubmit%22%3Afalse%2C%22asyncOnValidate%22%3Afalse%7D&theme=material

It's date is set to midnight in the +02:00 timezone, but it will show the date yesterday.

It should probably receive a timezone or respect the local timezone to render the value

**Comment by radekmie** [comment]
Hi @macrozone. `DateField` is designed to work with the native HTML element, that's all. In most cases, you'll need to implement your own anyway. Here, the timestamp is still correct - as you've said, it just _lost_ the timezone part. As there's no way to change it anyway, you can just add this information back during submit or `modelTransform`.

Anyway, it's not within the scope of `DateField`.

**Comment by macrozone** [comment]
hey @radekmie ,

its currently in a broken state, it does not reflect the given Date correctly, so it would be better to remove the datefield completly if it won't get fixed. The only working one is the antd-version: 

go to the [demo](https://uniforms.tools/#?preset=Welcome!&props=%7B%22autosave%22%3Afalse%2C%22autosaveDelay%22%3A100%2C%22disabled%22%3Afalse%2C%22label%22%3Atrue%2C%22placeholder%22%3Afalse%2C%22schema%22%3A%22new%20SimpleSchema(%7B%5Cn%20%20%20%20date%3A%20%7B%5Cn%20%20%20%20%20%20%20%20type%3A%20Date%2C%5Cn%20%20%20%20%20%20%20%20defaultValue%3A%20new%20Date(%5C%222019-04-23T00%3A00%3A00%2B02%3A00%5C%22)%5Cn%20%20%20%20%7D%2C%5Cn%5Cn%20%20%20%20adult%3A%20%7B%5Cn%20%20%20%20%20%20%20%20type%3A%20Boolean%5Cn%20%20%20%20%7D%2C%5Cn%5Cn%20%20%20%20size%3A%20%7B%5Cn%20%20%20%20%20%20%20%20type%3A%20String%2C%5Cn%20%20%20%20%20%20%20%20defaultValue%3A%20'm'%2C%5Cn%20%20%20%20%20%20%20%20allowedValues%3A%20%5B'xs'%2C%20's'%2C%20'm'%2C%20'l'%2C%20'xl'%5D%5Cn%20%20%20%20%7D%2C%5Cn%5Cn%20%20%20%20rating%3A%20%7B%5Cn%20%20%20%20%20%20%20%20type%3A%20Number%2C%5Cn%20%20%20%20%20%20%20%20allowedValues%3A%20%5B1%2C%202%2C%203%2C%204%2C%205%5D%2C%5Cn%20%20%20%20%20%20%20%20uniforms%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20checkboxes%3A%20true%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%2C%5Cn%5Cn%20%20%20%20friends%3A%20%7B%5Cn%20%20%20%20%20%20%20%20type%3A%20%5BObject%5D%2C%5Cn%20%20%20%20%20%20%20%20minCount%3A%201%5Cn%20%20%20%20%7D%2C%5Cn%5Cn%20%20%20%20'friends.%24.name'%3A%20%7B%5Cn%20%20%20%20%20%20%20%20type%3A%20String%2C%5Cn%20%20%20%20%20%20%20%20min%3A%203%5Cn%20%20%20%20%7D%2C%5Cn%5Cn%20%20%20%20'friends.%24.age'%3A%20%7B%5Cn%20%20%20%20%20%20%20%20type%3A%20Number%2C%5Cn%20%20%20%20%20%20%20%20min%3A%200%2C%5Cn%20%20%20%20%20%20%20%20max%3A%20150%5Cn%20%20%20%20%7D%5Cn%7D)%22%2C%22showInlineError%22%3Afalse%2C%22asyncOnSubmit%22%3Afalse%2C%22asyncOnValidate%22%3Afalse%7D&theme=bootstrap3) and change to the antd-theme. The date will change from 22.04 to 23.04.

Maybe i find a way to fix it.

**Comment by radekmie** [comment]
Well, it does, in UTC. It may works in other themes, as they have built-in pickers for that. And no, it won't get removed, as it's still a _rule_ to be able to render any schema.

**Comment by macrozone** [comment]
i sent in a PR for a fix at least for the unstyled.

the datefield now renders the given Date in the local timezone same as in the antd-theme.
