### ISSUE TITLE
AntD 3.17.0 theme display inconsistencies

### ISSUE THREAD

**Issue by delyanr** [vazco/uniforms#534]
Hello,

Recently discovered `uniforms` - and it works very well. Thanks for the hard work!

Unfortunately, I'm using the latest AntD release (3.17.0) and it does not appear to display some of the fields correctly, namely:
- There are no "*" required symbols next to labels
- Validation errors do not light up the related fields in red (the "x" is also misaligned)
- Finally, `wrapperStyle` on `AutoField` does not seem to be working

**See photo:**

![form_problems](https://user-images.githubusercontent.com/22347954/57375597-c58e1680-7195-11e9-8ad6-ae530b384e3c.png)

**Schema:**

```
const schema = new SimpleSchema({
  general: {
    type: new SimpleSchema({
      name: {
        type: String,
        required: true,
      },
      description: String,
      ...
    }),
  },
  ...
})
```

**Component code:**

```
...
<AutoForm
    showInlineError
    schema={schema}
    onSubmit={doc => console.log('Doc:', doc)}
    onSubmitSuccess={() => console.log('Submit Success')}
    onSubmitFailure={() => console.log('Submit Failed')}
>
  <Tabs tabPosition="left" defaultActiveKey="1">
    <Tabs.TabPane key="1" {...tabProps}>
      <Typography.Title level={4}>
        General
      </Typography.Title>
      <AutoField
        name="general"
        label={null}
        wrapperStyle={{ marginBottom: '32px' }}
      />
    </Tabs.TabPane>
    ...
  </Tabs>
</AutoForm>
...
```

It would be great if you could have a quick look.

Thanks!

**Comment by radekmie** [comment]
Hi @delyanr. It's really weird. As you can see in the [uniforms playground](https://vazco.github.io/uniforms/playground) (which currently uses version [3.14.1](https://github.com/vazco/uniforms/blob/master/website/package.json#L15); the styles are currently incorrectly loaded for 3.10.0, but it doesn't change with 3.14.1 nor 3.17.0), it works. Have you tried lower versions of `antd`?

**Comment by delyanr** [comment]
Hi @radekmie. Just spent some time playing around with older versions and debugging. Turns out the problem is that I'm using `babel-plugin-import` to reduce the size of the bundle. However, since I don't import any of the underlying AntD components in my code directly, `webpack/babel` skip them and `uniforms` ends up using unstyled versions somehow. What would you say is the best way to fix this without sacrificing `babel-plugin-import`?

**Comment by radekmie** [comment]
That's actually pretty bad. You should definitely report it to the maintainers, that such a problem exists (if you will, please @ping me or this issue there). As a workaround, I can suggest you to directly import all the components that `uniforms-antd` is using. Doing it once should fix this issue.

**Comment by delyanr** [comment]
Hey! I managed to circumvent the issue by disabling the importing of styles via `babel-plugin-import`, and importing them manually via `import 'antd/dist/antd.less'`. This is only related to the styles, so the components are imported on demand as necessary, which is a good solution for me.

However, `wrapperStyle` on `AutoField` is still not working properly - and I presume this is not related to the previous issue. Any ideas there? Thanks!

**Comment by radekmie** [comment]
Can you say something more about that `wrapperStyle` problem?

**Comment by delyanr** [comment]
Literally using the example above, using `wrapperStyle={{ marginBottom: '32px' }}` with `AutoField`. It reverts to the default value of 12px for all fields, as per the `wrapField` default.

Seems to me that passing an object to the `AutoField` renders `NestField` which does not pass `wrapperStyle` down to its children. Is this the expected behaviour?

**Comment by radekmie** [comment]
Yes, `NestField` is not passing own props down - it's correct. You may try `itemProps` which actually does that.

**Comment by delyanr** [comment]
Hello! Just introduced `itemProps` and is working great now. Thanks for the help!
