### ISSUE TITLE
Nesting Arrays breaks getProps from schemaMetadata

### ISSUE THREAD

**Issue by gerwinbrunner** [vazco/uniforms#536]
Hi,

when you try to fetch labels for nested arrays in a schema it does not do so correctly for arrays nested in other arrays.

I created a PR with the fix for it.
https://github.com/vazco/uniforms/pull/535

**Comment by radekmie** [comment]
Great, thank you!

**Comment by gerwinbrunner** [comment]
Seems to work now in `2.0.0-alpha.1`

Thanks!
