### ISSUE TITLE
Feature Request: Displaying non-schema error

### ISSUE THREAD

**Issue by MacRusher** [vazco/uniforms#54]
There are use cases where displaying non-schema error could be useful, e.g. displaying error returned from a method.

Right now forms `error` prop must be simple-schema-compatible, and `Error`/`Meteor.Error` are not.

Example usage:
```
<AutoForm
  error={new Meteor.Error('some-error', 'Message')}
/>
```

This kind of error could be displayed in `ErrorsField` component

**Comment by radekmie** [comment]
It seems reasonable, to do so. I think, that treating `error.message` as a whole message will be sufficient.

**Comment by radekmie** [comment]
I've added support for any error. It goes like this _(abstract)_:

```js
if (error instanceof ValidationError) return formatValidationErrorMessages(error);
if (error && error.message) return [error.message];
if (error !== undefined) return [error];

return [];
```

**Comment by MacRusher** [comment]
Thank you, this solution is great, exactly what I needed!
