### ISSUE TITLE
ErrorsField - filter out errors that are shown inline 

### ISSUE THREAD

**Issue by gerwinbrunner** [vazco/uniforms#540]
Is there a way to only show the "global" errors in the ErrorsField when using "showInlineError={true}"?

I'm having a form with several fields and I have what to show in the ErrorsField only the errors that haven't been show in fields inline above already.

How would I go about this?

**Comment by gerwinbrunner** [comment]
<img width="365" alt="Screenshot 2019-06-09 at 16 41 35" src="https://user-images.githubusercontent.com/75502/59160419-01d6ce80-8ad6-11e9-8299-c4e65a7c6a8d.png">

**Comment by radekmie** [comment]
Hi @gerwinbrunner. Are these _global_ errors related to some non-displayed fields or completely field-agnostic?

If the first one, you can create a variant of `ErrorsField` which will render errors of selected (provided as a prop) list of fields (think of it as a merge of few `ErrorField`). In that case, it might be quite easy to automate your problem, as you'd like to render `fields` and errors of `schema.getSubfields() - fields` (where `-` is a set difference).

If the other one, it might be a bit tricky without a custom schema, as `getErrorMessage` requires a field name and `getErrorMessages` does not provide one. If that's the case, please describe your case a bit more, we'll figure something out.

**Comment by mutaphysis** [comment]
I had a similar problem, the errors raised by the backend during submit (e.g. quota reached, access denied) are mixed with the inline errors from the validation.

I check for the error type in my custom errors field, `error.errorType === 'ClientError'`. 

Sth. like this:

```typescript
import BaseField from 'uniforms/BaseField';
import * as React from 'react';

type Props = {};

const NonInlineErrorsField = (props: Props, {uniforms: {error, schema}}) => {
  if (!error || error.errorType === 'ClientError') {
    return null;
  }

  return (<section>
    {
      schema.getErrorMessages(error).map((message, index) => (
        <p key={index}>{message}</p>
      ))
    }
  </section>);
};

NonInlineErrorsField.contextTypes = BaseField.contextTypes;

export default NonInlineErrorsField;
```

**Comment by radekmie** [comment]
Ping @gerwinbrunner.

**Comment by radekmie** [comment]
No answer so far, I'm closing. Feel free to comment anyway.
