### ISSUE TITLE
Custom Theme with custom components does break uniforms  

### ISSUE THREAD

**Issue by gerwinbrunner** [vazco/uniforms#541]
I'm trying to create a new theme package for [Shopify Polaris](https://polaris.shopify.com/components)
A basic functionality is already there and works nicely.

Some of the Polaris components seem to break Uniforms for some reason I can't really figure out.

I created an example app to illustrate the issue. 
There is 3 times the title field added. 
The first occurrence is a plain `AutoField`
The second is an `AutoField` wrapped in three levels of `div`s
The third is an `AutoField` wrapped in a [Polaris FormLayout](https://polaris.shopify.com/components/forms/form-layout#navigation)

Direct link to the sample app code:
https://github.com/Vilango/uniforms-example-app/blob/FormLayout-issue/imports/components/App.js#L29:L41

The last one is broken as you can see here. You can't type, nor is the field updated when you type in one of the other two fields.
<img width="520" alt="Screenshot 2019-06-09 at 22 47 33" src="https://user-images.githubusercontent.com/75502/59164264-26996900-8b0b-11e9-8f24-86a6628d2310.png">

Any hint what I am doing wrong here?

The Polaris theme can be found here:
https://github.com/Vilango/uniforms/tree/feature/uniform-polaris

The Polaris Uniforms example app can be found here: 
https://github.com/Vilango/uniforms-example-app/tree/FormLayout-issue

**Comment by radekmie** [comment]
Hi @gerwinbrunner. No, your code is correct. The thing here that uniforms are still based on the _old_ React context API, which is ignored by `React.PureComponent`s (old context change should be checked in the `shouldComponentUpdate`) and [`FormLayout` is one](https://github.com/Shopify/polaris-react/blob/38f607992af42d0c1abe9694b7a31e0b766ebbf8/src/components/FormLayout/FormLayout.tsx#L12).

There's no idiomatic way to fix it (besides using the new context API, which is already WIP). You can _reduce_ it to normal component with an additional prop, which will trigger rerender (like `Math.random()` or something) or create your own variant of `FormLayout` ([it's a very simple component](https://github.com/Shopify/polaris-react/blob/38f607992af42d0c1abe9694b7a31e0b766ebbf8/src/components/FormLayout/FormLayout.tsx#L19-L21)). I don't see any other option here.

**Comment by radekmie** [comment]
Ping @gerwinbrunner.

**Comment by radekmie** [comment]
No answer so far, I'm closing. Feel free to comment anyway.

**Comment by gerwinbrunner** [comment]
@radekmie thanks for your reply. 

Does the "new context API" have an ETA? 

> You can reduce it to normal component with an additional prop, which will trigger rerender (like Math.random() or something) or create your own variant of FormLayout (it's a very simple component).

How would that exactly look like? I'm not sure I get what you try to do here.

**Comment by radekmie** [comment]
Unfortunately no ETA on that, sorry. The _hacky_ way with bailing out the `shouldComponentUpdate` is to use `<FormLayout _={Math.random()}>` where you'd write `<FormLayout>`. Own variant of `FormLayout` is a 1-to-1 copy of that component, but deriving from `Component`, not `PureComponent`.

**Comment by gerwinbrunner** [comment]
Is there a branch for the new context API WIP that you mentioned above?

**Comment by radekmie** [comment]
Yes, there is [`new-context`](https://github.com/vazco/uniforms/tree/new-context).

**Comment by gerwinbrunner** [comment]
Just tried the approach in the sample.
But this does not seem to fix it :/

Actually it does not change the bahavior at all.

I changed 
```
   <FormLayout>
          <AutoField name="title" helperText="Helper" />
        </FormLayout>
```
to 
```
   <FormLayout _={Math.random()}>
          <AutoField name="title" helperText="Helper" />
        </FormLayout>
```

**Comment by radekmie** [comment]
Then you'll need a custom component or just wait for the new context, sorry.
