### ISSUE TITLE
Possibility to add a Label ClassName for TextField using Boostrap 4

### ISSUE THREAD

**Issue by oprobst-ethz** [vazco/uniforms#544]
Thanks for this awesome library. Is there a way to add a class name to a label using Bootstrap Theme? I think there is inputClassName (for the input) and wrapClassName (for the div). But I can't find a way to add a class to the label element.

Thank you
Oliver

Example with 

```JavaScript
<TextField name="title" placeholder="Test" />
```
results in

```html
<div class="form-group required">
 <label for="uniforms-0000-0002" class="">
  Test
 </label>
 <input class="form-control" id="uniforms-0000-0002" name="title" placeholder="Test" type="text" value="sfsdf">
</div>
```

**Comment by radekmie** [comment]
Hi @oprobst-ethz. Indeed, it's not possible. It'll be fairly simple to introduce a new prop called `labelClassName` - would you like to submit a PR?

**Comment by radekmie** [comment]
No response so far, I'm closing. Feel free to open a PR at any time.
