### ISSUE TITLE
Custom ToggleButton, props.onChange not doing anything

### ISSUE THREAD

**Issue by ChakirMrabet** [vazco/uniforms#547]
I'd like to build my own "boolean" component based on Material-UI's Swtich, however, I found that the `props.onChange` call doesn't have any effect, `props.value` never changes:

```javascript
import React from "react";
import PropTypes from "prop-types";
import { compose, setPropTypes, pure, withProps } from "recompose";

// Uniforms
import connectField from "uniforms/connectField";

// Material UI
import withStyles from "@material-ui/core/styles/withStyles";
import Switch from "@material-ui/core/Switch";

// Custom Components
import { InfoText } from "dashboard";

// JS Styles
const styles = {};

// Main component
const ToggleButton = props => (
  <div>
    <InfoText content>{props.label}</InfoText>
    <Switch
      checked={Boolean(props.value)}
      name={props.name}
      onChange={event => props.disabled || props.onChange(event.target.checked)}
      ref={props.inputRef}
      value={props.name}
      color="primary"
    />
  </div>
);

// Enhance and export
export default compose(
  setPropTypes({
    name: PropTypes.string.isRequired,
    label: PropTypes.string
  }),
  connectField,
  withProps(props => console.log(props)),
  withStyles(styles, { name: "FormToggleButtonComponent" })
  //pure
)(ToggleButton);
```

I can confirm that the `Switch` `onChange` event is working well and `event.target.checked` is returning the expected valued.

What is wrong with my code?

**Comment by ChakirMrabet** [comment]
I found that this happens when the custom component is not rendered directly into the AutoForm, but nested in another component that is in the AutoForm. How can I solve this? It seems a problem with the context?

**Comment by ChakirMrabet** [comment]
Solved.

I've added `getContext` to the parent component and now it works:

```javascript
.....
export default compose(
  withStyles(styles, { name: "SettingsWifiFormComponent" }),
  getContext(BaseField.contextTypes),
  pure
)(Component);
```

Sorry for opening an issue for this, it might help somebody else in the future. Closing.

**Comment by radekmie** [comment]
Hi @ChakirMrabet. Glad you've found it out! An in-depth explanation is already in [this comment](https://github.com/vazco/uniforms/issues/541#issuecomment-500550089).
