### ISSUE TITLE
Field options not working as expected (values must equal labels)

### ISSUE THREAD

**Issue by delyanr** [vazco/uniforms#549]
Hello!

**Related**: #517 

**Context**: Uniforms v2.1.0; JSON Schema; Ant Design

I'm trying to use `options` to define field names to use with `checkboxes` enabled; however, there is some weird issue where if the `label` is different from the `value`, then the particular checkbox loses the ability to check and un-check.

You can test it with the following schema:

```
{
    "type": "object",
    "properties": {
        "impact": {
            "type": "array",
            "title": "Select impacts:",
            "items": {
                "type": "string"
            },
            "options": [
                {
                    "label": "Impact One",
                    "value": "Impact One"
                },
                {
                    "label": "Impact Two",
                    "value": "Impact Two"
                },
                {
                    "label": "Impact Three",
                    "value": "Impact Three"
                },
            ],
            "uniforms": {
                "checkboxes": true
            }
        }
    }
 }
```

Changing the `label` or `value` anywhere bugs out.

Please have a look.

Thanks!

**Comment by radekmie** [comment]
Great bug report @delyanr! I'll look into that soon.

**Comment by delyanr** [comment]
@radekmie Thanks for the quick fix - working like a charm now!
