### ISSUE TITLE
ErrorField is not styled in SemanticUI

### ISSUE THREAD

**Issue by MacRusher** [vazco/uniforms#55]
`<ErrorField name="someField" errorMessage="some message" />` is showing message as plan text, without any error markup

**Comment by radekmie** [comment]
Unfortunately, not only in Semantic... Okay, I'll fix it.

**Comment by zeroasterisk** [comment]
my bad - @radekmie you could've assigned that to me

**Comment by radekmie** [comment]
@zeroasterisk - no problem - if something is quite obvious, there's no problem to do it for me. If something is not as it should - let me know, or open an issue/PR.
