### ISSUE TITLE
Problem upgrading from Uniforms 1.31.1 to 2.1.0

### ISSUE THREAD

**Issue by philipmjohnson** [vazco/uniforms#553]
Greetings, I am trying to update my sample Meteor application to Uniforms 2.1.0.  I have an AddStuff page that works fine under Uniforms 1.31.1. The form code (available in the branch uniforms-1.31.1) looks like this:

https://github.com/ics-software-engineering/meteor-application-template-react/blob/uniforms-1.31.1/app/imports/ui/pages/AddStuff.jsx

And when it runs, it creates a page like this:

<img width="1058" alt="uniforms-1 31 1-form" src="https://user-images.githubusercontent.com/290288/61094530-4910f180-a3eb-11e9-8c66-fd06da52b499.png">

After running the npm commands to update to Uniforms 2.1.0 (including the new bridge package for simple-schema2), I get the following error message:

<img width="1035" alt="uniforms-2 1 0-form" src="https://user-images.githubusercontent.com/290288/61094564-6fcf2800-a3eb-11e9-8e3c-5187b2018068.png">

A branch containing my updated system is available here:

https://github.com/ics-software-engineering/meteor-application-template-react/tree/uniforms-2.1.0

I looked through the release notes and couldn't find figure out what I need to fix in my 1.31.1 code in order for it to work in 2.1.0.  

Thanks for any help you can provide.

**Comment by radekmie** [comment]
Hi @philipmjohnson. I cannot find any bridge imported in your project. Have you read [2.0.0](https://github.com/vazco/uniforms/blob/master/CHANGELOG.md#v200-alpha0-2019-05-01) release note? Bridges were separated from the core and have to be imported separately.

**Comment by philipmjohnson** [comment]
@radekmie Thanks for the quick response!  Yes, the bridge package was imported:

https://github.com/ics-software-engineering/meteor-application-template-react/blob/uniforms-2.1.0/app/package.json#L21

**Comment by radekmie** [comment]
It is _installed_ but it also has to be imported in the project, via `require` or `import`.

**Comment by philipmjohnson** [comment]
Hold on a second... I'm realizing what you mean.

**Comment by philipmjohnson** [comment]
Thanks for the help, I read but did not understand the release notes.  Here's the line I needed to add to my code in order fix this issue (for future googlers):

https://github.com/ics-software-engineering/meteor-application-template-react/blob/uniforms-2.1.0/app/imports/api/stuff/stuff.js#L22

Note that I also had to npm add the bridge package and also import it at the top of the file.

**Comment by radekmie** [comment]
Importing it without actually creating the bridge would be enough. Glad it's solved!
