### ISSUE TITLE
Feature Request: Field level API to Form->getModel()

### ISSUE THREAD

**Issue by zeroasterisk** [vazco/uniforms#56]
I have a custom UI Input for date range picker, start & stop.

Until I can access both fields' values from a Field level component, I can't do a "number of days picked" calculation until the document saved in the database (or to component props).

Ideally, I want to, from a Field level component, have access to the parent form and all of it's API.
Then I could call the new _(and awesome)_ `getModel()` and look up the current, in-form value for any field.

Note: I can not simply use the new `formRef` access, because I am trying to use this inside a Field connected component.  I want access to this field's value (easy) and other fields' values (not so easy right now - that I can find)

**Comment by radekmie** [comment]
Doesn't [`findValue`](https://github.com/vazco/uniforms#field-props) cover your needs? I don't think, that access to the whole `model` is a good idea.

**Comment by zeroasterisk** [comment]
Not really, because input A needs to know the value of input B... in the case of a `DateRangePicker` the start and stop rely on each other's value, as a max/min and duration calculation...  I could do this at the form level, but I'd much rather do it at the field level, since I'm making a single widget for both input fields.

**Comment by radekmie** [comment]
That's the point of `findValue`: `Request another field value`.

**Comment by zeroasterisk** [comment]
thanks - I was able to get this to work, from the field level... using `findValue()`
