### ISSUE TITLE
Best Practise on how to light validated fields green

### ISSUE THREAD

**Issue by thebarty** [vazco/uniforms#560]
Hi guys,

what's the best way to achieve the result you can see in the right side of the picture?
Give the user some props while filling out the form by coloring the filled in fields green and checking the off.

I am using uniforms + bootstrap 3 + simpl-schema right now…

Has anyone done this? Could you give some example?

![](https://cloud.netlifyusercontent.com/assets/344dbf88-fdf9-42bb-adb4-46f01eedd629/fc399215-910e-48e7-87c9-0e87c5e13a64/42-best-practices-for-mobile-form-design.png)

**Comment by radekmie** [comment]
Hi @thebarty. I haven't done _that_ exactly, but I've seen many different ways to indicate a valid/invalid state of a field. It's easiest to create a custom field component with a proper error indication (see `error` and `errorMessage` props). When it comes to that error text underneath, see `showInlineErrors` flag.

**Comment by radekmie** [comment]
No response so far, I'm closing. Feel free to comment anyway.
