### ISSUE TITLE
Error in documentation for SimpleSchema2Bridge

### ISSUE THREAD

**Issue by twiddler** [vazco/uniforms#562]
There seems to be an error in the documentation about how to use SimpleSchema2Bridge, see https://uniforms.tools/docs/api-bridges#simpleschema2bridge. Following the other examples, the import on line 2 misses the curly braces. It should read `import { SimpleSchema2Bridge } ...`. Without braces it throws an error that SimpleSchema2Bridge is not a constructor.

**Comment by radekmie** [comment]
Hi @twiddler. Thanks for the report! I think we'll fix the docs *and* make bridges exported as a `default` export too.
