### ISSUE TITLE
Antd placeholder no rendering.

### ISSUE THREAD

**Issue by danyhiol** [vazco/uniforms#568]
When using SelectField `import SelectField from 'uniforms-antd/SelectField'` with simpleschema2 `import SimpleSchema from 'simpl-schema'` placeholder does not render.
```
test: {
    type:  Array
    minCount: 1,
    allowedValues: ["one", "two", "tree", "four"],
    uniforms: {
        placeholder: "some place holder",
        extra: "some extra",
    }
},
'test.$': String,
```
or 

```
<SelectField 
    name="test"
    showSearch
    allowClear
    optionFilterProp="children"
    placeholder: "some place holder",
    extra: "some extra",
    options=["one", "two", "tree", "four"]
/>
```
This may reference to [SelectField](https://github.com/vazco/uniforms/blob/8e49908e8c8e0b0b269b0510cef28d361fdd6878/packages/uniforms-antd/src/SelectField.js#L37)

**Comment by radekmie** [comment]
Hi @danyhiol. Yep, it's a bug. It should use `undefined` instead of an empty string.
