### ISSUE TITLE
Feature Request: Form level API to getFieldValue()

### ISSUE THREAD

**Issue by zeroasterisk** [vazco/uniforms#57]
Similar to #56 it would be convenient to be able to lookup the value for any field.

Basically, it's something like: `_.pick(formRef.getModel(), 'myfield')` 

That would work, but I suspect you could come up with something more elegant.

**Comment by radekmie** [comment]
Doesn't [`findValue`](https://github.com/vazco/uniforms#field-props) cover your needs?

**Comment by zeroasterisk** [comment]
I want access to a different field's value, not my own.

**Comment by radekmie** [comment]
Have you read `findValue` description?

`findValue` | `func(name)` | Request another field value.

**Comment by radekmie** [comment]
[Actually, it was implemented, because you've opened an issue.](https://github.com/vazco/uniforms/issues/8)

**Comment by zeroasterisk** [comment]
thanks - I was able to get this to work, from the field level... using `findValue()`

**Comment by sakulstra** [comment]
hmm i'm currently trying to use findValue('field') and awkwardly it only returns the correct value after i try save the form one time - any idea what i am doing wrong?

**Comment by radekmie** [comment]
@sakulstra: could you say something more?

**Comment by sakulstra** [comment]
i'm basically trying to do what this ticket is about:
accessing a value from on field to alter the options for another.

I have a component:
```
const CustomComp = (props) => {
  console.log(props.findValue('targetField')
  return (
    <SomeFormComponent {...props} />
  )
}

export default connectField(CustomComp)
```

If i now change the TargetFieldComponent CustomComp will log undefinied whenever i change the value of TargetFieldComponent.  When i press submit once - it starts to log the correct value.

**Comment by radekmie** [comment]
Weird, I've tried it and it's working here. Please, file a new issue and we'll work it out.
