### ISSUE TITLE
<SelectField> does not trigger onChange for default value

### ISSUE THREAD

**Issue by sfeidersullivan** [vazco/uniforms#570]
## Description
When `<SelectField>` defaults to the first `allowedValue`, that value can no longer be selected without changing to another value then changing back.
 
This is intended behavior for a `<select>` tag where state is handled by the DOM, but seems like unintended behavior for uniforms where components are controlled by outside state.

![Aug-05-2019 17-52-06](https://user-images.githubusercontent.com/10406171/62576741-4bcbfe80-b852-11e9-9ee9-01704bcad4a3.gif)

## Steps to reproduce
1. https://uniforms.tools/playground#?N4IgDgTgpgzlAuIBcIDqUA2BjA9gWygEIQAacCHMGZUAQwFd4cZaA3KZAM1ozjIaYt2AEUy0AnsgCMABhlkAJgEsWAIwxQFXHnxAZaqzMngR6UMmH1YoACxwYFUCNt7mQMLDah5ayEADsoAHcAAgBlJTxLKDDPb1oACmAAHX8Q9JCYJQAvKCQQlLSM4vhxMDzwkyV_AHMSVOLingwcIM0ANR4zGHyAbQByAA8YfpIQ_pGx_rxR8YxZofmAXQaMgF96_zWASlJ3OyCASX8MaqgAUQgKZyRuV34YcX8sAHl_MPpVPCVEW503WiPZ5vTqnBS0eAcP6uDYgeBeAh-OA-fzwJRYEBrIA
1. Select 'xs' from dropdown
1. Click Submit

Affects `uniforms-semantic`, `uniforms-bootstrap`, and `uniforms-unstyled` (any that use `<select>` tags)

## Expected Behavior
If user selects 'xs', the state should be updated

Works fine for `uniforms-material` since a placeholder is always added as the first item.

Would also be fine if a `null` or "please select" option was added by default, or if it was clear that the user must pass one in.

**Comment by radekmie** [comment]
Hi @sfeidersullivan. It works correctly if you enable the `placeholder` for this field. I have to think about how to make it consistent between themes.

**Comment by radekmie** [comment]
Now it seems to be consistent and fully usable. All fields without value start with placeholders, and only optional ones are allowed to set it back (which clears the value).
