### ISSUE TITLE
uniforms-bridge-simple-schema-2 depends on "simpl-schema": "^1.0.0 || ^0.0.4"

### ISSUE THREAD

**Issue by doronrk** [vazco/uniforms#571]
Hey @radekmie, I'm not positive that this is an issue since I'm new to npm, but I believe uniforms-bridge-simple-schema-2's package.json file is preventing upgrading to SimpleSchema@2.0.0. This file has `"simpl-schema": "^1.0.0 || ^0.0.4"` under dependencies. Perhaps I'm misunderstanding, thanks for your help and the useful package.

**Comment by radekmie** [comment]
Hi @doronrk. _A long time ago_, there was a `aldeed:simple-schema` ([aldeed/meteor-simple-schema](github.com/aldeed/meteor-simple-schema)). Then its author decided to move it to npm. That's how `simpl-schema` ([aldeed/simple-schema-js](https://github.com/aldeed/simple-schema-js)) was created. The npm package is incompatible with the old, currently deprecated, Atmosphere package. I've named it SimpleSchema@2, but it's still called SimpleSchema, with its own version numbering.

**Comment by doronrk** [comment]
Hey @radekmie, thanks for your answer. Just want to make sure I understand:

uniforms-bridge-simple-schema is for aldeed/meteor-simple-schema
uniforms-bridge-simple-schema-2 is for aldeed/simple-schema-js version 1.x.x

^ if that's correct, then are there plans to support aldeed/simple-schema-js version 2.x.x? 

Thanks again.

**Comment by radekmie** [comment]
Yes, it's all correct. Of course, it is planned, but there's no version 2 of that package yet.
