### ISSUE TITLE
Conditional uniform values with another field

### ISSUE THREAD

**Issue by kral** [vazco/uniforms#572]
Hello, I spent a lot of time trying to dynamically manage Material UI uniforms (via SimpleSchema2Bridge) form values based on another field.

Imagine, that I have select like this:

```
  frequency: {
    type: String,
    label: "Going party?",
    allowedValues: ['yes', 'no'],
  }
```

And I would like to conditionally disable this input:

```
  beers: {
    type: String,
    label: "How many friends are going with you?",
    uniforms: {
       disabled: true
    }
  }
```

It makes sense, that **this input should be enabled based on selected value = yes**.
I tried modelTransform, some kind of connectField workarounds, but I think I am missing some magic, cause I can not achieve this result.

Please help :-) Thanks a lot,
jk

**Comment by radekmie** [comment]
Hi @kral. You can make a component similar to [`DisplayIf`](https://uniforms.tools/docs/examples-custom-fields#displayif) or [`WithUniforms`](https://uniforms.tools/docs/api-context-data#accessing-context-data) and pass the `disabled` prop manually to your component.

**Comment by radekmie** [comment]
No response so far, I'm closing. Feel free to comment here though.

**Comment by kral** [comment]
@radekmie  Thank you very much for your advice. It works really great by using withUniforms and my own "proxy" component.
