### ISSUE TITLE
Support for typescript imports

### ISSUE THREAD

**Issue by wtrocki** [vazco/uniforms#576]
## Steps to reproduce

Create react app with --typescript flag.
Add uniforms using tutorial.

## Result:

Could not find a declaration file for module 'uniforms-semantic'
Sending just very basic type definition to @typed or deriving it could provide much better user experience.

**Comment by radekmie** [comment]
Hi @wtrocki. I've actually started rewriting some parts of the core package to TypeScript (it's 1.7% now). We are definitely going to work on it, but it'll take some time. The plan is to type the core and bridge packages first, then themes.

**Comment by wtrocki** [comment]
Do you have issue to show that this is happening? Any collaboration?

**Comment by radekmie** [comment]
It's on the roadmap, but there's no task for that, sorry. As always, every PR is welcome.

**Comment by wtrocki** [comment]
I meant here that uniforms can expose just top level types to enable imports. Rest can be as any. This will allow usage in ts. I do not care much what is used under hood

**Comment by radekmie** [comment]
OK, now I get it. Yes, we can definitely add those. Will get into that next week.

**Comment by lukasluecke** [comment]
@radekmie Any update on this? 🙂

**Comment by radekmie** [comment]
@lukasluecke it's almost on the of our to-do list (which will be public soon).
