### ISSUE TITLE
GraphQL example is missing labels

### ISSUE THREAD

**Issue by wtrocki** [vazco/uniforms#577]
When creating GraphQL example labels will not be provided. 
After checking source code I found that extra object needs to be passed.
For example:

```
    city:   {label: 'City'},
    state:  {label: 'State'},
    street: {label: 'Street'},
    zip:    {label: 'Zip'}
```

Can labels be derived from ast values?
Example: https://astexplorer.net/#/gist/aaf298cda868080a86c1e1838c9fb382/a98e0667d362bdba99fafeee99818b8c411c05be

**Comment by wtrocki** [comment]
Workaround for the moment is to use something like this:
```
visit(parse(schema), {
    FieldDefinition(node) {
        schemaData[node.name.value] = {
            label: node.name.value
        };
    }
})
```

**Comment by radekmie** [comment]
Hi @wtrocki. It's something I thought about it for a long time. It's not the best solution, as the schema names often are not very user-friendly, but they can definitely be a sensible default. It'll also unify DX between bridges.

**Comment by wtrocki** [comment]
Hmm.. I do not need to be in the core, but we can provide helper to wrap functions as above. Community contribution?

**Comment by radekmie** [comment]
Well, yeah, but it really makes sense to put it in the core. `GraphQLBridge#getProps` to be exact.

**Comment by wtrocki** [comment]
I have put some thought into entire graphql implementation and I think it needs some work to make it useful for production cases.

Main pain points I see now is:

### Performance
Generally parsing GraphQL schema (as oposed to documents) is quite bad idea. 
Getting thru complex AST was giving me extra 62 ms webpage rendering time on browser and 151ms on random phone. Using json schema do not add such overhead

## GraphQL specific issues 

Wrapping schema into form seems easy in hello world scenario but for normal use cases schema will diverge from form. Example? ID field in the schema is very rarely used as ID is assigned by server?

### How to address this issues

Generally GraphQL integration seems like just starting. I think the best GraphQL intergartion is no integration at all.

Imagine that I will put very complex schema into some cmd on build time and generate json schema. Then I can extend/modify json schema, push it to repo etc. without performance or usability penality. We can add extra directives to generator engine that can cover validation use cases etc. 

What this means is that uniforms will still be supporting graphql but in more usable way.

I'm working now on integrating uniforms with http://graphback.dev and I decided to not use GraphQL bridge

**Comment by wtrocki** [comment]
My assumption is that Uniforms GraphQL implementation allows people to use schema they have on server. Correct me if I'm wrong

**Comment by radekmie** [comment]
> Generally parsing GraphQL schema (as oposed to documents) is quite slow. [...]

Agree. It's up to you if you do it on runtime: it's possible to do it during the build. [`gajus/babel-plugin-graphql-tag`](https://github.com/gajus/babel-plugin-graphql-tag) is one option.

> [...] ID field in the schema is very rarely used as ID is assigned by server?

There's the [`AutoFields`](https://uniforms.tools/docs/api-fields/#autofields) component with `omitFields` prop for that. That's also why we don't provide any default validator and let users do it.

> [...] To be clear uniforms should be basing on InputTypes passed to mutations to be more aligned with entire concept

It's not stated in the docs, but it also works with input types. Check it out the [`GraphQLBridge` tests](https://github.com/vazco/uniforms/blob/master/packages/uniforms-bridge-graphql/__tests__/GraphQLBridge.js#L28).

> Generally GraphQL integration seems like just starting. I think the best GraphQL intergartion is no integration at all. [...] I'm working now on integrating uniforms with [http://graphback.dev](http://graphback.dev/) and I decided to not use GraphQL bridge

I agree that no default nor go-to validator for GraphQL forces us to have another one. JSON Schema is a great choice here - we do mix them internally too. 

But on the other hand, there are use cases for the current integration. You can create a form prototype instantly for any of your (input) types. In some situations, it's easier (and better in terms of bundle size) to use it as it is and write the validator by hand. The types are already there and so is the parsed schema (again, you can do it on a build step), so using it to make a form is often a no-brainer.

> We can add extra directives to generator engine that can cover validation use cases etc.

That's something that IMO decides on the schema choice. It'll be fairly easy (in terms of integration, possibly not implementation) to do it using ajv keywords or similar extensions.

> My assumption is that Uniforms GraphQL implementation allows people to use schema they have on server. Correct me if I'm wrong

Of course, it does! It also allows you to create a full-blown app with it. Maybe it's not as obvious as with JSON Schema, but it's doable (and people do it).

**Comment by wtrocki** [comment]
I will do prototype to show how this could work.

**Comment by wtrocki** [comment]
Actually this gives me more perspective and info to work on. I will give second go to GraphQL bridge and see if I can get something like @OmitFieldDirective

**Comment by wtrocki** [comment]
I'm playing with this and getting some strange resuls when using input types. 
I will follow up to see if that is issue on my side - if not going to create new issue:

<img width="603" alt="Screenshot 2019-08-19 at 14 50 37" src="https://user-images.githubusercontent.com/981838/63270900-ebe14900-c290-11e9-8a26-b8de8987d5f6.png">
