### ISSUE TITLE
simple-schema vs jsonschema

### ISSUE THREAD

**Issue by macrozone** [vazco/uniforms#581]
Hi!

I want to integrate uniforms into https://github.com/react-page/react-page to create plugins more easily.

I am just not sure about which schema-type i should support. SimpleSchema or JsonSchema ?

I use SimpleSchema for years and it worked for me, but it has some legacy and might not be as maintained as jsonschema and its ecosystem.

Are there some pros/cons comparing jsonschema bridge (with ajv) to simpleschema?

**Comment by radekmie** [comment]
Hi @macrozone! It's definitely an important decision. Personally, I really like JSONSchema. It's far more advanced, has tooling for almost every language and it's fully serializable. It's also straightforward to define custom constraints and validation rules via keywords.

From uniforms perspective, both should be equal (in terms of features).

**Comment by macrozone** [comment]
@radekmie thx! i will go try it out then!
