### ISSUE TITLE
Autosave on 2.3.1 not working

### ISSUE THREAD

**Issue by theodorDiaconu** [vazco/uniforms#582]
I've got a simple form (name:string using simple-schema), that is rendered something like 15 times. And I have auto-save feature. While typing it gets stuck, and onSubmit does not get called. 

This does not happen in the playground. I think it's related to the fact that I have 15 uniforms with autosave feature?

**Comment by theodorDiaconu** [comment]
Weird behavior, it seems that on the last 5-6 form elements. The autosave is working, but on the first one, it blocks the browser.

**Comment by theodorDiaconu** [comment]
This is my form in case you want quick test:

```import React from 'react';
import { AutoForm, TextField, BoolField, ErrorField } from 'uniforms-antd';
import SimpleSchema from 'simpl-schema';
import SimpleSchema2Bridge from 'uniforms-bridge-simple-schema-2';
import Row from 'antd/lib/row';
import Button from 'antd/lib/button';
import Col from 'antd/lib/col';
import Popconfirm from 'antd/lib/popconfirm';

const schema = new SimpleSchema2Bridge(
  new SimpleSchema({
    name: String,
    code: String,
  }),
);

const WBSCodeForm = ({ wbsCode, onSubmit, onDelete }) => {
  const isAdding = !onDelete;
  let formRef;
  return (
    <AutoForm
      onSubmit={(data) => {
        onSubmit(data, formRef)
      }}
      schema={schema}
      model={wbsCode}
      autosave={!isAdding}
      autosaveDelay={500}
      id={`form-${wbsCode._id}`}
    >
      <Row>
        <Col span={4}>
          <TextField name="code" placeholder="Code" />
          <ErrorField name="code" />
        </Col>
        <Col span={10} offset={1}>
          <TextField name="name" placeholder="Enter Name" />
          <ErrorField name="name" />
        </Col>
        {onDelete && (
          <Col span={2}>
            <Popconfirm title="Are you sure you want to delete this WBS Code?" onConfirm={onDelete}>
              <Button
                style={{ marginTop: '53px', marginLeft: '15px' }}
                type="primary"
                icon="delete"
              >
                Delete
              </Button>
            </Popconfirm>
          </Col>
        )}
        {!onDelete && (
          <Col span={2}>
            <Button
              style={{ marginTop: '53px', marginLeft: '15px' }}
              onClick={() => {
                formRef.submit()
              }}
              type="warning"
              icon="plus-circle"
            >
              Add
            </Button>
          </Col>
        )}
      </Row>
    </AutoForm>
  );
};

export default WBSCodeForm;
```

**Comment by kestarumper** [comment]
Hi @theodorDiaconu. I've copied your code, made a few tweaks, mocked few functions and it seems like it's working properly even on 50 copies simultanously. I'll post codesandbox later. First thing I noticed that you don't assign `formRef`. For now try fixing this.

**Comment by theodorDiaconu** [comment]
@kestarumper make sure it enters onSubmit when you have 20-30 forms in the same page with autoSave and Delay. Ultimately I went with autosave={false} until this gets solved.

**Comment by kestarumper** [comment]
@theodorDiaconu let me know if this satisfies you. `onSubmit` is called asynchronously after every change with delay and simulates saving (logs to console after delay). I haven't encountered any browser freezes and/or crashes.
https://codesandbox.io/embed/github/kestarumper/uniforms-issue-582/tree/master/

**Comment by radekmie** [comment]
I'm closing. If you'll encounter any issues again - feel free to write them here or file another issue.
