### ISSUE TITLE
can't specify placeholder with jsonschema

### ISSUE THREAD

**Issue by macrozone** [vazco/uniforms#586]
having this json schema:

```
 const schema = {
        title: 'Address',
        type: 'object',
        properties: {
            city:   {type: 'string', title: "City" uniforms: {placeholder: "Some other string"}},
        },
    }
```

the placeholder is not shown, it will always use title as placeholder. Also uniforms.label has no effect

**Comment by radekmie** [comment]
Hi @macrozone. Yep, it's the same case as #580 - labels logic is wired up incorrectly. We'll get to it soon.

**Comment by radekmie** [comment]
OK, it required a _slightly_ bigger change. It's all described in the [`CHANGELOG.md`](https://github.com/vazco/uniforms/blob/master/CHANGELOG.md).

**Comment by macrozone** [comment]
awesome :-*
