### ISSUE TITLE
Accelerate reproductions

### ISSUE THREAD

**Issue by theodorDiaconu** [vazco/uniforms#587]
It would be nice if you could do something like: https://codesandbox.io that includes a dummy setup of Uniforms running.

So if someone wants to show a bug or something automatically forks your sandbox and leaves the link inside GitHub.

**Comment by radekmie** [comment]
Hi @theodorDiaconu. Yep, it'll definitely help! We can actually include in even in the issue template. Definitely something to be done.

**Comment by theodorDiaconu** [comment]
Issue template sounds nice!
