### ISSUE TITLE
Uniforms Hooks

### ISSUE THREAD

**Issue by theodorDiaconu** [vazco/uniforms#588]
I've started to use hooks, and they make a lot of sense. Here's what I suggest, some ideas:

1. AutoForm to accept the prop ref as a `useRef()`
```
const form = useRef();
<AutoForm ref={form}>...</AutoForm>
```

2. ConnectField:
```
() => {
  const { onChange } = useUnifield()

  // would something like this even work?
}
```

3. Sub components (especially on large forms) should be able to have access AutoForm parent reference

```
() => {
     const uniforms = useUniforms();
}
```

**Comment by radekmie** [comment]
Hi @theodorDiaconu. Yes, all of these are planned, but it'd require a higher minimal React version which currently is [0.14](https://github.com/vazco/uniforms/blob/1bfdd0ae8d6287d5d8417c43270226c59c8710e7/packages/uniforms/package.json#L25-L26)! It is connected to the new context API in #405. It's still a work in progress and will definitely result in version 3.0.

**Comment by theodorDiaconu** [comment]
@radekmie maybe it's time to support minimum 0.16.8. Do you have any idea how many react 0.14 code-bases use uniforms ?

**Comment by radekmie** [comment]
I'm aware of at least one at 0.15 and at least a few on 15. We will definitely go straight to the hooks, shipping both hooks and the new context.
