### ISSUE TITLE
Help adding custom fields on an array of objects

### ISSUE THREAD

**Issue by cosio55** [vazco/uniforms#589]
Hello, I've been trying for more than 3 hours to get a custom field to work inside an array of objects, I already looked at the documentation and the questions already asked and got some ides but still haven't found an answer. What I need this for is to allow the user to upload many images and save each one as an object in the array. I'm still trying to figure out the <ListField /> and the children of that component so any help would be appreciated.

This is the schema I'm using:
```
carImages: {
    type: Array,
    uniforms: Image,
  },
  'carImages.$': Object,
  'carImages.$.url': {
    type: String,
  },
  'carImages.$.public_id': {
    type: String,
  },
  'carImages.$.type': {
    type: String,
  },
```
This is the custom component I'm using:
```
import React from 'react';
import connectField from 'uniforms/connectField';
import {
  ListField, NestField, ListItemField, TextField, ListAddField,
} from 'uniforms-bootstrap3';

function Image({ onChange, value }) {
  return (
    <ListField label={false} name="">
      <ListAddField name="$" />
      <ListItemField name="$" label={false}>
        <NestField name="">
          <TextField name="url" />
          <TextField name="public_id" />
          <TextField name="type" />
        </NestField>
      </ListItemField>
    </ListField>
  );
}
export default connectField(Image);
```

With this code I'm getting the panel in bootstrap 3 but no input to start adding the information, so this is the generated HTML:
`<div class="panel panel-default" id="uniforms-0000-000k" required=""><div class="panel-body"></div></div>
`

I'm first trying to figure out how to use the lists, but at the end I want to add the file/upload part of the component. Thanks for any help!

**Comment by cosio55** [comment]
Wow, after hours of looking around I found out what a stupid mistake I did, I needed to add the custom field to the object instead of the array:

```
carImages: {
    type: Array,
  },
  **'carImages.$': {
    type: Object,
    uniforms: Image,
  },**
  'carImages.$.url': {
    type: String,
  },
  'carImages.$.public_id': {
    type: String,
  },
  'carImages.$.type': {
    type: String,
  },
```

**Comment by cosio55** [comment]
Ok, so now I got the fields to appear, I can put an image in the input without any trouble but when I add more than one object/fields and I add a new image for example in the second or third image input the only image that gets changed is the first one, why can this be happening?

This is the custom field:
```
import React from 'react';
import connectField from 'uniforms/connectField';

const Image = ({ onChange, value }) => (
  <div className="ImageField">
    <label htmlFor="file-input">
      <div>Selecciona una imagen</div>
      <img
        style={{ cursor: 'pointer', width: '150px', height: '150px' }}
        src={value || 'https://via.placeholder.com/150.png'}
        alt=""
      />
    </label>
    <input
      accept="image/*"
      id="file-input"
      onChange={(e) => {
        const { files } = e.target;
        if (files && files[0]) {
          const copyArray = [...files];
          onChange(URL.createObjectURL(copyArray[0]));
        }
      }}
      style={{ display: 'none' }}
      type="file"
      multiple={false}
    />
  </div>
);

export default connectField(Image);
```

And this is the schema I'm using:
```
carImages: {
    type: Array,
    label: 'Imágenes para galería',
    optional: true,
  },
  'carImages.$': {
    type: Object,
  },
  'carImages.$.url': {
    type: String,
    uniforms: Image,
    optional: true,
  },
  'carImages.$.public_id': {
    type: String,
    optional: true,
    uniforms: {
      component: () => null,
    },
  },
  'carImages.$.type': {
    type: String,
    allowedValues: ['interior', 'exterior'],
  },
```

**Comment by radekmie** [comment]
Hi @cosio55. The problem lays in the way how `<label for="id">` works. In your code, each `<label>` targets the same ID (`file-input`) and each input have the same ID, which is prohibited. That's why each time you click a label, the first input is _really_ clicked. If you'll change it to a unique one, like `id` which uniforms guarantee, it works.

**Comment by cosio55** [comment]
What a stupid mistake, thanks for the help and congrats on the new landing!

In case someone wants to do something similar with galleries or similar:

```
import React from 'react';
import connectField from 'uniforms/connectField';

const Image = ({ onChange, value, id }) => (
  <div className="ImageField">
    <label htmlFor={id}>
      <div>Selecciona una imagen</div>
      <img
        style={{ cursor: 'pointer', width: '150px', height: '150px' }}
        src={value || 'https://via.placeholder.com/150.png'}
        alt=""
      />
    </label>
    <input
      accept="image/*"
      id={id}
      onChange={(e) => {
        const { files } = e.target;
        if (files && files[0]) {
          const copyArray = [...files];
          onChange(URL.createObjectURL(copyArray[0]));
        }
      }}
      style={{ display: 'none' }}
      type="file"
      multiple={false}
    />
  </div>
);

export default connectField(Image);
```
