### ISSUE TITLE
Nested errors with JSON Schema

### ISSUE THREAD

**Issue by adrianschneider94** [vazco/uniforms#593]
Hi,

inline errors for nested schemas don't work with JSON Schema. At least not like shown in the docs.
`getError(name, error)` compares the paths, but the path ajv returns has `/` as delimiter whilst uniforms uses `.`.

You can make it work by transforming the ajv errors:
```javascript
let adaptPath = validator.errors.map((error: any) => ({...error, dataPath: error.dataPath.replace(/\//g, ".")}))
```
However, I think it would be better to change the JSONSchemaBridge accordingly.

Kind regards and thanks for your work!

**Comment by radekmie** [comment]
Hi @adrianschneider94. Yes, ajv actually uses `/` but only for `schemaPath`. We do use [`dataPath` in `JSONSchemaBridge`](https://github.com/vazco/uniforms/blob/f349ea2dc0ff06e48f1da677ef147627452bdd56/packages/uniforms-bridge-json-schema/src/JSONSchemaBridge.js#L74), which is dot-separated.

[Playground example](https://uniforms.tools/playground/#?N4IgDgTgpgzlAuIBcICCATd0YwAQAoApAZQHkA5YgYwAsoBbAQwEoQAacCAezBmVEYBXeFxiMAblGQAzRgBs4HISLGSAIlDmMAnsgCMABgMd0ASzEAjOVHQz5ikFoubk8CIKgcwWqlBpc5dCgIOwVPEBhaBkZkEHx8ZlwAXgA-XGAAHQA7XFwqLiyYeFxGACtxZNwsqAB3XFRy_GASuTkAUQhuCBgkXDcPNlxBOA1ZQTl4Hr73KFwAX2YAbmzc_MLiyLomSsyc3L7tMChegHIuC1KoKngTthX9yB5g-FNYXt39_cZ3-8_c-EOx1wZwuVxudz2f1wjyOEBeb3SvyhuAsP0hyP-gNO50u11uSIxMOerymHwxfyo7wOR1ORQgpiyAHNbtDGPB4MEsqcANoGAC0AE4ALrAACscxO8wJyLm0s-svR8ulCqVezmyyy92kgiy11MBTy0DZUAAavJTOg2VwIPhNtFEmTVgUirhxObLSIIJUyuIAHT5ehgUzWW1RJhLbJI6DwQQQHL0LhBOTJNKO_ZuuQWq02hNJiOK3CmaQEDNZz2-4JdPAAMmrrvd2YrnWtMF91iZ8BozDlfRo3DqzSC8EYwampY91qbVfmGvls6lmr2axddqYZszE69SUNUGN67L1tDWxYGvu0djOWqdRIFGox4AQvT0IyoEfooNV4x95v8wsEuwIn8GoAEkskzaoOi6VwZiUGBtF1UgsmIQQLHoUxECQWQwlg-CqEQ79jVCOA5g4TsGCkFA4CYLIXioEA5iAA). If you type `x` in the input, and submit it, the error looks like this:

```json
{
  "details": [
    {
      "keyword": "pattern",
      "dataPath": ".a.b.c",
      "schemaPath": "#/properties/a/properties/b/properties/c/pattern",
      "params": { "pattern": "[0-9]{5}" },
      "message": "should match pattern \"[0-9]{5}\""
    }
  ]
}
```

How have you encountered this problem? I'm not sure about custom keywords and other _advanced_ (in a way) features, but in all of our cases it worked as it is.

**Comment by adrianschneider94** [comment]
Yes I've had this problem.

[Example that does not work](https://uniforms.tools/playground/#?N4IgDgTgpgzlAuIBcICCATd0YwAQAoApAZQHkA5YgYwAsoBbAQwEoQAacCAezBmVEYBXeFxiMAblGQAzRgBs4HISLGSAIlDmMAnsgCMABgMd0ASzEAjOVHQz5ikFoubk8CIKgcwWqlBpc5dCgIOwVPEBhaBkZkEHx8ZlwAXgA-XGAAHQA7XFwqLiyYeFxGACtxZNwsqAB3XFRy_GASuTkAUQhuCBgkXDcPNlxBOA1ZQTl4Hr73KFwAX2YAbmzc_MLiyLomSsyc3L7tMChegHIuC1KoKngTthX9yB5g-FNYXt39z9x0LlgAdS4EAA1u97l8vvBDsdcBkQOdLtdYXc9uDPo8jhAXm90mDUeD4LB4MQ3KYsgBzUEovHUyFHXqwooQUlkpG46motZFekgAlFWFs9nzAXgubC-bIvG8-CUwUHOm4E6MTo6W5iz6mAn0KYfWX7WnQ2Hwq7wVlU2Xo56vbVqwU_WDkLjwAHAmW69n67mM5mmt3sznSmE8wn8s2-0Wh9nh2VR1Ex3LhmPSQRZa6mAp5aCMAkANXkpnQWcB-E20USOtWBSKuHEeYLIgglTK4gAdPl6GBTNZi1EmEtsrjoPBBBAcvQuEE5Mk0uX9jW5PnCxB8GOJ33Q6ZpAQ5wv683gl08AAyQ_V2uLvedQEwZvWcnwGjMMX37h1ZpBeCMTtTbd1wEXg_zMsVJzEB8b9ns_q4CWTC5vOv4NkkGZQFmUCwTuRbQSwQH3IOw45NUdQkBQ1BbIwABCTLoGSUDdqRgyYWh8FrgsCTsBE_g1AAklk87VB0XSuDMSgwNoKakFkxCCBY9AaqEDiMCJYlZIxKFyVAcwcPeDBSCgcBMFkLxUCAcxAA)

The issue only applies to arrays.

However, I was wrong with the root of the problem. I switched to `jsonPointers: true` in the ajv options unawares, while I was testing. This is why I got the slashes in the dataPath. (JsonPointers is required for [ajv-errors](https://github.com/epoberezkin/ajv-errors) which is a great addition.)

Without `jsonPointers` the error looks like this:
```javascript
[
    {
        keyword: "const",
        dataPath: ".doesWork.testString",
        schemaPath: "#/properties/doesWork/properties/testString/const",
        params: {allowedValue: "test"},
        message: "should be equal to constant"
    },
    {
        keyword: "const",
        dataPath: ".test[0].doesNotWork", // uniforms would need ".test.0.doesNotWork", right?
        schemaPath: "#/properties/test/items/properties/doesNotWork/const",
        params: {allowedValue: "test"}
    }
]
```

**Comment by radekmie** [comment]
Yep, brackets in the `dataPath` are not handled correctly. OK, got it, we'll work on it.

**Comment by kyleder** [comment]
I encountered this same issue and solved it by doing a string replace of the square brackets in the `getError` method:

https://github.com/vazco/uniforms/compare/master...kyleder:kd-fix-nested-inline-errors

I'm not sure if that's the best approach to fixing the issue, but it seems to solve it for my case.
