### ISSUE TITLE
Conditional rendering

### ISSUE THREAD

**Issue by adrianschneider94** [vazco/uniforms#594]
Hi,

I know there have already been issues on this topic. But I did not manage to work it out yet.
I want to render a field (B) with props depending on another field (A), with AutoForm.

So I added the context to B and used `context.uniforms.model`. The first time I select a value in A, B get's rerendered, but every other time it won't.

Could you advise me a path to make this work?

**Comment by kestarumper** [comment]
Hi @adrianschneider94,
have you seen our [example field](https://uniforms.tools/docs/examples-custom-fields#displayif) `DisplayIf` in our documentation?

If this is not the thing you are looking for, you can provide us with your sample code using [this link](https://codesandbox.io/embed/uniforms-codesandbox-1p3gu) for further investigation. Feel free to ask more questions, and let me know if it helped :)

**Comment by adrianschneider94** [comment]
Thanks for your response @kestarumper!

I managed to do it now, but it was a bit more complex. I extended shouldComponentUpdate of the AutoField, but then it did not work on nested fields yet. So I set shouldComponentUpdate temporarily to true for all nested fields and I get what I want for now.

I will later add an example to this issue so others can see the approach and so that I can ask you for improvements.

**Comment by radekmie** [comment]
Hi @adrianschneider94. Yep, overriding `shouldComponentUpdate` is the way to go here. Actually returning `true` is _a bit_ overkill, but it works. We'd have to add an example of how to do it properly. In short, it could look like this:

```js
class DerivedXField extends XField {
  shouldComponentUpdate(props, state, context) {
    if (super.shouldComponentUpdate(props, state, context))
      return true;

    const prevModel = this.context.uniforms.model;
    const nextModel = context.uniforms.model;
    for (const field of relatedFieldsSomehow)
      if (!isEqual(get(prevModel, field), get(nextModel, field)))
        return true;

    return false;
  }
}
```

The only _creative_ part is the `relatedFieldsSomehow`, because it may depend on props, state, context itself - literally anything.

**Comment by adrianschneider94** [comment]
@radekmie
Yes I know. Thus 'temporarily'. I first wanted to get it running.
Thanks for the snippet!
