### ISSUE TITLE
JSON Schema UI vocabulary

### ISSUE THREAD

**Issue by adrianschneider94** [vazco/uniforms#595]
I stumbled across this thread during research, could be interesting for you:

https://github.com/json-schema-org/json-schema-vocabularies/issues/2

**Comment by radekmie** [comment]
Hi @adrianschneider94. That's actually a very interesting topic. Indeed, we are using the non-standard `uniforms` property from the start, but _maybe it's not the best way_. We'll get deeper in this matter, maybe it'll inspire us to do some changes.

I'll close the issue anyway, as it's not an issue _per se_. Go ahead and share it also on our [Gitter channel](https://gitter.im/vazco/uniforms) - maybe someone there will also be interested.

**Comment by philsturgeon** [comment]
@adrianschneider94 @radekmie hey, I'd just like to let you folks know we're kicking off discussion around UI schema. There won't be an official one but we have a https://github.com/json-schema-org/json-schema-vocabularies repo to track projects, and UI will be one of them. The issue you mentioned is moved over https://github.com/json-schema-org/json-schema-vocabularies/issues/2

Maybe anyone interested could swing by the slack and say hello! https://join.slack.com/t/json-schema/shared_invite/enQtNjc5NTk0MzkzODg5LTVlZGIxNmVhMGY2MWFlYTdiNDQ5NWFiZGUwOThhNmYxZDE0YzA5YjRiOTA5MGY4ZTZlZGZhZDFmYTY4NWM2N2Y
