### ISSUE TITLE
Support recursive json schemas

### ISSUE THREAD

**Issue by crubier** [vazco/uniforms#596]
Recursive JSON schemas such as this one (where the recursi e property is not required) make this library crash. It should not, ideally.

```
{
  "definitions": {
    "address": {
      "type": "object",
      "properties": {
        "billing_address": {
          "title": "Billing address",
          "$ref": "#/definitions/address"
        },
        "street_address": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "state": {
          "type": "string"
        }
      },
      "required": [
        "street_address",
        "city",
        "state"
      ]
    }
  },
  "type": "object",
  "properties": {
    "billing_address": {
      "title": "Billing address",
      "$ref": "#/definitions/address"
    }
  }
}
```

**Comment by radekmie** [comment]
Hi @crubier. It's not always possible, as your schema while being used in `<AutoForm />` would create an infinite number of fields (due to `billing_address` recursion). However, we can make the parsing lazy and allow the following code:

```js
<AutoForm schema={schema}>
  <AutoField name="billing_address">
    <AutoField name="billing_address">
      <AutoField name="street_address" />
    </AutoField>
  </AutoField>

  {/* Or equivalently */}
  <AutoField name="billing_address.billing_address.street_address" />
</AutoForm>
```

**Comment by crubier** [comment]
My actual use case is actually not about adresses, and involve an actual need for arbitrary depth recursion. But the key point here is that the recursion does not have to be infinite since the recursive element is NOT required. So by not displaying non-required recursive fields by default (but allowing the user to click to add it), then there is no infinite recursion (unless the user clicks an infinite amount of times)

**Comment by radekmie** [comment]
> [...] since the recursive element is NOT required.

Sure thing.

> [...] not displaying non-required recursive fields by default (but allowing the user to click to add it) [...]

It'll be possible, but not a built-in behaviour. You'll have to implement it on your own.

**Comment by crubier** [comment]
What would be the best way to do this on our side in your opinion?

**Comment by radekmie** [comment]
At first, wait for the implementation on uniforms site or file a PR with it. Then, create a custom `NestField`-like component that you need, so a component which conditionally renders optional subfields.

**Comment by radekmie** [comment]
@crubier I'm not sure if it was working before (haven't tried it) but it is definitely working in v2.6.6.
