### ISSUE TITLE
Warning: componentWillMount has been renamed, and is not recommended for use

### ISSUE THREAD

**Issue by vfonic** [vazco/uniforms#605]
> Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.
>
> * Move code with side effects to componentDidMount, and set initial state in the constructor.
> * Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
>
> Please update the following components: AutoValidatedQuickUnstyledForm, BoolField, ErrorField, SideEffect(NullComponent), TextField

I'm using React v16.8 and I'm getting a lot of such and similar warnings in the console. Because of this, it's really hard to see any new warning.

I understand that uniforms supports react all the way down to v0.14 (wow!)

I hope uniforms v3.0 can drop support for at least some of these older react versions. I'm also looking forward for uniforms with hooks. That will be amazing addition! https://github.com/vazco/uniforms/issues/588

Thanks!

**Comment by radekmie** [comment]
Hi @vfonic. Yes, it's definitely something we have to do. We are now finishing up the TypeScript migration and upgrading React (context API, lifecycle API and hooks) is next.

**Comment by vfonic** [comment]
Thank you, sir! 🎉

**Comment by radekmie** [comment]
Done on `v3`.

**Comment by vfonic** [comment]
😱 Gotta check it out!
