### ISSUE TITLE
How to define a read-only field?

### ISSUE THREAD

**Issue by jmaister** [vazco/uniforms#608]
I would like to show the ID of a client but keep it disabled.

    const schema = {
        title: 'Client',
        type: 'object',
        properties: {
            entityId: { type: 'string', disabled: true, label: 'ID' },
            name: { type: 'string', label: 'Name' },
            address: { type: 'string', label: 'Address', uniforms: {
                component: LongTextField
            } },
        },
        required: ['name', 'address']
    };

However, when I submit the AutoForm, it tries to validate it:

![image](https://user-images.githubusercontent.com/374021/66862064-177a6a00-ef88-11e9-940e-c2863cfee006.png)

How can I define the "entityId" field to show the ID, do not try to validate it and do not send it if I click submit?

**Comment by radekmie** [comment]
Hi @jmaister. The problem with your code is that your `entityId` is a number but the schema expects it to be a string. How to make it read-only? Use `disabled`, exactly as you did.

But there's another question:

> do not try to validate it and do not send it if I click submit?

You can use [`modelTransform`](https://uniforms.tools/docs/api-forms/#model-transformations) to do so. This function allows you to modify the model before validation. In your case - remove this field completely.
