### ISSUE TITLE
Separate, de-coupled Themes, or Theme contribution guide

### ISSUE THREAD

**Issue by refactorized** [vazco/uniforms#609]
**Background**

I am trying to fork the uniforms-material package and running into a lot of trouble.

1) I can't easily fork just the theme as it lives in a monorepo.  Forking the entire repo makes for a difficult time referencing the specific package locally.  I am surely missing some things, but I don't know what. 

2) If I just copy the typescript files defining the theme I have to then somehow get type script working in the smaller project, or in my larger project in which the components just live under the main src directory.  At best this means divining the proper configuration from the monorepo but I have not got TS working yet. 

3) If I skip TS altogether and pull the 4.2.1 versions of the components I get problems because the components _extend_ objects found in the base uniforms package.  This means I am locked into that specific version of uniforms, or have to extract the extended code into the theme because I can't extend a compiled es5 object in es6 code with babel.

**Requests / Suggestions**
1) Write themes that only depend on the proper API, not some upstream implementation detail. If this means duplicating too much functionality, then expose that functionality as helper methods that can be invoked (by anything) rather than classes that require source comprehension to extend.

and / or

2) Documentation on how to fork and improve the themes in the monorepo.

**Comment by radekmie** [comment]
Hi @refactorized. It's a tough one. For all this time I've tried to encourage custom themes and make it as easy as possible. Let me address your points one by one and then try to give a broader answer.

1. This one boils down to your idea of _forking_. If you mean forking the repo, then it's fairly easy - just do it. Want to add a new theme? Simply copy or edit one of the existing ones. If you mean something different, I'll _probably_ get to that later.
2. We've transitioned to TypeScript just recently. There are very few types at the moment (but we are working on it) and there's no special configuration (there is, but almost every line of it is used to make it work as desired in the monorepo).
3. Version 4.2.1 of Material UI I assume?
    > [...] of the components I get problems because the components _extend_ objects found in the base uniforms package. This means I am locked into that specific version of uniforms, or have to extract the extended code into the theme because I can't extend a compiled es5 object in es6 code with babel.

    What objects? Why are you locked? Is there some runtime problem? Did you mean tests? What kind of _extend_ operation? I'm completely lost here, sorry.

1. There is *no dependency* on any implementation detail! If there is any (I may overlook something), then we definitely have to fix it.
2. I'll get to it below.

I'm working on uniforms for over three years now. We've made hundreds of custom components across dozens of projects, including complete custom themes. Most of them began as _source forks_ of `uniforms-unstyled` - one simply copies the source and imports `./some/project/path/uniforms-custom-theme-with-a-cool-name` instead of an npm package. There's no `package.json` nor package-only tests.

In the end, I hope you'll be able to find your way to ~fork~ create a custom theme.

**Comment by refactorized** [comment]
Version 2.4.1 (of uniforms) is what I meant, sorry.  

Regarding extension if you look in `packages\uniforms-material\src\AutoForm.tsx` you see
```
import AutoForm from 'uniforms/AutoForm';

import ValidatedQuickForm from './ValidatedQuickForm';

const Auto = parent =>
  class extends AutoForm.Auto(parent) {
    static Auto = Auto;
  };

export default Auto(ValidatedQuickForm);
```

And it is here that I would get an error because babel seemed to choke on extending a (compiled) ES5 'class' into an ES6 'class'.  My host app in this case is just a simple Create React Instance without any kind of special configuration regarding babel.

Unfortunately I don't have the error handy as I am now just cloning the entire Uniforms repo and trying to reference it from disk.   This raises it's own set of issues, especially given the monorepo nature of the project, but I think most of them lie with yarn's current approach to handling local packages, caching, linking etc.

Right now I am trying to find a workable approach to modifying my own fork of uniforms while testing the changes against my main project.

Thanks for your quick reply,

**Comment by radekmie** [comment]
OK, so it's still the same problem as #433. I've tried a few things, but nothing seemed to work. Maybe it'll be easier with TypeScript - it's still an open topic. If you want to take a stab - feel free and open a PR.

On the other hand - have you tried to do a source fork (I mentioned it above)? There's no single reason to maintain it as a separate package other than ease of eventual publish.

**Comment by refactorized** [comment]
I am currently trying to just use a fork of the whole uniforms repo, and getting lots of weirdness, much or most of which is just issues with yarn and npm and local packages. 

Do you have any guidance on using a local copy of uniforms _in_ another sibling project?  

Also do you use yarn vs npm (becuase I get different results in each)?

Ideally I would just copy the material theme and make small changes as needed, as well as write custom controls (which seems the easy part).  In as much as I want to do that, what is the workflow for building and testing these themes as a contributor to uniforms?

Thanks

**Comment by radekmie** [comment]
Making a custom theme for an own project is one thing. Here I strongly recommend not to make a package, but simply a directory with components. Arguably `AutoField` is the most important one as it works as _router_ of the components. That's where the custom components fit in very well.

Contributing is another entirely different story. Copy the repo, `npm ci` in the root (I cannot guarantee that it'll work with yarn; also there's no `yarn.lock`) and that's it - now you can edit any of the packages. When you are done, run tests with `npm test` (it'll include linting). If there's a need to fiddle with the docs, run `npm start` in the `website` directory. If you work on something and want the docs to rebuild, run `npm run build -- --watch` (root level) in parallel to the `npm start`.

**Comment by refactorized** [comment]
> Making a custom theme for an own project is one thing. Here I strongly recommend not to make a package, but simply a directory with components. Arguably `AutoField` is the most important one as it works as _router_ of the components. That's where the custom components fit in very well.

So this is what I tried at first, and what I would like to do.  But in copying the uniforms-material files I ran into issues mentioned above; specifically I had to take a dependency on typescript, and also had to deal with #433 issues. 

Create-react-app is supposed to be typescript friendly so I can proceed down that route with some confidence that I will get it worked out. So #433 is, it seems, the true roadblock preventing me from simply copying and modifying a handful of components.

**Comment by refactorized** [comment]
https://github.com/refactorized/uniforms-skel/tree/broken

I have put up a repo for making this easier to express, and hopefully fix.  Here follows the readme from that repo:

# Uniforms theme copy and modify skeleton example.

## background

I am trying to create a theme for uniforms based on the existing uniforms-material package 
and running into some issues when copying the original components.  This repo aims to 
illustrate the problems I am trying to solve in an isolated fashion.  Hopefully it will help 
to find a fix.

## Reference set-up
1) Run `npx create-react-app uniforms-skel --typescript`.  
2) Copy code from https://uniforms.tools/docs/tutorials-basic-uniforms-usage, except as a single file (no import of GuestSchema) and using uniforms-material instead of uniforms-semantic.

_At this point running the app (`npm start`)renders a very simple form_

## Source-copying uniforms-material compnents

1) Replace the uniforms-material dependency with the copied src files from the package
2) Try to `npm start`, compilation complains about missing invariant type and suggests `npm install @types/invariant` which I run
3) Try to `npm start`, typescript error: `Binding element 'autoField' implicitly has an 'any' type.  TS7031` so I add `"noImplicitAny": false` to my `tsconfig.json` file.
4) try to run `npm start` and get the dreaded `TypeError: Class constructor _class cannot be invoked without 'new'` error.

**Comment by radekmie** [comment]
In the end, it all boils down back to #433. I'll close this one, reopen #433 and we'll continue there.
