### ISSUE TITLE
Warning: `value` prop on `select` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.

### ISSUE THREAD

**Issue by vfonic** [vazco/uniforms#611]
What's the best way to avoid these kinds of warnings on auto fields?

More specifically, here's what I have:

```jsx
import { SelectField } from 'uniforms-unstyled';

// ...
<SelectField name="type" />
```

I'm getting this kind of object from my backend:

```js
obj = {
  // ...
  type: null,
}
```

Is this something I should fix myself "manually" in the code or?

```js
obj = _.pickBy({ type: null }, _.identity); // lodash's function to remove falsy values
```

This is not ideal solution for me because:
1. Removes `false` values as well.
2. Doesn't clean nested values.

**Comment by kestarumper** [comment]
Hi @vfonic,

First of all, uniforms won't do that - you should take care of the data.

> 1. Removes false values as well.

You are right, it will remove all falsy values. One could replace it with an arrow function that explicitly checks for `null`:
```js
obj = _.pickBy({ type: null }, x => x !== null);
```

> 2. Doesn't clean nested values.

Yes it doesn't. You should implement it by yourself.

**Comment by vfonic** [comment]
Ah I see. Ok, I'll fix the data on my end.

Thanks for the explanation!
