### ISSUE TITLE
onChange replaced uniforms call

### ISSUE THREAD

**Issue by agustinkassis** [vazco/uniforms#613]
Hi, I've been trying to create a custom field, but been unable to set the onChange prop to work.
Here is my code.

```javascript
import { SelectField } from 'uniforms-bootstrap4';

class BrandsSelect extends React.Component {
  constructor(props) {
    super(props);
    this.handleChange = this.handleChange.bind(this);
  }

  handleChange(brandId) {
    const stuff = 'some stuff';
    typeof this.props.onChange === 'function' && this.props.onChange(brandId, stuff);
  }

  render() {
    return (
      <SelectField onChange={this.handleChange} {...props} options={['a', 'b', 'c']} />
    );
  }
}

export {
  BrandsSelect,
};
```
It looks the uniform onChange from the SelectField is being overriden.
So the new function gets called, but the original from Uniform doesn't, so the field value is ignored when submitted. 

```jsx
<AutoForm onChange={notCalledFunction}>
  <BrandsSelect name="brand" onChange={calledFunction} />
</AutoForm>
```

The "notCalledFunction" is never reached.

**Comment by radekmie** [comment]
Hi @agustinkassis. All fields created using [`connectField`](https://uniforms.tools/docs/api-helpers#connectfieldcomponent-options), including `SelectField`, receive a predefined `onChange` prop. Your usage overrides it, so each time the `SelectField` calls `onChange`, it calls your `handleChange` function and the form doesn't know about it.

Depending on what are you trying to achieve, you should either create a custom field using `connectField` (you'll have `onChange` available there) or put this logic into the component handling the form state.

**Comment by radekmie** [comment]
No response so far, I'm closing. Feel free to comment anyway.

**Comment by agustinkassis** [comment]
Hello, I have no clue how or when to use connectField, there’s no example.
https://uniforms.tools/docs/api-helpers#connectfieldcomponent-options

**Comment by radekmie** [comment]
Yep, there are no examples in the API docs. You can find a few elsewhere, e.g. [Tutorials > Creating a custom field](https://uniforms.tools/docs/tutorials-creating-custom-field), or [Examples > Custom field](https://uniforms.tools/docs/examples-custom-fields/).
