### ISSUE TITLE
What is "Built in focus state management" and why is it not supported by uniforms?

### ISSUE THREAD

**Issue by rootsher** [vazco/uniforms#616]

**Comment by radekmie** [comment]
Hi @rootsher. By _focus management_ we mean an API to perform specific actions (like validation) on blur or focus, focus a field (e.g. when it has failed validation), check which field is currently focused, or check if the field is _pristine_ (focused from last validation).

**Comment by radekmie** [comment]
I'm closing as the question seems to be already answered. Feel free to comment anyway.
