### ISSUE TITLE
typescript error in uniforms-materialui

### ISSUE THREAD

**Issue by macrozone** [vazco/uniforms#617]
given 

```
import { AutoForm, AutoFields } from 'uniforms-material';

// later

   <AutoForm
         ...
        >
          <AutoFields />
        </AutoForm>

```

yields:

`JSX element type '{ [x: string]: any; }' is not a constructor function for JSX elements.`
`Type '{ [x: string]: any; }' is missing the following properties from type 'ElementClass': render, context, setState, forceUpdate, and 3 more.`

the generated type of `AutoForm` is:

```
declare const _default: {
    new (): {
        [x: string]: any;
    };
    [x: string]: any;
    Auto: (parent: any) => any;
};
export default _default;
```

it seems to complain about the type of `new()` which should be a react component

**Comment by radekmie** [comment]
Hi @macrozone. It's because `Quick`, `Validated` and `Auto` are not well-typed yet and TypeScript tries to do it best. I'll try to provide at least _some_ typings in the next version.
