### ISSUE TITLE
Super Complex field(s)

### ISSUE THREAD

**Issue by gerwinbrunner** [vazco/uniforms#618]
Hi,

I'm trying to build a super complex field and run into some issues - so I assume I'm doing something in a false manner.

Setting:
I'm having a field(s) where I want the get a timestamp at the end - but to get there it is more complicated.

It depends on some inputs  the core are:
- List of available dates by the user  (i.e. Monday and Wednesday)
- List of available dates form the service provider (Monday, Tuesday, Wednesday)

So after the user picked a date that matched he gets timeslot options (for simplicity I sapre the logic)

The issue is if there is no overlap between the available dates I want to add an error and error message, but I seem to not find a way do that in a custom field.

I know I could do it in the validator on the form, but then I would have to copy that logic to all the forms this field is used...

How would I go about this?

**Comment by radekmie** [comment]
Hi @gerwinbrunner. As you've already said, you can put it in the form - it'll work, but it'll double the logic. What I can suggest is to make this field required (I assume it already is), and if there's no valid value, call `onChange(undefined)` from it, which means _remove_ the value (make it empty). This way you'll see an error that it's required but there's no way to input a value. Additionally, you can somehow indicate, that it won't work, as there's no valid value already (e.g. an inline message).

**Comment by radekmie** [comment]
No response so far, I'm closing. Feel free to comment anyway.

**Comment by gerwinbrunner** [comment]
Figured out to work around it. Thx @radekmie
