### ISSUE TITLE
div in NestField leads to an infinite loop

### ISSUE THREAD

**Issue by RSchwan** [vazco/uniforms#62]
I have following form:
```
<AutoForm schema={schema} onSubmit={doc => console.log(doc)}>
  <AutoField name="title" />
  <div className="two fields">
    <AutoField name="field1" />
    <AutoField name="field2" />
  </div>
  <ListField name="courses">
    <ListItemField name="$">
      <NestField>
        <AutoField name="title" />
        <AutoField name="description" />
        <div className="three fields">
          <AutoField name="min" />
          <AutoField name="max" />
          <AutoField name="max2" />
        </div>
      </NestField>
    </ListItemField>
  </ListField>
  <ErrorsField />
</AutoForm>
```
This code leads to an infinite loop and the browser freezes. If I replace
```
<div className="three fields">
  <AutoField name="min" />
  <AutoField name="max" />
  <AutoField name="max2" />
</div>
```
with
```
<AutoField name="min" />
<AutoField name="max" />
<AutoField name="max2" />
```
the browser doesn't freeze.

**Comment by RSchwan** [comment]
The browser also freezes if there is an HiddenField in NestField

**Comment by radekmie** [comment]
That's a really interesting bug. I'll try to investigate it.

**Comment by radekmie** [comment]
What browser are you using? I've tried, but my browser has never frozen, but `Uncaught Error: Field not found in schema: 'min'` appeared. It's still a bug of course.

**Comment by RSchwan** [comment]
Chrome on a mac

**Comment by radekmie** [comment]
Which version?

**Comment by RSchwan** [comment]
51

**Comment by radekmie** [comment]
That's even more interesting - I'm on 53 and it's a completely different error. Okay, I'll try to fix it.

**Comment by radekmie** [comment]
Okay, I've got rid of this _(at least in latest chrome)_. Please, check if it works for you.

**Comment by RSchwan** [comment]
Perfect! Works 👍
