### ISSUE TITLE
Using custom field validation (for example: isFQDN)

### ISSUE THREAD

**Issue by rootsher** [vazco/uniforms#620]
I would like to use isFQDN function from https://github.com/validatorjs/validator.js - how can I do it?

**Comment by radekmie** [comment]
Hi @rootsher. It strongly depends on the schema you are using. For example, if it's SimpleSchema, then use the `custom` property, if it's JSONSchema or GraphQL then use it directly in your validator. For each schema, please refer to its documentation.

**Comment by rootsher** [comment]
Okay, so..what schema do you prefer? and why?

Have you seen the "https://www.npmjs.com/package/typescript-json-schema" solution? It looks interesting, what do you think about it?

**Comment by radekmie** [comment]
_Slightly_t offtopic. Personally, I use SimpleSchema (both versions) in many Meteor projects and JSONSchema everywhere else. When it comes to typing JSONSchema (any schema in general), here's my general suggestion: https://github.com/vazco/uniforms/issues/607#issuecomment-542730239.

As the question is already answered, I'm closing.
