### ISSUE TITLE
Difference between "simple-schema" and "simple-schema-2"

### ISSUE THREAD

**Issue by rootsher** [vazco/uniforms#621]
simple-schema is using: `meteor/aldeed:simple-schema`
simple-schema-2 is using: `"simpl-schema": "^1.0.0 || ^0.0.4"`

But simple-schema package is DEPRECATED and is directing us to "https://github.com/aldeed/simple-schema-js" - simple-schema-2 package.. so I should use the v2 and forget the first one, right?

**Comment by rootsher** [comment]
I see that simple-schema-2 is the most commonly used (https://github.com/vazco/uniforms/network/dependents?package_id=UGFja2FnZS00MTI2OTkyOTI%3D)

**Comment by radekmie** [comment]
Hi @rootsher. SimpleSchema (`meteor/aldeed:simple-schema`) is an old Atmosphere package, designed to work with Meteor (and it cannot be used outside of it). SimpleSchema 2 (we call it that way; `simpl-schema` on npm) is a reimplementation without any Meteor-related logic. In general, if you are not using Meteor but would like to use SimpleSchema, then `simpl-schema` it is.
