### ISSUE TITLE
Bootstrap3 and Bootstrap4 issues.

### ISSUE THREAD

**Issue by kestarumper** [vazco/uniforms#624]
We're aware of some errors with `Bootstrap3` and `Bootstrap4` themes which cause our website to crash. Other themes work fine.
We've recently added ES6 compilation targets, which appear to be causing this problem. We're investigating this issue.

**Comment by radekmie** [comment]
I've spent some time trying to find out what's going on. The root cause is that docs are importing both ES5 and ES6 code. Docusaurus is transpiling classes anyway, so it's not broken _everywhere_. I think we'll have to change all our imports to named sooner than we thought.
