### ISSUE TITLE
multipleOf property (json schema) causes issues

### ISSUE THREAD

**Issue by refactorized** [vazco/uniforms#625]
please see: https://github.com/refactorized/uniforms-skel/tree/issues/multipleOf for a minimal reproduction.

I am getting this console error: 

`index.js:1375 Warning: React does not recognize the `multipleOf` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `multipleof` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

When I add a `multipleOf: 5` property to my json schema for a field.  Also there is no UX provision for multiples it seems, but that is the smaller issue.  Right now I would like to see the value ignored rather than set as a component property.

**Comment by kestarumper** [comment]
Hi @refactorized,
For now you could use [`filterDOMProps.register('multipleOf')`](https://uniforms.tools/docs/api-helpers/#filterdompropsregisterpropa-propb-propc-) to mitigate this warning. Translating `multipleOf` into `step` is a separate topic which we will discuss internally.

**Comment by radekmie** [comment]
We've discussed it internally, and the decision is **not** to include it in the bridge. If one would like to set the `step` property (which `NumField` respects), then set it explicitly using props or `uniforms` key in JSON schema.

**Comment by refactorized** [comment]
I am more concerned about the errors it causes.  To that effect I can use filterDOMProps.register().  If I were to implement a component to be sensitive to such a prop would there be a strategy I could employ to have the prop ignored by standard components but still available to a component that would not ignore it? 

Putting it into a uniforms property is undesirable as it is a standard JsonSchema attribute, though I suppose I could have the uniforms attribute added with a preprocessing step which seems might be necessary for most sufficiently complex schemas.

**Comment by radekmie** [comment]
Every field receives a `field` prop, which is a reference to the field in the schema definition. In JSON schema, it's an object with the definition - you can access each of its properties, including `multipleOf`.

The thing with adding it to the filtered props _by default_ is that JSON schema allows custom keywords. On the other hand, one can implement custom fields that will correctly handle them. With an explicit registration in the project, you can decide which properties you do use and/or handle.

The preprocessing of schemas is a common thing to do. For example, you can define translation keys, custom props depending on the environment (e.g., different in a mobile app), or specific client-only validations automatically.
