### ISSUE TITLE
Trying to set the main form as ReadOnly

### ISSUE THREAD

**Issue by jogster** [vazco/uniforms#628]
I have an existing application using forms, that supports readOnly forms for users to view but not update the data. I have looked through the code and cannot see any read[O]nly properties/attributes.

I do see disabled - but this makes the form hard to read.

**Comment by kestarumper** [comment]
Hi @jogster,
In general, we don't support that because not every theme supports that. There are a few ways to achieve this:
1. Create your custom styling or theme.
2. Use `Quickform` instead of `AutoForm` and pass no `onChange` function which won't update the form state.
