### ISSUE TITLE
ListItem layout

### ISSUE THREAD

**Issue by jmaister** [vazco/uniforms#630]
I created a form for a bill, it has some fields for the bill and an array for the bill lines. I am using JSON Schema and Material-UI.

    const schema = {
        title: 'Bill',
        type: 'object',
        properties: {
            entityId: { type: 'number', label: 'ID', disabled: true },
            billNumber: { type: 'string', label: 'Number' },
            client: {
                type: 'object',
                properties: {
                    entityId: { type: 'number', label: 'Client', 
                        uniforms: {
                            component: SelectField,
                            options: allowedClients
                        }
                    }
                }
            },
            billLines: {
                type: 'array',
                uniforms: {
                    component: ListField
                },
                items: {
                    type: 'object',
                    properties: {
                        product: {
                            type: 'object',
                            properties: {
                                entityId: {
                                    uniforms: {
                                        component: SelectField,
                                        options: allowedProducts
                                    }
                                }
                            }
                        },
                        price: { type: 'number'},
                        tax: { type: 'number'},
                        items: { type: 'number'},
                        total: { type: 'number'},
                    }
                }
            }
        },
        required: ['billNumber', 'date', 'client']
    }

I would like to know how to do 2 things:

1. How to style the ADD and DELETE buttons? 
2. Is it possible to layout the list items horizontally?

![image](https://user-images.githubusercontent.com/374021/68151915-8c631300-ff3a-11e9-95b5-0150f497357c.png)

**Comment by kestarumper** [comment]
Hi @jmaister,
You could style it with props directly on a specific field to some point. One might achieve sophisticated styling or custom layout by creating your own [`ListField`](https://uniforms.tools/docs/api-fields/#listfield).

**Comment by jmaister** [comment]
I checked to create my own ListField. However I would need to duplicate it, then Autoform, ValidatedQuickForm, QuickForm, then override getAutoField().

Could I create a PR for showing showing nicer buttons for MaterialUI? So everybody can benefit of using AutoForm and having something that works better out of the box.

**Comment by radekmie** [comment]
It's not entirely accurate. You can use the `autoField` prop or extend the `AutoForm` class directly, without all the intermediate classes. It'll work as desired, but fields like `NestedField` won't use your `AutoField` anyway. The only solution here is to have a completely custom theme.

If you'd like to give it a shot, then go ahead and file a PR. I cannot guarantee that it'll get merged, but we'll have something to discuss on.
