### ISSUE TITLE
Material-UI ListField improvements

### ISSUE THREAD

**Issue by macrozone** [vazco/uniforms#639]
The Listfield is handy, but its design could be improved:

- the Remove button is not prominent and can easily be missed. Replace it with a Button that has an outline or background
- The Add button is also not very prominent and stretched: It should also be a button with an outline or a background
- the list items are hard to tell appart: We need some separation and maybe a header per list item.

by the way: In one project, i replaced the whole list field with a tab-view. I used https://github.com/ctxhou/react-tabtab there which also allowed to add/remove and even sort entries. I think its worth to think about how we can make lists easier to manage

**Comment by radekmie** [comment]
Hi, @macrozone. It's definitely not possible for us to replace _lists_ with _tabs_. I do agree, that such lists are not very handy _in general_, but not every theme such a concept of tabs.

When it comes to enhancing the current implementation of `List*Field`, everyone is welcome to provide a PR to change it. A few people actually raised this issue in the past but, as I assume, no one came with a general and strictly better idea.

**Comment by macrozone** [comment]
@radekmie react-tab-tab was just an example that was surprisingly fitting for the task of list management, that's why i showed it as an example. Maybe i build a package around it.

Can't we just leave the issue open to gather some ideas? Personally, i find the default ListField barely useable at all. Some themes are okeyish, e.g. antd or bootstrap3, but the material-ui looks a bit broken, also bootstrap4 has non-clear add and remove buttons.

I push a PR if i find time, because i need a better solution anyway at some point

**Comment by radekmie** [comment]
I don't see a need to keep this open. We are aware of its state, it was clear a long time ago. A PR is always welcome, no matter if there's an open issue or not.
