### ISSUE TITLE
Remove use of globalThis

### ISSUE THREAD

**Issue by Floriferous** [vazco/uniforms#641]
Related to #619. 

The use of globalThis in the recent versions of uniforms-material has caused a bit of pain in our codebase including our testing setup.

I see that this is only used in one small place in `DateField`. From what I understand about it (never seen it before), it requires a polyfill to work outside of typescript (which you also use for your documentation website).

For this one single line in this repo, we have to import and use a polyfill, so is it really necessary?

**Comment by refactorized** [comment]
Had this issue too, and in my case just replaced `globalThis` with `window`.  Not sure if that helps, but +1 on this issue from me.
