### ISSUE TITLE
Allow customizing Select's placeholder

### ISSUE THREAD

**Issue by Floriferous** [vazco/uniforms#642]
Due to the code at this line: https://github.com/vazco/uniforms/blob/98e350a73559948cea448caee1b46aeb89dad9b2/packages/uniforms-material/src/SelectField.tsx#L82

we are forced to have a "placeholder label" displayed in the Select on dropdown. We'd like to customize this behavior, but it is impossible given the current boolean.

Also, displaying the placeholder as the first item in a select is not something that seems obvious to most people. For example, if I have a select with label "Country", placeholder "USA", I don't want an additional disabled "USA" item appear at the top of my options, especially since USA will appear again, below within the list of selectable options.

I suggest we remove the disabled placeholder value in the select field, or add a boolean to enable/disable this behavior.

**Comment by radekmie** [comment]
Hi, @Floriferous. It is a common practice to provide the placeholders to signalize the desired value kind or an action - providing an actual value there seems a bit odd. Anyways, let's discuss the proposed change. An additional prop for disabling placeholder will work, but it's an additional prop to support in all themes (or increase the number of differences between themes). On the other hand, this logic is there to allow _removing_ the value (`required={!!disabled}`). For now, I suggest you change the placeholder for more action-like or create a custom field.
