### ISSUE TITLE
How to import (and register?) components for AutoForm [Question] [Docs]

### ISSUE THREAD

**Issue by refactorized** [vazco/uniforms#647]
In the documentation for using predefined fields (https://uniforms.tools/docs/tutorials-using-predefined-fields) the following statement is made:

> we can explicitly tell the AutoForm what field should be rendered. Just don't forget to import the desired one!

In this case, the field to use is specified in the schema, like so: 

```
...
    additionalInfo: { // the field in the schema
      type: 'string',
      uniforms: {
        component: LongTextField  // <--specify the component 
      }
    }
```

I imagine that this is also the approach for using a custom component.

What isn't clear to me is how to import the component, and make uniforms aware of that component, _without_ passing individual fields in the body of the AutoForm component.

**Comment by kestarumper** [comment]
Hi @refactorized,
There is a separate documentation section for creating custom fields that you can find [here](https://uniforms.tools/docs/tutorials-creating-custom-field). A complete schema definition file for this example is [here](https://github.com/vazco/uniforms/blob/master/docs/examples/Tutorial/GuestSchema4.js).

So summarising, you have to `import YourCustomComponent from './path/to/YourCustomComponent'` **in a schema file** and pass it to the schema definition.
