### ISSUE TITLE
tslib-lib required when SimpleSchema2 schema has array fields.

### ISSUE THREAD

**Issue by danyhiol** [vazco/uniforms#648]
Since the last update (`2.6.1`), `tslib` is required for schema that has field array:
```
materials: {
    type: Array,
    optional: true,
  },
  'materials.$': {
    type: Object,
    blackbox: true,
  },
```
Error:
`Uncaught TypeError: tslib_1.__spreadArrays is not a function
    at SimpleSchema2Bridge.js.SimpleSchema2Bridge.getInitialValue `

Confirm: 
when `npm i tslib` the error disappears.

But the following error appears:
`Uncaught TypeError: Cannot read property 'map' of undefined at renderSelect`
Code concerned  -> `props.allowedValues.map(function (value) { return (react_1.default.createElement(SelectAntD.Option, { key: value, value: value }, props.transform ? props.transform(value) : value)); }))); };`

```
"react": "^16.12.0"
"uniforms": "^2.6.1"
"uniforms-antd": "^2.6.1"
"uniforms-bridge-simple-schema-2": "^2.6.1"
"simpl-schema": "^1.5.6"
```

**Comment by radekmie** [comment]
Hi @danyhiol. Just to explain the problem: we've been using a newer version without explicitly depending on it.

**Comment by danyhiol** [comment]
I can confirm that the first problem is solved by the last update.
But there is another problem wish occurs: 
`Uncaught TypeError: tslib_1.__spreadArrays is not a function`
`Uncaught TypeError: Class constructor _a cannot be invoked without 'new' at new AutoValidatedQuickAntDForm`

**Comment by radekmie** [comment]
@danyhiol Are you actually importing named exports, i.e. `import {X} from 'uniforms-Y'`? If so, what is your bundler - Webpack/Parcel/Meteor/...?

**Comment by danyhiol** [comment]
I actually always use imports in the form `import AutoForm from 'uniforms-antd/AutoForm';`. I'm using `Meteor` as `bundler`.

**Comment by radekmie** [comment]
With the release of [`v2.6.0`](https://github.com/vazco/uniforms/blob/master/CHANGELOG.md#v260-2019-11-06) named imports became the default and _safer_ ones (in a way). They allow your bundler to choose between ES5 and ES6 build. Please give it a try and let me know how it worked.

**Comment by danyhiol** [comment]
Oh thanks that worked, I completely missed it from [v2.6.0](https://github.com/vazco/uniforms/tree/v2.6.0)
