### ISSUE TITLE
React 15.2.0 warning about unknown props

### ISSUE THREAD

**Issue by serkandurusoy** [vazco/uniforms#65]
Both form and field components cause warnings on the browser console

```
Unknown prop `xxxx` on <yyyy> tag. Remove this prop from the element.
For details, see https://fb.me/react-unknown-prop
```

It seems this is new and the recommended approach is to distill the props passed on to the standard html component, and use a valid, stripped-down version of the props instead of `{...props}` spreading them all onto them.

https://fb.me/react-unknown-prop

**Comment by radekmie** [comment]
It's already reported in #64.

**Comment by serkandurusoy** [comment]
Sorry just saw that, I've perhaps been away for too long :(
