### ISSUE TITLE
ListField with reordering and better buttons look (Material-UI)

### ISSUE THREAD

**Issue by chomamateusz** [vazco/uniforms#651]
Hi!

I've recently written a component that adds reordering items to ListField and improves look of buttons (IconButon with fullWidth is not good-looking in my opinion :)). 

It is written only for Material-UI, so I didn't do a PR. Maybe I should? If so - as a new component or modifying ListField?

Check it out here (code and demo) -> https://bit.dev/amazingdesign/uniforms/list-field-reorder

I am quite new to this project, so I hope to hear feedback about my modifications :)

**Comment by radekmie** [comment]
Hi there, @chomamateusz. It sounds promising! I just can't access the demo right now - it's loading indefinitely or displaying random errors. I'll try again later (or in a different browser), but could you post here a few screenshots of it? Preferably with both simple items, like `NumField` or `TextField` but also more complex ones, like `NestField`. An array of arrays would also be nice.

**Comment by chomamateusz** [comment]
Ow, the demo is failing in my browser now too :/ think it may be connected with https://github.com/vazco/uniforms/issues/638 or just the in browser bundlers aren't perfect ;)

Old-fashioned demo:
https://github.com/chomamateusz/list-field-reorder-demo
http://list-field-reorder-demo.surge.sh/

Added nested arrays.

What do you mean to use `NestField`? I was using Uniforms mostly with `AutoForm` only, did not use its children much.

**Comment by radekmie** [comment]
Cool, now I can finally play with it! `NestField` is just a field for rendering objects and it's already in your demo.

Looks good for me, but I'd have to ask a few people actually using the current one if they like it as well. If so, we could include it in the v3.

**Comment by chomamateusz** [comment]
Cool :) It's now quite simple field, built in moment of need when developing bigger project.

I've built once a field generator like Uniforms (but Uniforms are more unified, so I started using it), and in my generator I had a more flexible field with e.g. collapsing possibilities. Drag and drop would be nice. I will probably continue to develop this field. I also have now monaco editor field also I think is too specified to include in Uniforms package, right?

It is possible that v3 will be released as you said "The first version should be released by the end of November 2019."?

**Comment by radekmie** [comment]
> It's now quite simple field, built in moment of need when developing bigger project.

Sure, that's normal. It's nice though!

>  I also have now monaco editor field [...]

Yep, it's too tied with it and not really in align with any theme package. You can release it by yourself as well.

> It is possible that v3 will be released as you said "The first version should be released by the end of November 2019."?

I'll try to squeeze it this week. Is 1st of December _valid_? :laughing:

**Comment by lightningboss** [comment]
Hey @chomamateusz this looks awesome. I was having a similar thought about the material UI integration.
@radekmie Is there a way I can support you with this?

**Comment by radekmie** [comment]
Hey @lightningboss. Well, there's nothing _to do_, but if you'll make something you think more people would like - just open an issue to discuss or even file a PR. When it comes to this very `ListField` - `v3` branch is already there so a PR could be created.

**Comment by radekmie** [comment]
We've discussed this and due to cross-theme compatibility reasons (all themes would need to implement reordering) we've decided not to do it. However, once #640 land, it'll be fairly easy to swap certain fields to their custom counterparts.
