### ISSUE TITLE
Bootstrap 3/4 input groups

### ISSUE THREAD

**Issue by Pagebakers** [vazco/uniforms#654]
There doesn't seem to be an easy to create input groups for bootstrap form fields.

```bootstrap 3
  <div class="form-group">
    <label class="sr-only" for="exampleInputAmount">Amount (in dollars)</label>
    <div class="input-group">
      <div class="input-group-addon">$</div>
      <input type="text" class="form-control" id="exampleInputAmount" placeholder="Amount">
      <div class="input-group-addon">.00</div>
    </div>
  </div>
```

```bootstrap 4
<div class="input-group mb-3">
  <input type="text" class="form-control" placeholder="Recipient's username" aria-label="Recipient's username" aria-describedby="basic-addon2">
  <div class="input-group-append">
    <span class="input-group-text" id="basic-addon2">@example.com</span>
  </div>
</div>
```

Any plans to add support for this? or have a suggestion how to accomplish this with AutoField?

I tried using wrapClassName, but there's no way to add extra children before or after the input.

Making this configurable would be really great:
```js
      <AutoField group prefix="€" suffix={<SuffixComponent />} />
```

```js
     let input
     if (group) {
        input = (
                <div className="input-group">
                        {prefix && <div className="input-group-addon">{prefix}</div>}
                        {children}
                        {suffix && <div className="input-group-addon">{suffix}</div>}
                 </div>
        )
     } else {
         input = children
     }

      {hasWrap && (
        <div
          className={classnames(wrapClassName, gridClassName(grid, 'input'))}
        >
          {input}
          {blockFeedback}
          {blockHelp}
          {blockError}
        </div>
      )}
```

**Comment by radekmie** [comment]
Hi @Pagebakers. There's a lot of places where we could put an additional node from props. I also sometimes miss one or two. The problem is that this would generate an immense number of such props. The best and suggested solution for your case would be to create a custom component.

**Comment by Pagebakers** [comment]
Creating a custom component was my first idea, but this means I'll have to create a new custom component for every field type because the way the components are structured. Which basically means I'll have to create to totally new theme in order to use this bootstrap3 functionality.

Another solution would be to be able to ignore the wrapField in the field components. That way you could create a custom GroupField that supports prefix/suffix and which in turn renders the appropriate field type component (just like AutoField)
This is also how the meteor:autoform components work, for example <TextField/> is just a bare field without the wrapper and <AutoField type="text"> includes the field with the form-group wrapper. This gives a lot more flexibility.

**Comment by radekmie** [comment]
Yep, you are right. The thing is that there's a lot of such possibilities and we simply cannot handle all of them. I'll give it a second thought, but don't be afraid of creating a custom theme.

I know how it looked like in AutoForms and we are trying to achieve a similar feeling but in React. If you have an idea of how it may look API-wise - do let me know.
