### ISSUE TITLE
SimpleSchema: minCount arrays set to null

### ISSUE THREAD

**Issue by danyhiol** [vazco/uniforms#656]
When defining a `non-empty` array with `SimpleSchema2` using `minCount`, default null value(s) are set in the form array. See picture below for more.
[Image](https://ibb.co/DMgHRRg) - [link](https://ibb.co/DMgHRRg)

**Comment by radekmie** [comment]
Hi @danyhiol. The image you've posted is not working but there is an actual problem with this schema:

```ts
new SimpleSchema({
  'xs': { type: Array, minCount: 3 },
  'xs.$': { type: Object },
  'xs.$.x': { type: String }
})
```

**Comment by danyhiol** [comment]
@radekmie I've updated the link. Also, why does it have to be an object? I'm trying to build an array of strings with a minimum of 2 elements (in case of the example) inside.
```
new SimpleSchema({
  members: {
    type: Array,
    minCount: 2, 
  },
  "members.$": {
    type: String,
    uniforms: {
       options: [{label: "Label1", value: "val1"}, {label: "Label2", value: "val2"}]
    }
})
```

**Comment by radekmie** [comment]
OK, it’s even worse then.

**Comment by danyhiol** [comment]
I don't know if I missed something, but the last update did not fixed the issue. Check it in the playground with the same schema. And you still get two null values inside the object.

**Comment by radekmie** [comment]
It's not really visible in the playground as we are serializing it with `JSON.stringify` and there's no `undefined` in JSON. You can test it out calling `bridge.getInitialValue(field)` or through React DevTools - the model is alright. The actual problem was that we were initializing the model with arrays with _holes_, now we explicitly set `undefined` values everywhere.

**Comment by danyhiol** [comment]
This did not solve the problem. Since there are still `null` values in the object. `bridge.getInitialValue(field)` returns `[undefined, undefined]`

**Comment by radekmie** [comment]
It's correct. You have to call `schema.clean` (remember not to mutate the object!) to get rid of that.

**Comment by danyhiol** [comment]
I called `const bridge = new SimpleSchema2Bridge(schema.clean());`
then `console.log(bridge)` I get `TypeError: Cannot convert undefined or null to object`.
Or am I missing something?

**Comment by radekmie** [comment]
No, you should call `schema.clean(model)` to get a clean model. I just noticed though, that cleaning doesn't remove those `undefined` values, but also it passes the validation. Using your example schema, `schema.validate({ members: [undefined, undefined] })` just works.

**Comment by danyhiol** [comment]
This is already at the validation level. I use: `validation context` for that. My problem is the fact that the `UI` is showing `non-empty` list. I was expecting the `UI` to be empty with a validation text like (you must provide at least 2 members). SimpleSchema considers this: `members: [undefined, undefined]` as valid and don't clear/clean it.

**Comment by radekmie** [comment]
It'll work with an actual list. Using `options` changes it to checkboxes. What is your use case?

**Comment by danyhiol** [comment]
Yes, I'm using a `SelectField` with `options`.
just as defined above
```
new SimpleSchema({
  members: {
    type: Array,
    minCount: 2, 
  },
  "members.$": {
    type: String,
    uniforms: {
       options: [{label: "Label1", value: "val1"}, {label: "Label2", value: "val2"}]
    }
})
```

**Comment by radekmie** [comment]
Yes, I can see the schema but what you'd like to achieve? Have a list of dropdowns?

**Comment by danyhiol** [comment]
My aim is to have the members field empty (without the 2 empty checkboxes) and a validation text requiring the user to choose at least 2 options. [Reproduction](https://uniforms.tools/playground/#?N4IgDgTgpgzlAuIBcIDqUA2BjA9gWygEIQAacCHMGZUAQwFd4cZaA3KZAM1ozjIaYt2AEUy0AnsgCMABhlkAJgEsWAIwxQFXHnxAZaqzMngR6UMmH1YoACxwYFUCNt7mQMLDah5ayEADsoAHcAAgBlJTxLKDDPb1oACmAAHX8Q9JCFWngoJBCUtIyi-HEwXJDhbPNUoqLHbnoMeAA1HjM8wNDKnISAShqMgF8SVIH02gVG-DyC2oySsryAIRx7KFp_MZDh0cL0mCUAL3LZuZCF8rCTJX8AcxG92vqGJtaMdpCAcjxPh7OQngYHBBTRvMwwPIAbU-AA8YL8vvCSF8fsjPhgEbCMQBdLY7TaPCDZG63GZbYqlcoAOXoeEMED-Z0BwNBbVgUKkyIATMiAMzIgAsyIArNjGXN6P4lJwcBA8BD8uSznEsABrVQ4GHs86mKBK9KDPEPLacCBKKD-BQK05zC55ACCECJ4nFtTwNwAwjhJdMQlIjbsip9TebLTAAHQAEk-ZMeFMWIQA8qoAFZQLDwAMEoMhi1WqPh_y0AgxxVx-aUvJXM13V1Fd3-PK8rNbYNmvMRyPh2i3KClm21O0hGl0px1jINvLyfUhHwwvJSYUyFv-AijiDWrZDx3O10Nr0-vI8kIDfHpZIgNf0zsX2Pxy7XWtbSXS2Xyu9zSjwJQ4fwKyHAPohgYHkF4ADIGJg_qkCErBsqBIBwRg0HDPkQGYAhEHAVyF7IkhHwXkhOEgIMuKPIa_gUYMvSkO4dhBAAkv4GA3FAACiTqyi4ui0DA4j-Fgib-GE9CqO6iBINwrj8HxAlCW8ShZDk3FQMMIDwF4BB-Bs8BaIMQA)

**Comment by radekmie** [comment]
OK, indeed, it's not really useful. It's a separate problem though - please do file a new issue for a problem regarding the multi-select.

**Comment by danyhiol** [comment]
okay...
Also, I realized that setting `autoSize: { minRows: 4, maxRows: 8 }`, on `LongTextField` return the following error: 
`Warning: Removing a style property during rerender (overflow) when a conflicting property is set (overflowY) can lead to styling bugs. To avoid this, don't mix shorthand and non-shorthand properties for the same value; instead, replace the shorthand with separate values. in textarea`.
Is this normal or should i file an issue?

**Comment by radekmie** [comment]
I've never seen that warning - do file another issue, including AntD version.
