### ISSUE TITLE
[Feature Request] Pass the modifier along with the document

### ISSUE THREAD

**Issue by serkandurusoy** [vazco/uniforms#66]
Form events such as `onSubmit` currently only passes `doc` but there are cases where a `modifier` is more suitable, especially for `update` forms

Consider a schema where all the fields are optional

```js
collection = new Mongo.Collection('sample')

schema = new SimpleSchema({
  foo: {type: String, optional: true},
  bar: {type: String, optional: true},
})

collection.attachSchema(schema)
``` 

and consider this document:

```js
doc = {
   foo: "some value"
}

<AutoForm onSubmit={ doc => collection.update( this.props.docId, { $set: {...doc} } ) } model={doc} schema={schema} />
```
Now if you delete the value of foo and submit, this will throw error saying that after filtering out, modifier is empty.

This is expected because `collection2` trims trailing spaces, deletes empty fields, runs autovalues etc before doing the actual insert, at which time `doc` becomes `{}` so instead, we need to `$unset: { foo: '' }` so to mitigate this, I am currently doing this:

```js
function handler(docId,doc) {
  const unsetDoc = schema.objectKeys
    .filter( key => !doc[key] )
    .map( key => ( {[key]: ''} ) )
    .reduce( (obj, unset) => {
      obj[Object.keys(unset)[0]] = unset[Object.keys(unset)[0]];
      return obj;
    }, {} );

  let modifier = {};

  if (Object.keys(doc).length > 0) {
    modifier.$set = {...doc}
  }

  if (Object.keys(unsetDoc).length > 0) {
    modifier.$unset = {...unsetDoc}
  }

  collection.update(docId, modifier);

}
```

But it would be awesome if `onSubmit` were able to provide me the `modifier` out of box, such that, the following would work:

```
<AutoForm 
  onSubmit={ (doc,modifier) => handler(this.props.docId, modifier) } 
  model={doc} 
  schema={schema} />
```

Now the original autoform has solutions similar to this:

* [update form](https://github.com/aldeed/meteor-autoform#update) automatically handles this, providing a modifier and passing it on to the collection
* [method update form](https://github.com/aldeed/meteor-autoform#method-update) which provides you a modifier and document id which you can pass on to your methods
* [hooks](https://github.com/aldeed/meteor-autoform#callbackshooks) where `onSubmit` passes a doc and a modifier and a `formToModifier` hook which directly takes the modifier whenever form fields change (like an `onChange` for update forms)

For code reference, you can take a look at [here](https://github.com/aldeed/meteor-autoform/blob/16f100ce96a13823b293414f5c615ea67693a39e/autoform-api.js#L365-L383) and [here](https://github.com/aldeed/meteor-autoform/blob/16f100ce96a13823b293414f5c615ea67693a39e/utility.js#L63-L93)

**Comment by radekmie** [comment]
Finally!
I've waited so long to get a possibility to provide an example with extending `BaseForm`. Let's create a `ModifierForm` (okay, it will be `AutoValidatedQuickModifierForm`)!

```js
import {AutoForm} from 'uniforms';
import {BaseForm} from 'uniforms'; // or stylised one, like uniforms-semantic

const Modifier = parent => class extends parent {
    static Modifier = Modifier;

    static displayName = `Modifier${parent.displayName}`;

    onSubmit (event) {
        if (event) {
            event.preventDefault();
            event.stopPropagation();
        }

        if (this.props.onSubmit) {
            // You can also omit unchanged keys.
            const $set = this.getModel();
            const $unset = getChildContextSchema.getSubfields()
                .filter(key => !$set[key])
                .reduce((acc, key) => ({...acc, [key]: ''}))

            this.props.onSubmit({
                Object.keys($set).length   > 0 && {$set},
                Object.keys($unset).length > 0 && {$unset}
            });
        }
    }
};

// This might seem a little bit crazy, but we have to override BaseForm#onSubmit
export default UpdateForm = AutoForm.Auto(AutoForm.Validated(AutoForm.Quick(Modifier(BaseForm))));
```

From here, you can easily create an `UpdateForm` with direct collection support.

**Note:** This API will remain unchanged, but some _shortcuts_ are planned.

**Comment by serkandurusoy** [comment]
Whoa! This is a precious gem! It never occured to me to extend from existing form components like this, wow!

**Comment by GoaGit** [comment]
You provide an excellent explanation @radekmie about how to construct a modifier form. What is the proper way to actually use the modifier form you created in the example, given a schema, model and function? My first idea is  would be:

import UpdateForm from '/path/to/updateform.js'
...
<UpdateForm 
  schema={SomeImportedSchema}
  model={SomeProvidedModel}
  onSubmit={SomeProvidedFunction}
/>

This does not render a form. Do I overlook something?

**Comment by radekmie** [comment]
No, @GoaGit, it's my fault - I wrote it as a concept and haven't tested it. Now I've done and I've just updated that implementation.

**Comment by GoaGit** [comment]
That's really awesome @radekmie. You've created a very elegant solution. Looking forward to be able to use it.
