### ISSUE TITLE
SubmitField and ErrorsField throw in TypeScript

### ISSUE THREAD

**Issue by chmac** [vazco/uniforms#661]
```
Foo.tsx
TypeScript error in Foo.tsx(13,10):
Property 'children' is missing in type '{}' but required in type '{ [x: string]: any; children: any; disabled?: any; inputRef?: any; label?: any; value?: any; }'.  TS2741
```

The typing that I see for the `SubmitField` from material is like so:

```typescript
/// <reference types="react" />
declare const SubmitField: {
    ({ children, disabled, inputRef, label, value, ...props }: {
        [x: string]: any;
        children: any;
        disabled: any;
        inputRef: any;
        label: any;
        value: any;
    }, { uniforms: { error, state } }: {
        uniforms: {
            error: any;
            state: any;
        };
    }): JSX.Element;
    contextTypes: {
        uniforms: any;
    };
    defaultProps: {
        label: string;
        variant: string;
    };
};
export default SubmitField;
```

If I make all the parameters optional on the first example (by editing the definition file) then my error goes away. I'm not sure how these definition files are built, so I'm not sure where these changes could be made. I guess there's typing missing in the material `SubmitField` component...

**Comment by radekmie** [comment]
Hi @chmac. Indeed, currently inferred types are... Not suitable to work with. We'll try to do as much as possible now, but more general support will come with v3.

**Comment by chmac** [comment]
OK. Will wait to see how it works in v3. Right now I worked around the issue by just replacing the `<SubmitField` with a simple `<Button`. I don't have the whole lerna setup running for uniforms so won't be able to do much in terms of useful PRs.
