### ISSUE TITLE
How to set a default value with GraphQLSchemaBridge?

### ISSUE THREAD

**Issue by znat** [vazco/uniforms#665]
I tried the following but the value is never set:

```
const schemaData = {
        linksTarget: {
            defaultValue: '_blank',
            options: [
                { label: 'Current tab', value: '_blank' },
                { label: 'New tab', value: '_self' },
            ],
        },
```

**Comment by radekmie** [comment]
Hi @znat. In GraphQLBridge the default value is called the [`initialValue`](https://github.com/vazco/uniforms/blob/81c554ff6cf5db9b092086c0490daaee0385b2e3/packages/uniforms-bridge-graphql/src/GraphQLBridge.ts#L130).

**Comment by radekmie** [comment]
No response so far, I'm closing. Feel free to comment anyway.

**Comment by znat** [comment]
Hi, sorry for not answering earlier, and thank you for the quick response @radekmie !
