### ISSUE TITLE
Autoform.js error: TypeError: class constructors must be invoked with new

### ISSUE THREAD

**Issue by averissimo** [vazco/uniforms#666]
Error on both `v2.6.3` and `v3.0.0-alpha.0`. Code for the form is dead simple with autofields and submit button.

I might be missing some incompatibility, if so I'm sorry for wasting time. I've been digging on this for a while, thus I'm posting the issue.

"@babel/runtime": "^7.7.6",
"react": "^16.12.0",
"react-dom": "^16.12.0",
"uniforms": "^2.6.3",
"uniforms-semantic": "^2.6.3",
"simpl-schema": "^1.5.6",

The error is `TypeError: class constructors must be invoked with 'new'`

In the console it says it was generated from the <AutoValidatedQuickSemanticForm> component.

On the 5th line of the code below 

```
// node_modules/uniforms-semantic/AutoForm.js                                                                          //
...
var Auto = function (parent) { var _a; return _a = /** @class */ (function (_super) {
        tslib_1.__extends(class_1, _super);
        function class_1() {
            return _super !== null && _super.apply(this, arguments) || this;
        }
        return class_1;
    }(uniforms_1.AutoForm.Auto(parent))),
    _a.Auto = Auto,
    _a; };
exports.default = Auto(ValidatedQuickForm_1.default);
```

Thanks.

**Comment by radekmie** [comment]
Hi there, @averissimo. Could you go up with the stack trace and paste the code from your project as well? It may be helpful.

In general, this may be the case of double transpilation. Please check if you do `import X from 'uniforms/X'` or `import { X } from 'uniforms'` (same for themes) - the latter should work.

**Comment by averissimo** [comment]
Thank you for the help. That was it.

I have no idea why that kind of import was used in the first case. This is the problem when I juggle multiple programming languages and then revive old code :)
