### ISSUE TITLE
Built-in Grid Layout support

### ISSUE THREAD

**Issue by p1Machado** [vazco/uniforms#667]
Hi, guys.

This is my first try on Uniforms. Got really excited thinking on the usage of a grid-area css rule to allow easy layouts using grid-template-areas.

What about a discussion on grids support to facilitate form layouts?

Checkout this experience and [how it came out on the screen](https://ibb.co/tPTq8xJ):

```
import React from "react";
import { AutoForm, AutoField } from "uniforms-material";
import { JSONSchemaBridge } from "uniforms-bridge-json-schema";
import Ajv from "ajv";

const ajv = new Ajv({ allErrors: true, useDefaults: true });

const schema = {
  title: "Guest",
  type: "object",
  properties: {
    firstName: { type: "string" },
    lastName: { type: "string" },
    workExperience: {
      description: "Work experience in years",
      type: "integer",
      minimum: 0,
      maximum: 100,
    },
  },
  required: ["firstName", "lastName"],
};

function createValidator(schema) {
  const validator = ajv.compile(schema);
  return (model) => {
    validator(model);
    if (validator.errors && validator.errors.length) {
      throw new Error({ details: validator.errors });
    }
  };
}
const schemaValidator = createValidator(schema);

const bridge = new JSONSchemaBridge(schema, schemaValidator);

export default {
  title: "Uniforms",
};

export const simple = () => {
  return (
    <AutoForm
      schema={bridge}
      onSubmit={console.log}
      style={{
        display: "grid",
        gridTemplateAreas: `
        "firstName lastName"
        "workExperience workExperience"
        `,
        gridColumnGap: 16,
      }}
    >
      <AutoFieldLayout name="firstName" />
      <AutoFieldLayout name="lastName" />
      <AutoFieldLayout name="workExperience" />
    </AutoForm>
  );
};

function AutoFieldLayout({ name }) {
  return <AutoField name={name} style={{ gridArea: name }} />;
}
```

Would be really happy to discuss and collaborate with PR.

**Comment by radekmie** [comment]
Hi @p1Machado. That looks pretty neat! I'd rather not include it in the package though. One, as a rule, we try to keep the API lean, two, it'd be rather hard to keep it consistent between themes as we don't provide any CSS code.

Anyway, I really like it and I'm glad that you've shared it. It shows how easy is to do such a layout with modern CSS and a small wrapper on top of uniforms. Please share the CSS snippet as well. Thanks!

**Comment by p1Machado** [comment]
I understand your concerns about the project scope and keeping it lean. You're right.
Even passed through my mind of creating another lib to wrap Uniforms. But, actually I've been thinking if it would be useful for the most people. Instead of creating a wrapper library and bothering about keeping it consistent with Uniforms, I thought of providing some additional use cases to your project's doc.

What do you think about enhancing the docs with some variety of use cases. Some devs might have trouble conceiving good approaches on top of Uniforms. I have big concerns about easy form development in the company I work, and can further explore some use cases for Uniforms.


Would be amazing to contribute to your project, I really enjoy the Uniforms API and will continue to look for productive ways of using it.

**Comment by radekmie** [comment]
Making it into a separate package is too much - that's true. There's the _Examples_ section in the docs. Feel free to file a PR and put it in there. We can agree on rearranging it later.

**Comment by radekmie** [comment]
OK, I think we've actually closed this topic. I still hope to see this PR though!

**Comment by p1Machado** [comment]
I'm still using Uniforms, just didn't achieved a real scenario in my project to share with everybody. When I came in a good design I will sure issue a PR to share it.

Just for curiosity, this the project I'm working on: [https://app.pmachado.xyz/projetos/1](https://app.pmachado.xyz/projetos/1)
Ps.: it doesn't work on old browser cause I'm still using Uniforms 2.5 with globalThis.
