### ISSUE TITLE
Issues with simpl schema

### ISSUE THREAD

**Issue by mariusrak** [vazco/uniforms#668]
Hi, get errors from `simpl-schema` (`simple-schema2`) with new (v2) uniforms.
```Error: Invalid definition for password field: "uniforms" is not a supported property```
 In previous version, [it was required to](https://github.com/vazco/uniforms/issues/261#issuecomment-294981710) `import 'uniforms'` once before `simpl-schema` was imported (#261). That make keyword `uniforms` work with simpl-schema. But with new version, I don't understand how can I make it work. I see something with bridges, but I don't understand. Am I supposed to import bridge package and create new brigde with every new schema? If so, it seems like rather big complication and overhead compared to previous version.
Thanks.

**Comment by radekmie** [comment]
Hi @mariusrak. No, you don't have to create bridges manually. Instead of importing `uniforms` you have to import `uniforms-bridge-simple-schema-2`. You can read more about this change in the [changelog](https://github.com/vazco/uniforms/blob/master/CHANGELOG.md#v200-alpha0-2019-05-01).

**Comment by mariusrak** [comment]
It didn't help.
In previous version I did `import "uniforms"` only once in initial file. Now I have `import "uniforms-bridge-simple-schema-2";` but I still get errors.
After I put it some other places, where I use `SimpleSchema` constructor, I get `Uncaught Invariant Violation: Unrecognised schema: [object Object]`.

According to [documentation](https://ics-software-engineering.github.io/meteor-example-form-react/) I have to create bridges as mentioned in original question.
According to [some uniforms example](https://ics-software-engineering.github.io/meteor-example-form-react/) I have to put it everywhere I use uniforms-created form. Which I tried and get the error.
Importing only in single initial file produce `Uncaught Error: Invalid definition for pass field: "uniforms" is not a supported property`

So, I got totaly lost, did I miss something in documentation where this is explained?

**Comment by radekmie** [comment]
You have to import it once before creating schemas for the SimpleSchema registration, but also once before the rendering the forms to make the bridge registered in uniforms.

**Comment by mariusrak** [comment]
I'm still confused. [Documentation](https://uniforms.tools/docs/tutorials-basic-uniforms-usage) show example with creating bridge, which is passed to `<AutoForm />`as schema. There is no info about importing something "once".

Also it is once per what? Once per project, once per file, once per function, once per form? Is there some "global" variable holding the bridge? 

Can you please show an example with simple schema 2?

Thanks.

**Comment by radekmie** [comment]
Yes, the documentation states so, as it's the only way to work with JSON schema.

_Once per project_ is enough.
* When you create a schema instance, it checks all of its properties, which can include the `uniforms` property. If it does, it has to be _registered_, which is in [`uniforms-bridge-simple-schema-2/register`](https://github.com/vazco/uniforms/blob/45c7ccc8d1292d79472b9ba8f8ce09026648e507/packages/uniforms-bridge-simple-schema-2/src/register.ts#L10), which is by default loaded when using `uniforms-bridge-simple-schema-2`.
* When you create a form instance, it transforms the received schema or bridge into a bridge, using [`createSchemaBridge`](https://github.com/vazco/uniforms/blob/45c7ccc8d1292d79472b9ba8f8ce09026648e507/packages/uniforms/src/BaseForm.tsx#L97). To do so, it has to be registered using `createSchemaBridge.register`, which is also included in [`uniforms-bridge-simple-schema-2/register`](https://github.com/vazco/uniforms/blob/45c7ccc8d1292d79472b9ba8f8ce09026648e507/packages/uniforms-bridge-simple-schema-2/src/register.ts#L7).
