### ISSUE TITLE
Invalid `id`

### ISSUE THREAD

**Issue by metamn** [vazco/uniforms#671]
Hello,

I've just run the example from: https://github.com/vazco/uniforms/issues/549
In the generated form we have:

```
<div class="ui checkbox"><input id="uniforms-0000-0001-Impact One" name="impact" type="checkbox"><label for="uniforms-0000-0001-Impact One">Impact One</label></div>
```

`uniforms-0000-0001-Impact One` contains a whitespace which is invalid: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id

**Comment by kestarumper** [comment]
Hi @metamn,
Yes, you are right, this is a bug. We'll get to it soon.
