### ISSUE TITLE
Missing icons when upgrading from 1.31 to 2.6

### ISSUE THREAD

**Issue by znat** [vazco/uniforms#673]
I recently upgraded uniforms (on ReactSemantic-UI) and all icons are gone. We use regular semantic ui icons in other places of the app and they're still there. Any idea where to look?

**Comment by radekmie** [comment]
Hi @znat. Version 1.3.0 was released [over three years ago](https://github.com/vazco/uniforms/blob/master/CHANGELOG.md#v130-2016-10-19) - that's a lot of versions! I don't recall any icons-related changes in that theme, though. Have you tried to update the version gradually (e.g. 1.3.0 -> 1.20.4 -> 1.31.1 -> 2.0.0 -> 2.6.5)? If not, please do and share your findings.

**Comment by znat** [comment]
It was actually from 1.31 not from 1.3 :)
I'll keep looking, it might have roots in the deeper Meteor magic

**Comment by radekmie** [comment]
No response so far - I hope you've already solved the issue. If you've found (or will find) something interesting, feel free to comment here.

**Comment by znat** [comment]
In the end it was just a conflict with our css. No issue on your side
