### ISSUE TITLE
html input readonly attribute

### ISSUE THREAD

**Issue by cunneen** [vazco/uniforms#674]
Hi, the `readonly` attribute of an html input doesn't seem to be supported. I want to use it in the case where one of the fields is calculated from others, so that the user sees and submits the value but can't modify it via the UI.

The `disabled` attribute doesn't fit my case as I want it to be styled appropriately via bootstrap themes and submitted accordingly.

edit: I'm using SimpleSchema and Bootstrap 3.

**Comment by radekmie** [comment]
Hi @cunneen. It was actually requested a few times already - both on Gitter and here (e.g. #628). Up to this point, we were strongly against, as it's hard to support it across all themes in a consistent way. Right now, thinking about v3 (#646), I think we can actually do it. It'll require _some_ work in the core (probably easy as soon as we'll manage the context extensions properly) and definitely more work in the themes. But the good thing about it is that we don't have to do it all at once - one at a time is OK.

The plan is as follows:
* Update (preferably) all themes to respect the `readonly` prop. That's something we can introduce right now, as a feature. It can be done by anybody, especially by outside collaborators just like you!
* Update the core to pass the `readonly` prop in the same manner as `disabled` right now. This part is actually bigger, _preferably_ doable in v3.
* If both above are done, officially support read-only mode in uniforms, stating it in the documentation.
