### ISSUE TITLE
How to scroll on error?

### ISSUE THREAD

**Issue by maximshmakov** [vazco/uniforms#678]
Hi, I need some help. I am trying to scroll the page to the first field with an error from the form.
Could you please guide me, to achieve that?

**Comment by kestarumper** [comment]
Hi @maximshmakov,
You could plug in your custom logic in [`onValidate`](https://uniforms.tools/docs/api-forms/#props-1) callback, which provides you with `error` from the schema. Based on that error, you have to _somehow_ select and scroll to the appropriate DOM element. For example you could use [`Element.scrollIntoView`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView).

**Comment by kestarumper** [comment]
I believe the above response solved the issue. Fell free to ask for more help if needed.
