### ISSUE TITLE
Question: How to focus on a specific field after submitting?

### ISSUE THREAD

**Issue by serkandurusoy** [vazco/uniforms#68]
I want to be able to focus on a specific field on a form after the form submit has been handled, but could not manage to get a reference to the input of a field component I want to target.

Tried to track down some API for that but could not find one, so what would be the canonical way to get a reference for an input?

**Comment by radekmie** [comment]
Well, there's no such API, because there don't have to be any `input` - take the `HiddenField` (with `noDOM` prop) as an example. Or a custom field with 2 `input`s. What then?

**Comment by serkandurusoy** [comment]
Well my main point is not about focusing, but it is about being able to get
a reference, though you are right that the reference would not mean
anything for non-standard componets.

I simply achieved this by creating a new input component that accepted a
prop that gets passed to the `input`'s `ref`

​

**Comment by radekmie** [comment]
Okay, so some fields like `TextField` or `NumField` could pass own `ref` prop to proper `input`. That should be enough, isn't it?

**Comment by serkandurusoy** [comment]
Sure, definitely. In fact, that's how I solved my immediate problem.

The only gotcha is you cannot name that property as `ref`because it is
reserved.

On Wed, Jul 13, 2016 at 12:36 PM, Radosław Miernik <notifications@github.com

**Comment by radekmie** [comment]
Okay, any idea, how to call it? How about `inputRef`?

**Comment by serkandurusoy** [comment]
Yep that's a good name, indeed!
