### ISSUE TITLE
Changing model inside onChangeModel doesn't re-render form to match form state

### ISSUE THREAD

**Issue by adamldoyle** [vazco/uniforms#682]
I'm trying to use the onChangeModel prop with an AutoForm to change one fields value based off of another field (specific use-case is selecting an option from a dropdown fills out some default values for other fields).  I'm running into an issue where the actual HTML form only shows the updated values after the first edit to the form and all subsequent edits don't produce any visible change with the form.  However, the model within the state has the updated values, so it seems that a re-render on the HTML form isn't happening.

Here's a reproduction that shows the issue (any updates to the first field should be replicated to the other four fields): https://codesandbox.io/s/reverent-voice-ddhwi

**Comment by radekmie** [comment]
Hi @adamldoyle. It's because you shouldn't modify the `model` the `onChangeModel` receives! It's a direct reference to the form `state`, therefore mutation of it doesn't trigger a render. This function is like a `onChange` for the whole form - it'll get called when the form changes. If you'd like to alter the model, you have to keep it somewhere (e.g. in the state) and then pass it back in the `model` prop.

Example usage:

```js
function App() {
  const [model, setModel] = useState();
  const onChangeModel = useCallback(model => {
    // Making a deep copy is one on the options.
    model = cloneDeep(model);
    model.e = model.d = model.c = model.b = model.a;
    alert(JSON.stringify(model, null, 2));
    setModel(model);
  }, [setModel]);

  return (
    <AutoForm
      placeholder
      model={model}
      schema={schema}
      onChangeModel={onChangeModel}
      onSubmit={model => alert(JSON.stringify(model, null, 2))}
    />
  );
}
```

**Comment by vcardins** [comment]
@radekmie I might be doing something wrong then, I tried your suggestion, just to log in to the console but it doesn't update the form values. Please, have a look: https://codesandbox.io/s/chained-dropdown-j0g2hc

**Comment by radekmie** [comment]
@vcardins You were not passing the `model` to your `useUniform` hook.
