### ISSUE TITLE
Too long scroll in uniforms Docs (Chrome)

### ISSUE THREAD

**Issue by dsusel** [vazco/uniforms#684]
Hi Guys! 

While using your Docs on Chrome I've encountered weird long scroll in simply every page.  I have a feeling that it even gets longer with the time - the more you work with Docs the longer the scroll is. It's quite frustrating if someone works on Docs with your package. 

The problem does not appear in Safari. 

Cheers!
Damian

**Comment by radekmie** [comment]
A small update: @Monteth and @kestarumper discovered that the problem is caused by Hotjar. @Monteth is still working on it.
