### ISSUE TITLE
Could a select implement the oneOf of JSONSchema ? 

### ISSUE THREAD

**Issue by Olumenti** [vazco/uniforms#685]
Hi, 

I'm using JSONSchema and I'm currently facing a problem with the use of `oneOf`. I was using [json-editor](https://github.com/json-editor/json-editor) on another proejct, it's is very powerful because it has a `select` to choose between each *oneOf* (taking the title of each) and shows the corresponding fields regarding the selected option. For now I have no way to use the schema I have (example below)

Could this method (`<select>` + changing fields) be implemented in your library or could give clues to build a custom field that would to it ? 

This is an example schema for this : 
```
{
  "$id": "https://example.com/arrays.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "garage",
  "type": "object",
  "properties": {
    "name": { "type": "string"},
    "vehicles": {"type": "array",
      "items": {
        "oneOf": [{"$ref": "#/definitions/bike"},{"$ref": "#/definitions/car"},{"$ref": "#/definitions/bus"}]
  }}},
  "definitions": {
    "bike": {"type": "object","title":"Bike",
      "properties": {
        "color": {"type": "string", "description": "color bike"},
        "size": {"type": "number", "description": "size bike"}
      }
    },
    "car": {"type": "object", "title":"Car",
      "properties": {
        "model": {"type": "string", "description": "model car"},
        "power": {"type": "integer", "description": "power car"}
      }
    },
    "bus": {
      "type": "object", "title":"Bus",
      "properties": {
        "seat": {"type": "integer", "description": "seat bus"},
        "height": {"type": "number", "description": "height bus"}
      }
    }
  }
}
```

**Comment by radekmie** [comment]
Hi @Olumenti. It's technically possible, but the current uniforms architecture won't help you much. The thing is that **the schema cannot make use of the model itself**. In this case, when a `NestField` for `vehicles.0` is rendered, we don't know, what properties it should contain. You can implement a field that will be used to render an element of `anyOf` type by manually traversing the schema and rendering nested fields accordingly. Play around with it, I'll try to come up with an example next week.

**Comment by RaphaelGillet** [comment]
To help me throught this, could you explain me how to extract a component like this (the schema is below)
 
Go from


```
export default class Editor extends React.Component {
    constructor(props) {
        super(props);
        const schemaValidator = createValidator(schema);
        const bridge = new JSONSchemaBridge(schema, schemaValidator);
        this.state = {bridge: bridge, schema: schema}
    }

    render() {
        const {bridge, schema} = this.state;
        let ref;
        return (
            <AutoForm schema={bridge} showInlineError ref={form => ref = form}>
                <ErrorsField/>
                
                <ListField name="vehicles">
                    <ListItemField name="$">
                         <NestField name={"bus"}/>
                    </ListItemField>
                </ListField>
                
                <SubmitField/>
            </AutoForm>
        )
    }
}

```

To something like 

```
const Special = () => <NestField name="bus"/> // ERROR Field not found in schema: "vehicles.0.vehicles.0.bus.seat"
const SpecialField = connectField(Special);

export default class Editor extends React.Component {
    constructor(props) {
        super(props);
        const schemaValidator = createValidator(schema);
        const bridge = new JSONSchemaBridge(schema, schemaValidator);
        this.state = {bridge: bridge, schema: schema}
    }

    render() {
        const {bridge, schema} = this.state;
        let ref;
        return (
            <AutoForm schema={bridge} showInlineError ref={form => ref = form}>
                <ErrorsField/>
                
                <ListField name="vehicles">
                    <ListItemField name="$">
                         <SpecialField/> // The prop `name` is marked as required in `SpecialField`
                    </ListItemField>
                </ListField>
                
                <SubmitField/>
            </AutoForm>
        )
    }
}
```

Schema is without oneOf, to try things

```
{
  "$id": "https://example.com/arrays.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "garage",
  "type": "object",
  "properties": {
    "vehicles": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/element"
      }
    }
  },
  "definitions": {
    "element": {
      "type": "object",
      "properties": {
        "bike": {
          "$ref": "#/definitions/bike"
        },
        "car": {
          "$ref": "#/definitions/car"
        },
        "bus": {
          "$ref": "#/definitions/bus"
        }
      }
    },...
}
```

**Comment by radekmie** [comment]
OK, so the thing is that you actually won't be able to use uniforms _below_ the `anyOf`. One option would be to render the field with the `anyOf` schema and use the `field` prop, which is the field definition in the schema. It's actually not really useful as you cannot really use uniforms after this point.

Another option would be to _somehow_ interpret `anyOf`/`allOf` in the `JSONSchemaBridge`, but it's a bigger topic. And it seems far harder to start with.

**Comment by radekmie** [comment]
I think it's clear what limitations we do have and what one could achieve now. I wanted to make an example to play with, but the thing is that I'd instead focus on v3, which _may_ change a few things to actually make it a little easier to implement. I'll close this one for now, though.
