### ISSUE TITLE
@types/prop-types/index has no default export

### ISSUE THREAD

**Issue by Olumenti** [vazco/uniforms#689]
Hi, 

I'm trying to build my app that uses uniforms but I got the error that comes from `import PropTypes from 'prop-types';` https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/BaseForm.tsx So I can't build my app, 
it says : `@types/prop-types/index has no default export`

From Stackoverflow for ex, I found that using something like `import * as PropTypes from 'prop-types` but this in the lib, not in my code

Could you suggest something to help me out ? 

Thanks

**Comment by radekmie** [comment]
Hi @Olumenti. Our TypeScript [config](https://github.com/vazco/uniforms/blob/357674acfe84aba8c983c6cee2d8e80a32df8107/tsconfig.json#L6) uses `esModuleInterop: true`, which enables `allowSyntheticDefaultImports`, which unifies the way of importing ES6 and CommonJS files (on the type system level). You can use it in your own config as well. As I've tried to turn it off, there are more problems, e.g. single imports from lodash (`lodash/get`, etc.). For now, I suggest to simply use this flag.

**Comment by Olumenti** [comment]
Ok thanks, it worked ;)
