### ISSUE TITLE
uniforms-bootstrap 2.6.6: TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by ziedmahdi** [vazco/uniforms#692]
After building an app created with CRA, I get this error whenever a form is rendered. The error seems related to #638. 
<pre>
TypeError: Cannot read property 'prototype' of undefined
at t.value (BaseForm.js:38)
at t.value (QuickForm.js:28)
at t.value (ValidatedForm.js:68)
at t.value (AutoForm.js:60)
at t.value (BaseForm.js:283)
</pre>
The error occurs with version 2.6.6 and also with version 3.0.0-alpha.1 (`npm i uniforms-bootstrap4@next`)

**Comment by mcoeur** [comment]
👍
