### ISSUE TITLE
(eslint) Unable to resolve path to module 'uniforms' inside docs folder

### ISSUE THREAD

**Issue by p1Machado** [vazco/uniforms#698]
Hello, I'm trying to submit a PR, but all the imports to local packages inside the docs folder are being rejected by the eslint setup. The website is building and running normaly.
Is there any additional setup to avoid this problem?

Also, out of curiosity, is there any reason for this folder not to be inside the website folder?

**Comment by p1Machado** [comment]
The npm script lint:code specifies the folders packages and website:
`"lint:code": "eslint --ext js,ts,tsx packages website"`

Whereas the lint-stages config runs with no additional file arguments:
`'**/*.{js,ts,tsx}': ['eslint'],`

**Comment by p1Machado** [comment]
Should I just bypass it using `git commit --no-verify`?

**Comment by radekmie** [comment]
Hi @p1Machado. Yes, this is simply a problem with our configuration - `docs` folder should be linted as well. The case for not having it inside the `website` is that _ideally_ these are some kind of documentation on its own. For now, use `--no-verify` - we'll fix those problems later.

Another point is that I'm still actively thinking about those examples (including that one added in #699) - technically, it'd be the best not to type it twice, but let Docusaurus build it into the source preview and executable component at once.

**Comment by radekmie** [comment]
It should be fixed now. As a part of removing duplication in our docs in #702 I've added linting of this directory as well.

@p1Machado Could you update your PR as well?

**Comment by p1Machado** [comment]
> It should be fixed now. As a part of removing duplication in our docs in #702 I've added linting of this directory as well.
> 
> @p1Machado Could you update your PR as well?

Of course. This weekend I will spend some time on this.
