### ISSUE TITLE
Unable to propagate 'classes' prop for SelectField on uniforms-material

### ISSUE THREAD

**Issue by p1Machado** [vazco/uniforms#700]
I am trying to style the FormControl in a SelectField, but neither style or classes are being provided to the TextField component.

I believe that at least the classes prop should be explicitly provided to TextField: https://github.com/vazco/uniforms/blob/master/packages/uniforms-material/src/SelectField.tsx

**Comment by radekmie** [comment]
Hi @p1Machado. I don't see the `FormControl`, therefore I guess you meant the one rendered by the [`wrapField`](https://github.com/vazco/uniforms/blob/944645fe6d2929e195238e910d2d29fc64ca3083/packages/uniforms-material/src/wrapField.tsx) helper, right? Yep, it'd be nice to have it configurable as well. I think adding a `wrapProps`, similar to most of the props for AntD version of `wrapField` would be good and enough.

We're mostly finished with v3 and I think this could be added there.

**Comment by p1Machado** [comment]
> Hi @p1Machado. I don't see the `FormControl`, therefore I guess you meant the one rendered by the [`wrapField`](https://github.com/vazco/uniforms/blob/944645fe6d2929e195238e910d2d29fc64ca3083/packages/uniforms-material/src/wrapField.tsx) helper, right? Yep, it'd be nice to have it configurable as well. I think adding a `wrapProps`, similar to most of the props for AntD version of `wrapField` would be good and enough.
> 
> We're mostly finished with v3 and I think this could be added there.

I've meant TextField. Actually material-ui renders a FormControl inside the TextField component. This component used [here](https://github.com/vazco/uniforms/blob/master/packages/uniforms-material/src/SelectField.tsx#L157) is the one I was refering as missing a possibility of passing a classes prop.


Sorry for taking so long to reply.

**Comment by p1Machado** [comment]
The solution made on #791 is what I was expecting! 👍
