### ISSUE TITLE
Can layouts be handled simply from schema itself ?

### ISSUE THREAD

**Issue by Aarshi-Kredx** [vazco/uniforms#701]
Hi,
I have been trying my hands on this library, as we handle a lot of form through schema itself using redux-autoform and was thinking of migrating our forms to uniforms. We would like to handle the layouts from the schema itself, especially using the Bootstrap UI. Like all the the fields inside an object to be aligned in row or column using the key grid which can be passed in schema. Somehow I haven't been able to accomplish it. 

So is it possible to handle layouts from the schema itself and if the answer is yes, how ?

**Comment by radekmie** [comment]
Hi @Aarshi-Kredx. I guess you've found the answer then :D Just to be sure - yes, it is possible - you can configure both the components and their props within the schema.

**Comment by Aarshi-Kredx** [comment]
Yeah had to look into the code for my answer. Would need to use bootstrap classname to configure the layout of default AutoField components .
