### ISSUE TITLE
issue rendering AutoForm in Next.js SSR

### ISSUE THREAD

**Issue by shrugs** [vazco/uniforms#703]
Hi, thank you for making uniforms!

I'm finding an issue when server side rendering an AutoForm in Next.js.

```
TypeError: Class constructor _class cannot be invoked without 'new'
    at new _ (/Users/matt/project/path/redacted/node_modules/uniforms/AutoForm.js:18:32)
```

which seems to be related to #433 and [this stackoverflow answer](https://stackoverflow.com/a/51860850) and perhaps also related to https://github.com/zeit/next.js/issues/8175

i've tried configuring [next-transpile-modules](https://www.npmjs.com/package/next-transpile-modules), but without much luck, as well as https://github.com/zeit/next.js/issues/8973#issuecomment-538677034 and https://github.com/zeit/next.js/issues/8358#issuecomment-521387124

---

as far as i understand, the issue is that typescript expects the object being `extend`ed to be a class, but the transpiled `uniforms/AutoForm` is an es5 prototypical-inheritance function. so it's throwing a `TypeError`.

here's my custom AutoForm:

```tsx
import AutoForm from 'uniforms/AutoForm';

import ValidatedQuickForm from './ValidatedQuickForm';

const Auto = (parent: any): any =>
  class extends AutoForm.Auto(parent) {
    static Auto = Auto;
  };

export default Auto(ValidatedQuickForm);

```

and the bundled `uniforms/AutoForm`:

```js
function _() {
    var args = [];
    for (var _i = 0; _i < arguments.length; _i++) {
        args[_i] = arguments[_i];
    }
    var _this = _super.apply(this, args) || this;
    // @ts-ignore
    _this.state = tslib_1.__assign(tslib_1.__assign({}, _this.state), { model: _this.props.model, modelSync: _this.props.model });
    return _this;
}
```

the error occurs on the line just above `// @ts-ignore` when calling `super.apply(...)`. 

--- 

i'm not knowledgeable enough about typescript and babel to know which flags to play with, but this may not be a uniforms-specific issue.

In any case, a simple workaround is to avoid server-side-rendering any AutoForm components using next.js's `next/dynamic` component, with `{ ssr: false }`.

```tsx
const DynamicEditOrganizationForm = dynamic(
  () => import('~/client/components/dashboard/forms/EditOrganizationForm'),
  { ssr: false },
);
```

**Comment by radekmie** [comment]
Hi @shrugs. There are few possibilities what's wrong, so let's start with the most obvious and simple ones:
1. Try using `import { AutoForm } from 'uniforms';` rather than `import AutoForm from 'uniforms/AutoForm';`. The first one will let your bundler decide which version of the package to choose.
2. Try making your `AutoForm` in align with one of the official ones, e.g. [this](https://github.com/vazco/uniforms/blob/944645fe6d2929e195238e910d2d29fc64ca3083/packages/uniforms-unstyled/src/AutoForm.tsx) one. The are some problems with transpiling TypeScript output with Babel in certain cases.

**Comment by shrugs** [comment]
@radekmie option 2 was the solution for me!

i originally changed the definition to get rid of my eslint error about the class named `_` not being in PascalCase, and didn't realize that anonymous classes affected the semantics of the code.

here's the working code i'm running:

```tsx
import { AutoForm } from 'uniforms';

import ValidatedQuickForm from './ValidatedQuickForm';

const Auto = (parent: any): any =>
  class AutoFormed extends AutoForm.Auto(parent) {
    static Auto = Auto;
  };

export default Auto(ValidatedQuickForm);
```

(you can see that i've named the class `AutoFormed` instead of letting it stay anonymous)

Thank you for your quick help! I've really enjoyed using uniforms so far, thank you for your efforts.
