### ISSUE TITLE
Alpha release of the v3 of the uniforms

### ISSUE THREAD

**Issue by wtrocki** [vazco/uniforms#704]
Hi 

Do you think it will be possible to release the next Uniforms Alpha v3?
The last release was a couple of months ago. 
Our team is working on extending uniforms by adding support for Ionic components and for the moment we are using unreleased versions of the master.

CC @radekmie

**Comment by radekmie** [comment]
Hi @wtrocki. We've made all tests pass just last week, and we're still knee-deep in completing types. Let's say we'll release a new alpha version next Wednesday, but don't expect it to be _ready_.

You can stick to v2 for now - it shouldn't be a big problem to migrate a theme to v3 afterward - it's one of our goals to make it as easy as possible. If you are using TypeScript, then expect to add a lot of `@ts-ignore` though.

**Comment by wtrocki** [comment]
@radekmie We have all typings we need and most of this looks amazing without any obvious limitation. What we looking is just snapshot to simplify our work - CUrrently, our repo has copy-paste of the entire uniforms source code that we need to update once for a while. I do not want to release another set of uniforms libraries on my own duplicating them on NPM as this could do some harm to the project

**Comment by radekmie** [comment]
Version `3.0.0-alpha.2` just got released.
