### ISSUE TITLE
Usage with already defined form

### ISSUE THREAD

**Issue by wtrocki** [vazco/uniforms#706]
Hi

I have been trying to promote uniforms in various communities and I found that it is very common to use the library to aggregate state and validation, but build components on your own. Teams often mention Formik (https://www.npmtrends.com/formik-vs-uniforms) as tool that gives that flexibility to use any component library while resolves hassle of building forms - mainly aggregating state changes and validation

This might sound really stupid - but is there an ability to work with Uniforms (even hacky way) that will give flexiblity around component creation but still handle validation and state? I'm aware that this is going against the uniforms design, but wanted to see how this relates with each other.

EDIT: checked code. This actually makes no sense for uniforms

**Comment by wtrocki** [comment]
Context: Formik is defined in the react docs: https://reactjs.org/docs/forms.html#fully-fledged-solutions

When trying to convince people to move to uniforms I would need to get some arguments. Matrix works amazingly: 
https://uniforms.tools/docs/compare-matrix

However there is a question of using existing layout/component library that is very common issue and requires implementing your own styles. 
Can we assume that uniforms is only for people who would like to use 5 currently supported styles?

**Comment by wtrocki** [comment]
If uniforms do not provide solution for state management and field level validation - which is somehow related to reducing boilerplate do you see any library or extension that can give that out of the box and then become complementary option to formik?

**Comment by wtrocki** [comment]
`While uniforms do not provide state mamagement it is providing binding on submit that should be enough to make network request or update application state`. 

Is this sentence correct?

**Comment by wtrocki** [comment]
I kinda went into discussion with myself and got the information that I wanted. Closing as invalid

**Comment by radekmie** [comment]
Hi @wtrocki. I'm not sure how many different questions you've asked here, but let me try to answer:
* You can build a very simple bridge that will not do anything besides providing a user-defined validator. This means you won't be able to use `AutoForm` (or `QuickForm`, to be exact). This is the closest to Formik you can get out of the box.
* You don't have to use `AutoForm` to generate your form. I quite often use it and still provide a complete layout.
* If you want to use uniforms with a different theme, you can either create a custom theme or don't use one at all. In one of our React Native projects (there's no official RN theme for uniforms yet), we do use uniforms but build all forms by hand. That's, I think, precisely the case you wanted to know - uniforms are being used only to manage the state and validation.
* Making uniforms work with field-level validation would be weird, but it not impossible. It'd require a special bridge and/or special handling within fields. The bridge receives field props, so it could intercept the `validator` prop and somehow incorporate it inside of the total validator. It'd still mean that every time the validation checks the whole form, but the rules are scattered through the form.

**Comment by wtrocki** [comment]
@radekmie Awesome response thank you so much! I have all the info needed.
