### ISSUE TITLE
how can I use Antd`s Grid by json-schema?

### ISSUE THREAD

**Issue by thuglifezhx** [vazco/uniforms#707]
I want to make two fields to be laid out as shown below.How can I use json-schema to config.

![image](https://user-images.githubusercontent.com/27938747/79313307-b7628180-7f32-11ea-9de0-be6d35f071fd.png)

Can I config like Antd`s Grid by this? How to do ?
```
const json = {
    title: 'Guest',
    type: 'object',
    properties: {
        firstName: {
           type: 'string', 
           span: 6   //use  span to config
        },
}
```

**Comment by radekmie** [comment]
Hi @thuglifezhx. Yes, all AntD fields accept `labelCol` and `wrapperCol` props of [`Form.Item`](https://ant.design/components/form/#Form.Item). Here's a [playground example](https://uniforms.tools/playground/#?N4IgDgTgpgzlAuIBcICCATd0YwAQAoApAZQHkA5YgYwAsoBbAQwEoQAacCAezBmVEYBXeFxiMAblGQAzRgBs4HISLGSAIlDmMAnsgCMABgMd0ASzEAjOVHQz5ikFoubk8CIKgcwWqlBpc5dCgIOwVPEBhaBkZkEHx8ZlwAXgA-XGAAHQA7XFzcKi4smHhcRgArcWTcLKgAd1xUCvxgeTkAUQhuCBgkXDcPNlxBOA1ZQTl4Hr73KABfZgBubLz8wuLcSLomKsyclbz4U3hrXoByDCxYGFO2Zf3c-G0wKDOuCzKoKngbu_vIHmCh1gvV293uVCO2l6uWAj2eZ2KEFMWQA5jdcE5NABhAIgmBgRhZXp6QZcaTSODwYmzQa1CCMMDPCA4uR4glE3AAJk5sxpvzBuWKjHgLxhcNFp0RyLRg0xchZbMJvQAzDTcHSGUyFel8UquXpebc9gLBW4oAgQeKEW5pei5drgLqOQAWNUaxnBB1O3qcgyG_kCgBepjA0LFTwlUtR6IJ8BFEA5pwA2gYALQATgAusAAKyzO2MZzy3E69m9PO0-ke5klx1l3B6dP-437PktlbQACOglM0HQvSTkrNCHRp2DYFHQpFp0z_Nm2X50kEWS-pkK-WgwqgADV5KZ0MKuBB8JtoolQfsCkUSuI9weRBAquVxAA6Ar0MCmawnqJMRYL9tcGgeBBATXB6C4II5GSNIL3uW85H3Q9jwgqD_yyAM8lMaQCAQpCHxfYIujwAAyEjcDw-8j0IzojxgF9rFReAaHPTCVmY7h6mAIJ4EYL8pko5CaOI2YlkA3J50A0S5wAlYr3WU8mF3RCqMfJINygLdlPwo8fy2FgxP5YDQJyGp6hIChqH0gAhJF0BRKA9OiQZFMYbTVPQ-YEnYCJ_FqABJLJEJqDoulCBxGBgbQV1ILJiEECx6COcLwki6KqFi9ytxSmkQGYhgpBQQl4FsWYgA) with JSON schema.
