### ISSUE TITLE
website https://uniforms.tools doesn't load in non-chromium browsers.

### ISSUE THREAD

**Issue by Syynth** [vazco/uniforms#708]
I know this isn't directly related to this library but I was unable to view the website for uniforms (and also find the link to the github repo) until I updated Edge to the new preview version that runs on chromium. Firefox and Edge both fail on an [invalid regular expression flag 's'.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Bad_regexp_flag)

**Comment by radekmie** [comment]
Hi @Syynth. It looks like [dotAll](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/dotAll#Browser_compatibility) is not supported in Firefox nor IE. This got introduced in #702. Thank for the report!
