### ISSUE TITLE
Json Schema Dependencies feature

### ISSUE THREAD

**Issue by nunonamorado** [vazco/uniforms#710]
Hello,

Does this tool work with JSON Schema Draft - [dependencies](https://json-schema.org/understanding-json-schema/reference/object.html#dependencies) ?
I've seen that in the documentation, you show how to [conditionally hide or show](https://uniforms.tools/docs/examples-custom-fields#displayif) a field according to another's value.
If I need to create more complex conditions, for example:

``` json
{
  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "credit_card": { "type": "number" }
  },
  "required": ["name"],
  "dependencies": {
    "credit_card": {
      "properties": {
        "billing_address": { "type": "string" }
      },
      "required": ["billing_address"]
    }
  }
}
```
How would I do it with your tool?

Thanks

**Comment by radekmie** [comment]
Hi @nunonamorado. No, it is not handled. The main problem is that the bridge (in this case `JSONSchemaBridge`) don't know the model. This means that all of the bridge functionalities, like creating validator, getting a list of fields and subfields, or providing props - have to be model-independent.

In uniforms you can, for example, use something similar to [`DisplayIf`](https://uniforms.tools/docs/examples-custom-fields/#displayif), which will conditionally render its children, depending on any condition you want. You can, of course, adapt it to your needs - maybe the model is enough in your case.

**Comment by nunonamorado** [comment]
@radekmie Thanks for you answer. I will try to go for something similar to the `DisplayIf`.
