### ISSUE TITLE
SelectField is not documented or covered in playground

### ISSUE THREAD

**Issue by wtrocki** [vazco/uniforms#712]
I'm trying to find a best way to get SelectField out of the box. Any recommendations?

**Comment by radekmie** [comment]
Hi @wtrocki. I don't understand your problem: [`SelectField` is documented](https://uniforms.tools/docs/api-fields/#selectfield) and is a part of the example forms in the playground (`size` field). What is it then?

**Comment by wtrocki** [comment]
Ah... Sorry. I totally ignored welcome and went to GraphQL schema/JSON schema etc.

**Comment by wtrocki** [comment]
It will be cool to see how to do it with GraphQL
