### ISSUE TITLE
Multistep form with schema changing on each step

### ISSUE THREAD

**Issue by shealan** [vazco/uniforms#719]
I am trying to create a multi step form from a schema array. The goal is to have Uniform generate each step, validate and then trigger the schema to refresh when validation succeeds.

I've scoured the docs and github but come up blank.

It ALMOST works... but if there are validation errors they are shown as expected. However, once the form becomes valid I can then change the fields back to invalid values and the validation errors are not trigger again.

I have created a sandbox here: https://codesandbox.io/s/fragrant-frog-yvm4q?file=/App.js

Steps to reproduce:

1. Try to submit with no data validation kicks in
2. Modify to fix validation and submit. Success!
3. Delete some of that data to make the validation trigger again
4. Oops. It still thinks the form data is valid

Thank you in advance for taking a look!

**Comment by kestarumper** [comment]
Hi @shealan,
Thanks for the sandbox, it really makes things easier for us.
> Steps to reproduce:
Try to submit with no data validation kicks in
Modify to fix validation and submit. Success!
Delete some of that data to make the validation trigger again
Oops. It still thinks the form data is valid

The problem might be in your schema definition and your expectations. Telling json-schema that a field is required **doesn't mean that it cannot be empty**. So basically, what happens here is that uniforms don't include any data in the model at the start (model is empty). The moment you start typing (change the field), it starts putting it inside the model, and when you delete that, it's just an empty string (still present in model), but it's not `undefined` and **Ajv** happily lets that through validation. You can notice that if you change the `age` which has constraints `0 <= age <= 100` works as you would expect it.

All of the above is not directly connected to the multi-step form problem. I can only suggest some approaches on how you could implement that, but that depends on the problem details.
1. You could create one big schema which describes every step of the form and only display certain fields at each step, which would result in one big model.
2. Or, create dynamic schemas, just as you did yourself. One thing to consider here is how to join these separate models, which will be created for each schema.

That's just an abstract. Feel free to ask more questions. I hope this helps.

**Comment by shealan** [comment]
@kestarumper thank you so much for writing such a detailed explanation. That's really helpful. Not a bug then, expected behaviour.
