### ISSUE TITLE
How can I customize an autofield generated by graphql bridge?

### ISSUE THREAD

**Issue by praseetha-nair** [vazco/uniforms#723]
Hi, I need some help. I am trying to get some details about user using a form. I need to add a dynamic form in my page. I have created the schema and generated the autofield. Could you please help me with adding some style to it?
This is what I need to display.
![contact](https://user-images.githubusercontent.com/64142875/81798112-457b5900-952d-11ea-8613-f1aaa0457a6e.png)
This is what I am getting now
![React_App (1)](https://user-images.githubusercontent.com/64142875/81798232-6cd22600-952d-11ea-87d5-eece7f6c7e30.png)

**Comment by kestarumper** [comment]
Hi @praseetha-nair,
If you need to style your components, you can add class names to them and manipulate via CSS rules, as stated in our [docs](https://uniforms.tools/docs/faq/#how-can-i-customizestyle-my-form-fields).
> How can I customize/style my form fields?
You can style your form fields simply by passing a className property.

So the solution would be the following:
1. Add `className` to your components
2. Provide a CSS rule, to change the layout from column to row-based, you could use `flex` property ([source](https://css-tricks.com/snippets/css/a-guide-to-flexbox/))

I hope this helps. Feel free to ask more questions.

**Comment by kestarumper** [comment]
I'm closing this issue since no reply was given. Feel free to re-open.
