### ISSUE TITLE
Strange apostrophe rendering

### ISSUE THREAD

**Issue by dandv** [vazco/uniforms#726]
The apostrophe used in the docs looks odd on Ubuntu 20 with Chromium 81:

![image](https://user-images.githubusercontent.com/33569/82396578-13716780-9a03-11ea-99a3-74bfa53887d7.png)

**Comment by Monteth** [comment]
Hi, I have problems reproducing your bug. Can you provide more info about your system?  I.e. font name or other specific data would help.

**Comment by dandv** [comment]
Hi, sorry for the scant bug report :) I had just installed Ubuntu 20. Probably an Ubuntu-specific problem. Feel free to close.

Page: https://uniforms.tools/docs/motivation
Browser: Chromium 83
Computed font: `system-ui, -apple-system, "Segoe UI", Roboto, Ubuntu, Cantarell, "Noto Sans", sans-serif, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";`, via https://uniforms.tools/styles.39c250a1.css

![image](https://user-images.githubusercontent.com/33569/82842975-5d899b80-9e90-11ea-99ec-8180936b11e6.png)

**Comment by Monteth** [comment]
Well, I also have Ubuntu 20 with chromium 83 on 2 machines, fonts also look the same, but my render is perfectly fine. 
@kestarumper I assume you have a similar environment, can u take a look here?

**Comment by kestarumper** [comment]
I also have Ubuntu 20 (chrome `83.0.4103.61`) and it renders correctly.

**Comment by Monteth** [comment]
Because of the inability to reproduce this bug, I'm closing this issue.
