### ISSUE TITLE
Motivation page assumes knowledge of Autoform, ValidatedForm

### ISSUE THREAD

**Issue by dandv** [vazco/uniforms#728]
https://uniforms.tools/docs/motivation seems to reuse a paragraph from the [Meteor blog post](https://blog.meteor.com/managing-forms-in-a-meteor-react-project-with-uniforms-33d60602b43a),

> Most of the time you’ll be using either AutoForm or ValidatedForm, but there are quite a few more to choose from

but new uniforms users who haven't used Meteor, may not have any idea what Autoform is. (I know Autoform, but actually never heard about ValidatedForm).

One solution would be to link to them, but probably even better to say something like,

> When you want to build a form, you essentially have two choices: build it by hand, or use a library that creates the form for you out of data or schemas that you have.

The Motivation page then kind of goes into the weeds about HOCs and didn't convince me as to why uniforms was built :) but let's focus on this issue first. (The whole page should be sent for feedback to a user completely new to uniforms, and who hasn't used Meteor). The [what is uniforms](https://uniforms.tools/docs/what-are-uniforms) page is great, but I found the Motivation confusing.

**Comment by radekmie** [comment]
Hi @dandv. Yep, this page is based on this article. I wouldn't say that any understanding of uniforms or `aldeed:autoform` is needed to read it. That's all - there are more form components provided by uniforms, but you'll mostly use one of those.

I agree that the _Motivation_ page is a bit... Misleading? Missing the point? Maybe merging it with the _What are uniforms?_ one would make more sense. It gets more clear with the comparison table in [_API Reference > Forms_](https://uniforms.tools/docs/api-forms). What is your opinion on that?

(I still think that _Why are uniforms?_ would be a better title yet not everybody loves Marvel)

**Comment by radekmie** [comment]
I believe it's _good enough_ right now and we'll change it as soon as we'll think out how to improve it.
