### ISSUE TITLE
Add React Hook Form to comparison matrix

### ISSUE THREAD

**Issue by dandv** [vazco/uniforms#729]
https://uniforms.tools/docs/compare-matrix

[RHF beats Formik](https://blog.logrocket.com/react-hook-form-vs-formik-a-technical-and-performance-comparison/) at most metrics and is aggressively maintained.

**Comment by radekmie** [comment]
Hi @dandv. Yep, I agree, it would make a good addition. Would you like to do that? I've never used it and probably won't find time in the nearest future (it stills goes on the board).

I hope you'll think the same (_aggressively maintained_) of uniforms as well :smile:

**Comment by LeongXianJun** [comment]
HI, I am a university student. Due to my course, I need to provide some contribution to the community and this issue seen okay for my level. I would like to know more about this.

From my understanding, I need to check react hook form whether it consists of the attributes mentioned in the comparison matrix and update the matrix accordingly. 

What would I need to do if i plan to solve this issue? Do i need to provide any proof when updating the matrix?

**Comment by radekmie** [comment]
Hi @LeongXianJun. That sounds interesting and I'm glad you consider uniforms for the project you'd like to contribute to :smile: 

Yes, you'd have to check `react-hook-form` for all the features listed in the table. A _proof_ sounds very bold, but a link to documentation and/or issues would be enough to add it. Feel free to open a PR, even if you'll have only part of the data - we'll try to finish it together. If something won't be clear - just ask. Maybe we'll have to add more details to this comparison.

**Comment by LeongXianJun** [comment]
Noted and Thank you for your reply, @radekmie. I will try to work on it first and see how it goes.

**Comment by LeongXianJun** [comment]
@radekmie How should i provide the link related to the feature? Put in the push request (put all of the link together in the description)? Or Commit Message (1 commit for 1 feature)?

**Comment by radekmie** [comment]
@LeongXianJun Listing all of them in the PR is enough.

**Comment by LeongXianJun** [comment]
@radekmie May I know more about the differences between Manual and Automatic state management mode?

**Comment by radekmie** [comment]
@LeongXianJun Automatic/Manual state management means that the form behaves like an uncontrolled/controlled React input.

```tsx
import clone from 'lodash/clone';
import setWith from 'lodash/setWith';

function ExampleAutomatic({ onSubmit, schema }) {
  return <AutoForm onSubmit={onSubmit} schema={schema} />;
}

function ExampleManual({ onSubmit, schema }) {
  const [model, setModel] = useState({});
  const onChange = useCallback((key, value) => {
    setModel(model => setWith(clone(model), key, value, clone));
  }, []);

  return <BaseForm model={model} onChange={onChange} onSubmit={onSubmit} schema={schema} />;
}
```
