### ISSUE TITLE
GraphQL bridge documentation

### ISSUE THREAD

**Issue by dandv** [vazco/uniforms#731]
Is there more documentation about the [GraphQL bridge](https://uniforms.tools/docs/api-bridges#graphqlbridge)? It would help to link to perhaps reading about the next step in the implementation, for those who jump directly to the GraphQL bridge or land there from a search.

**Comment by radekmie** [comment]
Hi @dandv. No, there's not. There's only an example you've linked. There's no _next step_ though - that's all. A bridge is used in the form later. The `GraphQLBridge` itself takes a `GraphQLType` or `GraphQLInputType`, a validator and an additional field configuration.

If you have more questions - do ask them here. We're focused on releasing v3 now and the documentation is the next big thing to work on.
