### ISSUE TITLE
How to add Date field(Scalar fields) in graphql schama?

### ISSUE THREAD

**Issue by praseetha-nair** [vazco/uniforms#732]
Hi,
I am createting a schema from graphql query and its  Auto Generated . In my  query there is a field of type date. So when I add schema as following

const schema = `

 scalar Date
 type Request {

             firstName:String
             requestId:Int
             requestDate: Date
 }

 type Query { anything: ID }
` 
it gives me an error **"Unsupported field type: Date"**. I have tried by adding 'scalar date' inside schema, but its not working. Do you have any idea to fix this?

**Comment by radekmie** [comment]
Hi @praseetha-nair. This error originates from the [`AutoField`](https://github.com/vazco/uniforms/blob/36a07ef26b23bdbd05fd08533979faa5f1e5d3fe/packages/uniforms-unstyled/src/AutoField.tsx#L53-L57), as the [`GraphQLBridge`](https://github.com/vazco/uniforms/blob/36a07ef26b23bdbd05fd08533979faa5f1e5d3fe/packages/uniforms-bridge-graphql/src/GraphQLBridge.ts#L188-L203) doesn't handle custom scalars. To tell the `AutoField`, what component you'd like it to use, you can use the third parameter of the `GraphQLBridge`:

```tsx
const schema = `
  scalar Date
  type Input {
    date: Date
  }

  type Query { anything: ID }
`;

const bridge = new GraphQLBridge(
  buildASTSchema(parse(schema)).getType('Input'),
  model => { /* Validate model... */ },
  { date: { component: YourComponent } }
)
```

**Comment by radekmie** [comment]
I guess it's all clear now. Feel free to comment if needed.
