### ISSUE TITLE
Mongoose support

### ISSUE THREAD

**Issue by mariusrak** [vazco/uniforms#735]
Hi, is there any plan to add support for mongoose?
It seems like quite popular tool, which should have available everything what unforms need.
I know, that there is option for custom adapters, but official support would be nice.
In worst case, I'd maybe go into writing the adapter myself if community would be interested and would help.

**Comment by radekmie** [comment]
Hi @mariusrak. Mongoose schemas are quite comprehensive but I don't think they are made to be used on the client-side (I'm not saying they can't). We wouldn't be able to dogfood it as well, therefore it'd be harder to maintain.

I strongly encourage you to create a custom package for that. If you do, do share it here - I'd like to test it myself. There's no problem in pulling it into the core later when the implementation will be ready (or at least _ready enough_ to be tested) if both sides would agree to.

**Comment by mariusrak** [comment]
Hi, the MVP version of the bridge is here https://github.com/mariusrak/uniforms-bridge-mongoose
I would appreciate any input or feedback. What can be my next steps with the bridge?

**Comment by radekmie** [comment]
Great! I just took a quick peek now - I'll be able to take a closer look next week - and I have actually two comments. First, is the lack of tests. It's kind of hard to tell if there's something missing and/or incorrect if you don't have any. Second, is the lack of types. Starting late-v2, uniforms are 100% TypeScript code (far better and stricter in v3).

**Comment by mariusrak** [comment]
I've added test, but I didn't make test environment work. I could use some help. Also I'm not sure how to bundle it.

**Comment by radekmie** [comment]
I'll try to find some time for that, but I can say that in this case, a standard Jest setup would be OK.

About bundling: we do use TypeScript now and if you'd do as well, you could use the same config.
