### ISSUE TITLE
Ability to specify disabled items in SelectField

### ISSUE THREAD

**Issue by yurtsiv** [vazco/uniforms#736]
Currently, there's no way of disabling particular items in SelectField.

One should write a custom field in order to achieve something like this:

![image](https://user-images.githubusercontent.com/18295488/83311801-974ffe80-a210-11ea-91d1-5136e7508ba4.png)

It would be nice to have such an ability by default.

f.e.

```
<SelectField
   name="selectField"
   disableItem={(item) => ...}
/>
```
or

```
<SelectField
   name="selectField"
   disableItems={["Item 2", "Item 4"]}
/>
```

Thanks!

**Comment by radekmie** [comment]
Hi @yurtsiv. I think we could add it but preferably in all themes. I've marked it as todo and we'll get to it after v3 release.
