### ISSUE TITLE
Integration with ostrio:files (Meteor-files) packages?

### ISSUE THREAD

**Issue by vladejs** [vazco/uniforms#74]
Seems like Meteor-files package is the de facto package to upload files right now. It will be awesome a seamless integration with that package. Include examples in the docs, etc.

**Comment by radekmie** [comment]
I'm not willing to do such integrations inside this package, because it's not really form-related - if it's easy, then it doesn't have to be part of it, if it's hard - it's an additional thing to maintain. But even so, I would like to hear, what kind of integration would you like to see. If this will cover one field, we can easily create it here and then add it to the README.

**Comment by serkandurusoy** [comment]
I think this should be a separate package like most aldeed:autoform custom inputs and integrations are.

The implementation should not be too hard, it is basically a hidden input along with whatever upload markup/script is being used for ostrio:files and that input can be part of the schema.

`connectField` makes it very easy to wire up any standard input (input-like-component) with uniforms.

**Comment by sabativi** [comment]
I would rather say that this can be related to forms, there are tons of forms on internet where you need to upload a photo like an avatar.
I think this could be a good functionnality to add here

**Comment by radekmie** [comment]
I understand, that it would be nice to have an all-in-one package, but I would rather go for a separate package. Even though, I want to know, what kind of integration would @vladejs like to have here.

**Comment by mixcas** [comment]
@vladejs I working on an upload field that uses [Slingshot](https://github.com/CulturalMe/meteor-slingshot). You might find it useful. 
[https://github.com/interglobalvision/applaya/blob/master/app/imports/components/fields/UploadField.jsx](url)

I'm thinking i might do a separate package for it in the future.

**Comment by macrozone** [comment]
I also suggest to focus on a clean api that allows to implement custom fields.

Uniforms is already really good at this. We have know 2 projects where we rolled our own sets of components (non-bootstrap or whatever) and unforms did a great job.

We also implemented a slingshot-field (can't share yet), which is easy to do. I try to share if i have some spare time.

**Comment by radekmie** [comment]
I'm closing - we've all agreed, that creating custom field is not that hard, so there's no need for built-in integration.

**Comment by vladejs** [comment]
You are right, I created a custom field of type `file`. When it changes it
bubbles the selected file up to the form component, so I can easily
validate the file and upload to my server onSubmit event.

Thanx @radekmie.

**Comment by dr-dimitru** [comment]
Hi @vladejs , @radekmie 

Came here from https://github.com/VeliovGroup/meteor-autoform-file/issues/17
Could we add examples for integration with uniforms to Meteor-Files?
If, so could you point me to the right direction?

**Comment by cyclops24** [comment]
Thanks @dr-dimitru and @radekmie ,
I'm follow this two issue for finding the right way for this integration. 😉 
@radekmie Can you tell more about creating custom input type in uniform? Is it related to BaseField? Can you show me an example about creating custom input type in form? (It can be very useful, for example now for Meteor-Files and later for select2, map, ....)

**Comment by macrozone** [comment]
Hi guys, I have created a gist from one of our implementations of ostrio:files with uniforms.

It's build with mantra-architecture, but could also be used with few adjustments in other architectures. I stripped away unneeded stuff (styling..), but i hope you get the idea:

https://gist.github.com/macrozone/b2207c19aed0838d5982a09a5399dcae

**Comment by andhdo** [comment]
Hi; I have created a widget using the ostrio basic example. Hope it helps.

https://gist.github.com/andhdo/8a88afa4390295c5e5f203c152cb0244

**Comment by dr-dimitru** [comment]
Hello @macrozone @andhdo ,

We would like to add your suggested usage to our wiki.
Could you send a PR?

**Comment by andhdo** [comment]
Feel free to add the @andhdo contribution to your wiki. I think it is a little bit longer to include it as a pull request in the uniforms code (for example tests and improvements in the display of the widget and is not standardized to uniform widgets, because it uses the React.createClass mechanism for component creation).

**Comment by adamczykjac** [comment]
As a supplement to @macrozone and @andhdo gists, here's a minimal running project integrating those two packages and generating image-dropping form field into a sample Simpl-Schema2 schema: https://github.com/adamczykjac/upload-image-uniforms.
