### ISSUE TITLE
AllOf, AnyOf and OneOf treatment hiden properties

### ISSUE THREAD

**Issue by brunoassiscarvalho** [vazco/uniforms#740]
I have a schema with "oneOf" when shows my form, some field are hiden, only shows the first object.
I try to implement a custom field with a select, and show the fields according to the selected option, but I couldn't make the other fields appear. How I make it? And this behavior of hiding the fields when it is oneOf is correct?

Follow my custom field code:

```js
import React, { useState } from 'react';
import { connectField} from 'uniforms';
import { makeStyles } from '@material-ui/core/styles';
import {FormControl, InputLabel, Select, MenuItem } from '@material-ui/core';

const useStyles = makeStyles((theme) => ({
  formControl: {
    margin: theme.spacing(1),
    minWidth: 120,
  },
  selectEmpty: {
    marginTop: theme.spacing(2),
  },
}));

function NavigationField({ value, field, model, onChange, itemProps }) {
  console.log("field");
  console.log(field);
  let uniforms={schema:{}}
  const [selected, setSelected] = useState(value);
  const [isNewNAvigation, setNewNAvigation] = useState(false);
  const classes = useStyles();
  const handleChange = (event) => {
    console.log(event.target.value);
    onChange(event.target.value);
    setSelected(field.oneOf.find((item) => item.title == event.target.value),setNewNAvigation(true));
    uniforms.schema = selected.properties;

  };

  function resolveAnyOf(field, value) {
    return (
      <FormControl className={classes.formControl}>
        <InputLabel id="demo-simple-select-label">Age</InputLabel>
        <Select
          labelId="demo-simple-select-label"
          id="demo-simple-select"
          value={value}
          onChange={handleChange}
        >
          {field.oneOf.map((item) => {
            return (
              <MenuItem value={item.title}>{item.title}</MenuItem>
            )
          })}
        </Select>
        <div>
          {JSON.stringify(selected)}
          {/* constructing subfields here */}
        </div>
      </FormControl>
    )
  }

  return (
    <div>
      {resolveAnyOf(field, value)}
    </div>
  );
}
export default connectField(NavigationField);
```

**Comment by radekmie** [comment]
Hi @brunoassiscarvalho. Could you post your schema? The `allOf`/`anyOf`/`oneOf` support is limited but I'd like to work on that. As I understand, you'd like to pick which one of `oneOf` variants you want to fill and then, based on that, render a different field - is it correct? I'd need more time to think about it.

**Comment by radekmie** [comment]
I wasn't able to properly use your schema but I've played around with their `oneOf` example. I don't think it will be possible to do it in the current architecture as the field definition cannot depend on the data. I can imagine making a sub-form here but it'd require manual schema manipulation. I'll think about it more and get back to you.

**Comment by radekmie** [comment]
As I've said before, it'd require a major change to make some bridge methods (`getField`, `getProps`, `getSubfields`, `getType`) value-dependent. One thing is that people may overuse it and make a bridge stateful, which is not desired. Another, even worse, would be the desynchronization between multiple field instances:
```tsx
const schema = {
  "type": "object",
  "oneOf": [
    { "properties": { "field": { "type": "number" } } },
    { "properties": { "field": { "type": "string" } } }
  ]
};

<AutoForm schema={makeBridge(schema)}>
  <AutoField name="field" value="1" />
  <AutoField name="field" value={1} />
</AutoForm>
```

Both are valid, both should work and _somehow_ yield one, consistent value. It is possible to write the same JSX now, but there's a far smaller chance that it's correct or expected. `react-jsonschema-form` don't have this problem as each field is rendered at most once.

I've also mentioned that it would be possible with dynamically created schemas and sub-forms. This is a very complex solution and it'll probably create performance issues. If it's crucial for your use case, I believe you can give it a try.

And just to make it clear: it is outside of the scope of this package to deal with it automatically. It is possible to create a custom field for each case, that is aware of this `oneOf` and based on values and/or schema renders different JSX.
