### ISSUE TITLE
[Question] Issue with v3

### ISSUE THREAD

**Issue by hmvp** [vazco/uniforms#744]
So this might not be the best place to ask, but did not found anything better. It seems somewhat related to #738 

We have a form that basically looks like this (resulting value)
```js
{
  listField: [
     { nestedObjectField1: "value", nestedObjectField2: 3 }, 
     { nestedObjectField1: "value", nestedObjectField2: 2 }, 
  ],
}
```
We have some components that basically only add logic to existing components. So for example we have a component that does an api call and to get a list of options and uses that for a SelectField
Which basically looks like:
```jsx
function CustomField({ ...props }) {
    const options = fetchOptions();

    return <SelectField {...props} allowedValues={options}  />;
}

export default connectField(CustomField, { includeInChain: false });
```
This component is used in the above form as `nestedObjectField1`
This all works in v2..
We basically define the form as  `<AutoForm><AutoFields /></AutoForm>` and use a modified bridge to set specific components for specific fields

I am trying to migrate to v3 since I am still in the implementing phase and don't want to do the migration in a few weeks/months.

Everything works as expected except this field..  
It keeps throwing the error: "Field not found in schema: "listField.0.listField.0.nestedObjectField1"" Which is kind of correct since it should be "listField.0.nestedObjectField1"

However for as far as I can reproduce this it works if `CustomField` is a direct descendant of a `ListField` or if I use a different field for example  `SelectField` instead of `CustomField`... So it seems there is some interaction between `ListField`, `NestedField` and my wrapped `SelectField`

My questions:
- Maybe my solution to add logic to existing components is wrong, should I do this differently?
- It seems `includeInChain` does not work anymore/is deprecated what should I use instead?

**Comment by radekmie** [comment]
Hi @hmvp. Great thanks for testing v3! For such a case, you can do two things:
1. If the `fetchOptions` is not using `props` in any way, then `CustomField` doesn't have to be a field.
2. Try passing `name=""` to the `SelectField`. It'll basically work in the same way as `includeInChain: false` would.

**Comment by hmvp** [comment]
Hmm your second option seems to work but gives me more questions:
- Yeah basically fetchOptions is dependant on some props (not the uniform default props but a few custom ones that get their data from the schema). So if I am correct you suggestion would be to move that code somehow to the bridge? It feels like the bridge concept would benefit from a extension mechanism so it is clear that there is a difference between parsing a schema type (like json schema or graphql) and extending field(type)s with custom logic..  I will look into that some more later..
- Your second option seems to work and I think I understand why it seemed to work as direct dependency since ListItemField also uses  `name=""` but NestField doesn't. However I still needed to keep `includeInChain:false` otherwise fields directly on the form would complain with "Field not found in schema: "otherField.otherField"". We have a few different wrapped `SelectFields` and even though I am sure the are all the same in the relevant places the seem to differ in behaviour. And some allow me to remove `includeInChain:false`   So I still have some digging to do..
-  Related to this last point.. I feel a bit weird about using name="". I feel that should be explained very clear in the docs since it is not something that is easily discoverable.

**Comment by hmvp** [comment]
Ah I found the reason why I needed includeInChain:false still for some components: I forgot to remove name from `props` so my `name=""` was negated by that

**Comment by radekmie** [comment]
1. No, it's OK to have it here. I thought that maybe this `fetchOptions` depends only on the field name (so `props.name`) and may not need to calculate all field props.
2. The `name=""` works because each component adds its name to the one in the context. So if a field render another one with the same name, you'll get a duplicated part of the name. In `NestField` each nested field receives only own part of the name (e.g. `subfield`), so when it's rendered in another one (e.g. `field`) it resolves to `field.subfield`.
3. v3 is still in development and there's no documentation for it yet.
4. Yep, you'd need to do `<SelectField {...props} allowedValues={options} name=""  />`

**Comment by radekmie** [comment]
I assume that everything is clear now. Feel free to comment anyway!

**Comment by hmvp** [comment]
Yeah got everything working properly on v3 (even cleaner than v2)
