### ISSUE TITLE
Feature: Missing JSON Schema properties

### ISSUE THREAD

**Issue by hmvp** [vazco/uniforms#748]
While implementing a form based on JSON Schema generated by [pydantic](https://github.com/samuelcolvin/pydantic/). I noticed a few JSON Schema properties that are not handled. See also [their docs](https://pydantic-docs.helpmanual.io/usage/schema/#json-schema-types) about JSON Schema properties.

Effectively I need to override `getProps` in the bridge with:
```ts
    getProps(name: string) {
        let props = super.getProps(name);

        if (props.const) {
            props.disabled = true;
            props.default = props.const;
            delete props["const"];
        }

        if (props.maxItems !== undefined) {
            props.maxCount = props.maxItems;
            delete props["maxItems"];
        }

        if (props.minItems !== undefined) {
            props.minCount = props.minItems;
            delete props["minItems"];
        }

        if (props.maximum !== undefined) {
            props.max = props.maximum;
            delete props["maximum"];
        }

        if (props.minimum !== undefined) {
            props.min = props.minimum;
            delete props["minimum"];
        }

        if (props.multipleOf !== undefined) {
            props.step = props.multipleOf;
            delete props["multipleOf"];
        }

        return props;
    }
```

I am not sure about the supported JSON Schema specs and whether these properties are in scope of being supported by default. And I am not sure if it is a valid asumption that `const` is read only. But I feel at least some might be worth to implement in the base JSONSchemaBridge. 

I don't know if this list is complete, its what are missing atm

**Comment by radekmie** [comment]
Hi @hmvp. We do have a similar extension in one of our projects. I think we could add it to the core but as a more general solution. Most of these properties are mapped 1-1, some may require a simple transform (I can't recall which one was it now). If you want, open a PR - preferably to v3.

I'm not sure about the `const` though. Using `disabled` is OK for now, but maybe we've just found a good example for #674.

**Comment by hmvp** [comment]
I see if I find the time to open PR. I am not sure if my solution is the correct one..
It might also be a good idea to collect some requirements/guidelines about whats in scope/props to support..

I am also not sure about const. We indeed use it now as a read only flag but there is a weird intersection between an input being disabled, being read only and the validation requirement that it contains a fixed value.

 #674 seems to imply that read only is needed but the value can be changed. 
We mainly use it to show a value that cannot be changed. We now use const as a flag but we should really add a readonly flag. I was not sure about const because I see a valid use case for a field where the user must choose the right value. 

I think there might be room for 3 flags:
-  `disabled-like`: Is this field validated/submitted at all (not sure if this says something about the presentation
- `read only-like`: Can the user change the value himself? 
- `const-like`: not really a presentation related flag but needed on the validation to make sure the value is set to a specific value (similar to `allowedValues: [value]`)

Between pydantic in the backend and uniforms in the frontend we have the strange requirement that everything on the form needs to be an input. So if we want some static texts of separators we need to make sure they exist in the schema which means they get validated and the values potentially used in the backend. Thus we use const a lot for fields like that to make sure no unexpected data is inserted..

**Comment by radekmie** [comment]
@hmvp We've decided to implement all the properties you've mentioned, except for `const` - it'll be possible to get back to it once #674 will be done.

If there are more properties of JSON Schema you see uniforms could use - let us know.
