### ISSUE TITLE
Bug: Default values from parent fields are ignored in JSON Schema Bridge

### ISSUE THREAD

**Issue by hmvp** [vazco/uniforms#749]
This test fails while expect (and I need it to succeed).
Both in v2 (master) and v3
```ts

    it('works with parent default values', () => {
      const localBridge = new JSONSchemaBridge(
        {
          title: 'Validator',
          type: 'object',
          properties: {
            friends: {
              default: [
                {
                  firstName: 'John',
                  lastName: 'Smith',
                },
              ],
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  firstName: {
                    title: 'Name',
                    type: 'string',
                  },
                  lastName: { title: 'Last Name', type: 'string' },
                },
                required: ['firstName', 'lastName'],
              },
              minItems: 1,
            },
          },
        },
        validator,
      );

      expect(localBridge.getInitialValue('friends')).toEqual([
        {
          firstName: 'John',
          lastName: 'Smith',
        },
      ]);
      expect(localBridge.getInitialValue('friends.0.firstName')).toBe('John');
    });
```
It fails on the second expect where it gets `undefined` instead of `'John'`.

I use the following workaround to override `getInitialValue` in the bridge
```ts
    getInitialValue(name: string, props: any = {}): any {
        const { default: _default, const: _const, type: _type } = this.getField(name);
        let {
            default: defaultValue = _default !== undefined ? _default : get(this.schema.default, name),
            const: constValue = _const,
            type = _type
            // @ts-ignore
        } = this._compiledSchema[name];

        // ADDED BELOW LINES
        if (defaultValue === undefined) {
            const nameArray = joinName(null, name);
            const relativeName = nameArray.pop()!;
            const parentName = joinName(nameArray);
            if (parentName !== "") {
                const model = this.getInitialValue(parentName, { lookUpParent: true });
                defaultValue = get(model, relativeName);
            }
        }
        // END ADDED LINES

        if (defaultValue !== undefined) return cloneDeep(defaultValue);

        if (type === "array" && !props.lookUpParent) { // << ADDED EXTRA EXPRESSION
            const item = this.getInitialValue(joinName(name, "0"));
            const items = props.initialCount || 0;
            return Array(items).fill(item);
        }

        if (type === "object") return {};

        return undefined;
    }
```

**Comment by radekmie** [comment]
Hi @hmvp. We are aware of that. The same happens for all other bridges as well. I think we should define a clear logic for all bridges at once and then implement that. One question though: do you think it is needed to support something like _cancelation_ of default values? I mean, parent field defines some default value but the nested field want's to ignore it.

**Comment by hmvp** [comment]
Good question: for our use case that is not really a question since I am not sure if that will ever happen. 

But I think that one way to do it is to define a default value on the child that behaves like undefined like an empty string. The example above only tries to fetch the parent value if nothing is defined for the child.

**Comment by radekmie** [comment]
We've thoroughly discussed this issue and decided not to implement it at all. At least not right now.

The thing is that the general implementation (field `a...x` has its default value in `a`) will impact the performance for all users but will help only a few. We've also thought about implementing it as an option of `JSONSchemaBridge`, but once again, we don't see enough value in it. However, a workaround _exists_ (I think it can be done without copying the `getInitialValue` at all) and thank you @hmvp for sharing it here.
