### ISSUE TITLE
invalid prop warning: grid

### ISSUE THREAD

**Issue by zeroasterisk** [vazco/uniforms#75]
```
warning.js:44 Warning: Failed prop type: Invalid prop `grid` supplied to `AutoValidatedQuickBootstrap4Form`.
```

I assume we need to allow... can I just add it here:
https://github.com/vazco/uniforms/blob/master/packages/uniforms-bootstrap4/src/components/forms/ValidatedQuickForm.js

How?

**Comment by radekmie** [comment]
These propTypes are derived from [`Bootstrap4Form`](https://github.com/vazco/uniforms/blob/master/packages/uniforms-bootstrap4/src/components/forms/BaseForm.js#L13-L16). Could you show your `grid` prop?

**Comment by radekmie** [comment]
It turned out, that an object in `grid` is one of desired values, but propTypes are lacking of it. I'll add it in a moment.
