### ISSUE TITLE
Name of field in error messages

### ISSUE THREAD

**Issue by coo1k** [vazco/uniforms#752]
This is the screenshot from the form on your website.
Here I see 2 error messages which do not have name of the field which are invalid. It would be hard for end user to guess which fields each error message belong to if there are multiple errors. Am I missing something here?

![Annotation 2020-06-24 172016](https://user-images.githubusercontent.com/4363135/85639892-061d4d80-b63f-11ea-9753-d1feb46e6ed5.png)

**Comment by radekmie** [comment]
Hi @coo1k. All error messages are produced by bridges. I guess that in your case it's `JSONSchemaBridge` with `ajv`. If so, these errors are coming from `ajv`. Now, to provide custom error messages - translated, changed, different for each field - you have to do it in your validator. There's a few packages to do that, like [`ajv-errors`](https://github.com/ajv-validator/ajv-errors).
