### ISSUE TITLE
SelectField `allowedValues` with special characters / diacritics

### ISSUE THREAD

**Issue by rereradu** [vazco/uniforms#753]
Hi,
When trying to add options with special characters / diacritics for a `SelectField`, I get the following error:

```Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.```

Example:

``` <SelectField name="someField" allowedValues={['ă', 'ș']}/> ```

Is there any workaround for this except using a custom field?

**Comment by radekmie** [comment]
Hi @rereradu. Indeed, we do use `btoa` to [provide unique value-dependant IDs](https://github.com/vazco/uniforms/blob/b0724e397d24fe4743de6c46487c4497f1de0a7e/packages/uniforms-material/src/SelectField.tsx#L135). I guess we'd need to add some escaping logic to handle whole UTF-8 charset.
