### ISSUE TITLE
Simplschema issue with loading form

### ISSUE THREAD

**Issue by wtrocki** [vazco/uniforms#755]
Hi

I have been trying to fix this problem for weeks and it still happens completely randomly for some people's machines while on other works. Looks like timing issue or something.
Register command is not called sometimes and the application ends with an error. 

Error:
<img width="1094" alt="Screenshot 2020-06-26 at 16 06 04" src="https://user-images.githubusercontent.com/981838/85871926-ffb9dd80-b7c6-11ea-888a-3cda31d69e45.png">

Dependencies:
<img width="622" alt="Screenshot 2020-06-26 at 16 06 57" src="https://user-images.githubusercontent.com/981838/85872005-1b24e880-b7c7-11ea-9caa-833588d070c3.png">

I have tried: 
- Swapping bundler
- Different versions of the simpl-schema
- Different versions of uniforms
- Reordering imports.
- pulling register directly to my app 

Problem can be reproduced in: https://github.com/aerogear/OpenVolunteerPlatform

**Comment by wtrocki** [comment]
Further investigation shown that this is due to the SimplySchema object returned in-app is different than the object used inside the package. I cannot explain it but fix will be to actually reexport simply schema from uniforms package

```
import SimpleSchema from 'simpl-schema';
import { filterDOMProps } from 'uniforms';

console.log("Calling register")
// Register custom property.
SimpleSchema.extendOptions(['uniforms']);

// There's no possibility to retrieve them at runtime
filterDOMProps.register(
  'allowedValues',
  'autoValue',
  'blackbox',
  'custom',
  'decimal',
  'defaultValue',
  'exclusiveMax',
  'exclusiveMin',
  'label',
  'max',
  'maxCount',
  'min',
  'minCount',
  'optional',
  'regEx',
  'trim',
  'type',
);

export SimpleSchema;
```

**Comment by radekmie** [comment]
Hi @wtrocki. Re-exporting SimpleSchema is not feasible nor planned to do. You have to check, what's happening in your build process. Maybe `simpl-schema` package is duplicated? I see no lockfiles (for npm nor for yarn) and the final resolution is not deterministic.

**Comment by wtrocki** [comment]
> Maybe simpl-schema package is duplicated? 

This happens without package being duplicated (even with lock files like yarn etc.)
Do not want to explain here how node/npm/yarn works and how packages can be hoisted etc.
Having a library that sets some properties to singleton on other libraries in node_modules is generally asking for troubles IMHO. This issue happened for multiple people in multiple repositories with different versions. Repo just needs to use yarn workspaces or lerna and things go sideways.

**Comment by radekmie** [comment]
> Having a library that sets some properties to singleton on other libraries in node_modules is generally asking for troubles IMHO.

we've had similar problems in the past and we've solved them as it means multiple copies of the lib are in the final bundle. Anyway, there's no other way to configure it, as that's how SimpleSchema works.

> Repo just needs to use yarn workspaces or lerna and things go sideways.

I don't know about yarn workspaces (I've never configured them nor worked with them more), but from my experience, Lerna only helps to reduce duplication. Even in the uniforms codebase, we do have multiple packages, using SimpleSchema for tests and it works correctly.

**Comment by wtrocki** [comment]
> Anyway, there's no other way to configure it, as that's how SimpleSchema works.

The best way to configure it is to call register on user APP. This API will allow users to control this problem. I'm coming from the point where we trying to promote package by simple schema thing and this issue is kinda blocking it because people coming back with - this stuff doesn't even work and pointing this issue. 

Maybe simple-schema is not the right format to promote then? What would you suggest. I'm hopeless. 
In my apps I used this workaround:
https://github.com/aerogear/OpenVolunteerPlatform/blob/master/platform/client-admin/src/config/SimpleSchema.ts

**Comment by radekmie** [comment]
1. There's no need to copy `filterDOMProps.register`, as long as uniforms package is not duplicated as well. This means you have to add a single line for the SimpleSchema and only if your bundler is having this problem (none of our projects is).
2. Exposing a method to register to a user-defined SimpleSchema instance sounds good - let's keep that in mind. Again, this will only call `SimpleSchema.extendOptions(['uniforms']);`.
3. We are not using SimpleSchema outside of Meteor at all (maybe there's one exception). In most cases, JSON Schema is the most robust and easiest to work with (including extending `JSONSchemaBridge`). Also, it's serializable, which is a killer feature for automatically generated forms.

**Comment by wtrocki** [comment]
1. Thanks for hint
3. Actually this is probably something we should be doing instead

CC @ kingsleyzissou

**Comment by radekmie** [comment]
OK, I guess everything is clear now - I'm closing. Feel free to comment anyway.
