### ISSUE TITLE
Unsupported field type: string,null

### ISSUE THREAD

**Issue by talena6** [vazco/uniforms#756]
I am trying to figure out a way to allow null fields. It seems that I should be able to to set `"type": ["string", "null"]` in my schema, but I get the error `Unsupported field type: string,null`. Is there any way around this?

**Comment by radekmie** [comment]
Hi @talena6. No, there's no support for multiple types. You can try using `anyOf`, but it won't help in this case either. Is there a need to have such a type? If not, you can make this field not required and later replace empty (`undefined`) values with `null`s.

If you want it to behave just like `type: 'string'`, you can extend JSONSchemaBridge and override `getType` function.

**Comment by radekmie** [comment]
I guess we won't think out anything better than we already have in #740.
