### ISSUE TITLE
Trouble using AutoField for schema type array

### ISSUE THREAD

**Issue by talena6** [vazco/uniforms#757]
I am using: 
```
"uniforms": "^2.6.9",
"uniforms-antd": "^2.6.9",
"uniforms-bridge-json-schema": "^2.6.9"
```

Here is how my schema looks:
```
{
  "type": "object",
  "properties": {
    "routes": {
      "type": "object",
      "label": "",
      "properties": {
        "routing": {
          "type": "array",
          "title": "Routing",
          "items": {
            "anyOf": [
              {
                "type": "object",
                "properties": {
                  "path": {
                    "type": "string",
                    "title": "Path"
                  }
              }
            ]
          }
        }
      }
    }
  }
}

```

And here is how I am trying to display only the "path" field.
```
<NestField name="routes">
    <NestField name="routing">
        <AutoField name="path" />
    </NestField>
</NestField>
```

But I get the error `Field not found in schema: "routes.routing.path"`. I am using the same method to display other data, but the only difference here is that it is of type array.

**Comment by radekmie** [comment]
Hi @talena6. This error is correct, as there's no `routes.routing.path` in your schema. uniforms use `$` to indicate _array element_ field. In your case, `routing` field should use `ListField` (arrays), not `NestField` (objects). You can find usage of `ListField` in the docs or in other issues.
