### ISSUE TITLE
Insufficient documentation on custom bridge

### ISSUE THREAD

**Issue by mariusrak** [vazco/uniforms#761]
Hi, I'm trying to create mongoose bridge, but [the documentation](https://uniforms.tools/docs/uth-bridge-concept) is not comprehensive enough to work with it. I have no idea what should particular method return. What should be format of returned variables and sometimes even purpose is not clear. The comments are often just redundantly said name of function with its parameters. Is there any other documentation on the topic that I'm missing? Or is it, please, possible to enhance it and provide comprehensive explanation?
Thanks.

**Comment by radekmie** [comment]
Hi @mariusrak. That's true, this part of the documentation is not very helpful. I think that in v3, using our new `CodeSection`, we could directly import the `Bridge` implementation into the docs and document it once, in the code (providing meaningful documentation for IDEs as well).

If you are in a dire need for insights about custom bridges and/or how to extend them, I recommend looking into the source of existing ones (to get the idea) and look through the older issues or even Gitter - many questions were already answered. If you won't find an answer, do ask it here - we'll re-use it for the docs later.

**Comment by mariusrak** [comment]
What is purpose of `getErrorMessage()` ? Other bridges mention some error's scope, but whats the scope?
Thanks

**Comment by radekmie** [comment]
The `getErrorMessage(name, error)` should return error message for field `name`, extracted from `error`. The _scope_ is referring to the _part of an error_, important for a given field. Similarly, `getError(name, error)` should return the _error_, not only the message. Something like this:
```ts
// In your validation library...
const error = createEmptyError();
addErrorForField(error, 'fieldA', 'Error message for fieldA');

// Elsewhere
bridge.getErrorMessage('fieldA', error) === 'Error message for fieldA';
bridge.getErrorMessage('fieldB', error) === '';
```

**Comment by mariusrak** [comment]
Oh, I've found another question: 
```
getValidator(options = { clean: true, mutate: true }) 
```
What are purposes of those options, when are they used?

**Comment by radekmie** [comment]
You can accept any kind of value there - the `validator` prop of `ValidatedForm` is being passed there directly ([v2](https://github.com/vazco/uniforms/blob/b0724e397d24fe4743de6c46487c4497f1de0a7e/packages/uniforms/src/ValidatedForm.tsx#L65-L670), [v3](https://github.com/vazco/uniforms/blob/a3dffb97b850d26cbbbbf8b306a58ccb2c674f6f/packages/uniforms/src/ValidatedForm.tsx#L53)). It's the only way to communicate with the bridge on a per-form basis.
