### ISSUE TITLE
Validation is not triggered in antd Selection (v3)

### ISSUE THREAD

**Issue by pro-kswe** [vazco/uniforms#769]
Thanks for this awesome lib and the update to v3 and antd v4! Currently, I try to migrate to uniforms v3. I think I found a regression bug. When using a selection field, the validation is not (re)triggered after changing the value. This can be reproduced with the help of the playground. Go to

https://uniforms.tools/playground/#?N4IgDgTgpgzlAuIBcIDqUA2BjA9gWygEIQAacCHMGZUAQwFd4cZaA3KZAM1ozjIaYt2AEUy0AnsgCMABhlkAJgEsWAIwxQFXHnxAZaqzMngR6UMmH1YoACxwYFUCNt7mQMLDah5ayEADsoAHcAAgBlJTxLKDDPb1oAJgAhCCUFAHMoAAoAHX8QgpDA0IiojVivHyzgPMK6kIVaeCgkEJr8-s74cTAWkOEm81rO-sduegx4ADUeM1bi_sGsgEphzoBfEjy1-toFCfhW9pH67t7WpJx7KFp_HbrN7Y7OmCUALz7jk8KzvrCTJT-dJbZ7fMYMSYzDBzEIAcjwsJB30KPAwOCCmihZhgrQA2rCAB4wRFw4kkOEI8mwjAkwk0gC690KjzuoLqECagPSRyZXR6fQAcvQ8IYIEjkSFUejMbNYHipOSEuSAMzkgAs5IArPTxcj6P4lJwcBA8Di2rzvnEsABrVQ4AlykImMwWh4WlkWzipKD-BRmr7I36tACCEA54l13zwgIAwjh9YcQlJ3SCLbCvUofX6AHQAElhPLZIyDIQA8qoAFZQLDwFNPE7p72-mB57P-WgEAvmot887hAFAyMnaP-VrKuushsZrMt3PZ2iZLsB74loUipxDkYj1ryV2FHwE1pSTUyd07darfzLUjuOxBACS_gwgKgAFEw8aXLpaDBxP4sKW_hhPQqjRogSDcK4_C_v-gFQmkgxflAmwgPAlQcCgtzwFo6xAA

Change the size field to

```
 size: {
            type: String,
            allowedValues: ['xs', 's', 'm', 'l', 'xl']
        },
```

1. Press the `Submit` button (no size selection done). => The size selection field is invalid (red).
2. Choose a size. => The size selection field is (still) invalid (red).

Expectation: After changing to a valid value, the field should turn into a valid state (none red).

I think this was the case with v2.

Thanks
Oliver

**Comment by radekmie** [comment]
Hi @pro-kswe and thanks for the report! Yes, it's a bug. [Here's a minimal reproduction](https://uniforms.tools/playground/#?N4IgDgTgpgzlAuIBcIDqUA2BjA9gWygEIQAacCHMGZUAQwFd4cZaA3KZAM1ozjIaYt2AEUy0AnsgCMABhlkAJgEsWAIwxQFXHnxAZaqzMngR6UMmH1YoACxwYFUCNt7mQMLDah5ayEADsoAHcAAgBlJTxLKDDPb1oAJgAhCCUFAHMoAAoAHX8QkMDQiKiNWK8fLOA8goLOJUwFJBDq_NqC-HEwKGawkyV_dJIa9pCeDBwgzQA1HjMYZoBtAHJaZZIQ5dVlgF0RgoBfEYOASjyT0nc7IIBJfwwBqABRCApnJG5XfhhxfywAeX8YXoqjwSkQHx0bloPz-gNmDwUtHgHEhrgOZHgFVRIHo_hgnQ0WgOQA). For some reason, first change does not remove the validation error but if you'll do it once more - it works.
