### ISSUE TITLE
Validate only certain keys

### ISSUE THREAD

**Issue by sabativi** [vazco/uniforms#772]
Hello,

While doing a multi steps form, I am trying to validate only one field by using this method https://uniforms.tools/docs/api-forms/#validatekey-value

But the entire form is validated : reproduction can be found here https://uniforms.tools/docs/api-forms/#validatekey-value

Inside I test only the "what" field but there is an error thrown on the betterNumber field which i do not want to validate.

How can I handle such case ?

Thanks

**Comment by radekmie** [comment]
Hi @sabativi. The `validate(key, value)` semantic is different - _validate the current model, with field `key` set to `value`_. The possibility of validating only specific fields was already partially covered in https://github.com/vazco/uniforms/issues/730#issuecomment-631490529 and mentioned in [_Introduction > Comparison matrix_](https://uniforms.tools/docs/compare-matrix). In short, it's not possible as many schemas cannot validate only a subset of fields.
