### ISSUE TITLE
[v3] the types of filterDOMProps.register don't seem to support custom strings anymore

### ISSUE THREAD

**Issue by shrugs** [vazco/uniforms#777]
This is on `uniforms@v3.0.0-rc.2`:

the types on [filterDOMProps.register](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/filterDOMProps.ts#L19) seem to constrain the available strings to the set of pre-registered options.

With the code

```ts
filterDOMProps.register('nullable');
```

I get the typescript error:

```
Argument of type '"nullable"' is not assignable to parameter of type '"allowedValues" | "changed" | "component" | "disabled" | "error" | "errorMessage" | "field" | "fieldType" | "fields" | "initialCount" | "label" | "name" | "onChange" | "placeholder" | "showInlineError" | "transform" | "value"'.
```

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/1535001/89339418-1e37b200-d66c-11ea-97a4-40be35f3e650.png">

## Workaround

casting the string to any like so:

```ts
filterDOMProps.register('nullable' as any);
```

opts us out of the type system, and the implementation of `register` works as expected

**Comment by radekmie** [comment]
Hi @shrugs. As said in the [changelog for v3.0.0-rc.0](https://github.com/vazco/uniforms/blob/master/CHANGELOG.md#v300-rc0-2020-07-15), registering new properties has to happen on type level as well:

```ts
declare module 'uniforms' {
  interface FilterDOMProps {
    nullable: never;
  }
}
```

**Comment by shrugs** [comment]
ah, thanks for the link - hadn't read the changelog 😅
