### ISSUE TITLE
Feature Request: Custom options for select field

### ISSUE THREAD

**Issue by RSchwan** [vazco/uniforms#78]
See http://autoform.meteorapp.com/select
This would allow dynamic select fields

**Comment by macrozone** [comment]
You can pass allowedValues as property to the select-field and add a transform-function that returns a label for each value to achieve the same thing.

In my case i created custom form elements where i declare an options-property, which is an array of {key, value} like in autoform because that is much easier to implement than allowedValues and transform.

**Comment by RSchwan** [comment]
I see your point. But wouldn't it be easier and more simple to bake it directly into the library?

**Comment by radekmie** [comment]
It's already done. You can read more in #23, but the API is the same - you can pass `options` property (or pass it in `uniforms` object in your schema). It can be either an object or an array (or a function, that returns it). Basically it overrides `allowedValues` and `transform`. [Source](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/bridges/SimpleSchemaBridge.js#L183-L202).

**Comment by RSchwan** [comment]
The options property works great!
The only thing I wonder is if there is a way to set a default label. If the field is optional there should be an option for deselection the field.
I tried to add something like this to the options array: `{ label: 'None', value: undefined }` but for the validator there is still a empty string selected.

**Comment by radekmie** [comment]
[Use `placeholder`](https://github.com/vazco/uniforms/blob/master/packages/uniforms-bootstrap3/src/components/fields/SelectField.js#L44-L48).

**Comment by RSchwan** [comment]
For the validator there is still a empty string and so my validation fails.
And the other thing is that you can't reselect the placeholder.
Autoform for example has a [`firstOption`](https://github.com/aldeed/meteor-autoform#affieldinput) property.

**Comment by radekmie** [comment]
Well, I have to think about it. Also, it would be nice, @RSchwan, if you could describe your desired API (and behaviour) here.

**Comment by RSchwan** [comment]
Ok I figured out where my problem was. I didn't know that custom validations are fired although I you have optional set to true.

**Comment by radekmie** [comment]
It's good to know it, thanks.
