### ISSUE TITLE
graphql@15 breaks uniforms

### ISSUE THREAD

**Issue by alexanderlperez** [vazco/uniforms#781]
**NOTE: reposted from gitter at request of @radekmie** 

At: https://gitter.im/vazco/uniforms?at=5f2fecd865e829425e708c7a
> As I quickly checked, the playground you've created is using graphql@15 but uniforms are not yet updated. I mean, it'll for 99.9% just work, but due to the way how npm resolves modules, your type (got from getType) is not an instance of the same type in uniforms, because uniforms import a separate copy of graphql@14. Please file an issue and we'll take care of it in the following week.

---

I've been trying to get a basic example running on codesandbox (https://codesandbox.io/s/agitated-rgb-3vlrr?file=/src/App.js) using **graphql@15** and the graphql bridge, but am getting `Unsupported field type: String!` for the single field in the schema. 

The example works in the uniforms playground.

Playground sample:
```
new GraphQLBridge(buildASTSchema(parse(`
type Log {
    title:   String!
}

type Query { anything: ID }
`)).getType('Log'), function (model) {}, {})
```

**Comment by radekmie** [comment]
Hi @alexanderlperez! Thanks for filing this issue. I'm already on it.
