### ISSUE TITLE
Outlined Material-UI TextField

### ISSUE THREAD

**Issue by correaricardo** [vazco/uniforms#782]
How can I pass props (specifically, the **variant** prop) to the Material-UI TextField?

![image](https://user-images.githubusercontent.com/7898290/89913023-dc04f800-dbb8-11ea-8153-16806e478787.png)

**Comment by correaricardo** [comment]
It seems that I need to create a [custom field](https://uniforms.tools/docs/tutorials-creating-custom-field), which is tedious because **variant** is a simple prop.

**Comment by correaricardo** [comment]
Well, It was easier than I thought it would be

![image](https://user-images.githubusercontent.com/7898290/89935852-76c0ff00-dbd8-11ea-98fe-715c02e81d2f.png)

**Comment by radekmie** [comment]
Hi @correaricardo. Thanks for letting us know, that you've managed to find it!
