### ISSUE TITLE
Can I use CSS-in-JS with Uniforms?

### ISSUE THREAD

**Issue by vfonic** [vazco/uniforms#783]
I'm trying to setup Emotion.js to work with Uniforms, but I can't get them to work together.

Here's what I tried:

```jsx
import styled from '@emotion/styled';
import AutoField from 'uniforms-unstyled/AutoField';

type StyledInputProps = { big: boolean }

const StyledInput = styled(AutoField)`
  border-radius: 8px !important;
  ${(props: StyledInputProps) => props.big && 'height: 80px'}
`;

export default StyledInput;
```

`AutoField` seems to ignore/skip any props that Emotion adds.

Any ideas where I could look further?

Thanks!

**Comment by radekmie** [comment]
Hi @vfonic. I'll look into it.

**Comment by radekmie** [comment]
As I've checked, it correctly renders styles, but **not** on `input`. You can verify it this way:

```tsx
const StyledInput = styled(AutoField)`
  background: red;
  border-radius: 8px !important;
  ${(props: StyledInputProps) => props.big && "height: 80px"}
`;
```

Each field (`NumField`, `TextField`, etc.) renders differently. This means you'd have to use different styles for each field. For example, [`TextField`](https://github.com/vazco/uniforms/blob/master/packages/uniforms-unstyled/src/TextField.tsx) passes `className` to the top-level `div`.

**Comment by vfonic** [comment]
Thanks, @radekmie!!! Indeed, I totally missed that `AutoField` creates more elements than just the input.

I ended up with something along the lines of:

```jsx
import styled from '@emotion/styled';
import AutoField from 'uniforms-unstyled/AutoField';

type StyledInputProps = { big: boolean }

const StyledInput = styled(AutoField)`
  ${(props: StyledInputProps) => props.big && 'height: 80px'}
  
  input {
    border-radius: 8px;
  }
`;

export default StyledInput;
```
