### ISSUE TITLE
ClassName for SelectField

### ISSUE THREAD

**Issue by michael-vasyliv** [vazco/uniforms#785]
It seems like ``className`` does not work for SelectField
inside component
![Screenshot from 2020-08-12 15-38-24](https://user-images.githubusercontent.com/19407350/90015925-f242af00-dcb1-11ea-8a34-521131d0c5eb.png)

in HTML 
![Screenshot from 2020-08-12 15-38-04](https://user-images.githubusercontent.com/19407350/90015957-fbcc1700-dcb1-11ea-9f49-dfe111145110.png)

additional information:
"preact-cli": "3.0.0-rc.7",
"preact": "10.3.4",
"preact-render-to-string": "5.1.4",
"preact-router": "^3.1.0",
"uniforms": "^3.0.0-rc.0",
"uniforms-bootstrap4": "^3.0.0-rc.0",
"uniforms-bridge-json-schema": "^3.0.0-rc.0",

**Comment by radekmie** [comment]
Hi @michael-vasyliv. I can see that there's an incorrect props type, but besides that - do you think that `className` is needed? There are others, specialized ones.

**Comment by michael-vasyliv** [comment]
@radekmie there are so many classes and no one fits me, I want to add class beside ``form-group``. As I understand SelectField extends from BaseField that takes ``className`` as a prop so in my opinion, it should work but I have a bug.

**Comment by michael-vasyliv** [comment]
@radekmie I took all classes that are discribed in https://uniforms.tools/docs/api-fields#selectfield (all props that have suffix className) and no one adds ``className`` beside ``form-group``

**Comment by michael-vasyliv** [comment]
@radekmie or are least there is a question is it a bug or its a designed feature (not accept className in SelectField)? because it works fine for TextField, bug for SelectField it does not work
![Screenshot from 2020-08-12 18-35-07](https://user-images.githubusercontent.com/19407350/90035565-9cc6cc00-dcca-11ea-84b2-4f1d98decb1e.png)

**Comment by radekmie** [comment]
@michael-vasyliv That's odd - we'll check that.
