### ISSUE TITLE
Regression with rc26

### ISSUE THREAD

**Issue by serkandurusoy** [vazco/uniforms#79]
Somehow, default is not prevented any more on onSubmit and this causes a full page refresh.

**Comment by macrozone** [comment]
Can you describe the scenario?

Maybe its related to my PR? https://github.com/vazco/uniforms/pull/77

**Comment by serkandurusoy** [comment]
Well the scenario is simple, the previous behavior was that you'd get a doc passed to your onSubmit handler and that's it. But now there is actual form submission so the page is getting refreshed.

**Comment by radekmie** [comment]
Just to be sure - it worked in rc.25?

**Comment by serkandurusoy** [comment]
Oh, I think I had 24 and jumped to 26 just half an hour ago. I did not even notice 25!

**Comment by serkandurusoy** [comment]
@macrozone I just looked at the changes from that PR and no that seems unrelated

**Comment by radekmie** [comment]
Yes, it's definitely unrelated @macrozone.

**Comment by serkandurusoy** [comment]
Haha he almost had a heart atack thinking his first small pr just broke the package, LOL :)

**Comment by radekmie** [comment]
I've tested rc.26 @serkandurusoy and it worked. I don't know what is going on.

**Comment by serkandurusoy** [comment]
Hmm, interesting, I'll look at other places in the app that may be causing such behavior. That's a login form so perhaps some reactive update on Meteor.loggingIn or something may actually be the culprit!

I'll close this issue for now and reopen if I can narrow it down to actually something related to uniforms.

Thanks!

**Comment by serkandurusoy** [comment]
Yep that was it. It seems a Meteor.loggingIn check higher up in the dom tree caused the component get swapped out to something else and then back, which kind of looks like a page refresh in this app.

**Comment by radekmie** [comment]
Well... Luckily, false alarm.

**Comment by macrozone** [comment]
@serkandurusoy haha 💯 

Yeah, I spent roughly 2-3 hours tracking down this bug and was so suprised that the solution was that easy. That's why i had some trust issues ;-)
