### ISSUE TITLE
Problem with title in selector (JSONSchema + uniforms-semantic )

### ISSUE THREAD

**Issue by aapodshivalov** [vazco/uniforms#792]
https://uniforms.tools/playground/#?N4IgDgTgpgzlAuIBcICCATd0YwAQAoApAZQHkA5YgYwAsoBbAQwEoQAacCAezBmVEYBXeFxiMAblGQAzRgBs4HISLGSAIlDmMAnsgCMABgMd0ASzEAjOVHQz5ikFoubk8CIKgcwWqlBpc5dCgIOwVPEBhaBkZkEHx8ZlwAXgA-XGAAHQA7XFzcKi4smHhcRgArcWTcLKgAd1xUCvxgeTkAUQhuCBgkXDcPNlxBOA1ZQTl4Hr73KABfZgBubLz8wuLcSLomKsyclbz4U3hrXoByDCxYGFO2Zf3c-G0wKDOuCzKoKngbu_vIHmCh1gvV293uMEE70-8F6uWAj2eZ2KEFMWQA5jc-kcTrhTuRGPQoJigmMJgA1eQeM6Y1pcWo2ClyDxTADa50xpwAQhyAMKnAC6s1uezBeQhUK-ACZYekES9ccjURjBodjvK8QSoJKaXI5HSGZTgbg2agOdzBqc-YLhaKhb99tAAI6CUzQdC9Nnij5fDle6Ha_n22bZe3SQRZL6mQr5aCMeBQRmmdBxrgQfCbaKJUH7ApFErieRJlMQKrlcQAOgK9DApms6aiTEWIZFeWg8EEEBy9C4QTkyTS2fuBbkRZEae7vabWXtK1M0gIw9HqfLwS6eAAZOvcIvk2OV51UzBy9Z0fAaFmZ_sz9x6sAgvBGLWpjvi_u17Mli2VsGv7gP0HmxWXN1gzJhE13VMqioWN43A4t6y2FhP3tNsOxyGp6hIChqEQzkUXQNEoAQ6JBlAxg4LHKd5gSdgIn8WoAEkshHGoOi6UIHEYGBtAjUgsmISF6CODjwi4niqD4iipCQWQwiFEAzwYaSImiLJDioEBZiAA

    const schema = {
        title: 'Address',
        type: 'object',
        properties: {
            subject:   {type: 'string', title: 'Name', defaultValue: '', allowedValues: ['A', 'B', 'C']},
            subject2:   {type: 'string', title: 'Name2', allowedValues: ['A', 'B', 'C']},
        },
        required: ['subject', 'subject2']
    }

I dont need title(=Name) in input field.
How to fix it?

**Comment by aapodshivalov** [comment]
Open the link and you find out the problem.

For me solution was
<AutoForm 
  ....
        placeholder // add this
/>

and 

    const schema = {
        title: 'Address',
        type: 'object',
        properties: {
            subject:   {type: 'string', title: 'Name', placeholder: ' ', allowedValues: ['A', 'B', 'C']},
            subject2:   {type: 'string', title: 'Name2', allowedValues: ['A', 'B', 'C'], placeholder: ' '},
        },
        required: ['subject', 'subject2']
    }


https://uniforms.tools/playground/#?N4IgDgTgpgzlAuIBcICCATd0YwAQAoApAZQHkA5YgYwAsoBbAQwEoQAacCAezBmVEYBXeFxiMAblGQAzRgBs4HISLGSAIlDmMAnsgCMABgMd0ASzEAjOVHQz5ikFoubk8CIKgcwWqlBpc5dCgIV3dPEBhaBkZkEHx8ZlwAXgA-XGAAHQA7XFzcKi4smHhcRgArcWTcLKgAd1xUCvxgeTkAUQhuCBgkXDcPNlxBOA1ZQTl4Hr6wgF9mAG5svPzC4txIuiYqzJzlvPhTeGtegHIMLFgYE7Ylvdz4bTAoU64LMqgqeGvbu8geYIOsF6OzudxggjeH3gvVywAeT1OxQgpiyAHNrn1DsdcCdyIx6FAMd5GL5_IFgqccYNWlxajYAGryDxTADaZwxJwAQhyAMInAC6Mxuu1BeXBkM-ACYYel4c8cUiUejBgcjvLcfioJKMTS6ehGXJmb02agOdzBic-fzBsTSQEghBKSchT89i6RXtoABHQSmaDoY0ncXvT4c4NQ7X810zbKu6SCLKfUyFfLQRjwKAG0zodNcCD4DbRRIgvYFIolcTybO5iBVcriAB0BXoYFM1gLUSYC1jHty0HggggOXoXCCcmSaRLd0rcmrInzI7H3ayruWpmkBBnc7zDeCXTwADID7gtzn57vOnmYA3rGj4DRi6u9vfuPVgEF4Iw21NTzWL_uZkWXs8hjYDAOjHtljLNZCyYLMzzzKoqDTDN4JrDtNhYIDXX7QcchqeoSAoahMM5ZF0FRKAMOiQZYMYND52XOYEnYCJ_FqABJLJZxqDoujsBRwkYGBtETUgsmICF6EOASHGE0SqHEhipCQWRBKFEB7wYFSImiLIDioEAZiAA

**Comment by radekmie** [comment]
Ah, you meant the default option label, OK! I'm glad you've worked it out!
