### ISSUE TITLE
Select does not show inline error

### ISSUE THREAD

**Issue by michael-vasyliv** [vazco/uniforms#793]
Select does not show inline error in uniforms-bootstrap4 and uniforms-bootstrap3
[playground](https://uniforms.tools/playground/#?N4IgDgTgpgzlAuIBcIDqUA2BjA9gWygEIQAacCHMGZUAQwFd4cZaA3KZAM1ozjIaYt2AEUy0AnsgCMABhlkAJgEsWAIwxQFXHnxAZaqzMngR6UMmH1YoACxwYFUCNt7mQMLDah5ayEADsoAHcAAgBlJTxLKDDPb1oAJgAhCCUFAHMoAAoAHX8QgpDA0IiojVivHyzgPMK6kNr6gpglAC8oJBCa_Kb6-HEwDvCTJX90kkbewp4MHCDNADUeMxhOgG0AcgAPGA2SEI3d_Y28PYOMM-2LgF1J-oBfCf87-4BKPNfSdzsggEl_DCjKAAUQgFGcSBMZn4MHE_iwAHl_GF6Ko8EpEEhuK4YXDEf4loCFLR4BwsTooI8QPBKmSQKocDh4DATLQwAAWED3IA)

here is result of inline error in uniforms-bootstrap4
![Screenshot from 2020-08-21 15-45-53](https://user-images.githubusercontent.com/19407350/90892129-80f7b000-e3c5-11ea-9192-17f27ec56495.png)

here is result of inline error in uniforms-antd
![Screenshot from 2020-08-21 15-46-24](https://user-images.githubusercontent.com/19407350/90892137-835a0a00-e3c5-11ea-984f-df098b6195cd.png)

as you can see there is text under input in antd but not in bootstrap4

**Comment by kestarumper** [comment]
Hi @michael-vasyliv,
We'll check this out and if bootstrap supports inline errors we will fix that.

**Comment by michael-vasyliv** [comment]
@kestarumper Hello! I've found the bug and fixed it in the #795
