### ISSUE TITLE
Some fields require attributes

### ISSUE THREAD

**Issue by pro-kswe** [vazco/uniforms#798]
Hi

I think this is a regression bug. Some fields like the NestedField warn me that some attributes are required, like disabled, changed, field, id etc.

Nevertheless everything works fine, I guess.

Maybe you can quickly spot the interface def and verify this

Thanks a lot
Oliver

**Comment by radekmie** [comment]
Hi @pro-kswe, thanks for your report. Indeed, certain types are _quite_ not there yet. If you could list the fields (with their theme) and props you are having problems with, it'd be great!

**Comment by pro-kswe** [comment]
Sorry for the delay, here is the list:

- import { NestField } from 'uniforms-antd';
- import { LongTextField } from 'uniforms-antd';
  - changed, disabled, field, fieldType, fields, id, onChange, showInlineError

Thought it was a bigger thing, but I guess this is rather a small issue. Thanks for keeping this lib up-to-date!

**Comment by radekmie** [comment]
@pro-kswe Could you confirm that? As in [`NestField`](https://github.com/vazco/uniforms/blob/1aa7139dfad63e6d73d4a1194ac7e6d7cebbb464/packages/uniforms-antd/__tests__/NestField.tsx#L8) and [`LongTextField`](https://github.com/vazco/uniforms/blob/1aa7139dfad63e6d73d4a1194ac7e6d7cebbb464/packages/uniforms-antd/__tests__/LongTextField.tsx#L9) tests, `name` is the only required one.

**Comment by pro-kswe** [comment]
That's right. Thanks a lot.

**Comment by oprobst-ethz** [comment]
Sorry for the question, but is this fixed? My IDE still shows me a warning...

**Comment by radekmie** [comment]
Hi @oprobst-ethz. Could you post a code sample and the error here? I was not able to reproduce this problem.

**Comment by oprobst-ethz** [comment]
Sure, I've just tried this piece of code in WebStorm:

```
import React from 'react';
import { AutoForm, ListField, ListItemField, NestField } from 'uniforms-antd';

export default function App() {
  return (
    <div className="App">
      <AutoForm>
        <ListField name="a">
          <ListItemField name="b">
            <NestField name="c" />
          </ListItemField>
        </ListField>
      </AutoForm>
    </div>
  );
}
```
That's what WebStorm brings up:

![uniforms_warnings](https://user-images.githubusercontent.com/77060593/103866568-44072e00-50c6-11eb-88cd-7ae40cafaeee.png)

Thanks  a lot for your effort.

**Comment by radekmie** [comment]
And what are these warnings? Are these from TypeScript or some other tool? If that's something built in your IDE, I have no clue how it works.
