### ISSUE TITLE
Submitting the form without terms acceptation

### ISSUE THREAD

**Issue by jBosak98** [vazco/uniforms#799]
After checking and unchecking the 'terms of use', it is possible to submit the form even when the terms are not accepted.
It occurs on the page: https://uniforms.tools/docs/examples-common-forms/
![image](https://user-images.githubusercontent.com/32513817/92715244-85c4d980-f35d-11ea-914d-09aec74fc6aa.png)

**Comment by radekmie** [comment]
Thank for the report, @jBosak98!
