### ISSUE TITLE
Feature: Access another field's value, from a custom component

### ISSUE THREAD

**Issue by zeroasterisk** [vazco/uniforms#8]
I can not seem to access another field's value/props from within a custom component (created via `connectField()`)

In my specific use case, I want a date range picker, where the `start` date becomes the `minimum` allowable value for the `stop` date... to do this, each input is it's own field/input... but they need to be able to access each other's values (and perhaps `field` and `error` too?)

**Comment by radekmie** [comment]
I've added `findError(name)`, `findField(name)` and `findValue(name)` in `1.0.0-rc.3`.
