### ISSUE TITLE
AutoLayout with LongTextField with JSON-Schema

### ISSUE THREAD

**Issue by jkinley** [vazco/uniforms#801]
Hi, I am new to react and uniforms, but this is a great Library. I might be missing something obvious here, but I did search through the issues before posting. 

So I need to use AutoFields but I don't know how to make it detect a textarea field. If I use the Uniforms object with component, it will not validate as JSON. What am I missing?

Thank you.

```
"problem": {
			"type": "string",
			"label": "Problem",
			"uniforms": { 
				"InputLabelProps": {"shrink": true},
				"component": LongTextField, 
				"InputProps": {rows: 2}, 
				"helperText": "Describe what problem this solves?",
				"margin": "normal",
				"variant": "outlined",
			}
        },

```

**Comment by jkinley** [comment]
HI all, I figured out a solution to my problem. I just added multiline: true. This works for the MUI. Hope this might help someone else. Thanks.

```
"summary": {
			"type": "string",
			"label": "Summary",
			"uniforms": {
				"multiline": true,
				"InputLabelProps": {
					"shrink": true
				},
				"InputProps": {
					"rows": 2
				},
				"margin": "normal",
				"variant": "outlined"
			}
		},
```

**Comment by radekmie** [comment]
Hi @jkinley. It looks different in different themes, but I'm glad you've found out it yourself!
