### ISSUE TITLE
How to maintain order of form fields?

### ISSUE THREAD

**Issue by jkinley** [vazco/uniforms#802]
Because the properties are contained in an object, not an array, the form fields are sorted alphabetically. Why aren't the form fields stored in an array? How are people handling this?

Thanks,

Jeff

**Comment by radekmie** [comment]
Hi @jkinley. It differs between schemas - GraphQL, JSON Schema, and SimpleSchema use objects, but _YourCustomSchema_ can use arrays. It's not a problem though, as the `getSubfields` method (e.g. [`SimpleSchema2Bridge.getSubfields`](https://github.com/vazco/uniforms/blob/19f3101b6686b954bc932daf6f0ad4cad9a6cec5/packages/uniforms-bridge-simple-schema-2/src/SimpleSchema2Bridge.ts)) returns a list of fields.

When it comes to the form, you can either manually render desired components in the form component, or use `<AutoFields fields={['fieldA', 'fieldB', ...]} />` (imported from your theme).

**Comment by jkinley** [comment]
Thanks, radekmie. This helps a bit, but still not sure how I can have my fields in the correct order. Because they are in an object, they come back unordered via the API request. I can use getSubfields() to get the list, but they are still out of order. Of course, I can manually sort the list, but that defeats the purpose of having auto layout (which is critical as we are getting data from an API).

**Comment by radekmie** [comment]
You don't do it on your schema. The `getSubfields` method I mentioned is only for a deeper understanding, that _there is_ an actual array underneath. But let's answer your question.

Usually, using `<AutoFields fields={...} />` is enough. If your layout is configured _somewhere_, it may be the case, that you'd want to calculate the `fields` prop based on the schema or anything else.

If you have different, maybe more specific requirements - you'd have to implement a custom field or logic to render the form differently, e.g. using external layout format.

**Comment by jkinley** [comment]
Thanks again, I am not sure this its the best way to do it, but I just added a fieldOrder property (kinda like the 'required' property) to my schema: 

```
"fieldOrder": ['title', 'summary', 'problem', 'impact', 'ticketNumber', 'priority', 'deliveryDate' ]
```

and I can pass that to the fields prop in Autofields. Have a great day.

**Comment by radekmie** [comment]
OK, so you are using JSON Schema. In this case, you can either pass it to `AutoFields`:

```tsx
<AutoForm schema={schema}>
  <AutoFields fields={schema.fieldOrder} />
  <ErrorsField />
  <SubmitField />
</AutoForm/>
```

Or create a custom bridge, extendeing the `JSONSchemaBridge`, overriding the `getSubfields` accordingly.

**Comment by jkinley** [comment]
Yeah, I passed it to autofields. Thanks!
