### ISSUE TITLE
Attributes onSubmitSuccess and onSubmitFailure are ignored

### ISSUE THREAD

**Issue by mariusrak** [vazco/uniforms#811]
I assume, that this code should after submit log (or show error) in console. But it does not. The callbacks are ignored.

```javascript
    <AutoForm
      schema={schema}
      onSubmit={(model) =>
        new Promise((res, rej) => {
          console.log(model);
          //rej("error");
          res("success");
        })
      }
      onSubmitSuccess={(r) => console.log(r)}
      onSubmitFailure={(e) => console.error(e)}
    />
```

Here is repro: https://codesandbox.io/s/vigorous-booth-g5n5l?file=/App.tsx

**Comment by radekmie** [comment]
Hi @mariusrak. Both `onSubmitFailure` and `onSubmitSuccess` [got removed in v3.0.0-alpha.3](https://github.com/vazco/uniforms/blob/master/CHANGELOG.md#v300-alpha3-2020-05-06). If you want to preserve this behavior, you have to do it inside of `onSubmit`.

**Comment by mariusrak** [comment]
They are still in documentation. And they were pretty nice pattern, so what is the rationale behind removing?

**Comment by radekmie** [comment]
Ah, sorry about that! We'll update the documentation soon. For _slightly more_ insights behind removing them, see #711. In short, they are easily replaceable and cause problems with (a)synchronous handling of `onSubmit`. For example, previously synchronous validation and submission (e.g. local form) were unnecessarily asynchronous.

**Comment by mariusrak** [comment]
Okay then. Thanks for explanation.
