### ISSUE TITLE
Setting Default Value for BoolField Prevents it Being Changed

### ISSUE THREAD

**Issue by LordA98** [vazco/uniforms#814]
Hi,

I have created an AutoForm to add things to the database.  This works great.

I am also trying to create a form for editing these records.  The records get listed with an 'Edit' button.  This edit button opens a modal with a form to edit that record.

I want to be able to set the default values to what they currently are.  For example, the 2 main fields are a 'name' field (Text) and a 'publish' field (Bool/Checkbox).  

My form is currently:

```
<AutoForm schema={menuBridge} onSubmit={submit}>
          <AutoField name="name" value={props.menu.name} />
          <BoolField name="publish" />
          <SubmitField />
</AutoForm>
```

I can set the default value for the text field using the value property.  However, when I set the value for the BoolField, it cannot be changed after that.  For example, the following snippet creates a checkbox which is not ticked:

`<BoolField name="publish" value={false} />`

However, this can then not be ticked.  It does not changed the checkbox to 'checked' when I click it.

I am using uniforms with Meteor, React and Simple Schema.  I also had this configuration in my SimpleSchema:

```
publish: {
      type: Boolean,
      defaultValue: true
},
```

By default, I wanted the menu to be published.  However, this was then setting the value of the published checkbox to true in the edit form as well.  I tried removing the default value but I still get the same error as explained above.

The documentation states that all fields inherit from a 'BaseField' but I could not find any documentation on the BaseField.

Is the correct property 'value'?  Or is something else?  I tried defaultValue and autoValue but these did not work.

I ideally want it to be dynamic, so I pass a React prop value into this value property as various menu's will differ.  Something like:

`<BoolField name="publish" value={props.menu.publish} />`

Should I create a new schema for this different form?  

Any help would be greatly appreciated.

**Comment by LordA98** [comment]
As usual, I spend hours struggling over something only to ask a question and then solve it right after.

The way to preset form values is using the model property on the AutoForm component, like so:

```
<AutoForm model={{name: "Preset", publish: true}} schema={menuBridge} onSubmit={submit}>
          <AutoField name="name" />
          <BoolField name="publish" />
          <SubmitField /> 
</AutoForm>
```

**Comment by radekmie** [comment]
Hi @LordA98. Glad you've found it out, but to make it clear: explicitly setting `value` will override the uniforms model.
