### ISSUE TITLE
Synchronous errors from onSubmit are ignored in v3

### ISSUE THREAD

**Issue by radekmie** [vazco/uniforms#819]
As found it while working on #812, there's a problem with errors from `onSubmit`. These errors are treated as _results_ and not actual problems. The problematic code is [here](https://github.com/vazco/uniforms/blob/1057654d1722c21aacc7a38eadf82946fbefbcab/packages/uniforms/src/BaseForm.tsx#L242-L245).

```tsx
onSubmit={model => {
  const errorOrNull = synchronousValidation(model);

   // Does not work but should.
  return errorOrNull;

  // Works as expected. 
  return Promise.reject(errorOrNull);
}}
```

**Comment by radekmie** [comment]
Some update: while working on that, I've come to the conclusion that synchronous errors from `onSubmit` are problematic. Returning them may be error-prone, as people may expect it to work in the same way as returning a value from asynchronous submission. Allowing throwing synchronous errors in `onSubmit` is problematic as well, as it may hide actual problems. Another option would be to make it work as follows:

```tsx
onSubmit={model => { return value; }} // [A] This value is accessible in `form.submit()` Promise. [B] This value is ignored.
onSubmit={model => { throw error; }} // This is an error, `onSubmit` cannot throw an error.
onSubmit={model => { return Promise.resolve(value); }} // This value is accessible in `form.submit()` Promise.
onSubmit={model => { return Promise.reject(error); }} // This error is treated as a validation error, being accessible in the form.
```

I think that is the best, as most `onSubmit` functions are asynchronous. Another, maybe easier to understand option ([B]), would be to force `onSubmit: (model: Model) => void | Promise<any>`, so ignore **any** synchronous result.

**Comment by Monteth** [comment]
I would opt for the 'B' as it's simpler and more consistent. I believe wrapping errors to Promise in sync scenarios won't be harmful.
