### ISSUE TITLE
Prevent validation when schema has changed and form is not submitted

### ISSUE THREAD

**Issue by macrozone** [vazco/uniforms#82]
validate=onChangeAfterSubmit or validate=onSubmit should prevent validation unless the user has submitted the form for the first time.

If you update the schema, this option is ignored and the form is validated.

Updating the schema is valid, e.g. if you have options from a collection that you define on the schema or if you translate the schema.

I'll check if I can do a PR.

**Comment by macrozone** [comment]
I think in ValidatedForm.componentWillReceiveProps

the same logic as in onChange should apply:

```
if (this.props.validate === 'onChange' ||
            this.props.validate === 'onChangeAfterSubmit' && this.state.validate) {
            this.onValidate(key, value);
        }
```

but componentWillReceiveProps does also sets state.validated and i don't know why yet, can you guys help?

**Comment by radekmie** [comment]
Yes, you are completely right @macrozone - just wrap `this.onValidate` in correct `if` (that from `onChange`). Do you want to create a PR for that?

**Comment by macrozone** [comment]
YOU - ARE - AWESOME!

many thanks @radekmie ! Works like a charm *_*

Btw. I created i18n_service for mantra that wraps meteor-universe-i18n and provides some convenience functions for mantra-apps. It's still rough, but works perferctly so far and i like to share:

https://gist.github.com/macrozone/f1ab1bf6f205f5bfb7518bac0d2854d5

It's meant to be initalized in the context in mantra app. 

It has a function translateSchema, that translates a simpleSchema. It's meant to be used in a container:

```

export const composer = ({context}, onData) => {
  const { SimpleSchema, i18n } = context();
    const registerSchema = i18n.translateSchema(
      new SimpleSchema({
         email: {
           type: String
        },
        password: {
           type: String
        },
        language: {
            type: String,
            allowedValues: [ 'de', 'fr', 'it', 'en']
        }
      } ]), 'register'
    );
    onData(null, {registerSchema });
};

```

Then in your locale-yamls:

```
register:
  email: Your email
  password: Your password
  language:
     label: Your preffered language
     de: German
     fr: French
     it: Italian
     en: English
```

Without this PR here, the form would validate on every language change. Now you can change locale even in the middle of filling out a form :-)

**Comment by radekmie** [comment]
Wow, just wow!
I haven't played a lot with mantra yet, but translating form during filling is a great feature!

And as to i18n - if you like, go ahead, create an PR - we'll see, if it makes sense to create a separate package. Looking forward your progress!
