### ISSUE TITLE
[Question] DisplayIf does not work inside ListField

### ISSUE THREAD

**Issue by jkinley** [vazco/uniforms#823]
Hi all, I am stuck on something and I tried using the Gitter board, but that does not seem to be very active. I am sure this issue is my lack of understanding, but I am stuck nonetheless.

I am trying to use DisplayIf inside a ListField, but it stops working. Outside of the ListField it works perfectly.

```
<ListField name="additionalFields" initialCount={1}>
	<ListItemField name={'$'}> 
	    <TextField name="name" />
	    <TextField name="type" />
	    <DisplayIf condition={context => context.model.type === "select"}>
		<TextField name="options" />
      	   </DisplayIf>
	</ListItemField>
</ListField>

```

I am using the same function as in the docs: 

```
  // make sure only one child; can't return array from a component.
	function DisplayIf<T = any>({ children, condition }: DisplayIfProps<T>) {
		const uniforms = useForm<T>();
		return condition(uniforms) ? Children.only(children) : null;
	}

```

I am fairly certain that the scope has changed, but I am not sure how to fix it. Any ideas, would be greatly appreciated.

**Comment by jkinley** [comment]
Hi All, I figured out some solutions to this and thought that I would post so that it might help others. This stuff is not always clearly documented, so I hope some of this eventually gets added. So here are two options:

1: ) Just use AutoForm and the layout engine works it out. Pretty incredible really. I thought for sure using the nested schema that I would have to manually writeout the JSX.

2. ) If you want more control, you can manually write the JSX out as I did above. However, you will have to pay attention to the CSS and make sure you are adding elements where needed. For example: 

```
<AutoForm schema={schema} onSubmit={test}>
	<TextField name="nameDefault" />
		<AutoField name="typeDefault" />

		<ListField name="additionalFields" initialCount={1}>
			<ListItemField name={'$'}>
				<div style={{width: '100%'}}>
					<TextField name="name"  />
					<TextField name="type" />
				</div>
			</ListItemField>
		</ListField>

	<ErrorsField />
	<SubmitField />
</AutoForm>

```

**Comment by radekmie** [comment]
Hi @jkinley. Your code is _correct_ but does something different than you may expect (I guess). Your condition (`context.model.type === 'select'`) checks, if the **top level** field `type` has a certain value. Based on the rest of the code, I assume you wanted to check the **adjacent** field `type` instead. Now, to do that, you'd have to know, which one is it - this array may have mutliple elements. To do that, you could use `context.name`:

```tsx
<ListField name="additionalFields" initialCount={1}>
  <ListItemField name="$">
    <TextField name="name" />
    <TextField name="type" />
    <DisplayIf condition={context => get(context.model, joinName(context.name, 'type')) === 'select'}>
      <TextField name="options" />
    </DisplayIf>
  </ListItemField>
</ListField>
```

The path stored in `context.name` will know about parent fields, but most importantly, array index. Here I added the `type` to it, so it means _value of `type` field "here"_.

**Comment by jkinley** [comment]
Thank you. I have tried this, but getting errors on 'get' and 'joinName'. Am I missing an import? Hmmm.

**Comment by jkinley** [comment]
Hi! Thanks. I found the uniforms helper joinName, but not sure where the get() method comes from.

**Comment by radekmie** [comment]
Ah, I forgot that:
```tsx
import get from 'lodash/get';
import { joinName } from 'uniforms';
```

**Comment by jkinley** [comment]
thanks!
