### ISSUE TITLE
Allow displaying only submit errors in ErrorsField

### ISSUE THREAD

**Issue by Floriferous** [vazco/uniforms#826]
When you use `ErrorsField`, it displays all the errors in the form. This can be a mix of inline/field-level errors, and the errors from the server on submit.

If you decide to show the errors inline, you usually don't want them to be displayed a second time at the bottom of the form.

I'd imagine the API to be something like this:

```jsx
<ErrorsField showInlineError={false} />
<ErrorsField showSubmitErrorsOnly />
```

**Comment by radekmie** [comment]
Hi @Floriferous. I know where that need is coming from but after I looked into the code, it seems that it may be the case that it's not needed at all. The thing is, that all bridges implement `getErrorMessages` **only** for `ErrorsField` to work. That means, one could override `getErrorMessages` to ignore validation errors (e.g. get rid of [this branch for `SimpleSchema2Bridge`](https://github.com/vazco/uniforms/blob/609bc4db78edba6795fde467b068df3df4969d52/packages/uniforms-bridge-simple-schema-2/src/SimpleSchema2Bridge.ts#L30-L36)). Let me know what you think.

**Comment by radekmie** [comment]
As it's already possible to implement this without hacks nor extra API surface, I consider this one closed. Feel free to comment anyway.
