### ISSUE TITLE
Allow passing showInlineError to AutoFields component

### ISSUE THREAD

**Issue by Floriferous** [vazco/uniforms#827]
I would expect to be able to set `showInlineError` on the `AutoFields` component, and have it pass down to each `AutoField`, just like you can do this with `showInlineError` on the `AutoForm` component.

There might be other props like this that you can set on `AutoForm`, but not on `AutoFields`?

**Comment by radekmie** [comment]
Hi @Floriferous. I'd like to know your exact use case because I have never had a situation, where I'd like to do that. I always enable it for the whole form or for a single field. Also, would it make sense to accept all other props instead?

**Comment by Floriferous** [comment]
Yeah, for me it's just a question of DX, making the uniforms API a bit more forgiving. 

Indeed, passing all the relevant props down on AutoForm and AutoFields would be great.
