### ISSUE TITLE
Custom errors are not displayed

### ISSUE THREAD

**Issue by serkandurusoy** [vazco/uniforms#83]
Using the following schema:

```js
new SimpleSchema({
  startDate: {
    type: Date,
    optional: true,
    custom: function() {
      const dueDate = this.field('dueDate');
      if (dueDate.isSet && !this.isSet) {
        return 'required'
      }
    }
  },
  dueDate: {
    type: Date,
    optional: true,
    custom: function() {
      const startDate = this.field('startDate');
      if (startDate.isSet) {
        if (!this.isSet) {
          return 'required'
        } else {
          const dueDateIsBeforeStartDate = moment(this.value).isSameOrBefore(moment(startDate.value));
          if (dueDateIsBeforeStartDate) {
            return 'dueDateIsBeforeStartDate'
          }
        }
      }
    }
  },
})
```

The custom errors are not displayed when the `dueDate` is left empty while there is a `startDate`, but the browser console shows the following error:

![image](https://cloud.githubusercontent.com/assets/4649948/17093817/26ac1df4-5254-11e6-9113-8b498828cded.png)

**Comment by radekmie** [comment]
How do you display those errors (I don't really know, how are they not displayed)?

---

Yes, this is known error - I've added it to the [troubleshooting section in the README](https://github.com/vazco/uniforms#troubleshooting).

**Comment by serkandurusoy** [comment]
OMG right, I'm not displaying the errors in that particular component, duh!

Thanks for the pointer to the readme. Is that something that the library can mitigate behind the scenes?

**Comment by radekmie** [comment]
I've tried, but chrome seems to be overprotective (again - #80).

**Comment by serkandurusoy** [comment]
oh...

**Comment by radekmie** [comment]
I thought about some "internal handling" but I don't have that much time right now (it's not a bug, but just an annoying thing) - if you want (anybody?) - I'll surely accept a PR for it.

**Comment by serkandurusoy** [comment]
Just to clarify it, since this is an event handler on the window, can we
not just have it on the baseform?

register the handler within componentDidMount and then dismiss it with
componentWillUnmount?

https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/components/forms/BaseForm.js#L12


On Mon, Jul 25, 2016 at 11:00 AM, Radosław Miernik <notifications@github.com

**Comment by radekmie** [comment]
Yes, we can do it, but it will hide all other `Uncaught ...` errors.

**Comment by serkandurusoy** [comment]
Hm, that means the readme is basically misleading people to hide all such
errors! I thinki the first thing we need to do is explain that on the
readme.

Moving on, do you think
https://developer.mozilla.org/en-US/docs/Web/API/PromiseRejectionEvent/promise
would help us identify the root cause of the error as belonging to uniforms?


On Mon, Jul 25, 2016 at 11:21 AM, Radosław Miernik <notifications@github.com

**Comment by radekmie** [comment]
If only we could "mark" these promises... I'll get to it later - meanwhile, any suggestions (and PR for clarify in README) are welcome.

**Comment by serkandurusoy** [comment]
Hm, I could not find anything in the promise object that could identify it as belonging to uniforms.

Marking would be a good idea, but that would require us to change the returned error... Hmm...

Can we change [this](https://github.com/vazco/uniforms/blob/22e50917e12fdb9b8d33c70b6d0458727f615687/packages/uniforms/src/components/forms/ValidatedForm.js#L138)

from 

```js
this.setState({error: catched}, () => catched ? reject(catched) : resolve());
```

to 

```js
this.setState({error: catched}, () => catched ? reject({...catched, uniformsPromiseError: true}) : resolve());
```

and then on the event handler that we set up on BaseForm, we can do:

```js
window.addEventListener('unhandledrejection', event => {
  if (event.reason.uniformsPromiseError) {
    event.preventDefault();
  }
});
```

What do you think?

**Comment by radekmie** [comment]
It would work, but... [Error don't have to be an object](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/components/forms/BaseForm.js#L47). It may sound weird, but it's an serious usecase.

**Comment by radekmie** [comment]
Also, spread operator strips prototype.

**Comment by serkandurusoy** [comment]
Oh yeah spread, ok that's easy. What about the error, do you know a case
where it won't be an error? and if it is not, what can it be? We could sure
check for the type and act accordingly!

On Mon, Jul 25, 2016 at 11:57 AM, Radosław Miernik <notifications@github.com

**Comment by radekmie** [comment]
We have such situation - error is simply an error code (a `Number`). Even so, it wouldn't be hard to change it.
