### ISSUE TITLE
Pass Semantic UI Form Props through Uniforms Components

### ISSUE THREAD

**Issue by niklasdahlheimer** [vazco/uniforms#838]
Hey guys,

What would be the best way to pass Semantic UI Form props like `size`, `widths`, `inverted`  (see [here](https://react.semantic-ui.com/collections/form/)) through the Autoform components to the underlying Semantic UI components? Is this only possible via custom themes? I had no luck with something like this:

```
<AutoForm ref={ref => fRef = ref} schema={bridge} onSubmit={data => handleSubmit(data, fRef)}>
   <Segment>
      <Form.Group>
            <TextField name='firstName' size={'mini'}/> <--- try to pass semantic UI prop "size" to Autoform component
            <TextField name='lastName'/>
      </Form.Group>
      <ListField name="addresses">
         <ListItemField name="$">
            <FormGroup>
               <AutoField name="street"/>
               <AutoField name="zip"/>
            </FormGroup>
         </ListItemField>
      </ListField>
      <SubmitField value='Submit'/>
      <ErrorsField/>
   </Segment>
</AutoForm>
```

I did not find anything in the doc about this, so I would be happy for recommendations here :)

Greetings

**Comment by radekmie** [comment]
Hi @niklasdahlheimer. That's correct, none of these props are supported. And as we are not using Semantic UI React (check [`TextField`](https://github.com/vazco/uniforms/blob/291c6c1e8d9952009590dcae2c94bd231c7fb9f2/packages/uniforms-semantic/src/TextField.tsx#L40-L74) source), we'd have to implement these ourselves. It'd probably be easy, as most of those should result in a different HTML class in the end. If you need those, feel free to create a PR with these changes or file a feature request - short description and a link to here areenough.
