### ISSUE TITLE
GraphQL field validation

### ISSUE THREAD

**Issue by pprathameshmore** [vazco/uniforms#840]
I have GraphQL schemas

```
type slackTeam {
    assetId: String!
    assetType: String!
    type : String!
    name : String!
    displayName: String!
    summary : String!
    description: String!
    classification: String!
    criticality: Int!
    risk: Int!
    trust: Int!
    complianceStatus: Int!
    status: String!
    expiresOn: String!
    webLink: String!
    owner: String!
    address: String!
    notes: String!
    deleted: Boolean!
    specialFields : SpecialFields!
}

type SpecialFields { teamId: String! teamName: String! appId: String! }
```

I am trying to render UI using AutoForm, here, all fields are common except specialFields. specialFields changes for every type. 
Also implemented validation on common fields, but I didn't get any idea how I can validate specialFields.

Please any documentation for this? or if any suggestion would be helpful.

Thanks.

**Comment by radekmie** [comment]
Hi @pprathameshmore. I don't really understand your problem. What do you mean that these fields are _common_? The type itself looks correct and correctly renders using `AutoForm` ([playground](https://uniforms.tools/playground/#?N4IgDgTgpgzlAuIBcICCATd0YwAQAoBxCAQzAAsBFAGQEoQAacCAezBmVBIFd4WYSANyjIAZiQA2cJjz4DhAESgSSAT2QBGAAxam6AJYCARhKjoxk6SBVHlyeBG5QmYFQGMo5FhPRQIFqWcQGDdyKABbEmQQADsoAHdcYjIqagAhCH10AHMofAAdGNxcI259H1QAZQAVStCIkgKi4twwEgg4fAADQpaW-FUwKFwYdwBraqgScNxgXr6FkhwEAEl0JFxKh30Y7IBCeYWWpbh4asGoDa3M3YPmo-KBodwr7dvDh5jp4deb_Y-jgYYK41AA5b6_Hb_e4PGDccKRCCqF6bN7Qh4tXwhTJgeD6FgxSHvGFHNwqHD6UT6NwkPEEonojG4NyZPE0iT6AYbFYxeB3Jm4TIwMbc3n8pkObgweCivkAhZuFjhVz6EgxDxbWlS2XijHSrUwBm6h5QAAeYH02AA8oTUX9jUd4lAjNQdiK7VCHQsWPE4hAjfK-iRMNhDR7iQKYix4LAAySFr5TDH1rg0ixvFMYl6-sCoG5VRIAGL6ZToPBXIb5yTF0swL0AX0K8qew0qlYLNZ8eGAuBj0zWRt7U3C4PCl3D-1wZDAA4ne1wjZi8oAxLhquRDLhN9AAI5laDoErI0rldBVWr1SLNi64ShOJGzKcxVTwDe7bkKBcfLq0ea0AB0uRnBc-AAOSjCQbgTMOoG0Aw8yiNw6p0kU-DhCwia0LMHyKjE0q4L48AkOUeAALy4AA2gAugA3B8lIEHs6GJv--oxr-8aEcRUj_mAUrkPgPZfGOGzgURMagQwuBjjgJC5KJmoxlueC7vuZh7KBC60HRMIMfgTEYcorEOFACAcYCCDcTAvH8YJuDCeOYnQAgknSbAAjybgoHXKZ8DKYKUB7pa6mafW2n0aIjHMUZABe-hgOZCaWSRNkwAJQkQl5cVgK5MkeY5ABa8X-apwXoBpWk6X0enRRI_75gMuAAGRNdJhl1Q1qj_qYuyvrgAB8uAAKxaIlfRcSlfFpXZDmiZ1uXuXJjkAMKcsiNJFLYU5-aYSx-SNzLkO0kExh0uASAS-yheFumRWh7XGc5fktW1LHSk93VQL15ADbg2ijfKE08VN6X2ZlTm-Qtsmed5JkIMyaolMMtLnVM-H_Ydx1uKdeAXbc11VS0NUPdlzWtXsAD0AB6FFaAAtAAnFRwBDfWAAkFP_jG0r3Sx2W0GNmLJcDtkZSJWXxVD-WiUVYAESwsD2dG0m0qEvZhAF2TcCoEC4GakDufiWYExFBBA9ZPXZK-gvFNA8DcBARQ9ubC6E_W8HND22UbD2NjKDLxWKr4oVfjE9BMGlPo8hycQAKIQKw_hIOIgQyDAqjqjalTcEY4ScgEVhLBnbg2gAapIWS0iIyeWFA7sgK-ETV8EDS8tSID1kAA)). When it comes to validation, it's completely up to you. You can either write your own code to do that or use an additional tool, like JSON Schema or Yup.

**Comment by pprathameshmore** [comment]
I got it. I have to implement code for the validation of special fields.
