### ISSUE TITLE
tree shaking and  "sideEffects": false ?

### ISSUE THREAD

**Issue by macrozone** [vazco/uniforms#843]
i use uniforms on https://github.com/react-page/react-page to generate forms and i wanted to re-export the bundled uniforms version (using something like `export * from 'uniforms-material'`).

i noticed that this will bundle everything in, even if you don't use any of the re-exports.

I think this is because uniform packages do not declare ` "sideEffects": false`, see https://webpack.js.org/guides/tree-shaking/

i think its quite safe to set that, altough there might actually be some sideeffects (i remember that uniforms extended simpl-schema automatically in some versions, that would be a side effect. not sure if its still the case).

**Comment by radekmie** [comment]
Hi @macrozone. Yes, none of the packages actually declare `sideEffects: false`. I also thought about it some time ago, and, as you said, it'd be fine for most packages. There are three exceptions:
* [`uniforms-bridge-simple-schema`](https://github.com/vazco/uniforms/blob/bbc4fcf7e33aa80fc3bf0ae6ae598d6d6f8d1ba4/packages/uniforms-bridge-simple-schema/src/register.ts#L41-L57) and [`uniforms-bridge-simple-schema-2`](https://github.com/vazco/uniforms/blob/bbc4fcf7e33aa80fc3bf0ae6ae598d6d6f8d1ba4/packages/uniforms-bridge-simple-schema-2/src/register.ts#L28-L44) use `filterDOMProps.register` to register their options. There's no need for tree shaking of this package though, as these consist basically two files - the bridge itself and this props registration (our side effects),
* [`uniforms-antd`](https://github.com/vazco/uniforms/blob/bbc4fcf7e33aa80fc3bf0ae6ae598d6d6f8d1ba4/packages/uniforms-antd/src/wrapField.tsx#L84-L92) do the same, to simplify other fields in the theme.

The only _problem_ is that I think that _almost_ none of the projects would benefit from that. The majority of projects use `AutoForm` which will include all other components. At most, one could eliminate `AutoForm` and one or two components (e.g. `AutoFields`). Do you think it's worth to do that, having in mind potential problems?

**Comment by macrozone** [comment]
@radekmie the problem that i had is that

if my library A re-exports library B,
any consumer that include something from A will have B automatically fully bundled, even if no re-export of B is used by the consumer, because the bundler cannot tree-shake B away as it might contain side effects.

My workaround was to not re-export uniforms-material directly, but to only export the Components that i needed as exports as lazy-load components (using something like @loadable/component

i think its worth for the different edge cases. 

E.g. consider a project using nextjs, where *some* pages use uniforms and some don't. Maybe in some pages you just import some types (without the special `import type`) or helper functions. these pages will have the full uniforms bundled into even if they just use some part of it.

On a side note, i think tree shaking allows libraries to use more complex libraries without declaring them as peer-dependencies (i think peer dependencies are often bad)

**Comment by mariusrak** [comment]
This change introduced a bug as I am getting error
```
Invalid definition for name field: "uniforms" is not a supported property
```
After downgrade to 3.1.0 it work correctly. I am using webpack, babel and babel preset-env to build app.
