### ISSUE TITLE
antd list error not styled

### ISSUE THREAD

**Issue by oprobst-ethz** [vazco/uniforms#844]
Hi

Thanks for this awesome package - I really like it and use it every day :-)

I've just figured out, that an error in a list is not styled when using antd. 

Steps to reproduce:

1. go to the playground, choose antd.
2. copy paste the following code for the schema and test.

```
new SimpleSchema2Bridge(
  new SimpleSchema({
    date: { type: Date, defaultValue: new Date() },
    adult: Boolean,
    size: {
      type: String,
      defaultValue: 'm',
      allowedValues: ['xs', 's', 'm', 'l', 'xl'],
    },
    rating: {
      type: Number,
      allowedValues: [1, 2, 3, 4, 5],
      uniforms: { checkboxes: true },
    },
    friends: { type: Array, minCount: 0, optional: true, custom() {
        if (true) {
          if (this.isSet) {
            return undefined;
          }
          return SimpleSchema.ErrorTypes.REQUIRED;
        }
        return undefined;
      }, },
    'friends.$': Object,
    'friends.$.name': { type: String, min: 3 },
    'friends.$.age': { type: Number, min: 0, max: 150 },
  })
)
```

Maybe I am doing something wrong, but I think it should be styled.

Thanks so much.
Regards,
Oliver

**Comment by radekmie** [comment]
Hi @oprobst-ethz. Could you elaborate on what do you mean by _styled_? The `name` and `age` fields are highlighted in red when missing.

**Comment by oprobst-ethz** [comment]
Hi @radekmie 
Sure. I've just recognised that "Show inline error" must be selected. Then in the List below "Friends" the error message is displayed in black.

Regards
Oliver

**Comment by radekmie** [comment]
Ah, it's not highlighted, when the whole array has an error... OK, I'll think about how to move from here.
