### ISSUE TITLE
Idea: Flexible component mapping

### ISSUE THREAD

**Issue by macrozone** [vazco/uniforms#85]
You can currently implement your own AutoField and do whatever you want there, which is nice. You can also define a property universe.component to pass a react-component directly.

However, if you want to share schemas between server and client, you usually put the schemas in a shared location. But importing components there looks like the wrong place (it's also not possible if your componets resides in /client).

One solution is to simply extend the schema in a container, where you add the universe.component-property, but there is a better solution:

Having something like a mapping function, that can be provided to Autoforms or Autofields would be a good solution:

```
import {connectField, defaultComponentMapping}  from 'uniforms';
import {createElement} from 'react';

const Auto = ({component = null, componentMapping = defaultComponentMapping, ...props}) => {
    if (!component) {
       component = componentMapping(props);
    }
    return createElement(component, props);
};

export default connectField(Auto, {includeInChain: false});
```

( i sketched the above code here, so it may contain errors)

`defaultComponentMapping` could be what we currently have in the AutoField (switch on props.fieldType, etc.)

You could then introduce your own properties on the schema, e.g. simply allow component to be a string:

```
export default new SimpleSchema({
   file: {
      type: String, // will be an url, .e.g from slingshot
      uniforms: {
        component: "SlingshotFileUploadField" // why not allow strings as well and map somewhere else the real component
      }
   }
});
```

and in your mappingFunction (somewhere in your client where its fine to import Components):

```
const myMappingFunction = (props) => {
   switch(props.component) {
     case 'TextField': return MyTextField;
     (...)
    case 'SlingshotFileUploadField': return SlingshotFileUploadField
    default: return defaultComponentMapping(props);
  }
}
```

Thoughts?

**Comment by radekmie** [comment]
I don't know, if this suits your needs, but [there's `autoField` prop on `QuickForm`](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/components/forms/QuickForm.js#L46) (and so `AutoForm`) - you can use it like this:

```js
const CustomAuto = props => {
    const Component = myMappingFunction(props) || AutoField;

    return (
        <Component {...props} />
    );
};

const CustomAutoField = connectField(CustomAuto, {includeInChain: false});

// Then...

<AutoForm schema={schema} autoField={CustomAutoField} />
```

**Comment by macrozone** [comment]
Yes, this also looks good. 

Maybe we put that pattern in the readme?

**Comment by radekmie** [comment]
Yes, README is still _under heavy development_. I don't have much spare time right now - either create a PR or give me some time.

**Comment by radekmie** [comment]
[Custom `AutoField`](https://github.com/vazco/uniforms#custom-autofield)
Would you be my reviewer, @macrozone?
