### ISSUE TITLE
Material: GraphQL type Boolean! (non nullable bool) combined with noValidate={false} (using browser's validation) makes checkbox required = you have to set the checkbox to 'true'

### ISSUE THREAD

**Issue by al222cv** [vazco/uniforms#850]
Hi and thanks for a cool project. 

This bug is for `uniforms-material`

When using` noValidate={false}` on the `AutoForm `(which will use the browser's validation), combined with GraphQL type `Boolean!` (non nullable boolean) makes the checkbox required, which means you have to click the checkbox and set the value to `true`. 

_I think this is wrong_, you should still be able to have a `false` value, just not `null`. 
https://stackoverflow.com/questions/57013591/can-we-return-null-for-a-boolean-value-in-graphql-response#:~:text=To%20declare%20a%20type%20that,type%20or%20an%20object%20type.

To test for your self, submit the form without checking the checkbox:
https://codesandbox.io/s/uniforms-codesandbox-forked-ep23q?file=/src/schema/graphql-schema/index.js

Couldn't figure out where in the code this i done, otherwise I could made a PR

**Comment by radekmie** [comment]
Hi @al222cv. You could add `{ isAwesome: { required: false } }` to your bridge (3rd parameter) to make it optional for uniforms alone. While this allows submitting unchecked checkbox, it also hides `required` styling (e.g., a red star in `uniforms-semantic`), but this seems fine, as it's not supposed to be required anyway. Let us know, whether it works for you.

**Comment by al222cv** [comment]
@radekmie Aha thanks for the answer. It works perfectly, so not an issue anymore. :)
