### ISSUE TITLE
uniforms-material: LongTextField doesn't look right

### ISSUE THREAD

**Issue by bennycode** [vazco/uniforms#854]
I am using `uniforms` with `uniforms-material` and I like it very much!

However, I experienced that the `LongTextField` component doesn't render properly. This can be seen on the demo page: https://uniforms.tools/docs/tutorials-using-predefined-fields#2-manipulating-the-schema

**Screenshot**

![image](https://user-images.githubusercontent.com/469989/104560600-63fa9c80-5646-11eb-99de-ce98160bfe07.png)

**Comment by radekmie** [comment]
Hi @bennycode. Is it actually rendering incorrectly in your app as well? I see that [it's incorrectly importing `uniforms-unstlyed`](https://github.com/vazco/uniforms/blob/c6748de4f87536440f05024e4d826b64e27d1d73/website/pages-parts/Tutorial/GuestSchema3.ts#L3) for all themes, but it's only in the docs.

**Comment by bennycode** [comment]
Happy it's just in the docs!

In my application it looks fine when pasting a lot of data. But in the beginning it just looks like a regular text field:

**Without Text:**

![image](https://user-images.githubusercontent.com/469989/104563169-9b1e7d00-5649-11eb-9b19-9056187c5448.png)

**With Text:**

![image](https://user-images.githubusercontent.com/469989/104563241-b25d6a80-5649-11eb-867f-fbe2c77181a5.png)

I am using:

- "uniforms": "3.0.0-rc.8",
- "uniforms-bridge-json-schema": "3.0.0-rc.8",
- "uniforms-material": "3.0.0-rc.8",

**Comment by radekmie** [comment]
That's correct - the only difference is the [`multiline` prop](https://material-ui.com/components/text-fields/#multiline) (we are not using [`TextareaAutosize`](https://material-ui.com/components/textarea-autosize/)).

**Comment by bennycode** [comment]
Ah, thanks for the info! All good then. Keep up the great work! Uniforms simplifies a lot for me during my day-to-day work. 😊
