### ISSUE TITLE
uniforms-material's NumField is missing step prop

### ISSUE THREAD

**Issue by xormik** [vazco/uniforms#855]
https://github.com/vazco/uniforms/blob/master/packages/uniforms-material/src/NumField.tsx#L35

[Docs suggest it's available in all UI frameworks](https://uniforms.tools/docs/api-fields#numfield), and it looks like it's in all of them except uniforms-material.

**Comment by radekmie** [comment]
Hi @xormik. Yep, that's a bug. Thanks for the report!
