### ISSUE TITLE
NumField with default value should allow clearing field before entering new value

### ISSUE THREAD

**Issue by xormik** [vazco/uniforms#856]
In the NumField component, when a default value exists, it can't be cleared out, but this should be allowed. E.g. When backspacing the last digit left, the value is replaced with the default value. This happens in all the components except in the uniforms-antd component, where the onChange handler is different.
[uniforms-antd's onChange](https://github.com/vazco/uniforms/blob/master/packages/uniforms-antd/src/NumField.tsx#L24)
[uniforms-material's onChange](https://github.com/vazco/uniforms/blob/master/packages/uniforms-material/src/NumField.tsx#L39)

In this [playground example](https://uniforms.tools/playground#?N4IgDgTgpgzlAuIBcICCATd0YwAQAoApAZQHkA5YgYwAsoBbAQwEoQAacCAezBmVEYBXeFxiMAblGQAzRgBs4HISLGSAIlDmMAnsgCMABgMd0ASzEAjOVHQz5ikFoubk8CIKgcwWqlBpc5dCgIOwVPEBhaBkZkEHx8ZlwAXgA-XGAAHQA7XFwqLiyYeFxGACtxZNwsqAB3XFRy_GASuTkAUQhuCBgkXDcPNlxBOA1ZQTl4Hr73KFwAX2YAbmzc_MLiyLomSsyc3L7TeGtegHJyQXpnCBO2Ff34bTAoU64LUqgqeBu73MgeYPgplgvV2-32WQuVxBfUez1wJwhl2CN1wQTGE16ACZ5rc9rk5rj8cssndpIIsp9TAU8tBGPAoAA1eSmdB0rgQfCbaKJUH7NZFXDiZmskQQSplcQAOny9DApmsnKiTCW2R-uGg8EEEBy-HoXCCckSqXSatyQrkLLZHL1BpVJLx-1M0gI5stoslwS6eAAZN7BcKrR7OuyYJLrFkAObwGg8037DVanLNILwRjyqaukXsoNe-bEsH4tVzfPzVV7fkbJWMJkWrNipI0qB0xkB0WKrYsYl3BPaqq1XAkCjUDsAIQgLIjUHb0UGXKYNbd7LtCwS7Ai_hqAEkshbqh0uqEHIwYNoKaQssRBBZ6IdD-Fj6eqOeFyKpEhZGECSBoww3yAmPS47yCAcxAA), try to backspace the 2 to change it to another number.

**Comment by radekmie** [comment]
Hi @xormik. It's mostly because AntD has a custom `InputNumber` component that works differently from `<input type="number" />`. I do agree that it is a problem though. Another thing is that if you remove the value from using the AntD theme the value becomes `''` (and `null` on blur), which leads to _should be number_ error. Thanks for the report!
