### ISSUE TITLE
uniforms@3.0.0 has incorrect React peer dependency

### ISSUE THREAD

**Issue by bennycode** [vazco/uniforms#859]
I am using "uniforms" 3.0.0 with "react" 17.0.1 but when installing uniforms I am receiving this error:

> uniforms@3.0.0" has incorrect peer dependency "react@^16.8.0"

Are there any known incompatibilities with React v17? Because for me it is running fine.

**Comment by radekmie** [comment]
Hi @bennycode! No, I don't think there are any problems with using `react@17` other than our `peerDependency` version. It's already on our radar, but thanks for the issue.

**Comment by radekmie** [comment]
Due to https://github.com/facebook/docusaurus/issues/4165 we'll have to postpone this one as 3.1 will be released today.
