### ISSUE TITLE
Solution for error in validation of optional array fields

### ISSUE THREAD

**Issue by niklasdahlheimer** [vazco/uniforms#860]
**TLTR: I solved this already but thought I post this if anyone else will be looking for a solution here.**

In my form I needed an array of fields with the following behaviour:

- zero or more entries are allowed (=> optional)
- when one or more entries added, they objects inside the array need to be valid
- I need to do the State Management myself, because I have additional logic to do (i.e. allow only one entry to have a certrain value in the "isDefault field), that why I'm using the ValidatedForm and not AutoForm.

Saving changes to the model in the "ordinary" way
```
const [model, setModel] = useState( {} );

const onFormChange = (key,value) => {
   setModel({...model, [key]: value});
};
```

**doesn't** work because adding array fields with `ListAddField ` will add empty array entries (i.e. key: `myArray`, value `[{},{}]`) to the model and adding content to the fields will add keys with dot-notiation (i.e. key: `myArray.myField` value `blabla`). Validation of the form will fail after the first click on the `ListAddField `, because the arrays are empty.

So you need to use a function from the lodash library like AutoFrom uses: 

```
 const onFormChange = (key, value) => {
    const newModel = _.setWith(_.clone(model),key,value,_.clone)
    setModel(newModel);
  };
```
which parses the key-path back to a "nested array attribute" before updating the model.

Hope this saves someone the evening that I spend solving this :D

Sandbox to play around with this issue:
[Sandbox](https://codesandbox.io/s/uniforms-array-validation-issue-lqio1?file=/index.js)

**Comment by radekmie** [comment]
Hi @niklasdahlheimer. I'm glad you've figured it out! I don't really get the reason why you'd have to do that. Wouldn't a custom validation or a specialized `ListField` (maybe a wrapper) be enough?
