### ISSUE TITLE
uniforms-antD: Provide option to display form element and label horizontally 

### ISSUE THREAD

**Issue by karthik-hr** [vazco/uniforms#861]
https://github.com/vazco/uniforms/blob/master/packages/uniforms-antd/src/BaseForm.tsx#L15

Want to replace className `ant-form-vertical` with `ant-form-horizontal` using props

**Comment by radekmie** [comment]
Hi @karthik-hr. Yes, it's not possible now without overriding `getNativeFormProps` method and it should. Thanks for the feature request!
