### ISSUE TITLE
Question: inline errors for custom fields.

### ISSUE THREAD

**Issue by afmfe-iul** [vazco/uniforms#864]
Hey!
I've looked at the documentation and other issues related to inline errors here and I'm having a hard time finding the right way to build my custom components (some of them don't use any of the `uniforms-semantic` components, eg `AutoField`, etc) in a way that uniforms is still able to automatically inject the inline errors components after validating the form.
Is there any resource on this subject that you can direct me to?

**Comment by radekmie** [comment]
Hi @afmfe-iul. I guess you'd like to support `showInlineError` within your custom fields, is it correct? If so, your custom fields should [use the `error`, `errorMessage`, and `showInlineError` props to do so](https://github.com/vazco/uniforms/blob/26ecd38d3aecdd540a000e817c9108a777de8972/packages/uniforms-semantic/src/TextField.tsx#L71-L73). Everything else is managed for you, through `connectField`/`useField`.

**Comment by afmfe-iul** [comment]
@radekmie That's exactly what I was looking for, thanks a lot! :)
