### ISSUE TITLE
ListItemField: Removing Default 'col-1' 

### ISSUE THREAD

**Issue by LordA98** [vazco/uniforms#868]
Hi,

Is there an easy way to remove the default 'col-1' from the ListItemField?

It seems to be used the default removeIcon placement but if I want to add a custom remove icon with ListDelField, the 'col-1' remains on the far left.

Is there any way to control it?  Either remove it entirely or change the columns?

Thanks,
Alex

**Comment by radekmie** [comment]
Hi @LordA98. I guess you are using the `uniforms-bootstrap4` theme, right? If so, no, there's no way to configure it. How exactly you'd like it to be configurable?

**Comment by LordA98** [comment]
Hi @radekmie, 

Sorry, yes, I'm using the `uniforms-bootstrap4` theme.  

I'd like the ability to control the default col (that is currently always `col-1`).  So, I'd like the ability to make it `col-0` or `col-X` if needed.

My custom <Delete /> component is slightly bigger than the `col-1` width.  It's also being used in a modal, which also makes the columns smaller.  I had been using the ListDelField instead, as that provided the required space for my <Delete /> component.  

However, the default col-1 is still there.  It would be great if there was more control over the column sizing for the default `col-1`.   If that makes sense?

At a stretch, it would also be good if there was a prop to control which side the removeIcon (or its corresponding col) were rendered on.  I think Bootstrap offers the 'order-' classes?  

I'd be happy to take a look into it?

**Comment by radekmie** [comment]
Yes, so the thing is that most of the `ListField` usages do not touch the `ListItemField` at all. On the other hand, using the whole `grid` property (including `xs`/`sm`/etc.) would make more sense. I'd say, let's discuss how the API surface would look like (which components would receive additional props, etc.).

In the meantime, you could easily create a custom `ListItemField` and use it with your `ListField`.

**Comment by LordA98** [comment]
Okay cool, thanks.   Yeah, I'll create a custom ListItemField for now.

**Comment by radekmie** [comment]
I'll close this one, as it seems there's not much interest in such a feature. If you'll have an idea for the API, we'll simply reopen it.
