### ISSUE TITLE
`showInlineError` for whole form

### ISSUE THREAD

**Issue by RSchwan** [vazco/uniforms#87]
I just have seen this pull request #84 and I think this is a really useful feature.
The only problem I see with it is that you have to add the `showInlineError` property to all fields manually. I think it would be great if you could set this prop on per example the  `AutoForm` component so that automatically all fields show a inline error.
Of course it would be possible to override it manually on a field.

What do you think?

**Comment by radekmie** [comment]
Yes, I've even started working on this (locally). At first, I thought about renaming it to `inlineErrors`, then ensure it is implemented in every package (I'm not sure, how to display it in `uniforms-unstyled`) and then allow `BaseForm` to pass this prop down (same as `disabled`).

**Comment by vladejs** [comment]
Have this been implemented? It doesn't work in my forms either with `showInlineErrors` nor `inlineErrors`

**Comment by radekmie** [comment]
@vladejs
Sorry for long delay - I was on vacation. No, It's not implemented yet (to be honest, it's only a concept). As of #84, you can use `showInlineError` on every field in bootstrap3 and bootstrap4 packages.

**Comment by serkyen** [comment]
showInlineError is still not working for me. I have tried with both antd and semantic ui. 
I can see here ([uniforms tool](https://uniforms.tools/)) that it is supposed to work with both of these but it's not for me...

```
<AutoForm
  schema={schema}
  onSubmit={doc => {
   Meteor.call('contacts.insert', doc, (err,res) => {
      if (err) {
         console.error(err);
      }
    })
}}
onSubmitSuccess={() => browserHistory.replace('/contacts')}
onSubmitFailure={() => alert('Promise rejected!')}
>
<TextField showInlineError={true} name="title" placeholder/>
<TextField showInlineError={true} name="firstName" placeholder />
<TextField showInlineError={true} name="lastName" placeholder />
<ErrorsField />
<SubmitField value="Create Contact"/>
</AutoForm>
```

Upon submission, I can see the ErrorsField is outputting all the errors at the bottom, but nothing inline.

What could I be doing wrong?
