### ISSUE TITLE
New theme idea: Bootstrap 5

### ISSUE THREAD

**Issue by michael-vasyliv** [vazco/uniforms#874]
Are you going to create bootstrap 5 project? Have you started yet?

an example of uniforms-bootstrap4 in boostrap5 project
![Screenshot from 2021-02-16 16-54-51](https://user-images.githubusercontent.com/19407350/108083893-3f964380-707c-11eb-8329-f34854775c3a.png)

Small investigation about differentce between 4 and 5
1. added a new size xxl
2. removed marging bottom in form control
3. removed badge-pill https://getbootstrap.com/docs/5.0/migration/#badges-1
4. removed form-group https://getbootstrap.com/docs/5.0/migration/#forms-2
5. renamed fload-right to float-end https://getbootstrap.com/docs/5.0/migration/#utilities-1

**Comment by radekmie** [comment]
Hey @michael-vasyliv. No, there is no plan to create a Bootstrap 5 theme, as we are not using Bootstrap at all in the company. However, I encourage you to do that, based on the existing themes (probably `uniforms-bootstrap4` would be the best choice), and then file us a PR.

**Comment by michael-vasyliv** [comment]
@radekmie please check https://github.com/vazco/uniforms/pull/880

**Comment by radekmie** [comment]
@michael-vasyliv here's the plan for this theme:
* Finish the PR review.
* Merge the PR as it is.
* Release it with the next version.
* Update playground.
* Update docs.

@Monteth will take care of it.
