### ISSUE TITLE
/register in uniforms-bridge-simple-schema-2 gets tree shaken

### ISSUE THREAD

**Issue by macrozone** [vazco/uniforms#888]
I saw that sideEffects is configured in the package.json, so that /register is not tree-shaken, but i think we additionaly need to include index.js as well to the side effects as it seems that register is not executed.

**Comment by mariusrak** [comment]
I have this issue too.
It is related to https://github.com/vazco/uniforms/issues/843
I get an error
```
Invalid definition for name field: "uniforms" is not a supported property
```

**Comment by macrozone** [comment]
@mariusrak you can apply this patch:

```
diff --git a/node_modules/uniforms-bridge-simple-schema-2/package.json b/node_modules/uniforms-bridge-simple-schema-2/package.json
index 61cf65b..e6c1a9d 100644
--- a/node_modules/uniforms-bridge-simple-schema-2/package.json
+++ b/node_modules/uniforms-bridge-simple-schema-2/package.json
@@ -7,7 +7,10 @@
   "sideEffects": [
     "es5/register.js",
     "es6/register.js",
-    "src/register.ts"
+    "src/register.ts",
+    "es5/index.js",
+    "es6/index.js",
+    "src/index.ts"
   ],
   "description": "SimpleSchema 2 bridge for uniforms.",
   "repository": "https://github.com/vazco/uniforms/tree/master/packages/uniforms-bridge-simple-schema-2",
```

you can use https://www.npmjs.com/package/patch-package to apply it until its released

**Comment by radekmie** [comment]
Hi @macrozone and @mariusrak and thanks for the report. Well, I joked in https://github.com/vazco/uniforms/pull/870#issuecomment-776724231 that we'll test on production and so we did :neutral_face: Anyway, I'll prepare a fix _soon_ and we'll release it tomorrow or on Wednesday.
