### ISSUE TITLE
[QUESTION]: uniforms-material TextField component margin="dense" causes issue when trying to change size in theme's default props.

### ISSUE THREAD

**Issue by simplecommerce** [vazco/uniforms#894]
Hi,

There seems to have an issue with the `uniforms-material` package when it comes to using themes with Material-UI.

![image](https://user-images.githubusercontent.com/31987945/110172537-4b4b6f00-7dcb-11eb-8277-9768ccc23726.png)

If you look at the screenshot, in my theme, I am passing the default prop `size` to `medium` to my `TextField` component.
When using the one provided in `uniforms`, it doesn't seem to take that prop into consideration, as you can see the rest of the TextField's are all the same size except for the one that is smaller, which is the `uniform` one.

I am using their theming logic: https://material-ui.com/customization/theming/.

What is weird is changing the `variant` works.

I think the problem is here: https://github.com/vazco/uniforms/blob/master/packages/uniforms-material/src/TextField.tsx#L31

You are setting `margin="dense"` and by default its not passed and if I try to overwrite it it doesn't work since you are specifying it.

**Comment by simplecommerce** [comment]
This would probably cause an issue also, if trying to override or pass custom props.

https://github.com/vazco/uniforms/blob/master/packages/uniforms-material/src/TextField.tsx#L29

But I don't personally use this one.

**Comment by simplecommerce** [comment]
This is an issue too, https://github.com/vazco/uniforms/blob/master/packages/uniforms-material/src/TextField.tsx#L27

If I don't want to have `fullWidth` on a text field, I can't set it to false.

**Comment by radekmie** [comment]
Hi @simplecommerce. In here, all of these properties, like `fullWidth` or `margin` are, indeed, set, but the `{...filterDOMProps(props)}` _can_ override it. E.g., if you use `<TextField margin={undefined} />` you basically remove this "default". Could you try it and let us know, whether it's enough.

**Comment by simplecommerce** [comment]
@radekmie Ok I can confirm that it works when I do it using your approach, the only downside I see is that I had to manually go force the `margin` and `fullWidth` props to `undefined` in order for it to follow the theme's default settings.

The difference with this and the other props in your package, is I didn't need to force these values.

But it works!

**Comment by radekmie** [comment]
Yeah, I believe we could change the way we set defaults... Do you have experience with it? I'd want the current uniforms default to stay as they are but let people configure it globally in their apps.

**Comment by simplecommerce** [comment]
hmm, i will try to think about it, i thought it was simple but I get your point now.

**Comment by radekmie** [comment]
I'll close this issue then, but please, do let us know - anyone - if you know, how we could set these default props in a less intrusive way.
