### ISSUE TITLE
[QUESTION]: changed and changedMap behavior

### ISSUE THREAD

**Issue by simplecommerce** [vazco/uniforms#898]
Hi,

I had a question in regards to the `changed` and `changedMap` context behavior.

I noticed that these get updated whenever something changes on the form, which is great.

But the problem I see, is that it doesn't seem to indicate if the value really changed or not.

For example, I have a blank form, I want my submit field to be disabled until a value actually changes or is entered in the form, which differs from the default model.

But in the situation, if I have a blank form, type in something in the field, it tells me it changed, which is good, but if I delete it, it still tells me something changed, but in fact, in my mind, if I removed my initial changes, its back to what it was before, so it should normally tell me nothing changed.

Do you have an idea on how I could achieve this?

The reasoning behind this, is I want to prevent an end-user from submitting a form, if nothing changes, as its pointless, in my mind.

**Comment by radekmie** [comment]
Hi @simplecommerce. Both work as intended, but maybe the intention is unclear. `changed` means that the value has changed, not that it differs from the initial one. What you could do is to have a custom `SubmitField` that could receive the initial model as a prop, get the current one with `useForm` and compare it _somehow_ (`_.isEqual`, etc.).

**Comment by simplecommerce** [comment]
@radekmie good idea, thanks for your help!
