### ISSUE TITLE
Success field for form validation - wrapField(uniforms-bootstrap4)

### ISSUE THREAD

**Issue by Atanasov-A** [vazco/uniforms#899]
Hello, 

thank you very much for your project, we are already using `uniforms` in a production. 
I am using `wrapField` from `uniforms-bootstrap4`. When I validate my filled form, and there are errors in a field an error class (`'is-invalid'`)  via `props.error` is set. The invalid fields are painted with a red border and one small red icon is shown. Unfortunately, this behavior is missing for valid inputs in green. I would like to be able to show the user when his input is valid, also with the bootstrap class (`'is-valid'`). 
My idea is to adapt in `wrapField.tsx:56` these lines: 
```
                "is-invalid": error,
                "is-valid": !error && !!value,
            })}
```

Would you be interested in this feature? Thank you for considering my request.

**Comment by radekmie** [comment]
Hi @Atanasov-A. Yep, that'd make a great feature. However, I'm concerned about it being a change. Maybe we could display it only for `changed` fields? What do you think?
