### ISSUE TITLE
changing an uncontrolled input of type text to be controlled

### ISSUE THREAD

**Issue by zeroasterisk** [vazco/uniforms#90]
> Warning: Text is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components

Have you seen this?  

I'm using this from a child component, setting state up to the parent:

```
parent (state.query)
  - component
    - AutoForm onSubmit={this.props.setQuery} model={this.props.query}
```

so on first render `this.props.query = {}`

then I type into a field, submit moves it into the parent's state, passes it back down via props, and it results in `this.props.query = { name: 'foo' }`

that seems normal to me, but react seems to be complaining...

**Comment by zeroasterisk** [comment]
As expected, when I default the model with empty strings for these fields, it works fine, no complaints.

Is that a requirement?

What about non-string values, like a select number `1-10`... if I don't have a value, I don't really want to default to `0`since `0` is not allowed... ??

**Comment by radekmie** [comment]
This should be done by `initialValue` (and this small [_hack_](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/components/fields/BaseField.js#L191-L195)). Two questions:

0. Which version?
0. Is this field required in your schema?

**Comment by zeroasterisk** [comment]
1. v 1.0.0-rc.29
```
    "uniforms": "^1.0.0-rc.29",
    "uniforms-bootstrap4": "^1.0.0-rc.29",
```
2. no - this is an optional field, not in the initial document/model... then type to "set" it and we get this ugly warning.

**Comment by radekmie** [comment]
Okay, I try to investigate it but could you try it in `1.0.0-rc.28`?

**Comment by radekmie** [comment]
It was a regression in `1.0.0-rc.29` - fixed now.
