### ISSUE TITLE
Property 'selected' does not exist on <SelectField /> (uniforms-semantic)

### ISSUE THREAD

**Issue by lortschi** [vazco/uniforms#915]
I am unable to find the 'selected value' property in the docs. In usual html < select / > tag the < option selected="true" value="..." / > will display in the selectbox as first selected value at pageload.

**Comment by radekmie** [comment]
Hi @lortschi. In React, there's no need to control the `selected` property manually - it's enough to use the `value` prop on the `<select>`. In uniforms, you'd never specify the `value` neither, as it comes from the form component - it's picked from the `model`, based on the field's `name`.

**Comment by lortschi** [comment]
Sure, but unfortunately in my case the values were requested and populated from db. So I got everytime random set of option values in the select. Ok I thought it would be nice to have this feature of determing the first selected value in the selectbox.

**Comment by radekmie** [comment]
First of all, the displayed values (labels) are irrelevant - only the _true values_ matter. Second of all, it's not a problem to fetch the data and then pass it correctly down to the components.

Could you post an example, preferably using our [CodeSandbox template](https://codesandbox.io/s/github/vazco/uniforms/tree/master/reproductions)?

**Comment by lortschi** [comment]
@radekmie to pass correctly how you said the "true values" into the options is of course a problem if the SelectField component is getting async populated. Here you need then a comparisement for the value you want as first selected value after the SelectField component is finished async. Otherwise is after every pagerefresh randomly set values. I hope you can follow me how is all the things ment? Sorry can currently not post an example of this problem. No matter I did the workaround with the reference to the SelectField component and do this vanilla js attribute set to option first value selected.

**Comment by radekmie** [comment]
I'm not sure anymore, sorry. I've never had a problem with population options for `SelectField` asynchronously. Do try to prepare an example.

**Comment by radekmie** [comment]
I'm closing this one, but feel free to comment or file a new issue if needed.
