### ISSUE TITLE
Uniforms should provide more options to handle `anyOf`

### ISSUE THREAD

**Issue by alexkreidler** [vazco/uniforms#918]
I've got some JSON Schema
```json
{
    "TickCount": {
        "anyOf": [
            {
                "type": "number"
            },
            {
                "$ref": "#/definitions/TimeInterval"
            },
            {
                "$ref": "#/definitions/TimeIntervalStep"
            }
        ]
    },
    "TimeInterval": {
        "enum": [
            "millisecond",
            "second",
            "minute",
            "hour",
            "day",
            "week",
            "month",
            "year"
        ],
        "type": "string"
    },
    "TimeIntervalStep": {
        "additionalProperties": false,
        "properties": {
            "interval": {
                "$ref": "#/definitions/TimeInterval"
            },
            "step": {
                "type": "number"
            }
        },
        "required": [
            "interval",
            "step"
        ],
        "type": "object"
    }
}
```

Based on [the algorithm for handling `anyOf`](https://uniforms.tools/docs/api-bridges/#note-on-allofanyofoneof) from the docs, instantiating an `AutoForm` with `TickCount` does the following:
- rendesr a `number` input (the first `type`)
- sets `required` to `["interval","step"]` (the accumulation of the required values)

This is exactly what happens my test, and unfortunately, this results in an incorrect form. `TickCount` itself is very much not required, but the field renders as such and thus prevents users from submitting the form properly. 

In another example from my JSON schema, I get a `required` value that is an empty array which also makes the field required and causes problems. I'll make a separate issue for that.

I would propose making the handling of `anyOf` a little more flexible. One solution that would work for me is to simply take the first value from `anyOf`. 

I am aware that some of these transformations could be done prior to passing to Uniforms; in fact I already do [quite a few of these](https://gist.github.com/alexkreidler/c9c051496933ca80bb46de46e67e46c1). Nevertheless, improving Uniforms to accept more versatile input makes it that much more powerful.

PS: that link might be useful if you want to work on improving the JSON Schema parser to be more flexible/ignore unsupported data. I'm not sure how much of a goal it is, so I won't open a separate issue for now

**Comment by radekmie** [comment]
Hi @alexkreidler. As you've already noticed, we are aware of the problems with `anyOf` (and others). Let's keep it short then: do you have an idea for the API here? I'd like to make it both easy and seamless as possible.

**Comment by alexkreidler** [comment]
No thoughts right now, but I'll think on it and let you know.

**Comment by radekmie** [comment]
Due to long inactivity, I'm closing this one. Feel free to add your ideas for an API or other approaches - we'll definitely reopen the issue and try to make `anyOf` handling better.
