### ISSUE TITLE
`anyOf` fields with empty required arrays are treated as required

### ISSUE THREAD

**Issue by alexkreidler** [vazco/uniforms#919]
I have a JSON Schema:
```json
"TextBaseline": {
    "anyOf": [
        {
            "const": "alphabetic",
            "type": "string"
        },
        {
            "$ref": "#/definitions/Baseline"
        },
        {
            "const": "line-top",
            "type": "string"
        },
        {
            "const": "line-bottom",
            "type": "string"
        }
    ]
}
```
Which becomes
```json
"TextBaseline": {
    "anyOf": [
        {
            "const": "alphabetic",
            "type": "string"
        },
        {
            "enum": [
                "top",
                "middle",
                "bottom"
            ],
            "type": "string"
        }
        {
            "const": "line-top",
            "type": "string"
        },
        {
            "const": "line-bottom",
            "type": "string"
        }
    ]
}
```
and then the compiled schema becomes:
```json
{
    "anyOf": [
        {
            "const": "alphabetic",
            "type": "string"
        },
        {
            "enum": [
                "top",
                "middle",
                "bottom"
            ],
            "type": "string"
        },
        {
            "const": "line-top",
            "type": "string"
        },
        {
            "const": "line-bottom",
            "type": "string"
        }
    ],
    "properties": {},
    "required": [],
    "type": "string",
    "isRequired": false
}
```

Now a string Field is rendered, but with the property `required` set to an empty array. Surprisingly, this results in the field being required. 

The interface shows the required asterisk, and I cannot submit the form because it doesn't validate.

![uniforms_required](https://user-images.githubusercontent.com/11166947/113359491-e1fd4400-9315-11eb-8cff-2b1e74cdd0a5.png)
![uniforms_devtools](https://user-images.githubusercontent.com/11166947/113359673-43251780-9316-11eb-9521-b620a7bf9c2a.png)

Please fix so an empty array means the field is not required. 

Thanks for this great library!

**Comment by radekmie** [comment]
Hi @alexkreidler. I see where the problem is (field receives `required: []`), but I'm not sure how to proceed here. _Technically_, `required` should be ignored for non-objects. Maybe changing [this condition](https://github.com/vazco/uniforms/blob/657ad910c64f6347458d128ecaea7c1c7bc8e23d/packages/uniforms-bridge-json-schema/src/JSONSchemaBridge.ts#L261-L263) to include non-booleans would be enough. If you'd like to, give it a try. If not, we'll look into it.

**Comment by alexkreidler** [comment]
Thanks, that's very helpful.

I'll try that change out within this week hopefully. I'll report back here if it works, then maybe send a PR.
