### ISSUE TITLE
New documentation

### ISSUE THREAD

**Issue by radekmie** [vazco/uniforms#92]
I'm starting to work on the new documentation. Here's a planned documentation summary. If you have any suggestions about what else should be included in here - please comment.

New documentation will be developed [here](https://github.com/vazco/uniforms/blob/master/README2.md) - every suggestion and PR is welcome!

Playground is coming soon, don't worry.

* [x] Description
* [x] Installation
    * [x] meteor
    * [x] npm
* [x] Quick start
* [x] Overview
    * [x] Forms components
    * [x] Fields components
* [x] Advanced topics
    * [x] Forms
        * [x] Asynchronous validation
        * [x] Hierarchy
        * [x] Autosave
        * [x] Post-submit handling
        * [x] Validation options and modes
        * [x] Example: ModifierForm
    * [x] Fields
        * [x] AutoField algorithm
        * [x] Guaranteed props
        * [x] Props propagation
        * [x] Example: CustomAutoField
        * [x] Example: CycleField
        * [x] Example: RatingField
    * [x] Schemas
        * [x] SimpleSchema definition
        * [x] Example: MyLittleSchema
    * [x] Context data
        * [x] Available context data
        * [x] Example: Conditional display
        * [x] Example: SubmitField
        * [x] Example: SwapField
* [ ] API
* [x] Troubleshooting
* [x] Contributing
* [x] Copyright and license

**Comment by serkandurusoy** [comment]
It would be awesome if the contributing section described

* setting up a local development environment
* how to use a local, unpublished development version of uniforms in a test
project

The last time I tried setting it up and trying to see if my changes fix a
known problem was a terrible experience, I could not get it to run so I was
not able to test if my PR fixed the problem or not.

**Comment by radekmie** [comment]
Great idea @serkandurusoy. I'll surely add it to the playground README, but probably also here - it might be useful.

**Comment by serkandurusoy** [comment]
Thanks! I believe it would also help encourage contributions.

On Wed, Aug 10, 2016 at 10:43 AM, Radosław Miernik <notifications@github.com

**Comment by vladejs** [comment]
It will be awesome to cover this use cases:
1. Conditionally show form fields based on another's field value, for instance, when user chooses 'Book' in category list, the form shows an ISBN field.
2. How to manage a list of custom fields, for example, I created an upload image custom component and don't know how to tell the schema to render a list of those components. Moreover, if I just tell it to render a list of standard TextField components but with type file, it just renders with type text:
```
images:
  type: [String]
  uniforms:
    type:'files'  
```

3. How to apply different option values to SelectField component, for instance, the list of categories should render with label capitalized:
```
<option value='books'>Books</option>
```

**Comment by radekmie** [comment]
Thanks @vladejs!
All of those have been discussed more in-depth in their issues and surely should be included into documentation.

**Comment by vladejs** [comment]
Is there an issue for usecase #1? I haven't find an thread about it

**Comment by radekmie** [comment]
To be honest I can't remember... Maybe we talked about it internally? Despite of all - I'm currently writing this _chapter_, and it will be ready soon.

**Comment by radekmie** [comment]
Okay @vladejs - it would be nice to hear, if everything is clear and you could add something more.

**Comment by vladejs** [comment]
is there a way to tell AutoForm component to render an horizontal form? Like [this one](http://cubanote.mod.bz/postStuff)

**Comment by radekmie** [comment]
If you are using bootstrap themes, then `form-inline` class should do the work (at least, I think it should - I'm not a bootstrap expert). Maybe `grid` would suffice? It is already implemented.

If you are using semantic or unstyled theme, then no, there's no builtin way to do this - you can either create custom components to handle this or extend current ones and then make a PR. How to do that? I think the same way as `grid` is handled in bootstrap themes.

**Comment by vladejs** [comment]
The way I have it on my form is applying a `col-md-4` class to labels and a `col-md-8` class to inputs. So the question would be, how to apply custom classes to all form labels and inputs right from AutoForm component, something like:
```
<AutoForm labels-classes="col-md-4" input-classes="col-md-8" ... />
```
Or apply them field by field (this is how I do it in AutoForm with Blaze):
```
<AutoForm template="bootstrap-horizontal" ... >
  <afField label-class="col-md-4" input-col-class="col-md-8" />
  ...
</AutoForm>
```
I don't know if this have been already discussed though

**Comment by radekmie** [comment]
That's exactly what is `grid` prop in bootstrap themes for. Just pass `grid={4}` to your `AutoForm`.

**Comment by vladejs** [comment]
It works!, but not with nested fields (those who are Array in schema) because they are rendered inside a Panel.

**Comment by radekmie** [comment]
I think, that there's no good way to show inline form with an array field.

**Comment by radekmie** [comment]
New documentation is quite ready. I've already swapped old README.md with the new one, CONTRIBUTING.md is also updated.

Does anyone have an idea for generating documentation from both JSDoc and propTypes? There are a lot of components right now, so doing it by hand is basically undoable.

**Comment by radekmie** [comment]
Right now API docs will remain incomplete.
Playground issue: #98.
