### ISSUE TITLE
Getting errors on autosave:  Can't perform a React state update on an unmounted component....

### ISSUE THREAD

**Issue by michaellill-corefihub** [vazco/uniforms#920]
I'm getting this error in our app when running tests with cypress:
```
Can't perform a React state update on an unmounted component.
This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s", "the componentWillUnmount method", "\n at AutoValidatedQuickBootstrap4Form\n at QuickCheckForm
```
https://github.com/vazco/uniforms/blob/49de014d604875d78b2d4b8234049d2e7fab499c/packages/uniforms/src/BaseForm.tsx#L215-L235

I think we need to check if component is still mounted right before setState in line 226?

**Comment by radekmie** [comment]
Hi @michaellill-corefihub. Thanks for the report! I think we'd rather `clearTimeout` it in `componentWillUnmount` instead.

**Comment by michaellill-corefihub** [comment]
@radekmie Yes, that is even better.

**Comment by michaellill-corefihub** [comment]
@radekmie Do you want me to provide a PR?

**Comment by radekmie** [comment]
I'm already on it, but thanks :smile:
