### ISSUE TITLE
JSONSchemaBridge in combination with ajv-validator v8 not working, while v7 is

### ISSUE THREAD

**Issue by petermanders89** [vazco/uniforms#923]
The bridge is no longer working with the new version of the ajv-validator (see https://github.com/ajv-validator/ajv/pull/1487). The property 'dataPath' has been renamed to 'instancePath'. 

https://github.com/vazco/uniforms/blob/657ad910c64f6347458d128ecaea7c1c7bc8e23d/packages/uniforms-bridge-json-schema/src/JSONSchemaBridge.ts#L97

This affects: JSONSchemaBridge in combination with the 'ajv-validator'.

**Comment by radekmie** [comment]
Hi @petermanders89. That's right, we have to update the `JSONSchemaBridge`. Thanks for the report!
