### ISSUE TITLE
Inline Styling 

### ISSUE THREAD

**Issue by Necmttn** [vazco/uniforms#93]
Hi, I was using Semantic UI for styling. but today ı have made a radical decision to use inline styling in my app. 
Currently I'm playing around with https://github.com/Khan/aphrodite/ which allows me write inline css in a goodway. 

but the problem is when autoform renders field its create 
`<section class="required field">
      <label for="uniforms-0000-0005">Website</label>
        <section class="ui input">
          <input type="text" id="uniforms-0000-0005" name="website" placeholder="" value="">               
        </section>
   </section>`

for style this element  i have to use tagline styling  but it's not practical when you think styling in scale. so how can i add className to fields? 

i check documents but didn't see. sorry to bother if the answer already out there. 

Cheers. 🍻

**Comment by radekmie** [comment]
All components accept `className`. Well, it's not in the documentation, because it was obvious to me... Okay, I'll add it later.

Also, remember you can always [read the code](https://github.com/vazco/uniforms/tree/master/packages/uniforms-semantic/src/components/fields).
