### ISSUE TITLE
Form crashes when validator returns errors (in tutorial and reproduction)

### ISSUE THREAD

**Issue by fedor-moiseev** [vazco/uniforms#933]
When submitting the form with invalid values (validator returns errors), the form crashes with the error provided below. **This affects [tutorials](https://uniforms.tools/docs/tutorials-using-predefined-fields) provided on the website, [reproduction](https://github.com/vazco/uniforms/tree/master/reproductions) in the GitHub repo, and [CodeSandbox template](https://codesandbox.io/s/github/vazco/uniforms/tree/master/reproductions) which is mentioned in bug report template.** Please see the workaround in the end of this issue.

The error:
```
Unhandled Runtime Error

TypeError: path is undefined
Call Stack
pathToName
node_modules/uniforms-bridge-json-schema/es6/JSONSchemaBridge.js (39:0)
getError/<
node_modules/uniforms-bridge-json-schema/es6/JSONSchemaBridge.js (70:0)
getError
node_modules/uniforms-bridge-json-schema/es6/JSONSchemaBridge.js (69:0)
useField
node_modules/uniforms/es6/useField.js (28:0)
AutoField
node_modules/uniforms/es6/createAutoField.js (8:42)
```

- Affected versions of the core, bridge, and theme packages you are aware of.
  - `uniforms`, `uniforms-bridge-json-schema`, `uniforms-unstyled`, `ajv` (all latest versions)
- Steps to reproduce. If possible, include a reproduction using our [playground](https://uniforms.tools/playground) or [CodeSandbox template](https://codesandbox.io/s/github/vazco/uniforms/tree/master/reproductions).
  - Using CodeSandbox template provided above or [my fork of it](https://codesandbox.io/s/youthful-mclean-48b0n).
- Possible workarounds, if you've found any.
  - Setting`error.dataPath` to `error.schemaPath` resolves the issue.
  Working example:
  ```js
   function createValidator(schema) {
    const validator = ajv.compile(schema);
    return (model) => {
      validator(model);
      console.log(validator.errors);
      return validator.errors?.length
        ? {
            details: validator.errors.map((error) => ({
              ...error,
              dataPath: error.schemaPath,
            })),
          }
        : null;
    };
  }
   ```

**Comment by radekmie** [comment]
Hi @fedor-moiseev. It's a problem with `ajv@8` and was already reported in #923. It'll be a part of the next release.
