### ISSUE TITLE
Enable use of 'map' type from JSONSchema

### ISSUE THREAD

**Issue by MatthewJonD** [vazco/uniforms#934]
Loving this library...saving so much time.
Quick question/ask
Getting the error-
```
Invariant Violation: Unsupported field type: map
```
Im using a 'map' in my models on a language field that allows data to be stored like -
``` 
"summary" : {
        "language" : {
            "en" : "Hello World"
        }
    },
```

With a schema that looks like this-
```{
  "title": "epochItem",
  "type": "object",
  "properties":
    "name": {
      "type": "string",
      "description": "Human Readable"
    },
    "summary": {
      "title": "summary",
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "language": {
          "type": "map",
          "properties": {
            "$*": {
              "type": "string"
            }
          }
        }
      },
      "description": "Complex Description of Summary"
    }
...
(More fields)
``` 

Any chance this is on the roadmap to be supported?

**Comment by radekmie** [comment]
Hi @MatthewJonD. I've never heard about `map` type in JSON schema, nor can I find it in the specification. What tool or library are you using for these? In general, it should be an `object` with [`patternProperties`](https://json-schema.org/understanding-json-schema/reference/object.html#id9).

And as for the question: no, there's no out-of-the-box handling for such objects. You'd have to make a field (React component) that would allow users to add their own keys.

**Comment by MatthewJonD** [comment]
For some context.  Im using Mongoose->mongoose-schema-jsonschema->To generate this schema...
https://www.npmjs.com/package/mongoose-schema-jsonschema


So the mongoose schema looks like -
```
   let richMetaDataItemSchema = mongoose.Schema({
        _id: false,
        name: { type: String },
        language: {
            type: Map,
            of: { type: String }
        }
    });
```

It then gets converted to with mongoose-schema-jsonschema that turns that into -
```
 "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "language": {
          "type": "map",
          "properties": {
            "$*": {
              "type": "string"
            }
          }
        }
```
This lets me quickly build CRUD forms for my Mongoose based apps.

I'll see if there are some options to not use the map field...


And-
Create a component to handle that UI need.  

Is there a way to register fields by the schema field type, and let any field that is rendered with the 
```
 <AutoFields />
```
Just use that custom component?
Right now I am doing-
```
 <AutoField name={'startDate'} component={DateTimeField} />
```
Where the {DataTimeField} is my own custom component.  

But I have the call each field out separately...
Vs rendering a component based on the type for the schema.

**Comment by radekmie** [comment]
Yep, I checked the code and it looks like your schema [hit this fallback](https://github.com/DScheglov/mongoose-schema-jsonschema/blob/3b4d980c25a63796b7c8eb964ab7ccbbd00ec100/lib/types.js#L198-L202). And thanks for opening https://github.com/DScheglov/mongoose-schema-jsonschema/issues/26! I'll link it here so both sides would benefit.

About registering a component: yes, there is [`AutoField.componentDetectorContext`](https://uniforms.tools/docs/uth-autofield-algorithm#overriding-autofield). In your case it'd look like this:
```tsx
function componentDetector(props, uniforms) {
    if (props.field.type === 'map') {
      return MapField;
    }

    return AutoField.defaultComponentDetector(props, uniforms);
  }
```

**Comment by MatthewJonD** [comment]
@radekmie Thanks much.  
@DScheglov Made changes to https://www.npmjs.com/package/mongoose-schema-jsonschema to support the map type.  Output now looks like 
```
 "summary": {
            "title": "summary",
            "type": "object",
            "properties": {
             
                "name": {
                    "type": "string"
                },
                "language": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string",
                        "__required": false
                    }
                }
            },
            "description": "Complex Description of Summary",
            "label": "Complex Description of Summary",
            "format": "language"
        }
```
Is now the output, which does have normal JSONSchema types/values.  
Now getting the error-
```
Unhandled Runtime Error
TypeError: Cannot convert undefined or null to object

Call Stack
Function.keys
<anonymous>
JSONSchemaBridge.getSubfields
node_modules/uniforms-bridge-json-schema/es6/JSONSchemaBridge.js (228:0)
```
I have only added the new field to the ```<AutoFields />``` component, so made sure it was narrowed down to our new type.
Will dig in more, but wanted to report some progress.

**Comment by DScheglov** [comment]
@MatthewJonD hey,

Oh! I see the problem with unneeded field `__required`. I will remove it.
However, I cannot help with UniForms, so, after the schema becomes correct but the problem with UniForms keeps -- contact UniForms to get support with the issue.

**Comment by radekmie** [comment]
@MatthewJonD, @DScheglov: I'd say it's a problem in uniforms: we assume that the `properties` key is always present for `object` fields ([source](https://github.com/vazco/uniforms/blob/6a21f52ab2d804c4e558ea9d6cf4ea3013d5a9d5/packages/uniforms-bridge-json-schema/src/JSONSchemaBridge.ts#L319-L321)). We'll fix that.
