### ISSUE TITLE
Question: How to dynamically load values to form?

### ISSUE THREAD

**Issue by fedor-moiseev** [vazco/uniforms#938]
I want to load values to a form dynamically (without modifying the schema) using Uniforms. I tried using [Model transforms](https://uniforms.tools/docs/api-forms#model-transformations), but the values reset on change.

Can anybody advise me how to better approach this? Any help is highly appreciated!

**Comment by fedor-moiseev** [comment]
Finally I have found a solution for this issue. It can be solved using [Model transforms](https://uniforms.tools/docs/api-forms#model-transformations)

**Comment by radekmie** [comment]
Hi @fedor-moiseev! What do you mean by "load values _to_ form"? If it's about populating the initial state, then you can do it outside of uniforms, i.e., fetch the data _somehow_ and render the form only if it's already fetched. If not, please describe your problem a little more or at least give an example.

**Comment by fedor-moiseev** [comment]
Sorry for not providing enough details. I have a schema pre-defined which is used for insert/update. When the user wants to update the object, this object is fetched from an external API and the form is rendered from the pre-defined schema. Now I want to insert the fetched values to the form.

Currently I found this approach which is not ideal, but it works:

```jsx
<AutoForm
  placeholder
  schema={bridge}
  onSubmit={onSubmit}
  modelTransform={(mode, model) => {
    return {...fetchedValues, ...model}
  }}
/>
```

**Comment by radekmie** [comment]
No problem! Then as I said, it'd be better to do it like this:
```tsx
const model = fetchModelSomehow();
if (isUpdate && !model) return <Loader />;
return <AutoForm {...} />;
```

**Comment by fedor-moiseev** [comment]
Thanks for your response! That's exactly what I'm doing. My question is if there's a better option than `modelTransform`. Is there something like `initialValues`, so that I can set them only once instead of setting them each time the form gets updated?

**Comment by radekmie** [comment]
Just use `model` for that. It serves as the _value_ prop rather than _initial value_, but in `AutoForm` it can be both.

**Comment by fedor-moiseev** [comment]
Thanks, this worked for me!

**Comment by kevinsimper** [comment]
I was also curios how to provide the initial state 😄 but this also helped me that I could provide it as 

```
<AutoForm
            schema={generatedForm}
            onSubmit={console.log}
            model={{
              firstName: "Hello",
              lastName: "World",
              telephone: "123123123123",
            }}
          />
```
