### ISSUE TITLE
Trying to delete ListItem gives Uncaught TypeError: parent.value.slice is not a function

### ISSUE THREAD

**Issue by Astroxslurg** [vazco/uniforms#94]
I'm trying to make a form where you can write many answer alteratives to a multiple choice question. But when i try to remove an alternative by pressing the "-" button I only get an error output in the console: Uncaught TypeError: parent.value.slice is not a function.

Schema (is also used for other purposes through the application):

```
export const checkpointsSchema = new SimpleSchema({
...

alternatives: {
    type: Array,
  },

  'alternatives.$': {
    type: Object,

  },

  'alternatives.$._id': {
    type: String,
    autoValue() {
      return shortid.generate();
    },
  },

  'alternatives.$.alternative': {
    type: String,
    label: 'Alternativ',
  },

  'alternatives.$.votes': {
    type: Number,
  },
...
```

Code:

```
<AutoForm
  schema={checkpointsSchema}
  onSubmit={onSubmit}
  >
  <ListField name="alternatives">
    <ListItemField name="$.alternative"/>
  </ListField>
</AutoForm>
```

Note that using` <AutoForm name="alternatives"/>` solves the issue, that however gives me forms for ID and votes too, which is of course not for the user to fill in.

**Comment by Astroxslurg** [comment]
Identified the problem myself. All that was needed was to change the code a little:

```
<ListField name="alternatives">
  <ListItemField name="$">
    <NestField>
      <TextField name="alternative"/>
    </NestField>
  </ListItemField>
</ListField>
```

**Comment by radekmie** [comment]
I'm glad you didn't give up!
