### ISSUE TITLE
Question- How to index into an array with ListField/ListItemFields

### ISSUE THREAD

**Issue by MDrooker** [vazco/uniforms#943]
Hi-
I have a schema that looks like-
```
{
    "title": "question",
    "type": "object",
    "properties": {
        "questionuuid": {
            "type": "string"
        },
        "tags": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },

        "startDate": {
            "type": "string",
            "format": "date-time"
        },
        "endDate": {
            "type": "string",
            "default": "2021-06-02T19:25:49.588Z",
            "format": "date-time"
        },
        "isActive": {
            "type": "boolean",
            "default": true
        },
        "type": {
            "type": "string",
            "enum": [
                "openQuestion",
                "triviaQuestion",
                "interviewQuestion",
                "topicQuestion",
                "optionQuestion"
            ],
            "description": "Current Type of Question"
        },
        "options": {
            "type": "array",
            "items": {
                "title": "itemOf_options",
                "type": "object",
                "properties": {
                    "questionOptionuuid": {
                        "type": "string"
                    },
                    "name": {
                        "title": "name",
                        "type": "object",
                        "properties": {
                            "default": {
                                "type": "string"
                            },
                            "translations": {
                                "type": "array",
                                "items": {
                                    "title": "itemOf_translations",
                                    "type": "object",
                                    "properties": {
                                        "language": {
                                            "type": "string"
                                        },
                                        "value": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "optionLabel": {
                        "type": "string"
                    },
                    "updateHash": {
                        "type": "string"
                    },
                    "isAnswer": {
                        "type": "boolean"
                    },
                }
            }
        },
        "__v": {
            "type": "number"
        }
    }
}
```

Im trying to create a custom editor for the 'Options' property. (Its an array of fields).
In my new editor control, I display all the item's of the options array.  And when selected, want to just have an editor displayed for those fields in the index of the item selected.   

Right now I have(simple example)-
```
<ListField name='options'>
      <ListItemField name="$">
          <AutoField name="isAnswer" />
          <AutoField name="updateHash" />
          <AutoField name="optionLabel" />
      </ListItemField>
</ListField>
```
This displays ALL the items in the array.

I have tried to change
``` <ListItemField name="$">``` to ``` <ListItemField name="1">```  thinking that would just display the single value of the "1" index.

Not sure how to just display the single element of the array.  And have the correct model item be edited.

**Comment by wadamek65** [comment]
Hey @MDrooker , thanks for the issue report.

What you described is the normal `ListField` behavior. It will always render as many children as there are elements in the model, even if you explicitly name the `ListItemField` with an index. But the main purpose of it is to render the `ListAddField` for you automatically, so if you do not need that or can handle it separately you can just skip using `ListField` and use a list item directly.

Like so:
```ts
<ListItemField name="options.1">
```

or by using `AutoField`

```ts
 <AutoField name="options.1">
```

You can also access the nested properties analogically

```ts
<AutoField name="options.1.isAnswer">
```

Please do tell me if this helps. If you need any more help feel free to ask more questions.

**Comment by MDrooker** [comment]
Thats perfect...
And ended up using the joinName function to keep it clean-
```joinName('options', `${optionIndex}`, 'isAnswer')}```

Amazing work on this library!

**Comment by wadamek65** [comment]
@MDrooker  I'm glad to hear this has helped you. I'll be closing this issue, but if you have any other related questions feel free to reopen it or open new one and we'll be happy to help.

**Comment by harleyharl** [comment]
@wadamek65 where did you get optionIndex from ? I'm trying to do something like this but I need to somehow access the index of the field being rendered. 

For example I have a component that renders an array of fields: 

`const FieldList = () => {
  const [value, setValue] = React.useState(null)

  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setValue((event.target as HTMLInputElement).value)
  }
  
  return (
    <ListField name="filters">
      <ControlledRadioButtonsGroup value={value} handleChange={handleChange}/>

      <ListItemField name="$">

        <ErrorField name="channel"/>
        <AutoField name="channel"/>

        <DisplayIf<Model> condition={_context => value==="continuousType"}>
          <AutoField name="continuous_type" />
        </DisplayIf>
        <DisplayIf<Model> condition={_context => value==="colourWheelType"}>
          <AutoField name="colour_wheel_type"/>
        </DisplayIf>
        <DisplayIf<Model> condition={_context => value==="discreteType"}>
          <AutoField name="discrete_type"/>
        </DisplayIf>
      </ListItemField>

    </ListField>
  )
}`

I want to be able to select a radio button that only shows one field depending on what is selected but the ControlledRadioButtonsGroup has the same state across all components. I'm thinking if i can access the index of the filter object where the radio buttons exist I can set a different radio button value for each filter

**Comment by radekmie** [comment]
Hi @harleyharl. You can use `useField` to know what the current `name` is, and extract it's last part - that's similar to what's the `ListAddField` is doing [here](https://github.com/vazco/uniforms/blob/344ed628f42b0adf0c7044aa29ee3d0ba00e185b/packages/uniforms-unstyled/src/ListAddField.tsx#L20-L26) to know it's parent (i.e., all but the last parts are used).
