### ISSUE TITLE
uniforms-antd. SelectField. Typing improvements to provide access to antd native props

### ISSUE THREAD

**Issue by aburtsev** [vazco/uniforms#951]
Motivation:
Ability to pass native antd props like "showSearch", "optionFilterProp", and others.
It already works. As far as I understand via filterDOMProps. But there are some issues with types.
 
Solution:
I suppose the root issue is of using Omit on the union as Omit looks in such a case only on the intersection of props. I attached a solution that works.

Please have a look. If it makes sense for you, I'll create a PR

![image](https://user-images.githubusercontent.com/3891411/117450975-965c3c80-af4a-11eb-8a20-8f41509fd296.png)

**Comment by wadamek65** [comment]
Hi @aburtsev , thanks for the report.

I checked out the behavior that you describe and it seems that you're right, the types for these props are not inferred as expected. The type is not being properly, as the `showSearch` prop and the others do exist but only on `SelectProps` and not on `CheckboxesProps` which _should_ be distinguished by whether or not the `checkboxes={true}` prop was provided or not. The types need to be improved there.

Your suggestions seems to show the types from declaration files? If so, these are generated automatically and we can't modify them. The changes have to be applied in [this part of source code](https://github.com/vazco/uniforms/blob/master/packages/uniforms-antd/src/SelectField.tsx#L13-L43). You're welcome to try and adjust the types there - or we will work on this issue ourselves sometime in the future.

**Comment by aburtsev** [comment]
Hi @wadamek65 , thanks for such a quick response. 

I probably found a way to fix this issue. Please have a look at the screenshot.
![image](https://user-images.githubusercontent.com/3891411/117694151-7ab19a00-b1c7-11eb-8b5b-9ddc5ec18d68.png)

And this is the demo in [TS playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAyhA2EDGwAKAnA9mAzlAvFAN4BQUUSAFsgNYBGmAHgPwBcUAZgIbw4QA0ZKH0QoM2NsODoAlgDsA5oPJJMAWzWY5knNPlKhUaVzk4OmdGskAKAG48ArhHa7ZigJQEAfFLcKA3CQkAL4koJBQAMLUSPRMEDjiuATEQlS0DIzs0k7KFDFxjEk6eop5qhpaknIOanQQ6HnGpuaWNvbwTuzRGUwAao4QACrgEJ74Pq76gaFho1AA8rYNsgAmEAA8Q-xQAKo+hLtQAGSLajLAWzs0ECCYHHtegXMRSysy60l4hKQq6ppydgMTCIEwhILhaBfFJvdBrTZwURoLDJAA+UQKmQSXx2sPhXy8QVUpmAUFQkQccIgcmA7GhPzS-y02XQuTSmKYLLZKg5RRR7AA5KoqSgBeCSAB6CVQAC0cvlCsVMpgCwAMrshgBJBYAOSV+oNSqCEEYYAspPWSHgXHQ0EhUE1ajAWGWqzxH0220eKSOp2sQygJuA1NWeBMICEzDOFyuUBudwe+yE7DkEGW6HcEPmXz6ACYUo7nZhXe71htEchkdg8OierEsYkUThcen8U3CSRiboyQBRGl5ulNvMpX4UJmAoysgTs3pZSfc-KzpKC4W20UhIA).

After types became work in the proper way,  a lot of TS-errors appeared in tests. For example: 
![image](https://user-images.githubusercontent.com/3891411/117694399-c82e0700-b1c7-11eb-9b32-5f17d57f3a41.png)


Please have a look at the solution. If it's ok for you. I'll try to fix errors.

**Comment by radekmie** [comment]
Hi @aburtsev! Thanks for your report and these in-depth checks - they are really useful. The idea of making `Override` distributive is great, however, it has some implications. Luckily, we don't use props unions that often so it'll be rather a quick check. If you'd like to give it a try - go for it!
