### ISSUE TITLE
How to Pass Props in JsonSchema for a Field

### ISSUE THREAD

**Issue by pavankramadugu** [vazco/uniforms#968]
In Documentation, I'm not getting how to pass props like placeholder, showinLineError etc as props in json schema instead of adding them in form structure. Any leads on this. Thanks

**Comment by radekmie** [comment]
Hi @pavankramadugu. Of course you can! Unluckily, it's not described in our [`JSONSchemaBridge` docs](https://uniforms.tools/docs/api-bridges#jsonschemabridge) yet, but there's a [section about it in the FAQ](https://uniforms.tools/docs/faq#how-can-i-pass-additional-props-to-the-custom-field). The API is simple: if a field has a `uniforms` property, it's treated as an object with additional props, passed down to the field.

Example:
```ts
const schema = {
  type: 'object',
  properties: {
    field: {
      type: 'string',
      uniforms: { propA: 'value', propB: true }
    },
  },
};
```

However, these props are being passed to the _component_, not the `connectField` wrapper around it. That means, they won't propagate as described [here](https://uniforms.tools/docs/api-fields#props-propagation), but rather be limited to the only component that received it.

**Comment by pavankramadugu** [comment]
Got it thanks. Per your knowledge Has any one tried implementing generation of the forms dynamically from service which gets json from a service which makes the schema properties using data from database

**Comment by radekmie** [comment]
Well, yes. For example, we've done that at least a dozen times at [Vazco](https://www.vazco.eu).

**Comment by radekmie** [comment]
As I understand, it's all clear now - I'm closing the issue then. If there's anything else, feel free to comment here or file another issue.

**Comment by pavankramadugu** [comment]
```
const schema = {
  type: 'object',
  properties: {
    email: {
      type: 'string',
      uniforms: { placeholder: true }
    },
  },
};

```

This is not showing placeholder as email in the ui

**Comment by radekmie** [comment]
Sorry for the delay, @pavankramadugu! I saw #973 already - will answer there.
