### ISSUE TITLE
[QUESTION]: Can't convert string to object

### ISSUE THREAD

**Issue by simplecommerce** [vazco/uniforms#982]
Hi, I seem to be experiencing a weird issue.

I am using a GraphQL schema with my form and I have a field that is a String type.
In my model, I load the string with a value.
I have a Select that is a custom component that allows me to select a different value and the selected value returned is an object.

When I change the selection the field in the model is updated correctly from a string to an object, and in the transform I can change it when I submit my form.

The issue I am having is when I use the formRef that I passed to AutoForm, and call onChange to change my field value to an object, it gives me this error: 

> Cannot use 'in' operator to search for 'name' in some string

It might be related to: https://github.com/vazco/uniforms/issues/960

You can see an example here:

https://codesandbox.io/s/cant-convert-string-to-object-with-onchange-o1o7q

I am using latest uniforms version.

I am triggering the change with `useEffect` in the code on line `116`.

In this example, I did not put a Select as the field, I simply wanted to show the error message.

Hope you can help.
Let me know if I am not being clear in my description.

Thanks!

**Comment by radekmie** [comment]
Hi @simplecommerce. In your demo, you are setting a `{ name: string; value: number }` object into a field of type `String` in your schema. In uniforms, the data types cannot change in the course of execution, therefore this is a forbidden change. (However, it could behave nicer than fail.)

What is the final result you'd like to achieve? I'm sure we'll figure something out.

**Comment by simplecommerce** [comment]
@radekmie thanks for your reply, yeah I understand.

I just found it odd that it didn't work when calling `onChange` from the `formRef` to switch from `string` to `object` but it worked when using `onChange` of the connected field.

I'll try to modify my example to show you what I mean.

**Comment by simplecommerce** [comment]
I can't reproduce it in my sandbox, maybe I was hallucinating, lol.
I will play with it some more and re-open this if needed, but for now I think its fine.

Thanks for the help!

**Comment by simplecommerce** [comment]
Hi @radekmie I am getting back to you about this question because I am experiencing issues that I didn't think i would have and would like your opinion.

In my form, I have a Select component that is using `react-select` library. 
In my model I have a field called `projectId` pointing to that `Select`.

When I add (form), if I select an option, it returns `{ label, value }` which updates my `projectId` field.
This works fine as is because the initial value is an empty string.

The issue I am having is when I edit.
My `projectId` field is filled with the `ID` of whatever project I selected.

But when I try selecting another option in the Select, it gives me this error, because its trying to change from a string to an object.

The reason I wanted to keep this behavior, was because I could then use the selected option's additional properties to display in my form or with other fields.

For example, if my project has an `availableModels` array which I need in order to pre-fill another form field, I can use it directly from the model when a project is selected, instead of having to create a separate query to go fetch that information which is already contained in my Select.

And when I submit, I can then transform and remove it from my final values.

I was expecting to be able to counter this error by using the `modelTransform` when `mode` is `form` in order to shape the model according to the schema, but the error check seems to be even before `modelTransform` is used.

Do you have any ideas or suggestions?

I know I could change my existing schema, but I am trying to avoid this.
I know I can also use `onChange` and alter the data directly before calling `onChange` from the autoform, but I am also reluctant to do this because I want to be able to have the option to use the data from the option and not only return the `ID` of whatever option is selected.

Any ideas would help.

Thanks!

**Comment by radekmie** [comment]
I'm not sure whether I understand the problem here. It sounds like the `Select` component you are talking about here accepts both `value` and `{ label, value }`, but always returns (calls `onChange`) with the latter? That's weird and I guess I misunderstood you.

I'm not sure what kind of data shape you'd like to have during the form edit, validation, and submission. If you could prepare a demo that shows how it works right now (preferably with the `react-select` component) and the way you'd like it to work, it'd be great.

**Comment by simplecommerce** [comment]
@radekmie yeah it was a bit complicated to write, I think a solution would be to allow us a way to overwrite or pass our own `changedKeys` function, if not passed, it would handle it using the default one that is built-in.

I didn't want to fork and change your existing method because I want to keep having your updates without having to maintain a separate fork just to have a specific change in behavior.

In my scenario and usage, I need to be able to change the type of the field value at all times, and regardless of how it changes, it would still identify as a changed key.

In my case, it changes from String to Object and vice versa because of the way certain components behave.
And in the end I transform my model structure using your `modelTransform` function for the different modes.

But if you need a more concrete example, I will try to create an example for you to look at.

**Comment by radekmie** [comment]
Well, if `changedKeys` is actually the only thing you'd need, then we definitely can improve that. Would adding `typeof valueA !== typeof valueB` [here](https://github.com/vazco/uniforms/blob/8dd2d7435d4a19c695af6e06fe0d27f97eeb7c0b/packages/uniforms/src/changedKeys.ts#L7) be enough?

**Comment by simplecommerce** [comment]
@radekmie Yes I think that would work! In my case, my default value for the field is a String `abc` and changes when I select another option in the Select, because `{ label, value }`, so from what I get in your code, it would validate using `isEqual`? That should work fine!

Thanks for your help!

**Comment by radekmie** [comment]
Then make sure if it's enough. If so, feel free to file a PR.

**Comment by simplecommerce** [comment]
@radekmie I did the change and tested it on my end and it seems to work and do what I need it to do.
I had trouble with adding tests.
I keep getting build errors on my hosting.
I am new to PR with github and don't know how to do it properly.
I wasn't even sure how to test it without manually changing the code in my installed version.

If you can provide a step by step process on how to change/test, what to change would be appreciated.

I tried to do a PR for https://github.com/vazco/uniforms/issues/974 also but ran into similar problems.

Sorry if only I was more familiar with it.

**Comment by radekmie** [comment]
Thanks for the PR! I'll answer all these questions in the PR.
