### ISSUE TITLE
Lodash Modularization

### ISSUE THREAD

**Issue by harryadel** [vazco/uniforms#983]
Hi guys, thank you for such a great package. I've noticed something that can be improved about your code base which is the usage of lodash library as a whole instead of the needed modules.

So, instead of:
```
    "lodash": "^4.0.0",
```
we can have: 
```
	"lodash.clonedeep": "^4.5.0",
	"lodash.memoize": "^4.1.2",
```
in uniforms-bridge-simple-schema-2 for example. 

This change can be extended to the entire codebase. Is that something you guys are interested in? I can open a PR if you want to.

**Comment by radekmie** [comment]
Hi @harryadel. We actually used these separated packages in the past and switched to the single one. There's a couple of benefits of doing so: there's only one version to take care of, the lodash package can be shared between projects (as it's a common dependency), and finally, it makes you 100% sure, that there are no duplicated sub-functions.

Also, just to reassure you - we are never importing the entire lodash package! Instead, we import a single function, like `import get from 'lodash/get'`.
