### ISSUE TITLE
Incorrectly typed props in TextField from uniforms-material

### ISSUE THREAD

**Issue by Florian3k** [vazco/uniforms#987]
`TextField` component props inside `uniforms-material` are typed using `StandardTextFieldProps` from `@material-ui/core/TextField`
Inside material-ui, `TextField`'s props are typed using
`type TextFieldProps = StandardTextFieldProps | FilledTextFieldProps | OutlinedTextFieldProps;`
This results in some props being typed incorrectly, for example `variant` prop has type `"standard" | undefined`, while it should be `"standard" | "filled" | "outlined" | undefined`

Using `uniforms-material 3.5.1`

**Comment by wadamek65** [comment]
@radekmie Do you maybe know if this was typed like this on purpose or is it simply an oversight? If it's an oversight I'll take over the issue and submit a PR.

**Comment by radekmie** [comment]
Yep, @wadamek65 is 100% right.
