### ISSUE TITLE
[QUESTION]: model field changes from default value to empty string

### ISSUE THREAD

**Issue by simplecommerce** [vazco/uniforms#990]
Hi,

I have a pretty specific question.
In a form, I have a field called `projectId` and by default it has a string inside.
For whatever reason, my child component re-renders, and the field changes to an empty string.
And also, I added a `onChange` in the `AutoForm` to see what is going on and I indeed see the projectId being changed to an empty string.

I am trying to debug it on my project and I am having no luck.

Do you have any idea by any chance, of a mechanism in your library what would manually change a field to an empty string for whatever reason?

Sorry if I am being unclear.

**Comment by radekmie** [comment]
Hi @simplecommerce. The only thing that I can think of is the [default value initialization](https://github.com/vazco/uniforms/blob/460421d945495f2c404a23b7fd129521343d23e8/packages/uniforms/src/useField.tsx#L80-L100) (if the field is required). Have you tried setting up a debugger breakpoint in the `onChange` handler and checking where exactly is it called?

**Comment by simplecommerce** [comment]
@radekmie You are right, I didn't think of using that to find out, but it does get triggered from the portion of code that you linked.
What is the reasoning behind this logic? 
From what I understand, if I use `useForm` instead of `useField` it will bypass that logic and should fix my `onChange` problem.
But I don't know why its triggering in first place if I call `useField` in this manner:

`const [{ value: autoFormValue="" }] = useField(name,{});`

In this example, I simply want to get the current value of the field in my model using `useField`.

I'm still checking on my end just to make sure I didn't miss anything that I did wrong.

**Comment by simplecommerce** [comment]
Ok the issue was in my component, where I was passing an empty "" value and it didn't like that.
Thanks for your help I appreciate it!!

**Comment by radekmie** [comment]
> What is the reasoning behind this logic?

This logic is there to set default (initial) values from the schema during the first render. If you don't want to do so, add `initialValue: false` to the second argument of `useField`.

> Ok the issue was in my component, where I was passing an empty "" value and it didn't like that.

If you'll pass a `value` there, it'll get propagated back to the model. That's expected and that's how `HiddenField` can be used.

---

In any case, I'm glad it workder out!
