### ISSUE TITLE
buildASTSchema infinite loop

### ISSUE THREAD

**Issue by krazyjakee** [vazco/uniforms#994]
```
"uniforms": "3.5.4",
"uniforms-bridge-graphql": "3.5.4",
"uniforms-material": "3.5.4",
```

I've found an infinite loop in buildASTSchema. Unfortunately I am unable to provide you a playground link as it crashes before it can save. Here is the GraphQL schema you can paste into the playground to trigger a crash. [Handy playground link](https://uniforms.tools/playground#?N4IgDgTgpgzlAuIBcICCATd0YwAQAoBxCAQzAAsBFAGQEoQAacCAezBmVBIFd4WYSANyjIAZiQA2cJjz4DhAESgSSAT2QBGAAxam6AJYCARhKjoxk6SBVHlyeBG5QmYFQGMo5FhPRQIFqWcQaBJ0AHkAOwl1JHFAphg3cigAWxJkEAioAHdcYjIqagAhCH10AHMofAAdCNxcI259H1QAZQAVVqTUkhq6-twwEgg4fAADWoGB-FUwKFwMLFg8YEmpgbd9GaQB1od9CPK19dwYeBJ4KB3cPdLDgEJj9bPoBB3bg_LH_pOAL30wNd6h8Hk96gBfWpg3AAYlw7XIhlwSOgAEcmtB0A1VA0mi0Ol1kmloTM5rhKE4IDjgLgSBFVPBEYcdgBJBS4SE_XBjWhrWgAOkq8HasyqAHJFtgYGLaAw1qJuBE3PB9Cw6vgUixfBJaLhVly3GqzrhfOdmngALy4ADaAF0ANxPfSiAj3TXa_lnC5QXlc-qmkjm_lgbgwcj4GkREgpK64MVey5ihi4GM4EiVHZivbe5F4NEYsz3MUc2iOrnO13u5SehxQBC-k4BoMhsMR3BRmOZl51-BJlPLdOxrO1hC53D5_SYoslstTCv4N1a6v_MAN9ZNqTB0PhyPRocrvupgQZuMALQBY4nU-L4NLTpdGqXEn5mxmuAAZO-U0-X1tVPzTEORlcAAPlwABWLQ1ymDcYC3Vtd07ONX1UQ8BxPMUAGE_1wNw6QaeYLlwUwSGNSDcPIYYSGVPw8AkNUvhvO9ywfKtn27UdP2_D0OPgACoCA8hQNwbQoOhWD4J3ds9y7Ede2TI9B0zW4e1w_DbFpeBiKgUitNEiiqJokZiIY6db1nAZ5zY_kVw_L97gAegAPWtLQAFoAE5bWAcDwQAEgc_lLjOR8PRXWhoIGCSWykjt9wBNC0ww88wBNFhYHbFgtLSeAklwRl5mgcpuBUCBcCgAAPSBllVCIzOYucHwkwDykZSL6mgeBuAgOoaVgjkLPBOV-hpFcdhpGxlEzFLcKXG8OVqegEi8bIWSiA4oAAUQgVh_FiSwglI1QlUiVpuCMFItgCKwjpOiIADVJDKb1rqgIaQAKmMMjpeBzHBIA)

```javascript
new GraphQLBridge(
  buildASTSchema(
    parse(`
      type Input {
        id: Int
        user_created(filter: users_filter, sort: [String], limit: Int, offset: Int, page: Int, search: String): users
    }

    input users_filter {
        id: String
      }

      type users {
        id: String
        avatar(filter: files_filter, sort: [String], limit: Int, offset: Int, page: Int, search: String): files
      }

      input files_filter {
        id: String
      }

      type files {
        id: String
        uploaded_by(filter: users_filter, sort: [String], limit: Int, offset: Int, page: Int, search: String): users
      }
  
    type Query { anything: ID }
    `)
  ).getType('Input')
)
```

I'm guessing since the methods within the types are referring back it just gets stuck going around and around?

Any help would be appreciated, thanks.

**Comment by radekmie** [comment]
Hi @krazyjakee. As you've said, it's crashing due to fields referring back, resulting in an infinite recursion. However, it's not a problem of the `buildASTSchema` nor `GraphQLBridge` (you can verify that by simply creating such a bridge and not using it). The problem is that the form you're using is rendering all fields by default. And this very schema generates an infinite number of fields.

There's no "depth limit" option in uniforms, but you can render the fields manually. You can check out #596, as it's essentially the same question but for JSON schema.

**Comment by krazyjakee** [comment]
Thanks for the reply and reference.

My use case is that I need to be able to generate forms using graphQL schema generated from a CMS without committing code (manually adding to a list of allowed fields) when there are schema updates. Can you suggest a way that I could achieve this?

**Comment by radekmie** [comment]
It depends on you use case, there are many options here. One that I already suggested and may work for you, is to implement a custom `NestField` that will show the nested fields only on click and/or when the value is present.

**Comment by radekmie** [comment]
I think that the topic is already covered. If needed, feel free to comment and reopen.
